### ISSUE TITLE
cvxgrp conda : no 1.0.x deployments on python 3 since 1.0.25.

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1002]
On conda, all python 3 releases of 1.0.x stop with [1.0.25](https://anaconda.org/cvxgrp/cvxpy/files?sort=basename&sort_order=desc&version=1.0.25&page=2), compare to [1.0.26](https://anaconda.org/cvxgrp/cvxpy/files?sort=basename&sort_order=desc&version=1.0.26&page=2). This is almost certainly because of ``version_getter.py`` thinking that versions 1.0.x are out-of-date, after 1.1.a0 was released.

We could fix ``version_getter.py``, or we could use this as a time to drop cvxpy distribution on the cvxgrp conda channel. @akshayka @SteveDiamond.

**Comment by SteveDiamond** [comment]
My vote is for dropping the cvxgrp conda and switching to conda forge.

**Comment by rileyjmurray** [comment]
We switched to conda-forge a while ago. Thanks, @h-vetinari!
