### ISSUE TITLE
Windows builds in cvxpy 1.0.X and 1.1.aX

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1003]
Three issues:
  1.  Our conda builds for Windows (run via AppVeyor) have had issues with SCS for a while. The underlying cause of the issues with SCS has been fixed, but our windows conda distribution
hasn't been fully updated to reflect this change. Changes are needed on both 1.0.x branches, and master (1.1 alpha).
  2.  I looked into AppVeyor [build history](https://ci.appveyor.com/project/StevenDiamond/cvxpy/history) and found a few instances where unittests failed on 1.0.x branches.
  3. I looked at PyPI uploads and found that Windows releases stop with 1.0.28.

There are separate cross-platform conda issues mentioned in #1002.

version 1.0.x
------------

**Simple problems:** The AppVeyor [1.0.31 installation script](https://github.com/cvxgrp/cvxpy/blob/1.0.31/continuous_integration/AppVeyor/configure_conda_and_install_cvxpy.ps1) needs up pull SCS from conda-forge, not pip. It also shouldn't specify <= 2.0. The AppVeyor [1.0.31 deployment script](https://github.com/cvxgrp/cvxpy/blob/1.0.31/continuous_integration/AppVeyor/deploy_windows.ps1#L13) should include conda-forge, rather than cvxgrp.

**Remark:** I linked to 1.0.31 above, but really these changes should be made on any "1.0 master" branch, if such a thing still exists.

**Complicated problems:** In [the AppVeyor build for 1.0.29](https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/31887603),  unittests fail for python 3.6 and 3.7. Until these are fixed, we can't expect conda or pypi deployments on python 3.6 and 3.7. [Python 3.5 wheels also stop with 1.0.29](https://pypi.org/project/cvxpy/1.0.29/#files) (compare to [1.0.28 wheels](https://pypi.org/project/cvxpy/1.0.28/#files)). Wheels don't upload for py35 because although unittests pass, AppVeyor logs show conda dependency conflicts (line [1737](https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/31887603/job/h4u0bhcccj24rwh6#L1737)) which prevent conda from installing twine (line [2553](https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/31887603/job/h4u0bhcccj24rwh6#L2553)). I don't yet know why the unittests fail for py36, py37, or why conda finds a dependency conflict for py35.

version 1.1 (master)
-------------------
**Simple problem:** The AppVeyor [deployment script](https://github.com/cvxgrp/cvxpy/blob/master/continuous_integration/AppVeyor/deploy_windows.ps1#L13) needs to add conda-forge, rather than cvxgrp.

**Remark** The conda-recipe was changed significantly with commit eff752f1d1151017a1cbe1a8c8a0abb12ebaa855, during 1.1.alpha development. The most consequential change is that the conda-build process now runs the full suite of unittests before deployment.

**Comment by h-vetinari** [comment]
So conda-forge builds cvxpy 1.1.x for windows just fine, and it also runs the full test suite (the last remaning difference between the cvxgrp-recipe is being resolved by https://github.com/conda-forge/cvxpy-feedstock/pull/38). 🙂

**Comment by rileyjmurray** [comment]
Resolved, since we switched to conda-forge sometime last year.
