### ISSUE TITLE
How to optimize perspective function？

### ISSUE THREAD

**Issue by liupeng2015** [cvxpy/cvxpy#1026]
The perspective function is convex, but cvxpy can not solve it,   e.g. f(x,t)=t*2**(x/t).  
I want to know how to solve it. 
Thanks!

**Comment by keithbriggs** [comment]
Take log?

________________________________

**Comment by aszekMosek** [comment]
CVXPY has rel_entr and

u >= t*exp(x/t)  iff    x <= - rel_entr(t,u)

In general when you can express a function in conic form then you can also express its perspective. https://docs.mosek.com/modeling-cookbook/practical.html#perspective-functions

**Comment by liupeng2015** [comment]
@aszekMosek  Thanks!  But I wonder why I can not find rel_entr in my CVXPY version 1.0.25.

**Comment by aszekMosek** [comment]
@liupeng2015 Sorry, I must have looked in a wrong place. kl_div applies here. Or just directly use the exponential cone is possible.

**Comment by liupeng2015** [comment]
@aszekMosek Thanks all the same！
I still find the way to solve the problem that contains perspective function( f(x,t)=t*2**(x/t) )  with cvxpy. 
It's been bothering me for a long time.  Thank you for you advice. 
 Please tell me if you have a solution.

**Comment by liupeng2015** [comment]
@aszekMosek   f(x,t)=t*2**(x/t) is convex function, but it is not DCP.

**Comment by liupeng2015** [comment]
@keithbriggs    f(x,t)=t*2**(x/t) is convex function, but it is not DCP. There is no such function in CVXPY.

**Comment by keithbriggs** [comment]
log(f) is DCP, so you're ok.


________________________________

**Comment by aszekMosek** [comment]
@liupeng2015  kl_div does what you need. I just incorrectly thought it is called rel_entr.

**Comment by liupeng2015** [comment]
Thankds!

log(f) is DCP, but  x/t is still not DCP after taking log.    @keithbriggs           

kl_div is defined as xlog(x/y)−x+y , how to use it?

**Comment by keithbriggs** [comment]
Yes - sorry, I was mistaken.

**Comment by ericlux** [comment]
Resolved via #1867. CVPXY 1.3 will support the perspective transform of an expression w.r.t. its variables. 
@SteveDiamond  I think this can be closed.
