### ISSUE TITLE
dqcp typos

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1083]
https://www.cvxpy.org/tutorial/dqcp/index.html:
>   An expression quasiconcave under DQCP if it is one of the following:

https://doi.org/10.1007/s11590-020-01561-8 Disciplined quasiconvex programming Akshay Agrawal, Stephen Boyd:
>  C ∩ (∞, t]

**Comment by kevkevinpal** [comment]
should it be 

>An expression `is` quasiconcave under DQCP if it is one of the following:

**Comment by keithbriggs** [comment]
Yes.
