### ISSUE TITLE
How to write tr(A^TLA) based DCP rules?

### ISSUE THREAD

**Issue by xpuoxford** [cvxpy/cvxpy#1092]
I am solving a bi-convex problem with two matrices A and L as two variables. I am using cvxpy with the extension on dmcp (sorry for repost, I opened an issue under dmcp, but it seems no one is maintaining that) Also the problem is because the cvxpy DCP rules. 

There is a trace term that I cannot make it recognised by dmcp: tr(A^TLA); wondering how to write it so that the dmcp can take it a dmcp problem. Thanks : )

I know that for tr(A^TA), it cannot be recognised, and it must be written as cvx.norm(A, 'fro')

What if there is another variable. It is obvious that given L, A is convex in tr(A^TLA). But it cannot be recognised. Any solutions to this?

**Comment by SteveDiamond** [comment]
I'm sorry but I don't totally understand your question. Was it addressed sufficiently here https://github.com/cvxgrp/dmcp/issues/15#issuecomment-665977091?
