### ISSUE TITLE
ARPACK error -1: No convergence

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1097]
I'm getting this error in a call to solve().  Maybe it will work if I can increase num_iter or reduce EIGVAL_TOL in the call to scipy.sparse.linalg.eigen.arpack.arpack, but is there any access to these parameters in constant.py for a normal user?

> Traceback (most recent call last):
>   File "try_taylor_approximations_to_integrals_02.py", line 118, in <module>
>     test_00()
>   File "try_taylor_approximations_to_integrals_02.py", line 74, in test_00
>     result0,weights=solve_constrained_RR(A0,B,A1,do_checks=True,verbose=False)
>   File "/home/kbriggs/MIMO_antenna_design/try_simultaneous_diagonalization_01.py", line 106, in solve_constrained_RR
>     result=prob.solve(method='dccp',solver=solver,ccp_times=ccp_times,mu=mu,tau=tau,eps=eps,max_iters=max_iters,verbose=False) # ,warm_start=True
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/problems/problem.py", line 396, in solve
>     return solve_func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 41, in dccp
>     if not is_dccp(self):
>   File "/usr/local/lib/python3.6/dist-packages/dccp-1.0.3-py3.6.egg/dccp/problem.py", line 172, in is_dccp
>     if problem.objective.expr.curvature == "UNKNOWN":
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/expressions/expression.py", line 134, in curvature
>     elif self.is_affine():
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/utilities/performance_utils.py", line 70, in _compute_once
>     result = func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/expressions/expression.py", line 177, in is_affine
>     return self.is_constant() or (self.is_convex() and self.is_concave())
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/utilities/performance_utils.py", line 70, in _compute_once
>     result = func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/atoms/atom.py", line 171, in is_convex
>     elif self.is_atom_convex():
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/atoms/quad_form.py", line 64, in is_atom_convex
>     return P.is_constant() and P.is_psd()
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/utilities/performance_utils.py", line 70, in _compute_once
>     result = func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/expressions/constants/constant.py", line 206, in is_psd
>     ev = extremal_eig_near_ref(self.value, EIGVAL_TOL, low=True)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/expressions/constants/constant.py", line 247, in extremal_eig_near_ref
>     ev = SA_eigsh(sigma)
>   File "/usr/local/lib/python3.6/dist-packages/cvxpy-1.1.3-py3.6-linux-x86_64.egg/cvxpy/expressions/constants/constant.py", line 238, in SA_eigsh
>     return eigsh(A, k=1, sigma=sigma, return_eigenvectors=False)
>   File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1567, in eigsh
>     OPinv=OPinv)
>   File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1347, in eigs
>     params.iterate()
>   File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 757, in iterate
>     self._raise_no_convergence()
>   File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 377, in _raise_no_convergence
>     raise ArpackNoConvergence(msg % (num_iter, k_ok, self.k), ev, vec)
> scipy.sparse.linalg.eigen.arpack.arpack.ArpackNoConvergence: ARPACK error -1: No convergence (271 iterations, 0/1 eigenvectors converged) [ARPACK error -14: ZNAUPD did not find any eigenvalues to sufficient accuracy.]
>

**Comment by imsaravan** [comment]
@keithbriggs were you able to solve this issue? I have this same issue running for me currently. It would be very helpful if you can help

**Comment by keithbriggs** [comment]
Sorry, I can't remember what happened about this.   I will have to find my code and run it again.

**Comment by imsaravan** [comment]
@keithbriggs oh :(

It would be very helpful for me if you can help. am facing this issue since 2 weeks. it was all fine and this happened all of sudden. Did you increase your max_iters(maximum iteration to the solver params)

**Comment by rileyjmurray** [comment]
CVXPY's behavior for checking psd / nsd has changed since July 2020 (when this issue was opened). The change may or may not fix your problem (hard to say without having the data). The general fix is to find the relevant matrix in your problem and use the ``psd_wrap`` atom. I.e., replace ``P = psd_wrap(P)``.
