### ISSUE TITLE
Solver Error

### ISSUE THREAD

**Issue by Ethisham** [cvxpy/cvxpy#1114]
Hi all,
I am getting solver error when I used binary variable ''b_ess'' in constraints, I used the GLPK solver recommended by the CVXPY in the console, but now I get this error 
''SolverError:` Either candidate conic solvers (['GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg, Zero), or there are not enough constraints in the problem.'' 
Any solution please I need to solve my problem in an open source solver.

`
import cvxpy as cp
from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt
# Generate data.
T = 96                # Total time slots as 1 slot is 15 min so in total it will be 24*4
t = 0.25              # delta t is 1/4 hr  
#P_s = np.loadtxt("PV_180310.txt")             # Solar data Input
P_s = np.array([5, 2, 3, 4, 1, 1, 1, 1, 2, 2, 3, 3, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 2, 3,
                5, 2, 3, 4, 1, 1, 1, 1, 2, 2, 3, 3, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 2, 3,
                5, 2, 3, 4, 1, 1, 1, 1, 2, 2, 3, 3, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 2, 3,
                5, 2, 3, 4, 1, 1, 1, 1, 2, 2, 3, 3, 1, 1, 1, 2, 2, 2, 3, 2, 1, 1, 2, 3])
#----------DG data----------------#
alpha = 32
beta = 21
gemmaa = 0.97
P_dgmin = 0
P_dgmax = 750
#--------------------Baterry parameters---------------#
SOC_min = 20                         # 20% as we are taking state of charge in percentage
SOC_max = 80
Cap = 750
P_bmax = 250
Eff = 0.93
#------------------Load data--------------#
P_L = np.array([5, 3, 7, 2, 12, 20, 6, 9, 5, 7, 11, 12, 11, 10, 5, 6, 7, 4, 9, 
                7, 9, 10, 7, 5, 5, 3, 7, 2, 12, 20, 6, 9, 5, 7, 11, 12, 11, 10,
                5, 6, 7, 4, 9, 7, 9, 10, 7, 5, 5, 3, 7, 2, 12, 20, 6, 9, 5, 7,
                11, 12, 11, 10, 5, 6, 7, 4, 9, 7, 9, 10, 7, 5, 5, 3, 7, 2, 12,
                20, 6, 9, 5, 7, 11, 12, 11, 10, 5, 6, 7, 4, 9, 7, 9, 10, 7, 5])

# Variables intialization
P_dg = cp.Variable(T)
P_ch = cp.Variable(T)
P_dis = cp.Variable(T)
SOC = cp.Variable(T+1)
b_ess = cp.Variable(T, boolean=True) 
constraints = []
for i in range(T):
    constraints += [P_dg[i] + P_s[i] - P_dis[i] == P_L[i] + P_ch[i], 0 <= P_dg[i],
                    P_dg[i] <= 750, 0 <= P_ch[i], P_ch[i] <= P_bmax*b_ess[i], 
                    (-P_bmax)*(1 - b_ess[i]) <= P_dis[i], P_dis[i] <= 0, SOC[0] == 30, 
                    SOC[i+1] == SOC[i] + (P_ch[i]*(Eff/Cap)*t*100) + (P_dis[i]*(1/(Eff*Cap))*t*100),
                    15 <= SOC[i+1], SOC[i+1] <= 70] 

obj = 0

for i in range(T):
    obj += alpha + beta*P_dg[i] + (cp.square(P_dg[i]))*gemmaa
           
prob = cp.Problem(cp.Minimize(obj), constraints)    
prob.solve(solver=cp.GLPK)    `

**Comment by rileyjmurray** [comment]
Use SCIP, or XPRESS Community edition. If both of those don’t work, search our GitHub issues for “ECOS_BB”, you should find someone made a fork of CVXPY 1.1 which has ECOS_BB.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ethisham** [comment]
> Use SCIP, or XPRESS Community edition. If both of those don’t work, search our GitHub issues for “ECOS_BB”, you should find someone made a fork of CVXPY 1.1 which has ECOS_BB.
> 
> Sent with [GitHawk](http://githawk.com)

Okay let me try, thank you for your quick response.
XPRESS community edition can be used for commercial purpose?

**Comment by rileyjmurray** [comment]
I hadn't thought of that, but yes!

https://community.fico.com/s/fico-xpress-optimization-licensing-optio

Problem size is capped so the sum of variables and constraints is  <= 5000.

**Comment by Ethisham** [comment]
Yup I had a look it is.
Thanks @rileyjmurray ...

**Comment by Ethisham** [comment]
Hi @rileyjmurray,
I am getting this error, does this belong to solver?
I am just using one binary variable b_ess[i], which is causing all problem and it is not making constraint non linear because I am multiplying it with constant in above problem, so there is no open source solver for using binary variable?

**Comment by rileyjmurray** [comment]
That error looks like you're using an out-of-date version of CVXPY. The XPRESS interface was recently rewritten.

If you install the version of CVXPY on the master branch then you will also have access to ECOS_BB. Be aware however that ECOS_BB may return incorrect solutions with no warning.
