### ISSUE TITLE
Maximizing a Ratio/Percent

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1148]
Inside a very large and complex LP, I create two continuous, affine (unconstrained) expressions:`x` and `y`.  
Due to how they are created, I know that `0 < x < y <= U`. Obviously: `x/y < 1`.

In my LP *objective*, how do I ***maximize*** the ratio `x/y`?  

Things I tried:

 - Maximizing `x*cp.inv_pos(Y)` states my problem is non DCP (also if I try to minimize the inverse)
 - I found various LP formulations for maximizing ratios (e.g. [here][1] or [here][2]) but these requires rewriting the *constraints* on all the terms in the expressions for `x` - I have no idea how to do that with `cvxpy`.  
   If this is the way to go then an example would be very helpful!

  [1]: http://lpsolve.sourceforge.net/5.5/ratio.htm
  [2]: https://download.aimms.com/aimms/download/manuals/AIMMS3OM_LinearProgrammingTricks.pdf#page=8

**Comment by rileyjmurray** [comment]
CVXPY does not employ automatic reformulation for linear-fractional problems. The second link you provided gives the transformation you would need to perform manually. Refer also to https://docs.mosek.com/modeling-cookbook/linear.html#homogenization.

**Comment by adishavit** [comment]
In the referenced formalization one needs to alter the constraints on the
expressions.

With cvxpy’s declarative style and when incrementally building the model
how do I (eventually) find and break up those constrains pertaining to the
expressions in the ratio?

**Comment by SteveDiamond** [comment]
@adishavit maximizing the ratio is DQCP I believe. Try solving the problem with the flag ``qcp=True``. (https://www.cvxpy.org/tutorial/dqcp/index.html)

**Comment by adishavit** [comment]
Unfortunately, my problem is not DQCP (due to other factors) and ratio is not convex.  

I did manage to solve this using piecewise linear approximations for `exp()` and `log()` and compositing them together.

The result usage looks like this:
```
    # the limits (for the PWL function approximation):
    min_x = 1000
    max_x = 100000

    # variables and constraints
    x = cp.Variable()
    y = cp.Variable()

    cstrs += [min_x <= x,
              2 * x <= y,
              y <= max_x]

   # generate a ratio_() *function*
    ratio_ = ratio_factory((min_x, max_x))  #  <<<====
 
    # the ratio variable
    rat = ratio_(x, y, cstrs)  #  <<<====

    # Minimize or maximize - both work well
    obj = cp.Minimize(rat)
    # obj = cp.Maximize(rat)

    prob = cp.Problem(obj, cstrs)
    prob.solve()

    print(f'x={x.value}')
    print(f'y={y.value}')
    print(f'x/y = {x.value / y.value}')
```

The magic:
```
# for ratios x/y with: L <= x <= y <= U
def ratio_factory(domain: Tuple[float, float], n_segments: int = 7, samples=300, factor=1e5):
    log_ = log_factory(domain, n_segments, samples, factor)
    exp_ = exp_factory((log(domain[0]) - log(domain[1]), 0), n_segments, samples, factor)  # assumes x <= y (hence exp_U==0)

    def ratio_(x: cp.Variable, y: cp.Variable, cstrs):
        return exp_(log_(x, cstrs) - log_(y, cstrs), cstrs)  # ratio composition 

    return ratio_  # returns a function
``` 
The results are accurate to about 4 digits and can be improved with more PWL segments.

The underlying implementation is completely generic and can be use with any piecewise linear mapping - not just the math functions shown here. The functions `log_factory()` and `exp_factory()` are just wrappers to automatically generate the piecewise linear mappings using the [pwlf library](https://github.com/cjekel/piecewise_linear_fit_py). 

I'm still polishing the code, but if there is interest I would happy to publish it.
