### ISSUE TITLE
Minimizing `cp.tv(cp.hstack([...]))` works,  `cp.tv(cp.vstack([...]))` doesn't 

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1150]
I'm not sure this is a bug, but when I minimize a  `cp.tv(cp.hstack([...]))` expression the expression is indeed minimized.  
However, when using `cp.vstack()` instead -  `cp.tv(cp.vstack([...]))` the result is worse than without it at all.

Is there a difference between `vtsatck` and `hstack` when used to create 1D vectors?
Alternatively, does `cp.tv()` operate differently on row and column vectors?

**Comment by SteveDiamond** [comment]
Could you check the dimensions of ``cp.hstack([...])`` and ``cp.vstack([...])``? They might not be 1D.

**Comment by adishavit** [comment]
Your are right, but I don't understand why this is so.  
Perhaps I'm not checking the right thing. I'm checking with `ndim`:

```
print ([e.var.ndim for e in data]   # >> [1,1]
l=[e.var for e in data]
cp.vstack(l).ndim  # ndim ==  2
cp.hstack(l).ndim  # ndim == 1
```
Is this the expected behaviour?

**Comment by SteveDiamond** [comment]
This is expected behavior. cvxpy follows numpy: https://numpy.org/doc/stable/reference/generated/numpy.vstack.html

**Comment by adishavit** [comment]
But if the data is in fact 1D (just a single 1D column or row _vector_) shouldn't `cp.tv()` yield the same result in both cases?  
If not, then maybe the docs should be clarified.
