### ISSUE TITLE
Round constraint in optimizer 

### ISSUE THREAD

**Issue by exw410** [cvxpy/cvxpy#1212]
Hi - Given a decision variable `x`, I was wondering if I could impose the following type of constraint:

(|x| / v) >= round(to nearest 100)

where `v` is a vector of same size as `x`. 

I am trying to round the LHS to the nearest 100 amounts. Thank you.

**Comment by adishavit** [comment]
You may add 50 (half of 100) to your variable and use a slightly modified `floor` as shown [here](https://math.stackexchange.com/questions/1862885/linear-program-with-ceiling-or-floor-functions/1863895#1863895) with an integer variable.
