### ISSUE TITLE
Behavior of cp.lambda_sum_largest

### ISSUE THREAD

**Issue by marchinidavide** [cvxpy/cvxpy#1218]
The current implementation of `cp.lambda_sum_largest` uses `scipy.linalg.eigvals` which returns a complex array even with a symmetric matrix. The imaginary part of the eigenvalues array is zero (as expected)
This would not happen with `np.linalg.eigvals`, `np.linalg.eigvalsh`, `scipy.linalg.eigvalsh`. 
Since the documentation of `cp.lambda_sum_largest` clearly states that the input matrix needs to be symmetric, using `LA.eigvalsh` would make the function work and also be faster. 

 - OS: macOS Catalina 10.15.7
 - CVXPY Version: 1.1.7

**Comment by rileyjmurray** [comment]
We've previously run into (and fixed) similar inefficiencies elsewhere in the codebase. We'd welcome a PR to make this change, and any related changes.

**Comment by marchinidavide** [comment]
Thanks for the reply, will give it a try!

**Comment by tuelwer** [comment]
I think this issue was fixed in 4501b0f82c9878a 👍
