### ISSUE TITLE
Two test failures on aarch64-linux

### ISSUE THREAD

**Issue by rmcgibbo** [cvxpy/cvxpy#1241]
**Describe the bug**
It looks like a two cvxpy tests have been failing on the NixOS aarch64 build system:
https://hydra.nixos.org/job/nixpkgs/trunk/python38Packages.cvxpy.aarch64-linux

Here's a particular log: https://nix-cache.s3.amazonaws.com/log/yzgzfvvzh5r4sxzldznya30yf5rvcgwq-python3.8-cvxpy-1.1.8.drv

**Output**
Here are the particular error messages:
```
=================================== FAILURES ===================================
_______________________ TestECOS_BB.test_ecos_bb_mi_lp_2 _______________________

self = <cvxpy.tests.test_conic_solvers.TestECOS_BB testMethod=test_ecos_bb_mi_lp_2>

    def test_ecos_bb_mi_lp_2(self):
>       StandardTestLPs.test_mi_lp_2(solver='ECOS_BB')

cvxpy/tests/test_conic_solvers.py:1384: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cvxpy/tests/solver_test_helpers.py:770: in test_mi_lp_2
    sth.verify_objective(places)
cvxpy/tests/solver_test_helpers.py:137: in verify_objective
    self.tester.assertAlmostEqual(actual, expect, places)
cvxpy/tests/base_test.py:38: in assertAlmostEqual
    super(BaseTest, self).assertAlmostEqual(a, b, places=places, delta=delta)
E   AssertionError: 7945.000004659319 != 8373 within 4 places (427.9999953406814 difference)
___________________________ TestDgp.test_sum_matrix ____________________________

self = <cvxpy.tests.test_dpp.TestDgp testMethod=test_sum_matrix>

    def test_sum_matrix(self):
        w = cp.Variable((2, 2), pos=True)
        h = cp.Variable((2, 2), pos=True)
        alpha = cp.Parameter(pos=True, value=1.0)
        problem = cp.Problem(cp.Minimize(alpha*cp.sum(h)),
                             [cp.multiply(w, h) >= 10,
                              cp.sum(w) <= 20])
        problem.solve(SOLVER, gp=True, enforce_dpp=True)
        np.testing.assert_almost_equal(problem.value, 8)
        np.testing.assert_almost_equal(h.value, np.array([[2, 2], [2, 2]]))
        np.testing.assert_almost_equal(w.value, np.array([[5, 5], [5, 5]]))
    
        alpha.value = 2.0
        problem.solve(SOLVER, gp=True, enforce_dpp=True)
>       np.testing.assert_almost_equal(problem.value, 16)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 15.99999975991318
E        DESIRED: 16

cvxpy/tests/test_dpp.py:770: AssertionError
```

One of these may be real and the other may be numerics noise? I understand that you might not test on this platform, which is why I wanted to bring this to your attention.

**Version**
 - OS: Linux aarch64
 - CVXPY Version: 1.1.7 and 1.1.8

**Comment by rmcgibbo** [comment]
Here's a log of the same errors in 1.1.10 https://gist.github.com/r-rmcgibbo/f4931b36a63e285d528ae989b4329201

**Comment by rileyjmurray** [comment]
@rmcgibbo thanks for notifying us. The first error is real, but it's not all that unexpected. ECOS_BB has known correctness issues and we no longer automatically select it on a user's behalf (they have to call ECOS_BB explicitly). The second problem certainly looks like numeric noise.

For the second problem, the fix is just to reduce the test's precision requirements.

There are probably several fixes for the first problem (which ultimately need to be along the lines of "inform the user that ECOS_BB is still broken but don't return an error that would make it look like the unittests failed"). @akshayka and @SteveDiamond I thought we encountered and fixed almost this exact same issue in the past. Does this look familiar to you two?

**Comment by rmcgibbo** [comment]
Am I correct that you don't believe this test failure is really specific to aarch64? It's just that ECOS_BB is a bit flaky, and the numerics happen to be slightly different between x86 and aarch64, without either necessarily being more likely to be correct in general.

**Comment by SteveDiamond** [comment]
@rileyjmurray I believe these tests were commented out/fixed for conda-forge. @rmcgibbo we should definitely fix the tests in general, lowering the precision for the latter test and doing something (not sure what lol) for the ECOS_BB test.

**Comment by rmcgibbo** [comment]
In 1.1.12, it looks like the tolerance issue might be fixed, but the ecos_bb failure is still there:
https://gist.github.com/r-rmcgibbo/4bf1b21010e6536bb18f2934ee160077#file-python38packages-cvxpy-L1366-L1383
