### ISSUE TITLE
Unable to install cvxpy==1.20 on DBR 5.5 cluster

### ISSUE THREAD

**Issue by bandarusridhar** [cvxpy/cvxpy#1245]
Hi Team,

Getting an error like:
Command "/databricks/python3/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-xicdzblt https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=f2a778dd9bb3e4590dbe3bbac28e7c7134280c4ec97e3bf8678170ee58c67b21 https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=f2a778dd9bb3e4590dbe3bbac28e7c7134280c4ec97e3bf8678170ee58c67b21 https://files.pythonhosted.org/packages/7b/74/54c5f9bb9bd4dae27a61ec1b39076a39d359b3fb7ba15da79ef23858a9d8/numpy-1.16.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=2d279bd99329e72c30937bdef82b6dc7779c7607c5a379bab1bf76be1f4c1422 https://files.pythonhosted.org/packages/00/16/476826a84d545424084499763248abbbdc73d065168efed9aa71cdf2a7dc/numpy-1.19.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=13af0184177469192d80db9bd02619f6fa8b922f9f327e077d6f2a6acb1ce1c0 https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl#sha256=368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9 https://files.pythonhosted.org/packages/15/0e/255e3d57965f318973e417d5b7034223f1223de500d91b945ddfaef42a37/setuptools-53.0.0-py3-none-any.whl#sha256=0e86620d658c5ca87a71a283bd308fcaeb4c33e17792ef6f081aec17c171347f https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl#sha256=78b5b185f0e5763c26ca1e324373aadd49182ca90e825f7853f4b2509215dc0e" failed with error code 1 in None

**Comment by SteveDiamond** [comment]
Sorry for the slow response. Does this system have gcc? Also would you consider using miniconda?

**Comment by bandarusridhar** [comment]
> Sorry for the slow response. Does this system have gcc? Also would you consider using miniconda?

Yes @SteveDiamond, this system has GCC. The same works on higher version of Databricks cluster but its failing on lower version i.e. 5.5

**Comment by rileyjmurray** [comment]
Closing this issue because
1. our method of distributing cvxpy has changed since March of this year -- we now have wheels and conda-forge.
2. the description of the issue doesn't really make sense (the latest cvxpy version in Feb 2021 was 1.1.10).

If someone else finds themselves in a similar databricks situation, please post here and we can re-open the issue!
