### ISSUE TITLE
Installing from source on OS X 11 (Big Sur) with Python 3.9

### ISSUE THREAD

**Issue by jvlmdr** [cvxpy/cvxpy#1252]
Hi,

I recently tried to install from source on OS X 11.2 with Python 3.9 and encountered a few difficulties. I managed to get around the issues and I have documented the process below. I hope it helps.

Here is my setup (in a virtual environment):
```
% python --version
Python 3.9.1
% pip freeze
numpy==1.20.1
scipy==1.6.1
% swig -version
SWIG Version 4.0.2
...
```
```
% git clone git@github.com:cvxgrp/cvxpy.git
...
% cd cvxpy
% git log | head -1
commit fab8c31d36aa2b8b4b01c7a3a9b6d40dff2433b7
```

If I try to install directly:
```
% pip install -e .
```
I get an error:
```
...
    File "setup.py", line 39, in <module>
      python_target = distutils.version.LooseVersion(
    File ".../Python.framework/Versions/3.9/lib/python3.9/distutils/version.py", line 306, in __init__
      self.parse(vstring)
    File ".../Python.framework/Versions/3.9/lib/python3.9/distutils/version.py", line 314, in parse
      components = [x for x in self.component_re.split(vstring)
  TypeError: expected string or bytes-like object
```
The issue here is that `distutils.sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')` is returning an integer (11), whereas `distutils.version.LooseVersion()` expects a string. (See the related numpy issues https://github.com/numpy/numpy/pull/17906 and https://github.com/numpy/numpy/issues/18093)

We can get around this by setting the environment variable
```
% MACOSX_DEPLOYMENT_TARGET=11.2 pip install -e .
```
This spent a long time "`Installing build dependencies`" and eventually gave an error:
```
    running dist_info
...
    init_dgelsd failed init
    Traceback (most recent call last):
...
      File "setup.py", line 23, in finalize_options
        import numpy
      File ".../pip-build-env-l0wd90re/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
```
It seems `numpy` is raising an exception on import because some sanity tests failed. This is strange because I can do `import numpy` myself without any problem. I noticed that there is a requirement for `numpy==1.19` under `[build-system]` in `pyproject.toml`. It seems like the install script is trying to install numpy version `1.19.0`. Since this version [does not contain a wheel for python 3.9](https://pypi.org/project/numpy/1.19.0/#files), numpy is being built from source, resulting in the Polyfit issue above.

Here, the easiest option was to modify `pyproject.toml`, changing the requirement `numpy==1.19` to `numpy>=1.20`.
```
% MACOSX_DEPLOYMENT_TARGET=11.2 pip install -e .
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
...
Building wheels for collected packages: ecos, scs
...
Successfully built ecos scs
Installing collected packages: qdldl, scs, osqp, ecos, cvxpy
  Running setup.py develop for cvxpy
Successfully installed cvxpy ecos-2.0.7.post1 osqp-0.6.2.post0 qdldl-0.1.5.post0 scs-2.1.2
```

Alternatively, I tried downgrading my numpy version to 1.19.5 and modifying the line of `pyproject.toml` accordingly. This also worked (still with `MACOSX_DEPLOYMENT_TARGET=11.2`).

**Comment by jvlmdr** [comment]
The initial `TypeError` was also described in issue https://github.com/cvxgrp/cvxpy/issues/1190

**Comment by jvlmdr** [comment]
Update:
With numpy 1.19.5, all of the tests pass (709 passed, 172 skipped).
With numpy 1.20.1, I had some failures (24 failed, 685 passed, 172 skipped), mostly due to `cvxpy.error.SolverError: Solver 'SCS' failed`. I could open a separate issue for this if/when you like.

It was important to change the requirement in `pyproject.toml` to match the numpy version.
With numpy 1.20.1, I used requirement `numpy>=1.20` (current latest version is 1.20.1).
With numpy 1.19.5, I used requirement `numpy>=1.19,<20`.
(Note that if I used the requirement `numpy>=1.19` with numpy 1.19.5, then I would get an error when I try to `import cvxpy` because it was built with 1.20.1.)

Maybe it is better to use the `>=1.{x},<1.{x+1}` form (or the explicit version), as it seems that `1.19` implies `1.19.0` not `1.19.*`? (I am not an expert in pypi versioning.) The change from `oldest-supported-numpy` to explicit versions was introduced in PR https://github.com/cvxgrp/cvxpy/pull/1234.

**Comment by h-vetinari** [comment]
conda-forge [has](https://anaconda.org/conda-forge/cvxpy/files) 3.9 builds for big sur; produced [here](https://github.com/conda-forge/cvxpy-feedstock).

Assuming you have conda installed already:
```
conda config --add channels conda-forge
conda install cvxpy
```

**Comment by SteveDiamond** [comment]
We added explicit upper bounds for numpy versions, which hopefully fix this.
