### ISSUE TITLE
Small mistake in TestParamConeProg.test_psd_var()

### ISSUE THREAD

**Issue by jvlmdr** [cvxpy/cvxpy#1253]
It looks like there is a small mistake here:
https://github.com/cvxgrp/cvxpy/blob/c88f09215252c932c101c842dd684a60c16ea4cf/cvxpy/tests/test_param_cone_prog.py#L98-L100

I guess it should be `np.isclose(2 * ..., ...)` rather than `2 * np.isclose(..., ...)`.

It might be worth looking into why this test was still passing.

**Comment by rileyjmurray** [comment]
@akshayka can you take a look at this?
