### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#1273]
This is a tracking issue for a new feature we would like to add to CVXPY: code generation.

**Is your feature request related to a problem? Please describe.**
In real-time settings, such as control (of cars, drones, space rockets, robots, and so on), a convex optimization problem may need to be solved several times a second. The convex optimization problem being solved has the same form, but different numerical data (parameters). In these applications it can be infeasible to run a Python interpreter, which can be slow. Instead developers either need to interface with solvers directly, a time-consuming and error-prone task, or use other ecosystems that provide code generation, many of which are closed source and specialized only to QPs.

**Describe the solution you'd like**
CVXPY should add support for code generation for parametrized problems.

The user would type in a problem with parameters, and CVXPY would emit a C function that took the parameters as input, transferred the parameters to the problem data, solved the problem, and returned a solution. We could also emit Python bindings.

Like the `solve` method, a `codegen` method might take a solver as a keyword argument (eg, `OSQP` or `ECOS`, which were designed to be friendly for embedded applications). 

Something like

```
problem.codegen(solver=cp.OSQP, directory='/path/to/directory/')
```

We could start by supporting a limited class of problems, such as QPs and second-order cone programs.

CVXPY 1.1's support for parametrized problems and extraction of the ASA maps will likely be key in making code generation possible.

**Describe alternatives you've considered**
CVXPY 1.1 introduced faster compilation of parametrized problems, via extraction of the ASA map. So subsequent compilations of parametrized problems are much faster. It might already be possible to run CVXPY in some embedded settings if the dynamics are sufficiently slow. 

**Additional context**
Here is the paper that describes the work on parametrized problems, and extraction of the ASA map: https://arxiv.org/abs/1910.12430

**Comment by rostyboost** [comment]
That would be great. One expedient shortcut here to avoid implementing complete codegen would be to use file formats such as MPS supported by most solvers as an IR, combined with an "ASA map to MPS" file.
A C implementation would then load both files using a solver C API to efficiently create a model from scratch. Parameter values could then be efficiently swapped from a solver model internal representation (similar to what is done [here](https://github.com/cvxgrp/cvxpy/pull/1276/files#diff-e1578b2679a34515497b2c54710089cdd92c015b536f176e956d133b465fb73bR156-R163)) to solve arbitrary instances of the DPP problem.
