### ISSUE TITLE
`self.NAME` is undefined in objective.py

### ISSUE THREAD

**Issue by r-barnes** [cvxpy/cvxpy#1314]
**Describe the bug**
`self.NAME` is apparently undefined. Looking at `objective.py`, I see:
```
    def __init__(self, expr):
        self.args = [Expression.cast_to_const(expr)]
        # Validate that the objective resolves to a scalar.
        if not self.args[0].is_scalar():
            raise ValueError("The '%s' objective must resolve to a scalar."
                             % self.NAME)
        if not self.args[0].is_real():
            raise ValueError("The '%s' objective must be real valued."
                             % self.NAME)
```
But `self.NAME` doesn't come from anywhere.

**Version**
 - OS: Any
 - CVXPY Version: master

**Additional context**

**Comment by akshayka** [comment]
It looks like `NAME` is defined for subclasses of `Objective`, but not for `Objective` itself. This is not practice, as you've pointed out.

The name of the class is really not needed in these errors. They should simply be

```python3
raise ValueError("The objective function must resolve to a scalar.")
```

```python3
raise ValueError("The objective function must be real-valued.")
```

**Comment by r-barnes** [comment]
@akshayka : Another way to approach it would be to define a `NAME` on the base class and then override that in the descendant classes. `NAME` is also used in the `__str__` method.
