### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kingofkill** [cvxpy/cvxpy#1324]
**Describe the bug**
Everytime introduces the expression `(cp.diag(Y_c @ A @ R_c.T @ X.T) @ Q)` into my objective,  the terminal exits and displays only "**Segmentation fault (core dumped)**". Without this expression is fine.

Is it caused by the dimension of the matrix is too large? where Y_c.shape=(190, 4), A.shape=(4, 4), R_c.shape=(43, 4),
 Q.shape=(190, 1) and all this four matrix is constant. X is the cp.Variable() which shape (190, 43).

**Output**
"Segmentation fault (core dumped)"

**Version**
 - OS: both ubuntu and windows10
 - CVXPY Version: 1.1.7
 - Numpy Version: 1.19.2
 - Python Version: 3.7.9

**Additional context**
The  function source code can be found here. 
https://github.com/kingofkill/cvxpy_opt/blob/main/opt_2.py

Any help would be much appreciated !

**Comment by SteveDiamond** [comment]
Hi, I don't understand what you're doing in the objective. Is it even a scalar valued expression?

**Comment by kingofkill** [comment]
What I want to say in this expression is that I want to measure the transformation cost,  `Y_c` is the original state , `Y`(equals `X*R_c`, so it isn't a scalar) is the current state and `A` represents the unit price of the transitions between different(from and to) states. In the meanwhile, Q in this formula is the amount need to be transited.
