### ISSUE TITLE
Upgrading QCQP to latest CVXPY

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1330]
Are there any plans for upgrading or integrating [QCQP](https://github.com/cvxgrp/qcqp)  to the latest version of CVXPY?

**Comment by rileyjmurray** [comment]
It's not really on our radar. This sort of effort would need to be coordinated on the QCQP repo.

Separately, I think it will be difficult to make progress on this. My reasoning is that QCQP doesn't really have unit tests, and that makes it very hard to be confident in the correctness of major refactoring.
