### ISSUE TITLE
Do not use numpy deprecated type

### ISSUE THREAD

**Issue by rpradal** [cvxpy/cvxpy#1334]
When using numpy v1.20.0, the type `numpy.complex` is marked as deprecated.

This is problematic because cvxpy uses it [here](https://github.com/cvxgrp/cvxpy/blob/ef0f6702f7db865e0beb1550477780fd323fbac8/cvxpy/interface/numpy_interface/ndarray_interface.py#L49) (and probably in other places as well).

Would it be possible to change it so this library can be fully compatible with the latest versions of numpy ?

I was thinking of using `numpy.complex_` instead. If the change is that simple i will be happy to open a PR myself.

**Comment by bogoalix** [comment]
I had some questionable behavior coming from this function that is probably related to this issue. 

Creating a problem with a constraint being a complex64 type caused the constraint to be casted to float64 by deleting the imaginary part, whereas using a complex type kept the imaginary part.

Maybe the condition should also check every complex types ?

**Comment by Laurens-T** [comment]
I ended up at this issue because of `numpy.complex` warnings. The warning states that `np.complex` is just an alias for the python builtin `complex`, and it should be safe to swap them.
