### ISSUE TITLE
Option to force CVXPY to use non-DPP compiler when running solve.

### ISSUE THREAD

**Issue by kmonson** [cvxpy/cvxpy#1340]
**Is your feature request related to a problem? Please describe.**
I have a problem that scales based on a user setting. For larger problems the DPP compiler slows everything down more than it benefits the overall run time. For smaller problems (which must be solved repeatedly) it's very useful to keep the problem DPP compliant.

From benchmarking I've discovered the optimal problem size to switch from a DPP to a non-DPP problem.

**Describe the solution you'd like**
A flag for the solve method to optionally force it to use the non DPP compiler to build the problem.

**Describe alternatives you've considered**
Currently I use this code to force CVXPY to use the non DPP problem generation:

```
        if not self.use_dpp:
            # Inject a nonsense constraint to make the problem non DPP
            constraints.append(
                cvxpy.Parameter(value=0) * cvxpy.Parameter(value=0) >= 0
            )
```

**Comment by rileyjmurray** [comment]
Resolved by #1669.
