### ISSUE TITLE
using 2 norm in objective function

### ISSUE THREAD

**Issue by sandeepparameshwara** [cvxpy/cvxpy#1353]
Hello members,

I want to add this term to my objective function

 `Wij( || X- Y ||_2 - D)^2`

where `Wij, D` are scalars. ||X-Y||_2 is 2-norm, X&Y are vectors of size 3. If I make the below formulation in cvxpy, I get an error:

```
import cvxpy as cp
import numpy as np

D = 1
Wij = 10
x = cp.Variable(3)
Y = np.array([1,2,3])

term = cp.norm(x- Y,2)-D
cost = Wij*cp.quad_form(term,1)
# constraints not shown, but correctly in place

problem = cp.Problem(cp.Minimize(cost),constraints)
problem.solve(verbose = True,solver='OSQP')
```

```
raise ValueError("Invalid dimensions for arguments.")
ValueError: Invalid dimensions for arguments.
```

Is this formulation correct, allowed? If not, how can I change this? In the second argument of quad_form instead of 1, I tried np.eye(1) but it doesn't help. Can someone kindly guide me? If I directly use norm in objective function, I get an error
`cvxpy.error.SolverError: Problem could not be reduced to a QP, and no conic solvers exist among candidate solvers ({'qp_solvers': ['OSQP'], 'conic_solvers': []}) 
`
Thank you
Sandeep

**Comment by SteveDiamond** [comment]
This problem is not convex. You'll need to use some system other than cvxpy that handles non-convex problems.
