### ISSUE TITLE
Minimal working docker install guide w/ py3.7/py3.8/py3.9?

### ISSUE THREAD

**Issue by matzhaugen** [cvxpy/cvxpy#1361]
Hi guys,
Is there any chance you could provide a minimal working install for a docker file with pip and python >=3.7? Currently the docs only show how to do this with pip but the install doesn't work with for example the following dockerfile:
```
FROM python:3.7.10-slim
# INSTALL BLAS
RUN apt-get update && apt-get install libatlas-base-dev liblapack-dev libblas-dev -y
# THIS FAILS
RUN pip install cvxpy
```

I've tried a number of ways to install with the openblas package but nothing seems to work. On a mac 10.15.7, I manage to install cvxpy with python 3.7.10 and numpy 1.19.2 but not numpy 1.20 (latest). But the docker file above does not work.

Having a minimal working install for the higher python versions >= 3.7 would be tremendously helpful, both on docker with pip/poetry or on a mac, e.g. 10.15 with numpy 1.20.

**Comment by phschiele** [comment]
@matzhaugen You closed the issue, so I hope you already found a solution. 
If someone else finds this issue, below is a minimal working Dockerfile. However, working with `conda` might be an option to consider as well. 
```
FROM python:3.7.10-slim
RUN apt-get update && apt-get install build-essential -y
RUN pip install cvxpy
```
There is usually no need to install openblas, as it is the default blas version that comes with the numpy wheel (see [here](https://numpy.org/install/) under "NUMPY PACKAGES & ACCELERATED LINEAR ALGEBRA LIBRARIES".
Indeed, we can check this by running:
```bash
docker build . -t cvxpy
docker run -it cvxpy bash
python
```
```python
import numpy
numpy.show_config()
>>> openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by matzhaugen** [comment]
Hey @phschiele yes, I found a solution, which was basically your solution. It seems like the numpy build system is complicated with the mac accelerate backend, which was why I was resorting to docker. But it seems like the ECOS and and SCS are having similar issues.

https://github.com/embotech/ecos-python/issues/29
https://github.com/bodono/scs-python/pull/38

**Comment by phschiele** [comment]
@matzhaugen We are working on wheels for Linux at the moment, such that you can directly `pip install cvxpy` in the Dockerfil without compiling. The PRs you linked also will fix some conflicts with certain numpy versions.

**Comment by matzhaugen** [comment]
Excellent, thanks!

**Comment by SteveDiamond** [comment]
New wheels for ECOS are online, going up to Python 3.9.
