### ISSUE TITLE
Atom for quantile of weighted Monte-carlo simulations

### ISSUE THREAD

**Issue by aisurfer** [cvxpy/cvxpy#1362]
I would like to solve a task:
I have vector of variables X.
Given a matrix M containing Monte-carlo simulations for each of X I need to find such a vector of weights W that maximizes particular quantile of weighted sum of distributions, calculated over simulations.

How I calculate quantile value:
M has shape (num simulations, len of X)
X and W are 1d vectors of the same shape
M_weighted = M * W
quantile_value = np.quantile(np.sum(M_weighted, axis=1), quantile)

So I would like to find W that maximizes quantile_value.
The problem is that I have to define a gradient to let a solver know how to change values of W to achieve better results.

I expect I have to implement atomic function that takes W as Variable() and M as Parameter() and has method numeric() calculating quantile.
But I am lost how to implement _grad() method.

Is my approach correct an could anyone assist me?

**Comment by SteveDiamond** [comment]
If you need to implement a gradient, then you should be using a different optimization package like ``scipy.optimize``. In cvxpy you can't really implement your own atoms.

Not sure if this is relevant, but here's something on quantile regression in cvxpy: https://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/quantile_regression.ipynb

**Comment by aisurfer** [comment]
@SteveDiamond  Excuse me for reopening, but yout answer is unclear.

> In cvxpy you can't really implement your own atoms.

Well, I do not want to contribute to the package but why I can't implement it in my project?

>If you need to implement a gradient, then you should be using a different optimization package

As I see any of atoms have _grad() method, so I expect it is required for new atoms
https://github.com/cvxpy/cvxpy/blob/master/cvxpy/atoms/sum_largest.py#L45

I would like to use my new atom in constraint expression for optimization problem. Example:


```
#
###################### weighted_quantile.py ##########################
#

from cvxpy.atoms.atom import Atom
import numpy as np


class weighted_quantile(Atom):
    """Calcs weighted quantile
    x is weights 1D array of shape asset_count
    simulations is 2D array of shape trials x asset_count
    quantile is float in [0, 1]
    """

    def __init__(self, x, simulations, quantile):
        self.simulations = simulations
        self.quantile = quantile
        super(weighted_quantile, self).__init__(x)

    def validate_arguments(self):
        if self.simulations.shape[1] != self.args[0].shape[0]:
            raise ValueError("Second argument is simulations and must have shape[1] = asset count")
        if self.quantile < 0 or self.quantile > 1:
            raise ValueError("Third arg is quantile and must be in [0, 1]")
        super(weighted_quantile, self).validate_arguments()

    def numeric(self, values):
        result, _ = self._find_quantile(values[0])
        return result

    def _grad(self, values):

        # WHAT SHOULD BE HERE ???

        grads = np.zeros(self.args[0].size)
        return grads

    # OWN private method
    def _find_quantile(self, weights):
        assert weights.ndim == 1
        results = np.sum(self.simulations * weights, axis=1)
        qindex = min(results.shape[0] - 1, int(results.shape[0] * self.quantile))
        indices = np.argsort(results)
        index = indices[qindex]
        result = results[index]
        return result, index

    def shape_from_args(self):
        """Returns the (row, col) shape of the expression.
        """
        return tuple([self.args[0].size, ])

    def sign_from_args(self):
        """Returns sign (is positive, is negative) of the expression.
        """
        # Same as argument.
        return (self.args[0].is_nonneg(), self.args[0].is_nonpos())

    def is_atom_convex(self):
        """Is the atom convex?
        """
        return True

    def is_atom_concave(self):
        """Is the atom concave?
        """
        return False

    def is_incr(self, idx):
        """Is the composition non-decreasing in argument idx?
        """
        return True

    def is_decr(self, idx):
        """Is the composition non-increasing in argument idx?
        """
        return False

    def get_data(self):
        return [self.simulations, self.quantile]


#
#
########################### test.py ##########################
#

import sys
from cvxpy import *
import dccp
import numpy as np

from weighted_quantile import weighted_quantile

np.random.seed(1)

asset_count = 10
trials = 100
qmedian = 0.5
qrisk = 0.1
min_risk = 1.

# Constants
simulations = (np.random.random(size=(trials, asset_count)) - 0.5) * \
        np.arange(asset_count) * np.arange(asset_count) / asset_count + \
        (np.arange(asset_count) / asset_count - 0.5)
means = np.arange(asset_count) / asset_count - 0.5
print(means)
print(simulations[0, :])

# Vars
x = Variable(asset_count)

initial_weights = np.ones(asset_count, dtype=np.float) / asset_count
best_weights = np.zeros(asset_count, dtype=np.float)
best_weights[-1] = 1

f_risk = weighted_quantile(x, simulations, qrisk)
print("qrisk", f_risk.numeric([initial_weights]))
print("qrisk", f_risk.numeric([best_weights]))  # lower than previous
print("f_risk", f_risk.is_convex())  # true

# Constraints
constraints = [sum(x) == 1,
               x >= 0.0,
               f_risk >= min_risk  # THIS IS NOT is_dsp() HOW TO MAKE IT DSP?
               ]

# Problem
objective = Maximize(sum(x @ means))
problem = Problem(objective, constraints)
for con in constraints:
    print("con", con.is_dcp())

print("problem is DCP:", problem.is_dcp())   # false
print("problem is DCCP:", dccp.is_dccp(problem))  # true
result = problem.solve(method = 'dccp')  # OTHER SOLVERS FAIL
    
print('weights', x.value, "result", result)


```

**Comment by SteveDiamond** [comment]
Does ``dccp`` really work in this case? That's actually quite hilarious and unintended. If you implement the gradient method correctly it might actually be fine to just use ``dccp``. What kind of mapping is weighted_quantile (i.e. R^n -> R or R^n -> R^m)?

**Comment by aisurfer** [comment]
R^n -> R
for 1D vector of weights and 2D vector of simulations we compute a single number

**Comment by aisurfer** [comment]
This is output. Seems f_risk constraint is totally ignored
```
means [-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4]
simulations[0, :] [-0.5        -0.37796755 -0.49995425 -0.37790068 -0.66519057 -1.01915351
 -1.02946324 -0.55675244 -0.36068816  0.71441555]
equal weight qrisk -0.4527674838238247
best mean w qrisk -2.5967685658419515
f_risk is_convex True
constraints is_dcp() True
constraints is_dcp() True
constraints is_dcp() False
problem is DCP: False
problem is DCCP: True
result (0.39929603625876275, 3.5941524769781794, [array([9.06620404e-05, 1.00133430e-04, 1.12785814e-04, 1.30854752e-04,
       1.59117764e-04, 2.08932705e-04, 3.10018343e-04, 5.32168360e-04,
       2.22221787e-04, 9.98133093e-01])], 'Not_converged')
RISK  -2.592363410710413
```

**Comment by SteveDiamond** [comment]
> R^n -> R
> for 1D vector of weights (Variable) and 2D vector of simulations (constant) we compute a single number - summed quantile meaning value at risk of asset portfolio,
> 
> dccp actually does not solve the problem. It just not fails unlike other solvers that expect problem is DCP

Then _grad is simply the gradient. You'll need to play around with the dimensions, try doing it for 1D vectors first.

``f_risk`` is totally ignored because you said the gradient was zero. To emphasize, what you're doing is extremely outside the box and unsupported but it might possibly work. Gradients are only used by dccp, not by cvxpy. You can't implement a pure cvxpy atom without many modifications throughout the code, to inform the compilation process of the atom's properties.

**Comment by aisurfer** [comment]
@SteveDiamond  I implemented _grad() method  as follows (and updated full code snippet)
But there is no effect and solver sets max weight for x with highest mean to maximize objective and TOTALLY ignores f_risk constraint

```
    def _grad(self, values):
        nprint("_grad VALUES", values, "values[0]", values[0], "type", type(values[0]))
        w = values[0]
        result_init, index_init = self._find_quantile(w)   # VALUE AT CURRENT POINT
        nprint("INIT", result_init, index_init, w)
        step = 0.01
        grads = []

        for i in range(w.shape[0]):  # CHECK FOR SMALL CHANGES OF EVERY COORDINATE
            wp = np.copy(w)
            wp[i] += step
            result_p, index_p = self._find_quantile(wp)
            grad = (result_p - result_init) / step
            nprint(i, "DIM", result_p, index_p, wp, "GRAD", grad)
            grads.append(grad)

        grads = np.array(grads)  # HERE WE HAVE VECTOR OF PARTIAL DIFFS
        nprint("/weighted_quantile grads", grads)
        return grads

```

**Comment by SteveDiamond** [comment]
Ok that's too bad, it was worth a try. Now that you've implemented grad though it should be easy to put this in scipy.optimize, which is designed for gradient based optimization. Despite the _grad functions, cvxpy does not use gradient based optimization. The _grad functions are only there for the dccp extension.

**Comment by rileyjmurray** [comment]
With Steven's most recent comment, I think this discussion has come to a close. Further discussion should probably happen on the DCCP repo.
