### ISSUE TITLE
When will python 3.9 be supported?

### ISSUE THREAD

**Issue by jackalack** [cvxpy/cvxpy#1366]
In the cvxpy documentation under `Install`, it is specified that it is only compatible with 3.5, 3.6, or 3.7. Is there a plan or timeline for making it compatible with 3.9?

**Comment by h-vetinari** [comment]
conda-forge supports python 3.9 already;
```
conda config --add channels conda-forge 
conda create --name my_env cvxpy python=3.9
```

**Comment by phschiele** [comment]
@jackalack Python 3.9 should work without problems, the CI tests are already including it. I think it's just a matter of updating the docs, or do you get any specific error when installing with 3.9?

**Comment by jackalack** [comment]
@phschiele and @h-vetinari thank you for your responses. @phschiele to answer your question, I was indeed asking due to the documentation specifying compatibility up to 3.7. I was unsure if there were known issues with 3.8 and 3.9

**Comment by SteveDiamond** [comment]
I changed the documentation.
