### ISSUE TITLE
Install order with numpy can break cvxpy

### ISSUE THREAD

**Issue by naphatkrit** [cvxpy/cvxpy#1367]
**Describe the bug**
Installing a pinned version of numpy together with cvxpy in the same pip command will cause cvxpy to be built against the wrong version of numpy. This is presumably due to pip building all packages first before installing, meaning at build time, cvxpy does not know which version of numpy it should build for.

**To Reproduce**
On a clean python environment (I used the `python:3.7` docker image):

```
$ pip install numpy==1.19.2 cvxpy==1.1.1
...
$ python
Python 3.7.10 (default, Apr 10 2021, 16:02:25)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

If we instead run a command to install numpy first, it works fine:
```
$ pip install numpy==1.19.2 && pip install cvxpy==1.1.12
...
$ python
Python 3.7.10 (default, Apr 10 2021, 16:02:25)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
>>>
```

If we instead pin numpy to its latest version, that also works fine:
```
$ pip install numpy==1.20.3 cvxpy==1.1.1
...
$ python
Python 3.7.10 (default, Apr 10 2021, 16:02:25)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cvxpy
>>>
```
Presumably, this will break on the next major numpy upgrade.

**Expected behavior**
cvxpy should install correctly in all cases, to allow it to be installed as part of a pinned requirements.txt file.

**Version**
 - OS: MacOS 11.12.3, on docker
 - CVXPY Version: 1.1.12

**Comment by h-vetinari** [comment]
You're using two different versions of cvxpy, is that intentional?
```
$ pip install numpy==1.19.2 cvxpy==1.1.1
$ pip install numpy==1.19.2 && pip install cvxpy==1.1.12
$ pip install numpy==1.20.3 cvxpy==1.1.1
```

**Comment by naphatkrit** [comment]
That’s a typo, meant to say 1.1.12

**Comment by h-vetinari** [comment]
Based on the error
```
>>> import cvxpy
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```
it's possible that the wheel builder CI accidentally compiled cvxpy against numpy 1.20, which effectively makes that the lowest supported version. With conda-forge, installing cvxpy is supported for numpy >= 1.17 (and 1.16 if you only need cvxpy 1.1.11).

**Comment by naphatkrit** [comment]
shouldn't cvxpy compile against the lowest supported version of numpy by default, and only fall back to what's installed when present? 

here's my understanding of what's going on when running `pip install numpy==1.19.2 cvxpy==1.1.1`
1. pip downloads all packages
2. pip builds packages that require building. At this time, cvxpy compiles against whatever numpy is installed. Because nothing is installed at this point, it picks the latest version (somehow, not clear to me how).
3. pip installs all packages, which includes the older numpy.

Given that pip provides no install order guarantees (even other package managers don't support this perfectly, e.g. imagine downgrading numpy), I think the safest thing to do is pick the lowest supported numpy. The code shouldn't require any new API versions anyways - if it does, it should update its dependency to point to that version of numpy or higher.

**Comment by h-vetinari** [comment]
I think a key point that might be cause for misunderstanding is whether you compiled the packages yourself? I had assumed for a standard install that pip would install the available wheels for your platform, but perhaps that's not the case?

**Comment by naphatkrit** [comment]
that's a good question. pip is definitely compiling packages manually. What platforms do we build wheels for? I'm just using the standard docker `python:3.7` image (it also repros in `python:3.9` image fwiw).

**Comment by naphatkrit** [comment]
sorry, when i said "packages", i meant cvxpy. pip is compiling cvxpy manually instead of downloading binary wheel.

**Comment by h-vetinari** [comment]
It seems the linux wheels on PyPI for 1.1.12 are missing: https://pypi.org/project/cvxpy/#files ... @SteveDiamond 

@naphatkrit
In the meantime, I would suggest installing [miniforge](https://github.com/conda-forge/miniforge/#download) and then following the installation instructions for conda-forge.

**Comment by naphatkrit** [comment]
gotcha, can someone provide an update here on linux wheels when available? We're not really looking to switch package managers as part of trying out cvxpy. We do have a workaround for now that we would love to remove (basically installing numpy first).

**Comment by h-vetinari** [comment]
For wheels, it seems you're out of luck. I just checked on PyPI, and none of the 1.1-series releases has linux wheels (it should be noted that I'm not a maintainer here, just a drive-by commenter who also happens to maintain the conda-forge packaging side of cvxpy).

So for now you'll have to live with the work-around (_or_ update to the newest numpy also at runtime, _or_ install with conda - I swear it's not rocket science, and generally a better experience than pip, partly for the exact reasons that this thread exists 😉).

**Comment by naphatkrit** [comment]
Why aren’t we willing to provide wheels for Linux? It seems pretty odd to say that cvxpy only works against a set of package managers, but not the default one.

**Comment by naphatkrit** [comment]
Note that lack of prebuilt wheel has other implications. Manual builds take a long time, which our developers pay the cost for when testing against docker images.

**Comment by h-vetinari** [comment]
Well, it's not "we", it's the maintainers here, and packaging for python is a painful and thankless job. Maybe @SteveDiamond & @rileyjmurray can comment, but unless you prepare a PR that runs & builds the various flavours of manylinux-wheels required, we shouldn't use "we".

> It seems pretty odd to say that cvxpy only works against a set of package managers, but not the default one.

It does work without, you "just" have to compile. And - I dare say - if you work in the data science space, conda is becoming the default moreso than pip (though depending on which packages you're using exactly, but certainly if you're doing GPU-heavy things).

PS. Here's a (not-so-recent-anymore) [report](https://ursalabs.org/blog/2019-06-07-monthly-report/) of the maintainers of [arrow](https://arrow.apache.org/), why maintaining wheels was becoming an unbearable overhead, whereas conda just works (by comparison). The wheel-building has since been reinstated, but more or less only because some people stepped up to help.

**Comment by h-vetinari** [comment]
I'll note that https://github.com/cvxpy/cvxpy/blob/master/pyproject.toml already has the correct build metadata, maybe the ordering issue could be fixed with some care around making sure that the installation here is [PEP 517](https://www.python.org/dev/peps/pep-0517/)-conformant (though compilation would then still be necessary).

**Comment by naphatkrit** [comment]
that would be a huge win IMO, so it will at least install correctly even if it compiles. is it a matter of removing setup_requires from setup.py so that it uses the one from pyproject.toml?

**Comment by h-vetinari** [comment]
TBH, I'm not so sure, best thing is to try. 🙃

**Comment by SteveDiamond** [comment]
I'm not very familiar with the details of linux wheels. My understanding from @bstellato is that we need to make "manylinux" wheels, which are not something I know how to make. Currently we provide wheels for Windows and Mac.

**Comment by bstellato** [comment]
It is now much easier than before with cibuildwheel and github actions. I used in in the [qdldl-python wrapper](https://github.com/oxfordcontrol/qdldl-python/blob/master/.github/workflows/build.yml) and @akshayka used it for the [pymde package](https://github.com/cvxgrp/pymde/blob/main/.github/workflows/build.yaml).

**Comment by phschiele** [comment]
Sounds interesting. I also do not have experience with building "manylinux" wheels, but I'd be happy to give it a try in the next few days.

**Comment by akshayka** [comment]
> Sounds interesting. I also do not have experience with building "manylinux" wheels, but I'd be happy to give it a try in the next few days.

@phschiele, that would be amazing! Thanks to your recent PR (#1368), it should hopefully be easier to build manylinux wheels --- cibuildwheel + github actions really does make it a lot easier, like @bstellato.

If you do make an attempt to build manylinux wheels, I'd be happy to answer questions, and help you debug issues you run into.

**Comment by h-vetinari** [comment]
Deserves shout-out: good on you @naphatkrit for taking up the debugging and fixing.

**Comment by phschiele** [comment]
Indeed, great spot @naphatkrit. Can confirm that locally removing `scs` from `setup.py` fixes the issue described in the initial post. Your PR there is also merged already, so updating to the next version of `scs` should fix things on cvxpy side as well.

**Comment by naphatkrit** [comment]
it turns out even ecos has the same problem at python 3.9 (but not 3.7 and below because it provides prebuilt wheels for those). i've opened a PR there https://github.com/embotech/ecos-python/pull/30.

Regarding making scs optional, it's not needed to solve this problem. It might be nice though have a holistic approach where we allow users to specify which solver they want at install time and only install the libraries for that solver. That said, this doesn't block any fixes.

**Comment by rileyjmurray** [comment]
@naphatkrit the main cvxpy package will always require SCS, ECOS, and OSQP. The reason is that most users, unfortunately, don't recognize the distinction between cvxpy as a modeling platform and the underlying solvers, so requiring them to install solvers separately is a barrier to our least experienced users. Michael Grant made a conda package called ``cvxpy-base`` that doesn't install any solvers by default (he made it for licensing reasons, though).

**Comment by SteveDiamond** [comment]
Linux manywheels are now built, and cvxpy-base is available on pypi as well.
