### ISSUE TITLE
SCS lasso example not working anymore

### ISSUE THREAD

**Issue by h-vetinari** [cvxpy/cvxpy#1369]
Hey, I'm trying to prepare a PR for updating the SCS python bindings a bit, and started rerunning the ipynb [notebook](https://github.com/bodono/scs-python/blob/master/test/scs_benchmarks.ipynb) in the `test` folder.

The last change was in in pre-1.0 times, which means the expectation is not that this runs out of the box; however, after some trivial adaptations, the following code fails with an internal cvxpy-error that's not enough to help me determine the cause.

```python
import numpy as np
import cvxpy
import scipy
import scs

# Lasso
np.random.seed(hash('lasso') % 2 ** 31)

# Dimensions
n = 100
m = 50

x_true = scipy.sparse.rand(n, 1, density=0.1) 
A = scipy.sparse.random(m, n, density=0.2, data_rvs = np.random.randn)
b = A @ x_true + 0.1 * np.random.randn(m, 1)
b = np.array([x for x in b.flat])
mu = 1

# Problem construction
x = cvxpy.Variable(n)
objective = cvxpy.Minimize(0.5 * cvxpy.sum_squares(A @ x - b) + mu * cvxpy.norm1(x))
prob = cvxpy.Problem(objective)

prob.solve(solver='SCS', verbose=True)
prob.solve(solver='SCS', verbose=True, acceleration_lookback=0)
```

Results in:
```
===============================================================================
                                     CVXPY                                     
                                    v1.1.12                                    
===============================================================================
(CVXPY) May 13 08:24:12 PM: Your problem has 100 variables, 0 constraints, and 0 parameters.
[...]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```

**Comment by SteveDiamond** [comment]
Can you try updating to master? There might be a bug in 1.12 that we fixed.

**Comment by h-vetinari** [comment]
Hey @SteveDiamond, thanks for the quick response. Is there a new version forthcoming soon (e.g. after CI is fixed)? It would make my testing life much easier...

**Comment by SteveDiamond** [comment]
Sure we can do a new patch when the CI is in better shape.

**Comment by h-vetinari** [comment]
> Sure we can do a new patch when the CI is in better shape.

No rush, but just pinging on this since the gh actions PR got merged.

**Comment by h-vetinari** [comment]
I built a conda artefact for https://github.com/cvxpy/cvxpy/commit/86307f271819bb78fcdf64a9c3a424773e8269fa in https://github.com/conda-forge/cvxpy-feedstock/pull/57, and can confirm that this works now - closing

**Comment by SteveDiamond** [comment]
@h-vetinari we have a new version now.
