### ISSUE TITLE
Switch testing from nose to pytest

### ISSUE THREAD

**Issue by h-vetinari** [cvxpy/cvxpy#1371]
Nose is dead as a doornail - [repo](https://github.com/nose-devs/nose/) hasn't been updated in 5 years. It's time to switch to pytest! 🤩 

Luckily, the change is as painless as can be, because the current test suite works out of the box with pytest - I'm already [doing that](https://github.com/conda-forge/cvxpy-feedstock/blob/master/recipe/meta.yaml#L54) in the conda-forge recipe. 🥳

**Comment by SteveDiamond** [comment]
Thanks! We actually use pytest. Is nose still listed somewhere?

**Comment by h-vetinari** [comment]
Still shows two hits currently (hence why I assumed it's still in use - glad to hear you switched already!): https://github.com/cvxpy/cvxpy/search?q=nose
