### ISSUE TITLE
constructing a convex quadratic programming problem equivalent to maximum Sharpe ratio

### ISSUE THREAD

**Issue by akhorshidi** [cvxpy/cvxpy#1373]
**Describe the bug**
The maximum Sharpe ratio problem have a quasiconvex/concave objective function. Then, we cannot solve it directly using CVXPY. However as shown in the following document, we can transform it into a convex quadratic to use cvxpy: [https://people.stat.sc.edu/sshen/events/backtesting/reference/maximizing%20the%20sharpe%20ratio.pdf](https://people.stat.sc.edu/sshen/events/backtesting/reference/maximizing%20the%20sharpe%20ratio.pdf)

Here is what I've implemented so far to find the portfolio maximizing the Sharpe ratio, but it still evaluated to an error:

`DCPError`: Problem does not follow DCP rules. Specifically: The objective is not DCP. Its following subexpressions are not: Promote(var363, (3,)) @ var362

**To Reproduce**
```
import numpy as np
import cvxpy as cvx;
return1 = np.random.normal(loc=0.05, scale=0.25, size=252)
return2 = np.random.normal(loc=0.01, scale=0.2, size=252)
return3 = np.random.normal(loc= -0.05, scale=0.15, size=252)
returns = np.array([return1, return2, return3])
# risk free rate
rf = 0.01;
# number of stocks m is number of rows of returns
m = returns.shape[0]
#covariance matrix of returns
cov = np.cov(returns)
# vector of mean returns
returns_mean = returns.mean(axis=1)
# x variables (to be found with optimization)
x = cvx.Variable(m)
# scaled/transformed weights
lamda = cvx.Variable()
y = cvx.multiply(lamda, x)
# portfolio return
mu = x @ returns_mean
# excess returns
muhat = mu - rf
# portfolio var
portfolio_variance = cvx.quad_form(y, cov)
# transformed variable y = lamda*x => sum(y) = lamda * sum(x) = lamda * 1 = lamda
#objective function
objective = cvx.Minimize(portfolio_variance)
# constraints
constraints = [(returns_mean - rf).T @ y == 1, cvx.sum(y) == lamda, lamda >= 0]

cvx.Problem(objective, constraints).solve()

x_values = y.value / lamda.value
x_values.round(2)
```

**Expected behavior**
Is my implementation sound in this strategy?

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: Win 10 Python 3.8.8
 - CVXPY Version: 1.1.12

**Additional context**

**Comment by SteveDiamond** [comment]
You can't multiply two variables together as in
```
# x variables (to be found with optimization)
x = cvx.Variable(m)
# scaled/transformed weights
lamda = cvx.Variable()
y = cvx.multiply(lamda, x)
```
You'll need to try again with the problem formulation.

**Comment by akhorshidi** [comment]
> 
@SteveDiamond 
Thank you for your comment. 
Thanks to the source codes of the PyPortfolioOpt, I've reformulated the problem, and now it runs without error. However, division by a nearly zero value amplifies the results! 

```
print(y.value)
[ 12.41775744   3.20056019 -15.61831763]
print(lamda.value)
3.6854372922814357e-22
print(x_values)
[ 3.36941222e+22  8.68434310e+21 -4.23784653e+22]

```

**Comment by phschiele** [comment]
You would need to add bounds on the weights to get sensible results (multiplying the rhs by `lamda` to get the constraint for the transformed variables).
