### ISSUE TITLE
conda bad environment name

### ISSUE THREAD

**Issue by ben-schwen** [cvxpy/cvxpy#1384]
Tried to install cvxpy as described [here](https://www.cvxpy.org/install/index.html), but named my conda environment `cvx` instead of the suggested cvxpy. Apparently this leads to a bug where functions are not loaded.

**To Reproduce**
Create environment:
```
conda create --name cvx
conda activate cvx
```
Install via pip or conda forge (both have the same error)
```
pip install cvxpy
```
Actual error after launching python:
```
import cvxpy as cp
cp.Variable(1)
``` 

**Output**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cvxpy' has no attribute 'Variable'
```

Using the suggested name `cvxpy` also for the conda environment works like a charm.

**Version**
 - OS: `Ubuntu 20.04`
 - CVXPY Version: `1.1.12`

**Comment by h-vetinari** [comment]
> Install via pip or conda forge (both have the same error)

In case you tried with `pip` first, please create a new environment and install with conda first:

```
conda create -n cvx_env -c conda-forge "python=3.8" cvxpy  # of course, you can change the python version
conda activate cvx_env
python
[...]
```

I've tried and this works for me.

**Comment by ben-schwen** [comment]
@h-vetinari thanks for the answer, but the point of the whole bug is to name the conda environment `cvx` and not `cvx_env`

**Comment by h-vetinari** [comment]
The name of the environment has no bearing on the functioning of the package.

```
C:\Users\[...]\Dev>conda create -n cvx -c conda-forge "python=3.8" cvxpy
[...]
C:\Users\[...]\Dev>conda activate cvx
(cvx) C:\Users\[...]\Dev>python -c "import cvxpy as cp; x = cp.Variable(1); print(repr(x))"
Variable((1,))
```
