### ISSUE TITLE
Risk Parity and Entropy

### ISSUE THREAD

**Issue by tschm** [cvxpy/cvxpy#1390]
Hi,
I am running a simple strategy essentially allocating the same weight to any asset, e.g.

```
class _ParityWeight(EquityPortfolio):
    def __init__(self, assets):
        super().__init__(assets)

        self.objective = cvx.Maximize(cvx.sum(cvx.entr(self.weights)))

        self.constraints = [self.l_bound <= self.weights,
                            self.weights <= self.u_bound,
                            self.leverage == 1.0]
```

This works like a charm. In case l_bound = 0 and u_bound = 1, all assets get exactly the same weight as entropy is a concept seeking balance. 

In a variation of this idea I try to find balance in the vector volatility_i * weight_i (some call this risk-parity).  
```
class _ParityVolatility(EquityPortfolio):
    def __init__(self, assets):
        super().__init__(assets)

        weighted_vola = cvx.multiply(self.volatility_assets, self.weights)

        self.objective = Maximize(cvx.sum(cvx.entr(weighted_vola)))

        self.constraints = [self.l_bound <= self.weights,
                            self.weights <= self.u_bound,
                            self.leverage == 1.0]
```
This seems to allocate more weight to more volatile assets exactly the opposite of my intention. Did I misunderstand entropy? Or the concept of cvx.multiply? 

Many thanks

**Comment by tschm** [comment]
@phschiele?

**Comment by tschm** [comment]
Here's a little script you could use for experiments

```
import cvxpy as cp

# Volatilities of two assets
volatility = [0.1, 0.2, 0.15, 0.3, 0.1]
weight = cp.Variable(shape=len(volatility))
#risk_weight = cp.multiply(weight, volatility) 
risk_weight = cp.Variable(shape=len(volatility))
print(type(risk_weight))
obj = cp.Maximize(cp.sum(cp.entr(risk_weight)))
constraints = [weight >= 0,
               weight <= 1,
               cp.sum(weight)==1,
               risk_weight == weight*volatility]
            

prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.ECOS, verbose=True)

# Print result.
print("\nThe optimal value is:", prob.value)
print('\nThe optimal solution is:')
print(risk_weight.value)
print(weight.value)
```

**Comment by tschm** [comment]
Here's a little script for your experiments

```
import cvxpy as cp
import numpy as np

# Volatilities of two assets
n = 5

volatility = cp.Parameter(shape=(n))
weight = cp.Variable(shape=(n))
obj = cp.Maximize(cp.sum(cp.entr(cp.multiply(volatility, weight))))
constraints = [weight >= np.zeros(5),
               weight <= np.ones(5),
               cp.sum(weight)==1]

volatility.value = [0.1, 0.2, 0.15, 0.3, 0.1]
prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.ECOS, verbose=True)
print(prob)

# Print result.
print("\nThe optimal value is:", prob.value)
print('\nThe optimal solution is:')
print(volatility.value)
print(weight.value)
print(np.sum(weight.value))
```

**Comment by phschiele** [comment]
Hi @tschm!
I usually think of a bit of a different formulation when it comes to risk parity (e.g. you do not consider covariances), but still, it would make sense that higher vola assets should get less weight in general.

I actually just tried it out with a script very similar to the one you just posted :smile: 
Perhaps its easiest to consider a two asset-case with weights x and y first. Your objective function (without weighting) is
`- x log(x) - (1-x) log (1-x)` and by taking the derivative we can see that indeed the optimal solution is `x=y=0.5`.

Now lets allow a weighting of one of our assets by a factor `a>1`. Our objective becomes:
`- ax log(ax) - (1-x) log (1-x)`, and after taking the derivative and some moving around we see that at our solution `x<0.5` and `y>0.5` must hold. This extends to more assets as well, such that all assets weighted by a factor `<1` will be weighted more than `1/n` and vice versa for factors `>1` (e.g. try out the following `volatility = [1.1, 1.2, 0.9, 0.8]`).

**Comment by tschm** [comment]
Hi @phschiele 
will try with your numbers now. Ignoring the volatility weighting as in

```
import cvxpy as cp
import numpy as np

# Volatilities of two assets
n = 5

weight = cp.Variable(shape=(n))
obj = cp.Maximize(cp.sum(cp.entr(weight)))
constraints = [weight >= np.zeros(5),
               weight <= np.ones(5),
               cp.sum(weight)==1]

prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.ECOS, verbose=True)
print(prob)

# Print result.
print("\nThe optimal value is:", prob.value)
print('\nThe optimal solution is:')
print(weight.value)
print(np.sum(weight.value))

```
works beautifully.

**Comment by tschm** [comment]
Got it working for the volatility scaled version

```
import cvxpy as cp
import numpy as np

# Volatilities of 5 assets
n = 5

volatility = cp.Parameter(shape=(n))
weight = cp.Variable(shape=(n))
risk_weight = cp.multiply(volatility, weight)

obj = cp.Maximize(cp.sum(cp.entr(risk_weight)))

constraints = [weight >= np.zeros(5) * cp.sum(weight),
               weight <= np.ones(5) * cp.sum(weight),
               cp.sum(risk_weight)==1]

volatility.value = [0.1, 0.2, 0.15, 0.3, 0.1]

prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.ECOS, verbose=True)
print(prob)

# Print result.
print("\nThe optimal value is:", prob.value)
print('\nThe optimal solution is:')

# All entries in the risk_weight vector should be constant
print(risk_weight.value)

# Rescale the weight vector
print(weight.value / np.sum(weight.value))
```

**Comment by phschiele** [comment]
So if you just want the "risk_weight" to be equal, it would be equivalent to do 
```py
volatility = np.array([0.1, 0.2, 0.15, 0.3, 0.1])
reciprocal = 1/volatility
weights = reciprocal/sum(reciprocal)
print(weights)
>>> [0.28571429 0.14285714 0.19047619 0.0952381  0.28571429]
```
which is inverse volatility position sizing.
But perhaps you want to add further constraints or modify your objective, such that the simple 1/vol methodology no longer works.

**Comment by tschm** [comment]
Yes, it's all about the extra constraints. What I did wrong in my first attempt was the constraint cp.sum(risk_weight)==1 vs. cp.sum(weight) == 1. It helps to maximize the entropy of a vector of length 1. Many thanks for your help on that one :-)
