### ISSUE TITLE
CVXPY not working with scipy.sparse matrices and verbose=True

### ISSUE THREAD

**Issue by Michael-git96** [cvxpy/cvxpy#1395]
**Describe the bug**
I recently upgraded cvxpy to version 1.1.12 and now when I run an optimisation with a sparse constraint matrix and verbose=True, I get an error.

**To Reproduce**
import cvxpy as cp
import numpy as np
from scipy import sparse

x = cp.Variable((10, 1))
c = -np.ones((10,))

objective = cp.Minimize(c.T@x)

G = sparse.eye(10)
h = np.ones((10, 1))*10
prob = cp.Problem(objective, [G@x <= h])

res = prob.solve(verbose=False)

**Expected behavior**
It used to work fine with the previous version, and it still works fine if verbose=False. Setting verbose=False in the code above will lead to the correct result.

**Version**
 - OS: Windows
 - CVXPY Version: 1.1.12

**Comment by SteveDiamond** [comment]
This works on master. We will put out a patch soon, for the moment try installing from source.

**Comment by Michael-git96** [comment]
Ok, thank you, I will install from the source and wait for the patch. If this has already been fixed I will just go ahead and close this issue.
