### ISSUE TITLE
Quasiconvex/concave programming problem with addition operator

### ISSUE THREAD

**Issue by path-doc** [cvxpy/cvxpy#1397]
Following on from the conversation in google groups:
https://groups.google.com/g/cvxpy/c/Ufz2dez8KnU

import cvxpy as cp

x1 = cp.Variable()
x2 = cp.Variable()
BC = [3 * x1 + x2 <= 100]

Consider the two rather standard quasi-convex programs in cvxpy:

The following QCP solves without much trouble:

objCD = cp.sqrt(x1) * cp.sqrt(x2)
probCD = cp.Problem(cp.Maximize(objCD), BC)
probCD.solve(qcp=True, verbose=True)
print("x1 = ", x1.value, "and x2 = ", x2.value)

Whereas the following fails:

objCES = (cp.sqrt(x1) + cp.sqrt(x2)) ** 2
probCES = cp.Problem(cp.Maximize(objCES), BC)
probCES.solve(qcp=True, verbose=True)
print("x1 = ", x1.value, "and x2 = ", x2.value)

**Comment by path-doc** [comment]
I'm starting to think that the real problem is that the CES objective function involves the product of two posynomials. Might this be what's going on behind the scenes?

**Comment by SteveDiamond** [comment]
It's probably a numerical issue, rather than anything to do with the mathematical type of the problem.

**Comment by path-doc** [comment]
Just to give you a bit of context, in case you were unaware, CD stands for Cobb-Douglas and CES stands for Constant Elasticity of Substitution. These functions feature very widely in economics: both as production and utility functions. 

For the CES function, you would typically assume a form:

(a1 * x1 ** b + a2 * x2 ** b) ** ( 1 / b)

for some 0 < b < 1 and a1 + a2 = 1.

For b -> 0, the CES specialises to the CD function (x1 ** a1) * (x2 ** a2) 

For b -> -infty, it specialises to the Leontief function min( x1 / a1 , x2 / a2).

See https://economics.stackexchange.com/questions/361/how-can-i-obtain-leontief-and-cobb-douglas-production-function-from-ces-function

The n-variable case for large n shows up a lot in Computable General Equilibrium modelling. I'm currently looking at your work on QCP/GeomP to generalise existing approaches by avoiding derivatives and providing fast solutions.

**Comment by rileyjmurray** [comment]
@SteveDiamond it's weird that regarding numerical issues, MOSEK, SCS, ECOS, and CVXOPT all fail more or less immediately. SCS complains about degenerate problem data (see below):
```
Preparing to bisect problem

minimize 0.0
subject to 3.0 @ var0 + var1 <= 100.0
           var3728 <= var3740 + var3752
           SOC(reshape(-param3712 + 1.0, (1,), F), Vstack(reshape(-param3712 + -1.0, (1, 1), F), reshape(2.0 @ var3728, (1, 1), F)))
           SOC(reshape(var0 + 1.0, (1,), F), Vstack(reshape(var0 + -1.0, (1, 1), F), reshape(2.0 @ var3740, (1, 1), F)))
           SOC(reshape(var1 + 1.0, (1,), F), Vstack(reshape(var1 + -1.0, (1, 1), F), reshape(2.0 @ var3752, (1, 1), F)))

WARN: m less than n, problem likely degenerate
Finding interval for bisection ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/riley/Documents/Research/software/cvxpydev/cvxpy/cvxpy/problems/problem.py", line 394, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/riley/Documents/Research/software/cvxpydev/cvxpy/cvxpy/problems/problem.py", line 821, in _solve
    chain.reduce(), solver=solver, verbose=verbose, **kwargs
  File "/home/riley/Documents/Research/software/cvxpydev/cvxpy/cvxpy/reductions/solvers/bisection.py", line 206, in bisect
    problem, t, solver, low, high, max_iters_interval_search
  File "/home/riley/Documents/Research/software/cvxpydev/cvxpy/cvxpy/reductions/solvers/bisection.py", line 95, in _find_bisection_interval
    raise error.SolverError("Unable to find suitable interval for bisection.")
cvxpy.error.SolverError: Unable to find suitable interval for bisection.
```
Only SCS reports a failure due to trying to find an interval. All other solvers return a generic solver failure. If the issue is in finding the interval for bisection, then maybe it would be helpful if QCP allowed users to pass in interval information. Pinging @akshayka.

**Comment by phschiele** [comment]
@rileyjmurray Wich version of SCS are you on? I just ran the script above and while I get some `Solution may be inaccurate` warnings, eventually the solution `x1 =  16.670182250645297 and x2 =  49.98943470319022` is found. 
`CPLEX` also finds `x1 =  16.666969934058425 and x2 =  49.99909009046979` with no inaccuracy warning.

**Comment by path-doc** [comment]
Can you clarify that that result is for the CD problem, not the CES?

**Comment by phschiele** [comment]
@path-doc Thanks for clarifying, I'm getting the same error as @rileyjmurray for the CES function.

**Comment by akshayka** [comment]
@riley, users can already specify the bisection interval, via the kwargs `low` and `high`. https://www.cvxpy.org/tutorial/dqcp/index.html#solving-dqcp-problems

The issue is numerical. Somehow the canonicalized problem becomes very poorly scaled.

When I multiply the objective by 1/1000, and solve with MOSEK, I get

```
x1 =  8.336601640499596 and x2 =  74.99013270688198
```

which appears to be correct.

This suggests that we should really come up with an automatic scaling strategy, as we've discussed on and off for a while.
