### ISSUE TITLE
Combining Boolean and non-boolean vairables into single vector

### ISSUE THREAD

**Issue by armarion** [cvxpy/cvxpy#1402]
I am doing a mixed-integer optimization that involves several matrix operations on my Boolean variable vector:

w = cp.Variable(n, boolean=True)

Currently the variable w is initialized as Boolean with length n, but now I want to set the first element to be non-Boolean. Is there a way to change the Boolean property for a subset of the variable vector w? Or, could I create two variable vectors and then combine them into a single vector?

**Comment by phschiele** [comment]
@armarion You can do something like:
```py
y_real = cvxpy.Variable(n)
y_bool = cvxpy.Variable(m, boolean=True)
y = cvxpy.hstack([y_real, y_bool])
```
Hope that helps :)

**Comment by armarion** [comment]
Yes! Exactly what I needed. Thank you!
