### ISSUE TITLE
Add a relative entropy atom (consistent with SciPy's rel_entr).

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1406]
CVXPY has a ``kl_div`` atom that's consistent with SciPy's ``kl_div``. SciPy also has a function called ``rel_entr`` that only differs from ``kl_div`` by a linear expression. The ``rel_entr`` function is consistent with Wikipedia's definition of relative entropy and KL divergence (that is, Wikipedia considers these as two names for the same function).

We should add an elementwise ``rel_entr`` atom to CVXPY to be consistent with SciPy, and expose the more "canonical" relative entropy function in a natural way. This should be very easy to implement. If someone wants to contribute this atom we'd need (1) the atom itself, (2) some test cases for the atom, (3) web documentation for the atom.

See also #733.

**Comment by Michael-git96** [comment]
@rileyjmurray - I would be up to give it a try if no one else has already started working on it?

**Comment by phschiele** [comment]
@Michael-git96 I have also just started with this issue. Let's align through discord.

**Comment by rileyjmurray** [comment]
Closed by #1427 and #1439.
