### ISSUE TITLE
Demo for "Mixed-integer quadratic program" can not run

### ISSUE THREAD

**Issue by Harden1313** [cvxpy/cvxpy#1407]
**Describe the bug**
In the Official website ”Mixed-integer quadratic program“，the following demo is not work,it can't run.

when I run, it produce the following error:
cvxpy.error.SolverError: Either candidate conic solvers (['GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg, Zero), or there are not enough constraints in the problem.

I don't know how to figure out,help

**Comment by SteveDiamond** [comment]
Do ``prob.solve(solver=cp.ECOS_BB)``.

**Comment by 7summer** [comment]
when I use ECCOS_BB, it produce the following error:
UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.

**Comment by SteveDiamond** [comment]
Make sure you're using the latest cvxpy.
