### ISSUE TITLE
Not able to install cvxpy

### ISSUE THREAD

**Issue by rishik-00** [cvxpy/cvxpy#1409]
I tried installing cvxpy using pip in a virtual environment but it is showing me errors, I have also tried to install it by downloading the wheel file but that too shows same error, I have already upadated my build tools using https://visualstudio.microsoft.com/downloads/ this link. 
![Screenshot (9)](https://user-images.githubusercontent.com/43490153/120478018-09ca6000-c3ca-11eb-88ed-3982802cb067.png)
![Screenshot (10)](https://user-images.githubusercontent.com/43490153/120478040-0f27aa80-c3ca-11eb-8e28-b9bf2c813b06.png)
![Screenshot (11)](https://user-images.githubusercontent.com/43490153/120478045-0fc04100-c3ca-11eb-958f-28ea2e76a061.png)

**Comment by rishik-00** [comment]
I think the issue is with build tools only, I have downloaded but how do i make sure it is using the latest tools only and how do i check what version of build tools do i have

**Comment by SteveDiamond** [comment]
You visited this link "https://visualstudio.microsoft.com/visual-cpp-build-tools/"? I'm surprised the wheel doesn't work. That's too bad.

**Comment by phschiele** [comment]
@rishik-00 It looks like you are trying to install an older version of cvxpy, can you try to install the most recent one?
