### ISSUE TITLE
How to Suppress / Backward map the cvxpy's transformed problem?

### ISSUE THREAD

**Issue by pqrz** [cvxpy/cvxpy#1410]
I would began by saying, Cvxpy is one of the most well-performant modelling framework in terms of speed, simplicity and features.

This is a question / request for a issue we facing with Cvxpy.
Given a optimization problem to Cvxpy, it applies heavy transformation on it before submitting it to solver.

But we require to submit raw / untransformed problem to the solver (since we want to interpret infeasibility report, other insights from the solver - e.g. Mosek, Gurobi).

Is there a way to:

1. Either completely suppress the Cvxpy's transformation?
2. Or somehow map the transformed problem back to the original / raw problem?

**Comment by SteveDiamond** [comment]
Thanks so much for the kind words! Could you be more specific about what you need? The full generality transformation is very complicated so it's easier to look at specific use cases. For example, are you interested in the largest feasible set of constraints? Or in getting lots of information for a specific problem type, like a LP?

**Comment by pqrz** [comment]
Thank you for your interest.

Generally speaking, we are interested in mapping all the constraints and variables from transformed_problem back to original_problem. Isn't cvxpy already doing this for extracting the variables values of original_problem after solver finishes?

Specifically speaking, just returning largest feasible set of constraints would perfectly fulfill our immediate needs.

**Comment by SteveDiamond** [comment]
If you do ``problem.get_problem_data(solver)`` you can get all the information cvxpy has. You want to look at the ``param_prob`` object, documented in ``cone_matrix_stuffing.py``. You'll have to play around with it and look at the fields. Basically the variables are stored as a a map of ``var.id`` to offset in a single aggregate variable, and the constraints are stored as a list so you can just see which ones are from the original problem.

**Comment by pqrz** [comment]
Thanks Steve! `problem.get_problem_data(solver)` looks very promising.

I had few doubts:
* Just in case, do we also have a tutorial / example around `problem.get_problem_data(solver)` for extracting original variables / constraints or deep diving into Cvxpy's codebase is the only way out?
* On a sidenote: Is it safe to assume **"Cvxpy only introduces new variables, but doesn't change the ordering of original variables"**? (since in that case, for extracting original variables - we can easily add a information_flag: `binary=True` and remove it later)

**Comment by SteveDiamond** [comment]
Sorry there is not tutorial. This is not a documented feature, we provide it for our own use and situations like this where someone wants all this information.

"Cvxpy only introduces new variables, but doesn't change the ordering of original variables" This is true. But you can very easily see the ordering of the variables in the ``var_id_to_col`` field. This gives the offset of the variable into a the final aggregation of all variables into a single vector (i.e. the ordering of all variables).

**Comment by pqrz** [comment]
Actually, we are working on backward-mapping of constraints (i.e. from transformed_problem to original_problem).

During most of the transformations, Cvxpy indeed is preserving backward-mapping in **inverse_data**, just not for [aux_constr](https://github.com/cvxpy/cvxpy/blob/693a58a7d784bca7c0b6460f462ec22326555f6d/cvxpy/reductions/canonicalization.py#L67).

Any specific reason for not preserving backward-mapping for **aux_constr**?

**Comment by SteveDiamond** [comment]
The purpose of the existing backward mapping is to recover the values of the original variables and the dual values of the constraints. aux_constr are not present in the original problem so are not relevant to this task.

**Comment by pqrz** [comment]
* Query: Is the second statement **_aux_constr are not present in the original problem_** perfectly true? I mean isn't the **aux_constr** contributing partially to the original_constraint?
* Example: For a sample quadratic constraint:

> The original constraint 
>```python
>c = x.T @ Q @ x  +  A @ x   <=   b
>```
>is getting transformed to
>```python
>canon_constr  = y  +  A @ x   <=   b
>aux_constr    = SOC(y, Q_new @ x)     # where Q_new is the Quadratic to Conic equivalent of original Q matrix
>```
I may be wrong, feel free correct me!

**Comment by SteveDiamond** [comment]
That's true, the aux_constr are related to the original problem. But their dual variables don't carry any information about dual variables of the original problem.

**Comment by pqrz** [comment]
That makes sense, Thanks!
-  So, we now tried to add this simple change (i.e. backward-mapping of **aux_constr**) in our custom Cvxpy. Change snippet (only Line 70 to Line 77): 

```python
62         for constraint in problem.constraints:
63                 # canon_constr is the constraint rexpressed in terms of
64                 # its canonicalized arguments, and aux_constr are the constraints
65                 # generated while canonicalizing the arguments of the original
66                 # constraint
67                 canon_constr, aux_constr = self.canonicalize_tree(
68                     constraint)
69                 canon_constraints += aux_constr + [canon_constr]
70[new]            #####------------ CHANGE START ------------#####
71[new]            # inverse_data.cons_id_map.update({constraint.id: canon_constr.id})
72[new]            if aux_constr:
73[new]                new_cons_id_list  = [(constr_i.id, constr_i.size) for constr_i in (aux_constr + [canon_constr])]
74[new]                inverse_data.cons_id_map.update({constraint.id: new_cons_id_list})
75[new]            else:
76[new]                inverse_data.cons_id_map.update({constraint.id: canon_constr.id})
77[new]            #####------------ CHANGE END ------------##### 
78         new_problem = problems.problem.Problem(canon_objective, canon_constraints)
```
- But, we aren't fully sure if this implementation is indeed correct. If possible, could you once confirm its correctness, given the purpose is:

>Purpose: To only get fully exhaustive inverse_data, i.e. : 
>```python
>data, chain, inverse_data = prob.get_problem_data(cp.MOSEK)
>```
