### ISSUE TITLE
pip installation of cvxpy broken

### ISSUE THREAD

**Issue by samfux84** [cvxpy/cvxpy#1418]
**Describe the bug**
When trying to install cvxpy with the pip option --no-deps, then it still tries to install numpy and scipy.

Originally I just wanted to install cvxpy for Python 3.8.5 (which has already numpy 1.19.2 and scipy 1.6.3 installed). Apparently cvxpy is not happy about those versions for whatever reason. So as a next step I tried to actively prevent cvxpy from installing numpy and scipy by adding the pip option --no-deps, which still does not work.

What does it take to install cvxpy without destroying the existing setup of Python packages?

**To Reproduce**
pip install --no-deps cvxpy

**Expected behavior**
When I specify the --no-deps option, then I expect that pip only installs the package I am asking for and not numpy and scipy

**Output**
I-

**Version**
 - OS: CentOS 7.9
 - CVXPY Version: 1.1.3

**Additional context**
-

**Comment by phschiele** [comment]
@samfux84 Is it a typo, or are you actually using CVXPY 1.1.3? In this case, I would first try to use CVXPY 1.1.13.

I have tried to replicate your setup in docker:
```Dockerfile
FROM centos/python-38-centos7
RUN pip install numpy==1.19.2 scipy==1.6.3 && \
    pip install cvxpy && \
    pip list
```

And it seems to work fine for me. 
```bash
Package    Version    
---------- -----------
cvxpy      1.1.13     
ecos       2.0.7.post1
numpy      1.19.2     
osqp       0.6.2.post0
pip        19.3.1     
qdldl      0.1.5.post0
scipy      1.6.3      
scs        2.1.4      
setuptools 41.6.0     
```

If the problem persists, it would be great if you could add some console output.

**Comment by samfux84** [comment]
Thank you for your reply.

The installation worked now.
