### ISSUE TITLE
Add build-backend="setuptools.build_meta" in cvxpy pyproject.toml

### ISSUE THREAD

**Issue by ash0707** [cvxpy/cvxpy#1423]
**Describe the bug**
My organization deploys applications using virtualenv with --system-site-packages. I am hitting an error while installing an application which uses cvxpy. The error is:
 AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

The issue is described at https://github.com/pypa/setuptools/issues/1694, however a later version of setuptools also does not fix it for cvxpy. Apparently a solution is to add
build-backend="setuptools.build_meta" in pyproject.toml file - which I see is missing for cvxpy. Could you please consider adding this?

 - CVXPY Version: All

**Comment by SteveDiamond** [comment]
Ok I made the requested change.

**Comment by ash0707** [comment]
Steve, do you know when a next release is scheduled?

**Comment by SteveDiamond** [comment]
We decided in the dev channel to roll back this change. @ash0707 the desired change is present in version 1.1.14, but will rolled back in 1.1.15.
