### ISSUE TITLE
dual variables for SciPy LP solver interfaces 

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1425]
From the SciPy user digest, as of SciPy 1.7.0:

> When ``linprog`` is used with ``method`` ``'highs'``, ``'highs-ipm'``, or
> ``'highs-ds'``, the result object now reports the marginals (AKA shadow
> prices, dual values) and residuals associated with each constraint.

Adding support for this would follow up on  #1416. Pinging @Michael-git96.

**Comment by Michael-git96** [comment]
@rileyjmurray - thanks for letting me know, glad to see the dual variables are returned for the HiGHS solvers in the latest SciPy version. I will create a pull request linked to this issue.
