### ISSUE TITLE
Add an interface to the highs MIP solver

### ISSUE THREAD

**Issue by brunorigal** [cvxpy/cvxpy#1443]
Apparently [Highs](https://github.com/ERGO-Code/HiGHS/blob/87ca783572a0ad8ee8a8b98f73585ae58d2e0032/examples/call_highs_from_python.py) includes an MIP solver. I tested the LP solver which is really fast and scalable. As MIP solving is based on LP problems, I assume that it will be also efficient for MIP solving. As efficient open source MIP solvers are rare, I thought it may be interesting to add it to cvxpy.

**Comment by rileyjmurray** [comment]
It should be easy for us to add this feature once it's accessible through SciPy.

**Comment by brunorigal** [comment]
I started a discussion [here](https://github.com/scipy/scipy/issues/14455), if you have some insights.

**Comment by brunorigal** [comment]
The MIP option is now in scipy with the integrality option [here](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.linprog.html#scipy.optimize.linprog).

**Comment by Michael-git96** [comment]
@brunorigal - Thanks for letting us know! I can start working on getting the HiGHs MIP solver integrated, it should be fairly straightforward.

**Comment by tasseff** [comment]
If it's helpful at all, I have what's probably a rough start on a fork [here](https://github.com/tasseff/cvxpy). I'm not completely familiar with cvxpy's internals, though, so I may be missing some important pieces.

**Comment by SteveDiamond** [comment]
The fork looks reasonable. There are a few changes required but we can easily help with those if you make a PR.
