### ISSUE TITLE
Check if a "solution" satisfies all of a problem's constraints?

### ISSUE THREAD

**Issue by chrisyeh96** [cvxpy/cvxpy#1452]
Is there any way currently in CVXPY to check if a particular "solution" satisfies all of the constraints? There is a [StackOverflow post](https://stackoverflow.com/q/16974122) from 2013 that asks about this, but the answer proposed no longer works in the current version of CVXPY.

For example, consider the following problem:

```python
import cvxpy as cp
x = cp.Variable(1, name='x')
y = cp.Variable(1, name='y')
prob = cp.Problem(
    objective=cp.Minimize(x**2 + y**2),
    constraints=[x >= 1, y >= 2])

# Now I want CVXPY to check if (x=0, y=2) is a valid solution (it clearly is not).
# I would like cvxpy to have the ability to check something like:
assert not prob.is_valid({
    'x': 0,
    'y': 2
})
```

**Comment by SteveDiamond** [comment]
Assign values to variables using ``var.value = ...``. Then check constraints with ``constr.violation()``. The violation is 0 if the constraint is satisfied exactly.
