### ISSUE TITLE
When the library will be ready for M1 apple technology?

### ISSUE THREAD

**Issue by jcp404** [cvxpy/cvxpy#1454]
**Is your feature request related to a problem? Please describe.**
Installation generally goes well on an Intel/x86-64 Mac, but not on M1/ARM64 

Thanks!

**Comment by akshayka** [comment]
What part of the installation does not go well?

**Comment by jcoutoperez** [comment]
I have a virtual envitoment with python 3.8 installed.
I run  `pip install cvxpy` and the tasks is running for ever and is not possible to install the library.
Here the "infinite status": 
```
Collecting cvxpy
  Using cached cvxpy-1.1.14.tar.gz (1.3 MB)
  Installing build dependencies ... \

```
I was googling a little bit and it looks like the lirbary is not ready for M1 apple computers with the new architecture.
Is this assumption correct? or maybe I am missing something? If this is the case, could you please provide doc to install the lubrary on M1 architecture?

Many thanks!

**Comment by SteveDiamond** [comment]
@jcoutoperez presumably you could install from source and that would work on M1. Maybe pip is not working because the Mac wheels aren't built on M1.

**Comment by bnaras** [comment]
I just confirmed that cvxpy installs fine on Apple M1 using 

https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh

Of course, specialized solvers may be a problem, but the basic installation and examples work in my meagre testing.

**Comment by jcp404** [comment]
Hi all,

So many thanks for you answers I will try it. I appreciate your support!
You are doing a nice work guys! :)
