### ISSUE TITLE
Segfault compiling conv expression

### ISSUE THREAD

**Issue by ghackebeil** [cvxpy/cvxpy#1455]
**Describe the bug**
The following minimal example highlights an issue in expression compilation where using a scalar-vector multiplication term inside a `conv` expression causes a segfault when a length-1 vector is used. The segfault occurs within `cvxcore/src/cvxcore.cpp::build_matrix` when compiling the model into matrix form.

**To Reproduce**
```python
import cvxpy as	cp

x = cp.Variable((1,)) # or cp.Variable((1,1))
problem = cp.Problem(
    objective=cp.Minimize(
	cp.max(cp.conv([1.], cp.multiply(1., x)))
    )
)
problem.solve("ECOS") # or any solver
```
The segfault does not occur if the first argument in the `cp.multiply` term is changed to a non-scalar (e.g., `cp.multiply([1.], x)`), or if the vector variable `x` has more than one element.

**Expected behavior**
Anything but a segfault. If the expression system thinks the involved dimensions are invalid, an earlier exception would be great.

**Version**
 - OS: mac, python 3.6
 - CVXPY Version: master

**Comment by ghackebeil** [comment]
Something like the following may be all that is needed.
```bash
diff --git a/cvxpy/cvxcore/src/LinOpOperations.cpp b/cvxpy/cvxcore/src/LinOpOperations.cpp
index e854d9f5..6f001943 100644
--- a/cvxpy/cvxcore/src/LinOpOperations.cpp
+++ b/cvxpy/cvxcore/src/LinOpOperations.cpp
@@ -434,8 +434,10 @@ Tensor get_conv_mat(const LinOp &lin, int arg_idx) {
   Matrix constant = get_constant_data(*lin.get_linOp_data(), false);
   int rows = lin.get_shape()[0];
   int nonzeros = constant.rows();
-  int cols = lin.get_args()[0]->get_shape()[0];
-
+  int cols = 1;
+  if (lin.get_args()[0]->get_shape().size() > 0) {
+    cols = lin.get_args()[0]->get_shape()[0];
+  }
   Matrix toeplitz(rows, cols);

   std::vector<Triplet> tripletList;
```

**Comment by SteveDiamond** [comment]
Fixed on master. Thanks for figuring it out!
