### ISSUE TITLE
low performance when performing qp involving n*n matrix even if the matrix is essentially low-rank.

### ISSUE THREAD

**Issue by xinstein** [cvxpy/cvxpy#1460]
The problem objective:
$x^T P^T A P x + x^T x + b * x + sum(abs(x^T - x^T Q^T Q))$

The first quadratic term is low-rank, and can be reformulated into quad_form(A, Px) to take advantange of the low rank decomposition, just as hinted in cvxpy's documentation.

Here's where I'm stuck: the term with `abs` involves multiplying x^T with a matrix Q^T Q, which is low-rank but dense if computed out. I tried the following two ways of expression, the latter is expected to reduce computation overhead due to low-rank decomposition, but no luck, both approaches exhibited same unacceptibly long solve time.
```
x.T @ (Q.T @ Q )
```
or
```
(x.T @ Q.T) @ Q
```

I'm not very familiar with implementations of convex optimization, maybe what I thought is wrong, but if it's only for gradient propagation, I suppose the latter expression should save a lot of computation time compared to the former.

I need advice on this, thank you whoever sees this issue and takes it seriously. If the advice involves implementing custom operators / atomic functions, I'd be happy to learn

**Comment by SteveDiamond** [comment]
You need to create a new variable and add a constraint:
```
z = cp.Variable(n)
constr = [z == Q @ x]
```
Then in your objective you have ``abs(x^T - z^T @ Q)``.

**Comment by xinstein** [comment]
> You need to create a new variable and add a constraint:
> 
> ```
> z = cp.Variable(n)
> constr = [z == Q @ x]
> ```
> 
> Then in your objective you have `abs(x^T - z^T @ Q)`.

Thank you, that's brilliant and life-saving!

Big improvement in iteration speed, but converging speed is slow, goes through 100k+ iterations without converging using OSQP, all default parameter settings. I'll play around for a while and see if I could resolve this myself.

**Comment by xinstein** [comment]
It seems MOSEK handles my problem very well, 
Thank you for the important advice, closing this
