### ISSUE TITLE
Strange error handling of constraints

### ISSUE THREAD

**Issue by SteveDiamond** [cvxpy/cvxpy#1462]
**Describe the bug**
The behavior when accidentally passing in an expression in the list of constraints (as opposed to an equality/inequality), is very odd. I'm not sure what is happening.

**To Reproduce**
I encountered the bug while solving a portfolio optimization problem like below:
```
import cvxpy as cp
import numpy as np

n = 3
np.random.seed(1)
mu = np.random.randn(n)
Sigma = np.random.randn(n, n)
Sigma = Sigma.T @ Sigma

w = cp.Variable(n)
obj = cp.Maximize(mu.T@w - cp.quad_form(w, Sigma))
constr = [cp.sum(w), w >= 0]
prob = cp.Problem(obj, constr)
prob.solve(verbose=True)
```

**Expected behavior**
Some sort of error should be raised in this case. Definitely the problem shouldn't solve!

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: Mac
 - CVXPY Version: 1.1.15

**Additional context**

**Comment by akshayka** [comment]
Good catch.

The Expression masquerading as a constraint is propagated forward in `Dcp2Cone` --- canonicalization doesn't meaningfully distinguish between constraints and expressions in this reduction. https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/canonicalization.py#L59-L70

Next, in `ConeMatrixStuffing`, the expression masquerading as a constraint is silently dropped.

https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py#L317-L331

**Comment by akshayka** [comment]
A simple fix is to ban the construction of `Problem`s with invalid constraint lists. In particular just check that each entry is in fact a `Constraint` object. I can make a PR.
