### ISSUE TITLE
got error: 'LinOp' object has no attribute 'shape'

### ISSUE THREAD

**Issue by FearlessBox** [cvxpy/cvxpy#1465]
**Describe the bug**
'LinOp' object has no attribute 'shape'
  File "E:\experiments\Experiment-CRL - normalize\model\qcqp_test.py", line 16, in <module>
    qcqp = QCQP(prob)

**To Reproduce**
The example offered on https://github.com/cvxgrp/qcqp

from numpy.random import randn
import cvxpy as cvx
from qcqp import *

n, m = 10, 15
A = randn(m, n)
b = randn(m, 1)

x = cvx.Variable(n)
obj = cvx.sum_squares(A*x - b)
cons = [cvx.square(x) == 1]
prob = cvx.Problem(cvx.Minimize(obj), cons)

qcqp = QCQP(prob)
---------------------------got error this line

**Expected behavior**

**Output**
got error: 'LinOp' object has no attribute 'shape'

**Version**
 - OS: win10
 - CVXPY Version:0.4.9
 - QCQP version: 0.8.3

**Additional context**

**Comment by SteveDiamond** [comment]
QCQP is not really supported anymore. It requires cvxpy 0.4.9, which is an extremely old version. If you're interested you could upgrade QCQP to use the latest cvxpy.

**Comment by rileyjmurray** [comment]
As Steven said, this is really a QCQP issue. We can't provide support for cvxpy 0.4.x, so your best bet is to upgrade QCQP to cvxpy 1.0.
