### ISSUE TITLE
CVXPY `Parameter(..).is_psd()` not working

### ISSUE THREAD

**Issue by paulhyuk** [cvxpy/cvxpy#1466]
**Describe the bug**
`Parameter(..).is_psd()` returns `False` while we get a cholesky decomposition from `np.linalg.cholesky()`

**To Reproduce**
<img width="569" alt="Screen Shot 2021-08-25 at 5 24 34 PM" src="https://user-images.githubusercontent.com/29054878/130867225-ab4ff49c-50e4-45aa-b0c1-67db973b0333.png">

**Expected behavior**
If `np.linalg.cholesky()` returns a decomposition, we expect `Parameter(..).is_psd()` to return `True`

**Output**

**Version**
 - OS: Debian GNU/Linux 10 (buster)
 - CVXPY Version: 1.1.15

**Additional context**

**Comment by rileyjmurray** [comment]
Since there isn't a bug here, and we haven't gotten a response, I'm closing this issue. Feel free to ask for advice on StackOverflow with a cvxpy tag, or to move things to GitHub Discussions.
