### ISSUE TITLE
Support SCS 3.0

### ISSUE THREAD

**Issue by bodono** [cvxpy/cvxpy#1471]
The scs-python 3.0 PR is here: https://github.com/bodono/scs-python/pull/50

The SCS 3.0 PR is here: https://github.com/cvxgrp/scs/pull/169

The new version adds some extra features including naturally handling quadratics in the objective, the 'box' cone and is overall faster and more reliable.

It makes a few breaking API changes which are documented in the linked PRs.

**Comment by rileyjmurray** [comment]
Minor question: what's a "box cone"?

**Comment by rileyjmurray** [comment]
As an update: both of the PRs mentioned in Brendan's initial comment have been merged to their respective repositories. We should get going on this ASAP.

**Comment by bodono** [comment]
This is a good chance to plug the new documentation here: https://www.cvxgrp.org/scs
And the cones are explained here: https://www.cvxgrp.org/scs/api/cones.html

In short when running tests on the miplib, netlib, maros meszaros etc., datasets where box constraints are very common, eg, something like l <= Ax <= u, I noticed that often the values of l and u can have large differences, eg, some values are 0 and some are 1e20. If we convert this to use the positive orthant cone it introduces very poor numerical conditioning into the linear systems to be solved, since it would entail using something like:

-Ax + s_1 == -l
s_1 >= 0

Ax + s_2 == u
s_2 >= 0

However, if we support the box cone {(t, s) | l <= s / t <= u} then we can easily support the above constraint by using:

-Ax + s == 0
t == 1
(t,s) \in box cone

Now the bad conditioning is only in the cone projection routine where, since usually bounds like 1e20 are not tight, it does no harm (and means we don't have to double the size of the matrix A too). This provides significant speed improvements for SCS in datasets that have box constraints. See also https://github.com/cvxpy/cvxpy/issues/1470 where infinite values are passed which cannot be handled using the positive orthant cone but which the box cone can handle.

I think it would be useful and natural for cvxpy to support the box cone at some point, since several solvers support them (or more accurately several solvers support box constraints), eg. SCS, OSQP, MOSEK and GUROBI (I believe).

**Comment by phschiele** [comment]
@rileyjmurray I could kick off the implementation in the next days.

**Comment by rileyjmurray** [comment]
@phschiele that would be awesome!

**Comment by bodono** [comment]
@phschiele yes please! As a basic start I put together this PR: https://github.com/cvxpy/cvxpy/pull/1492

It doesn't pass the tests yet, but I think SCS 3 and SCS 1, 2 should both be supported.

It doesn't add support for any of the new features however, it would be great to add those.

**Comment by rileyjmurray** [comment]
Resolved by #1499, thanks to great work by @phschiele!
