### ISSUE TITLE
Different problem formulations lead to different statuses

### ISSUE THREAD

**Issue by Mark531** [cvxpy/cvxpy#1475]
**Describe the bug**
I've run a regression with a constraint, in scalar and matric formulation. The optimal values are very close, but the solver status is different...

**To Reproduce**
```
import numpy as np
import cvxpy as cp

x = np.arange(100)
y = 10 * np.sin(x * 0.1) + 20

# First formulation
beta = cp.Variable(2)
cost = cp.sum_squares(beta[1] * x + beta[0] - y)
problem = cp.Problem(cp.Minimize(cost), [beta[1] * x + beta[0] >= y])
print("Optimal value: %f" % problem.solve())
print("Status: %s" % problem.status)

# Second formulation
X = np.vstack((np.full_like(x, 1), x)).T
beta = cp.Variable(2)
cost = cp.norm2(X @ beta - y)**2
problem = cp.Problem(cp.Minimize(cost), [X @ beta >= y])
print("Optimal value: %f" % problem.solve())
print("Status: %s" % problem.status)
```

**Expected behavior**
I expect both formulations to return the same optimal value and the same solver status.

**Output**
> Optimal value: 11015.621605
> Status: optimal
> Optimal value: 11015.600694
> Status: optimal_inaccurate

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.1.3

**Comment by rileyjmurray** [comment]
Hi @Mark531. Unfortunately, it is not possible for us to guarantee the same result for mathematically equivalent problems. On CVXPY's end, that's because different formulations will be "canonicalized" and passed to solvers in slightly different forms. The solvers themselves are sensitive to the representation of a problem.

**Comment by Mark531** [comment]
Hi @rileyjmurray. Thanks for your reply. Well, what bugs me is that these problems are not "equivalent" (such as a primal and a dual) but mathematically identical. So, what's your suggestion about how the problem should be formulated for the default solver?

**Comment by SteveDiamond** [comment]
The first formulation with “sum_squares” is strongly preferred.

**Comment by Mark531** [comment]
Ok, thank you.
