### ISSUE TITLE
Add documentation for cvxpy-base

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#1527]
Users can now install cvxpy without any bundled solvers, using cvxpy-base (on pypi or conda forge). We should document this package.

**Comment by phschiele** [comment]
@akshayka There is one paragraph about `cvxpy-base`, but it is at the very end of the install section: [https://www.cvxpy.org/install/index.html#install-without-default-solvers](https://www.cvxpy.org/install/index.html#install-without-default-solvers)

If you prefer to move it somewhere else, just let me know.

**Comment by akshayka** [comment]
Oh, that's great! Somehow I missed it.
