### ISSUE TITLE
Allow to send a list of solvers

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#1529]
### Discussed in https://github.com/cvxpy/cvxpy/discussions/1522

This feature has been suggested independently by multiple users.

<div type='discussions-op-text'>

<sup>Originally posted by **erelsgl** November  2, 2021</sup>
In some problems, some solvers may be better than others, but they might also fail with a `SolverError`.  I suggest allow, as the "solver" parameter, to send a list of solvers rather than just one. The function will try them in the order they are given, and return the first solution for which no `SolverError` is raised.</div>

**Comment by rileyjmurray** [comment]
I see one complication with this feature. How would we parse solver options? There aren't consistent names for things like the maximum number of iterations used by a solver or solver termination criteria.

**Comment by Transurgeon** [comment]
completed with PR above :)
