### ISSUE TITLE
ARPARCK no convergence on the identity matrix

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1532]
@taozuoqiao pointed out in #1424 that ARPACK can fail to converge on the identity matrix. Moreover, this failure occurs randomly (see below). We should perform PSD/NSD checks by using the Gershgorin Circle Theorem to avoid any failures in detecting when a diagonal matrix is PSD/NSD within a specified tolerance.
```python
In [1]: import numpy as np

In [2]: from scipy.sparse.linalg import eigsh

In [3]: x = np.identity(600)
   ...: n_failed = 0
   ...: for i in range(1000):
   ...:     try:
   ...:         eigsh(x, k=1, which='SA', sigma=-1e-10)
   ...:     except:
   ...:         n_failed += 1
   ...: print(n_failed)
40

In [4]: x = np.identity(600)
   ...: n_failed = 0
   ...: for i in range(1000):
   ...:     try:
   ...:         eigsh(x, k=1, which='SA')
   ...:     except:
   ...:         n_failed += 1
   ...: print(n_failed)
8

```
I'll create a PR soon which addresses diagonal (and diagonally-dominant) matrices.

**Comment by taozuoqiao** [comment]
Thanks a lot for the fix!
