### ISSUE TITLE
Misleading guidance on install page.

### ISSUE THREAD

**Issue by SteveDiamond** [cvxpy/cvxpy#1541]
**Describe the bug**
The install instructions say to run ``pytest cvxpy/tests`` to test the installation, both via pip and conda. But does this actually work? It doesn't work on my machine. This seems like something that would only work if you installed from source.

I would suggest we drop the instructions for testing.

**To Reproduce**
Try ``pytest cvxpy/tests``

**Expected behavior**
The tests should be run.

**Output**
N/A

**Version**
 - OS: Mac 11.6
 - CVXPY Version: 1.1.17

**Additional context**
Another issue is that for some installations ``pytest`` is not recognized as a command and ``python -m pytest`` must be used instead.

**Comment by h-vetinari** [comment]
It should be possible to do something like `pytest --pyargs cvxpy` without relying on the exact repo layout

**Comment by phschiele** [comment]
@h-vetinari Thanks for the tip, that does work and is better than pointing to the exact package location when installed via pip!
