### ISSUE TITLE
DCPError: Problem does not follow DCP rules.

### ISSUE THREAD

**Issue by muhlbach** [cvxpy/cvxpy#1545]
**Describe the bug**
Hi there! First of all, I love using CVXPY so a big thanks to all developers! Makes life as a researcher so much easier. Also, this is actually not a bug, but more a question!

Basically, I'm setting up a problem, which gives me the following error message:
```
DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
var12404.T @ ([[ 18.07030469]
```
I've been reading your guidelines on DCP rules, but I thought my optimization problem was fine. Apparently it is not, and I would like any inputs that can guide me in the right direction.

I consider the following model:

![Screen Shot 2021-11-10 at 13 16 01](https://user-images.githubusercontent.com/31421850/141170244-083d7062-8a8d-4e70-ad55-8b501ded1c6b.png)

where Y,W,Z are real-valued N-dimensional vectors, X is a real-valued (N*p)-dimensional matrix, gamma is a known constant, tau and beta are conformable vectors, and U,V Gaussian noise. I'm trying to solve for tau, beta, and Z at the same time via:
 
![Screen Shot 2021-11-10 at 13 18 46](https://user-images.githubusercontent.com/31421850/141170556-964cfb34-6560-4969-92fb-b2719a2520e6.png)

**To Reproduce**
```
import numpy as np
import cvxpy as cp

# Data settings
N = 100
p = 5
Z = np.random.randn(N,1)
X = np.random.randn(N,p)

# True parameters
beta = np.repeat(a=1, repeats=p).reshape(-1,1)
gamma = np.array([1]).reshape(-1,1)
tau = np.array([10]).reshape(-1,1)

# Outcome variables
W = Z @ gamma + np.random.randn(N,1)
Y = W @ tau + X @ beta +np.random.randn(N,1)

# Set up decision variables
Z_var = cp.Variable(shape=(N,1), integer=False)
tau_var = cp.Variable(shape=(1,1), integer=False)
beta_var = cp.Variable(shape=(p,1), integer=False)

# Losses
U_expr = Y - W @ tau_var - X @ beta_var
loss_U = cp.sum_squares(U_expr)
loss_V = cp.sum_squares(W - Z_var @ gamma)
loss_ZU = (Z_var.T @ U_expr) ** 2

objective = cp.Minimize(loss_U + loss_V + loss_ZU)

# Cannot run
problem = cp.Problem(objective=objective, constraints=constraints).solve(verbose=True)
```

**Expected behavior**
I was expecting this to be able to run, but perhaps the problem is not solvable or the setup is wrong.

**Version**
 - OS: macOS Big sur
 - CVXPY Version: cvxpy 1.1.17 py38h50d1736_0 conda-forge

**Comment by SteveDiamond** [comment]
I don't think this is convex. The problem is the cross term ``Z_var.T @ U_expr``. You can check convexity using the cvxpy analyzer: https://github.com/cvxpy/cvxpyanalyzer
