### ISSUE TITLE
Only use one core when multiprocessing

### ISSUE THREAD

**Issue by ddrise** [cvxpy/cvxpy#1549]
**Describe the bug**
I am using a  server with EPYC 7543. When I run a multiprocessing program (each procss run a mix inter optimize task) , I find out that each process has a very low cpu usage. By using htop, I found that only one cpu core is used.

**Comment by phschiele** [comment]
Hi @ddrise!
Which solver are you using to solve the optimization problem? Can you explain the expected behavior a bit clearer (e.g. how many processes are being run, what's the CPU utilization per process, what's the overall CPU utilization, ...).

**Comment by ddrise** [comment]
> Hi @ddrise! Which solver are you using to solve the optimization problem? Can you explain the expected behavior a bit clearer (e.g. how many processes are being run, what's the CPU utilization per process, what's the overall CPU utilization, ...).

Hi, for example , if I have 5 processes, the cpu utilization per process is 20 % ( on the same core). The problem is mix integer programing and  solver is ECOS_BB or SCIP (same behavior). 
I have solved the problem now. By default Anaconda will install the MKL version numpy. I deleted anaconda and reisntalled Miniconda and installed OpenBLAS version numpy, then the problem is solved.

**Comment by rileyjmurray** [comment]
@ddrise ECOS_BB is single-threaded, so you won't see it use more than one core.

SCIP does support multi-threading, but it might need to be configured properly. If you could not get SCIP to use multi-threading when MKL is installed then you should probably reach out to the SCIP developers. MKL is **much** faster than OpenBLAS for more complicated linear algebra computations.

**Comment by ddrise** [comment]
> @ddrise ECOS_BB is single-threaded, so you won't see it use more than one core.
> 
> SCIP does support multi-threading, but it might need to be configured properly. If you could not get SCIP to use multi-threading when MKL is installed then you should probably reach out to the SCIP developers. MKL is **much** faster than OpenBLAS for more complicated linear algebra computations.

Thank you for your explaination, I think you may misunderstood my problem. Each process ran a seperate mix integer optimize task, and all of these tasks are using one single cpu core together.
