### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by Algue-Rythme** [cvxpy/cvxpy#1554]
The API documentation section (currently online) misses the API doc for various classes, for example: https://www.cvxpy.org/api_reference/cvxpy.problems.html#id4

I needed to look at the sources to find the doc of `SolverStats`: https://github.com/cvxpy/cvxpy/blob/7c322f0783cc719c7b6a57e52c2593ae72e00e19/cvxpy/problems/problem.py#L1375

I have the feeling by looking at the .rst file that it should have been generated automatically instead: https://github.com/cvxpy/cvxpy/blob/master/doc/source/api_reference/cvxpy.problems.rst#solverstats

**Comment by SteveDiamond** [comment]
Fixed. Agreed, @akshayka  we should add some sort of pre-commit check to make gh-pages so that if it fails to create the API docs it will abort.

**Comment by phschiele** [comment]
@SteveDiamond I'm not too familiar with gh-pages, but I can check if I find something in that regard.

**Comment by SteveDiamond** [comment]
@phschiele basically we have a ``Makefile`` where we run a bash script essentially that builds the docs with sphinx on the ``gh-pages`` branch (which is what github generates the website from). The relevant section starts here: https://github.com/cvxpy/cvxpy/blob/7c322f0783cc719c7b6a57e52c2593ae72e00e19/Makefile#L157
