### ISSUE TITLE
Warning for poorly scaled problems

### ISSUE THREAD

**Issue by SteveDiamond** [cvxpy/cvxpy#1557]
**Is your feature request related to a problem? Please describe.**
We should raise a warning when a problem is poorly scaled. For example, if extremely large numerical values are present in the constants/parameters. In general, we need to raise awareness about scaling issues as much as possible.

**Describe the solution you'd like**
We should show the warning every time the problem is solved.

**Describe alternatives you've considered**
We have language on the website discussing scaling issues, which could be expanded, but I don't think this is sufficient for raising awareness.

**Additional context**
N/A

**Comment by rodfloripa** [comment]
I agree!!! I didn't know that solvers work better with objective values around 1

**Comment by Michael-git96** [comment]
I think this issue is linked to an issue raised before: #1205 . @SteveDiamond - do you think the scaling warnings should be implemented in qp_matrix_stuffing and cone_matrix_stuffing, or is there a better place for them? Also, @rileyjmurray asked some good questions with regards to the types of checks and defaults in #1205 .

**Comment by SteveDiamond** [comment]
Thanks, I had missed #1205. I will close this in favor of that issue.

I support @rileyjmurray's suggestions. The check could go in ``apply_parameters`` in ParamQPProg and ParamConeProg. This is where the solver standard form is produced. It will be hard though to give much debugging information other than that large or small values exist.

Another option would be to check all numeric constants, so in constant.py. That won't catch parameters but might be the best place to start, since it will be easier to give debugging info by identifying where the problematic values are being introduced.
