### ISSUE TITLE
Very slow in creating large quadratic objective

### ISSUE THREAD

**Issue by algebravic** [cvxpy/cvxpy#1566]
I have a program with a quadratic objective which has 157000 nonzero terms.  I'm trying to create it.  I make a list of the monomials, which takes about 2 seconds.  But, after 20 minutes, cp.sum of the list still hasn't finished!  Should it really take that long?

**Comment by SteveDiamond** [comment]
Can you vectorize your problem?

**Comment by algebravic** [comment]
Hi Steven, Yes, I was able to vectorize the problem -- the objective is now
a sum of 5 terms like x^t Q y^T, where x and y are variables and Q is a
numpy array.  This should be a quadratic program.  However, when I try to do

prob.solve(solver='CPLEX') (we have cplex.py and cplex installed), it gives
an error message saying that Problem does not follow DCP rules.  How do I
tell it that it's not a DCP, but I want cplex to solve it (which it can
handle)?

Victor

**Comment by SteveDiamond** [comment]
You need to use ``cp.quad_form(x, P)`` instead of ``x.T @ P @ x``.

**Comment by algebravic** [comment]
Steven, Thanks, that worked.

Victor
