### ISSUE TITLE
Leaf boolean / integer plus another attribute

### ISSUE THREAD

**Issue by dmalyuta** [cvxpy/cvxpy#1571]
I think [L139](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/expressions/leaf.py#L139) should be `or` if I am interpreting [L137](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/expressions/leaf.py#L137) correctly. Is this a bug? Feels like we should be able to set a nonnegative integer variable without a problem.

**Comment by SteveDiamond** [comment]
It's not a bug. Variables can only have one property. See #566. We've had a lot of discussion about this and it's clearly not a popular design choice, but there are internal reasons for doing it this way.
