### ISSUE TITLE
Develop a policy for the working (un-released) version of cvxpy on master

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1576]
Historically, the version of cvxpy on master has been left equal to that of the last release. So installing from source today (December 12, 2021) would install "cvxpy 1.1.17," but the actual code would be different from the public 1.1.17 release.

I think it would be more natural to (1) set cvxpy's working version to that of the *next minor release* and (2) to have flags indicate that the version hasn't been released yet. This would be more in line with the sentiment behind semantic versioning: once a minor version has been released, it should only see updates that amount to bug fixes.

The scipy folks essentially take this approach. Their current setup.py file contains the following lines ([link](https://github.com/scipy/scipy/blob/master/setup.py#L56-L61)):
```
MAJOR = 1
MINOR = 9
MICRO = 0
ISRELEASED = False
IS_RELEASE_BRANCH = False
VERSION = '%d.%d.%d' % (MAJOR, MINOR, MICRO)
```
I'll note that they're on version 1.9.0, even though the most recent public release of scipy was 1.7.3. You can read about their versioning policies [here](https://scipy.github.io/devdocs/dev/core-dev/index.html#version-numbering).

The scipy developers also have automated tooling that sets more specific version numbers when scipy is installed from source. The more specific numbers reference the last commit in the git repo. I've partially adapted their approach to my local copy of cvxpy. After installing from source, I see the following version
```
import cvxpy as cp
cp.__version__
Out[3]: '1.2.0.dev0+1073.5a60139'
```
I like the idea of more detailed version numbers for installation from source. This reduces the likelihood that we'll be unable to reproduce someone's issue because we incorrectly thought we were running the same version.

@SteveDiamond @akshayka @bstellato what are your thoughts? Are you open to the idea of having the working version be that of the next minor release? We could potentially be more sophisticated (e.g., using release candidates), but I think being one version ahead would suffice for now.

**Comment by SteveDiamond** [comment]
This is fine with me. I like the idea that installations from source will have tags unique to the commit.
