### ISSUE TITLE
How to use C++ to directly call the CVX (C++ code) without any python code?

### ISSUE THREAD

**Issue by zhumingpassional** [cvxpy/cvxpy#1579]
**Is your feature request related to a problem? Please describe.**
In my project, python is forbidden, and I have to use C++ to call CVX, how to do it? Could you please provide several examples?
If I have to use CVX in other CPUs such as ARM, how to solve this problem?

**Describe the solution you'd like**
I hope CVX can provide other programming language interface, e.g., C++, JAVA. I also hope CVX supports more OSs.

Thank you very much.

**Comment by SteveDiamond** [comment]
Right now you can only use CVXPY from Python. Are you sure it doesn't work on ARM?

**Comment by zhumingpassional** [comment]
I'm not sure whether cvxpy works on ARM. It is said that python code can be moved to ARM.  It may be not as convenient as C++ code if working on ARM. 

Will cvxpy support C++ interface in the future? I hope. What do you think about it?

**Comment by SteveDiamond** [comment]
At some point there will be support for code generation in the style of https://cvxgen.com/docs/index.html
But I can't promise any timeline.

**Comment by rileyjmurray** [comment]
Closing as out-of-scope for now. Anyone can feel free to follow-up on cvxpy's GitHub Discussions page.
