### ISSUE TITLE
Fix dependencies versions

### ISSUE THREAD

**Issue by mirkosavasta** [cvxpy/cvxpy#1583]
It would be useful to fix the dependencies versions within the requirements file to prevent problems.

A new version of scs has been released the 16th of December 2021 and this caused problems to a brand new installation of the library.

Thanks in advance.

**Comment by MennovDijk** [comment]
Having the same issue here.

@mirkosavasta did you resolve this yourself already? If so, how?

**Comment by phschiele** [comment]
@mirkosavasta @MennovDijk Can you share some details on the issues you are facing?

**Comment by mirkosavasta** [comment]
@MennovDijk To solve it is enough to fix the dependencies directly in the requirements.txt that you use to build a docker container or just to create a virtual environment.

Just add the following to your requirements.txt and you should be fine.

scs==2.1.4
osqp==0.6.2.post0
ecos==2.0.8

**Comment by mirkosavasta** [comment]
Hello @phschiele,

the versions of cvxpy dependencies are not fixed in your requirements.txt.

This implies that a new release of one of the libraries cvxpy depends on can break some cvxpy functionality because if you install cvxpy from scratch you always install the latest version of the dependencies.

Thanks.

**Comment by phschiele** [comment]
@mirkosavasta I can see that a broken build after a new (sub)dependency release is not great.

Having had similar issues in the past, I can highly recommend `poetry` to freeze the subdependencies. This way, the builds are easily reproducible. 

I'm not sure if from the perspective of a library fixing the requirements to a specific version is ideal, as one generally would want to support the widest range of dependency versions possible.
Perhaps one could fix the major versions of the packages to prevent unexpected compatibility conflicts, assuming semantic versioning of the dependencies. 

However, for your case at hand the general compatibility with scs 3.0 was tested beforehand, but that of course can not rule out issues with the installation for all users.

**Comment by mirkosavasta** [comment]
Thanks a lot for your advice.
