### ISSUE TITLE
Two methods for reformulating a large portfolio optimization model

### ISSUE THREAD

**Issue by dcajasn** [cvxpy/cvxpy#1585]
**Describe the bug**
I was trying to solve the Gini Mean Difference portfolio model proposed by [Yitzhaki](https://www.jstor.org/stable/1808584?origin=JSTOR-pdf):

![image](https://user-images.githubusercontent.com/61527316/146652679-e14695bb-a6a6-4731-9b0b-9a0d5bd8f0de.png)

Its equivalent linear programming model is:

![image](https://user-images.githubusercontent.com/61527316/146652686-055a1702-f651-437b-bc76-0a6ce5bdc49a.png)

Where x is the vector of weights and r is the matrix of returns. This problem has continuous variables that increase in proportion to T(T-1)/2, where T is the number of observations. When I use 700 observations and 200 assets the problem consumes all my memory even when I use commercial solvers like Mosek or Gurobi. In the end, my computer get freeze and I have to restart it to try to solve the problem with a small sample. My computer is a AMD Bulldozer 4 cores 3.6Ghz and 8GB RAM, windows 10 and I was running Python 3.7. The error happen with spyder and jupyter notebooks.

**To Reproduce**
```
import numpy as np
import pandas as pd
import cvxpy as cp
import mosek
import scipy.stats as st
from timeit import default_timer as timer
from datetime import timedelta

#%%
def gini(mu, returns, D, assets, obj='MinRisk', l=2, rf=0):
    (T, N) = returns.shape
    
    k = cp.Variable()
    d = cp.Variable((int(T*(T-1)/2),1))
    w = cp.Variable((returns.shape[1],1))

    constraints = [d >= D @ w,
                   d >= -D @ w,
                   w >= 0]

    risk = cp.sum(d)/((T-1)*T)
    ret = mu @ w
    
    if obj == 'MinRisk':
        constraints += [cp.sum(w) == 1]
        objective = cp.Minimize(risk * 1000)
    elif obj == 'Sharpe':
        constraints += [cp.sum(w) == k,
                        k >= 0,
                        ret - rf * k == 1]
        objective = cp.Minimize(risk * 1000)
        
    prob = cp.Problem(objective, constraints)

    try:    
        prob.solve(solver=cp.MOSEK, mosek_params={mosek.iparam.num_threads: 4})
        w = pd.DataFrame(w.value)
        w.index = assets
        w = w/w.sum()
    except:
        w = None
    return w

#%%
rs = np.random.RandomState(123)

sizes = [200]
objs = ['MinRisk', 'Sharpe']
data = {}
weights = {}
n_sim = 1
k = 0
T = [700]

for t in T:
    for n in sizes:
        
        cov = rs.rand(n,n) * 1.5 - 0.5
        cov = cov @ cov.T/1000 + np.diag(rs.rand(n) * 0.7 + 0.3)/1000
        mean = np.zeros(n) + 1/1000

        Y = st.multivariate_normal.rvs(mean=mean, cov=cov, size=t, random_state=rs)
        Y = pd.DataFrame(Y)
        assets = ['Asset '+ str(i) for i in range(1,n+1)]
        mu = Y.mean().to_numpy()
        returns = Y.to_numpy()

        D = np.array([]).reshape(0,len(assets))
        for j in range(0, returns.shape[0]-1):
            D = np.concatenate((D, returns[j+1:] - returns[j,:]), axis=0)

        for obj in objs:
            name = obj + '-' + str(t) + '-' + str(n)
            data[name] = []
            weights[name] = []
            for i in range(n_sim):
                start = timer()
                w = gini(mu, returns, D, assets, obj=obj, l=2, rf=0)
                end = timer()
                data[name].append(timedelta(seconds=end-start).total_seconds())
                weights[name].append(w)
            k += 1
            print(name)
```

**Expected behavior**
I expect that the code run the loop and save the time of each loop and the optimal values of w in the dictionaries.

**Output**
Two dictionaries, one with the time used to run each loop and the other one with the optimal values of w. 

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.15

**Additional context**
No additional context.

**Comment by rileyjmurray** [comment]
Sorry for the delay @dcajasn. I looked into this a while ago and noticed that although it's taking a long time for cvxpy to compile the problem, it's *also* taking a long time for MOSEK to solve the problem. (The durations are actually pretty much the same.)

The difficulty with this problem is that the matrix ``D`` is large (T^2 rows and N columns) and dense. Numerical solvers need to perform linear algebra operations on large matrices that contain ``D`` as a submatrix, so the solvers are simply facing a computationally expensive linear algebra problem.

You can improve the situation by reducing the size of the dense matrix the solver ends up dealing with. The code below gives the option of reformulating the problem by introducing a helper variable. It generates problems that can easily be solved on a personal laptop when ``(T, N) = (700, 200)``. I've stripped it down to only handle the ``'MinRisk'`` objective. Let me know if you'd like me to explain its logic!

```
def gini(mu, returns, D, assets, lift=False):
    (T, N) = returns.shape

    d = cp.Variable((int(T * (T - 1) / 2),))
    w = cp.Variable((N,))
    constraints = []

    if lift:  # use Riley's reformulation
        ret_w = cp.Variable(T)
        constraints.append(ret_w == returns @ w)
        mat = np.zeros((d.shape[0], T))
        """ 
        We need to create a vector that has the following entries:
            ret_w[i] - ret_w[j]
        for j in range(T), for i in range(j+1, T).
        We do this by building a numpy array of mostly 0's and 1's.
        (It would be better to use SciPy sparse matrix objects.)
        """
        ell = 0
        for j in range(T):
            for i in range(j+1, T):
                # write to mat so that (mat @ ret_w)[ell] == var_i - var_j
                mat[ell, i] = 1
                mat[ell, j] = -1
                ell += 1
        all_pairs_ret_diff = mat @ ret_w
    else:  # use the original formulation
        all_pairs_ret_diff = D @ w

    constraints += [d >= all_pairs_ret_diff,
                    d >= -all_pairs_ret_diff,
                    w >= 0,
                    cp.sum(w) == 1,
                    cp.Parameter(value=0) * cp.Parameter(value=0) >= 0]

    risk = cp.sum(d) / ((T - 1) * T)
    objective = cp.Minimize(risk * 1000)

    prob = cp.Problem(objective, constraints)

    try:
        prob.solve(solver=cp.MOSEK, mosek_params={mosek.iparam.num_threads: 4},
                   verbose=True, )
        w = pd.DataFrame(w.value)
        w.index = assets
        w = w / w.sum()
    except:
        w = None
    return w
```

**Comment by dcajasn** [comment]
Thanks @rileyjmurray, I really like your reformulation. It works very well in medium scale problems. I made another formulation in [Cajas (2021)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3988927) based on [Chassein and Goerigk (2015)](https://kluedo.ub.uni-kl.de/frontdoor/deliver/index/docId/3899/file/paper.pdf) work. This formulation works well for large scale problems (T>=1000).

Here is the equivalent model:

![image](https://user-images.githubusercontent.com/61527316/152631317-8f8c05af-e88a-40d3-ab89-e63c5d20cc88.png)

where the weights w_i for Gini mean difference take the form:

![image](https://user-images.githubusercontent.com/61527316/152631357-03bd1d35-eea1-4bbf-9676-b109d9894364.png)

```
def gini(mu, returns, D, assets, lift=0):
    (T, N) = returns.shape

    d = cp.Variable((int(T * (T - 1) / 2),1))
    w = cp.Variable((N,1))
    constraints = []

    if lift in [0, 1]:  # use Riley's reformulation
        if lift == 1:    
            ret_w = cp.Variable((T,1))
            constraints.append(ret_w == returns @ w)
            mat = np.zeros((d.shape[0], T))
            """ 
            We need to create a vector that has the following entries:
                ret_w[i] - ret_w[j]
            for j in range(T), for i in range(j+1, T).
            We do this by building a numpy array of mostly 0's and 1's.
            (It would be better to use SciPy sparse matrix objects.)
            """
            ell = 0
            for j in range(T):
                for i in range(j+1, T):
                    # write to mat so that (mat @ ret_w)[ell] == var_i - var_j
                    mat[ell, i] = 1
                    mat[ell, j] = -1
                    ell += 1
            all_pairs_ret_diff = mat @ ret_w
        elif lift == 0:  # use the original formulation
            all_pairs_ret_diff = D @ w
    
        constraints += [d >= all_pairs_ret_diff,
                        d >= -all_pairs_ret_diff,
                        w >= 0,
                        cp.sum(w) == 1,
                        cp.Parameter(value=0) * cp.Parameter(value=0) >= 0]

        risk = cp.sum(d) / ((T - 1) * T)

    elif lift == 2:
        a = cp.Variable((T,1))
        b = cp.Variable((T,1))
        y = cp.Variable((T,1))

        owa_w = []
        for i in range(1,T+1):
            owa_w.append(2*i - 1 - T)
        owa_w = np.array(owa_w) / (T * (T-1))

        constraints = [returns @ w == y,
                       w >= 0,
                       cp.sum(w) == 1]
   
        for i in range(T):
            constraints += [a[i] + b >= cp.multiply(owa_w[i], y)]

        risk = cp.sum(a + b)

    objective = cp.Minimize(risk * 1000)

    prob = cp.Problem(objective, constraints)

    try:
        prob.solve(solver=cp.MOSEK,
                   mosek_params={mosek.iparam.num_threads: 2},
                   verbose=False,)
        w = pd.DataFrame(w.value)
        w.index = assets
        w = w / w.sum()
    except:
        w = None
    return w
```

**Comment by rileyjmurray** [comment]
@dcajasn I think it's safe to say this issue is resolved. Would you be interested in creating an example notebook that shows the performance tradeoffs of the three formulations? If so, then we can leave this issue open until we've merged a pull request from you with the example notebook. If not, then we can go ahead and close this issue.

**Comment by dcajasn** [comment]
I totally agree @rileyjmurray, thank you very much for your help.
