### ISSUE TITLE
Can't solve simple GP

### ISSUE THREAD

**Issue by adishavit** [cvxpy/cvxpy#1591]
I don't understand why this GP:
```
        x = cp.Variable(pos=True)
        y = cp.Variable(pos=True)
        cstrs = [10 <= x, x <= 20, y <= x, x * y == 7]
        prob = cp.Problem(cp.Maximize(y), cstrs)
        prob.solve(gp=True)
```
fails with:
```
...
  File "C:\...\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 101, in _reductions_for_problem_class
    raise DGPError("Problem does not follow DGP rules." + append)
cvxpy.error.DGPError: Problem does not follow DGP rules.The following constraints are not DGP:
var0 @ var1 == 7.0 , because the following subexpressions are not:
```

Setting bounds on `y`, using `Minimize`, or `x * y <= 7` instead of `x * y == 7` all fail for the same reason.

Isn't the whole point of GP to multiply variables?

BTW, the same program with [gpkit](https://gpkit.readthedocs.io/en/latest/index.html#) runs fine.

**Comment by adishavit** [comment]
I think it is an installation issue.

**Comment by adishavit** [comment]
(Reopening issues)
I'm trying to run the GP example from the site:

```
        import cvxpy as cp

        # DGP requires Variables to be declared positive via `pos=True`.
        x = cp.Variable(pos=True)
        y = cp.Variable(pos=True)
        z = cp.Variable(pos=True)

        objective_fn = x * y * z
        constraints = [
            4 * x * y * z + 2 * x * z <= 10, x <= 2 * y, y <= 2 * x, z >= 1]
        problem = cp.Problem(cp.Maximize(objective_fn), constraints)
        problem.solve(gp=True)
        print("Optimal value: ", problem.value)
        print("x: ", x.value)
        print("y: ", y.value)
        print("z: ", z.value)
```
This fails with:

```
...
  File "C:\tools\miniconda3\envs\roomassignments\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 101, in _reductions_for_problem_class
    raise DGPError("Problem does not follow DGP rules." + append)
cvxpy.error.DGPError: Problem does not follow DGP rules.The following constraints are not DGP:
4.0 @ var0 @ var1 @ var2 + 2.0 @ var0 @ var2 <= 10.0 , because the following subexpressions are not:
```

My setup:
```
>conda list cv
# packages in environment at C:\tools\miniconda3\envs\roomassignments:
#
# Name                    Version                   Build  Channel
cvxopt                    1.2.7                    pypi_0    pypi
cvxpy                     1.1.17           py37h03978a9_1    conda-forge
cvxpy-base                1.1.17           py37h9386db6_1    conda-forge
```
Is there some other package or flag that I need to set or install?

**Comment by keithbriggs** [comment]
This works for me with cvxpy 1.1.3.

**Comment by adishavit** [comment]
Didn;t work for me with 1.1.13 either. ☹️

**Comment by akshayka** [comment]
I think you may have some sort of installation error.

Can you print the version of CVXPY in the Python script (add `print(cp.__version__)` as the second line of your script)?

This works locally on my machine (tested it on 1.1.13, 1.1.15, 1.1.17, ... ). I get the output

```
Optimal value:  2.0000000014446626
x:  1.0000000002665232
y:  1.9999999999185367
z:  1.0000000004965397
```

We also test many dgp problems in our unit tests.

**Comment by akshayka** [comment]
The local tests from above were run using manylinux wheels from PyPi, and from conda-forge. Our unit tests are run on all major platforms, including Windows. The error you're seeing is quite strange. I don't know what it could be, other than an installation error.

**Comment by adishavit** [comment]
You're right. Very strange. 
When I now ran it isolated from other code it succeeds.
Something gets corrupted in my local function context.
Investigating.

**Comment by adishavit** [comment]
Closing this for now. Sorry for the noise. It was a Heisenbug...
