### ISSUE TITLE
When I try to run the code provided in a paper, it has following errors related to CVXPY

### ISSUE THREAD

**Issue by dqxiaoduan** [cvxpy/cvxpy#1600]
**Describe the bug**
When I try to run the code provided in a paper, it has the following errors related to CVXPY: 

(bayesrace) C:\Users\Lenovo\bayesrace>pip install -e .
Obtaining file:///C:/Users/Lenovo/bayesrace
Collecting pandas==1.0.3
  Using cached pandas-1.0.3-cp36-cp36m-win_amd64.whl (8.7 MB)
Collecting cvxpy==1.0.15
  Using cached cvxpy-1.0.15.tar.gz (915 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\envs\bayesrace\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-hpu8en1_\\cvxpy_9e73400b3c3d4e82b6ff31bd1122b730\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-install-hpu8en1_\\cvxpy_9e73400b3c3d4e82b6ff31bd1122b730\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Lenovo\AppData\Local\Temp\pip-pip-egg-info-hpjhbaju'
         cwd: C:\Users\Lenovo\AppData\Local\Temp\pip-install-hpu8en1_\cvxpy_9e73400b3c3d4e82b6ff31bd1122b730\
    Complete output (1 lines):
    error in cvxpy setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ab/6f/bcab45a432befe375f056ea31a7cc9c7468d07922768cb63c3dec5733afa/cvxpy-1.0.15.tar.gz#sha256=dff246a3fa03fe5c815f290825345a6ad5ff49df5e1882f123e632a4217bbcd1 (from https://pypi.org/simple/cvxpy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cvxpy==1.0.15 (from bayes-race) (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.2.23, 0.2.24, 0.2.25, 0.2.26, 0.2.27, 0.2.28, 0.3.0, 0.3.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 1.0.25, 1.0.26, 1.0.27, 1.0.28, 1.0.29, 1.0.31, 1.1.0a0, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0a4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15, 1.1.16, 1.1.17, 1.1.18)
ERROR: No matching distribution found for cvxpy==1.0.15

**To Reproduce**
You can find the code for this paper here: https://github.com/jainachin/bayesrace

And I am running the code in the installation section on this page. 

**When I run the first 4 lines of code, it has no errors, the first 4 lines of code is:**
conda create --name bayesrace python=3.6
conda activate bayesrace
git clone https://github.com/jainachin/bayesrace.git
cd bayesrace/

**But when I try to run the 5th line of code, that is (pip install -e .), the above errors occurred.** 

I am using Windows 11. 

Thank you!!!

**Comment by phschiele** [comment]
@dqxiaoduan Can you try changing `'cvxpy==1.0.15'` to `'cvxpy==1.1.18` in `the setup.py` file?

**Comment by dqxiaoduan** [comment]
Hi, thanks for the response, but I am not sure if I can change the setup.py file in this repository: https://github.com/jainachin/bayesrace

Because I think I do not have the access to change the code, it is not written by me. 

How about this solution: https://github.com/jainachin/bayesrace/issues/2 
But when I try the solution: conda install setuptools setuptools<58 in my anaconda prompt, it is not working because the system said no such file exists, and can anyone help me with that? Thanks!!!

**Comment by phschiele** [comment]
@dqxiaoduan I thought you have cloned the repository so you can make local changes. 

As for the alternative, I think you need "setuptools" only once?
Like so:
`conda install setuptools<58`

**Comment by dqxiaoduan** [comment]
Thank you for the instruction!

**But when I try this command(conda install setuptools<58), it is still not working with the following error:** 

(bayesrace) C:\Users\Lenovo\bayesrace>conda install setuptools<58
系统找不到指定的文件。(The English translation for this is the system cannot find the corresponding files.)

**So instead of using the conda install setuptools<58 command, I use the conda install setuptools=52.0.0 command to downgrade the setuptools manually from 58.0.4 to 52.0.0. However, the old errors/bugs disappear, but the new errors/bugs come out:** 
![QQ截图20220110161704](https://user-images.githubusercontent.com/89945534/148841104-30f1de12-d687-4e1f-a107-9c621b8194e4.png)

**Comment by phschiele** [comment]
Can you try a more recent version, like 57?

I think this clearly is not a big in CVXPY itself, so I would suggest moving this discussion to the [Discord](https://discord.gg/4urRQeGBCr) if things don't work out with the above suggestion.

**Comment by dqxiaoduan** [comment]
Thanks for the instruction, the problem has been solved by downgrading the setuptools to a lower version.
