### ISSUE TITLE
Why data report no buxj?

### ISSUE THREAD

**Issue by JianqiangDing** [cvxpy/cvxpy#1601]
Hi, I am using cvxpy to solve a linear optimization problem under some constraints, the problem is the iterating solving procedure does not always remain stable, even there shall be a solution that exists theoretically. I am using MOSEK as the solver,  here is the MOSEK infeasibility report and info after calling MOSEK to analyze the cvxpy output problem file (**.gz).

> MOSEK DUAL INFEASIBILITY REPORT.

Problem status: The problem is dual infeasible

The following constraints are involved in the infeasibility.

Index    Name             Activity         Objective        Lower bound      Upper bound     

The following variables are involved in the infeasibility.

Index    Name             Activity         Objective        Lower bound      Upper bound     
495                       1.000000e+00     1.454947e-01     0.000000e+00     NONE            

                    Analyzing the problem

*** Structural report
               Dimensions
               Constraints   Variables     Matrix var.   Cones       
               358           2346          0             1           

               Constraint and bound types
               Free          Lower         Upper         Ranged        Fixed       
 Constraints:  0             0             0             0             358         
   Variables:  359           1987          0             0             0           

               Cone constraint types
               Quad          R. quad       Primal exp    Dual exp      Primal pow  
        Cones  1             0             0             0             0           

*** Conic structural report

Quad
       Dimension   #           
       [256,511]:  1           
             All:  1           

*** Data report
               Nonzeros      Min           Max         
        |cj|:  2034          5.7e-03       1.0e+03     
       |Aij|:  7764          1.7e-05       2.0e+00     

               # finite      Min           Max         
      |blci|:  358           0.0e+00       1.0e+00     
      |buci|:  358           0.0e+00       1.0e+00     
      |blxj|:  1987          0.0e+00       0.0e+00     

*** Done analyzing the problem

Interior-point solution summary
  Problem status  : DUAL_INFEASIBLE
  Solution status : DUAL_INFEASIBLE_CER
  Primal.  obj: 1.4549473543e-01    nrm: 1e+00    Viol.  con: 0e+00    var: 0e+00    cones: 0e+00  
Optimizer summary
  Optimizer                 -                        time: 0.00    
    Interior-point          - iterations : 0         time: 0.00    
      Basis identification  -                        time: 0.00    
        Primal              - iterations : 0         time: 0.00    
        Dual                - iterations : 0         time: 0.00    
        Clean primal        - iterations : 0         time: 0.00    
        Clean dual          - iterations : 0         time: 0.00    
    Simplex                 -                        time: 0.00    
      Primal simplex        - iterations : 0         time: 0.00    
      Dual simplex          - iterations : 0         time: 0.00    
    Mixed integer           - relaxations: 0         time: 0.00    

The problem is, why the data report shows me that there is no |buxj| (upper bound for xj), even I define constraints using cvxpy as 

```python
cost = cp.sum_squares(lhs_m @ x - rhs_v)
prob = cp.Problem(cp.Minimize(cost),
                  [
                      0 <= g @ x - h,
                      g @ x - h <= 1,
                      z @ x >= 0,
                      x >= -1000,
                      x <= 1000
                  ])
```
Am I wrong somewhere? any suggestion would be helpful for me.

**Comment by aszekMosek** [comment]
CVXPY reformulates the problem, canonicalizes, dualizes, so everything ends up elsewhere than you thought and with different signs.

As a simple example, even the older versions of CVXPY which did not dualize, would write a bound such as ``x>=c`` for a variable ``x`` in the constraint section as constraint of the form ``-x<=-c``, so there would be ``-c`` in ``buc`` rather than ``c`` in ``blx``. Or something along these lines.

If you want any such information to make sense you must save the problem MOSEK actually gets in readable format (for example ``save_file="something.opf"``, see https://docs.mosek.com/latest/faq/faq.html#cvxpy) and then relate the infeasibility reports, problem analyzer output, etc., with respect to that file.

If you need full control over this kind of things then use the solver's API directly.

**Comment by aszekMosek** [comment]
And if you want more stability then consider minimizing ``cp.norm`` instead of ``cp.sum_squares`` - equivalent problem, but often better numerical properties.

**Comment by JianqiangDing** [comment]
big thanks for your quick response, really useful advice. Calling MOSEK API directly do shall be the better way to debug infeasibility.

**Comment by JianqiangDing** [comment]
> CVXPY reformulates the problem, canonicalizes, dualizes, so everything ends up elsewhere than you thought and with different signs.
> 
> As a simple example, even the older versions of CVXPY which did not dualize, would write a bound such as `x>=c` for a variable `x` in the constraint section as constraint of the form `-x<=-c`, so there would be `-c` in `buc` rather than `c` in `blx`. Or something along these lines.
> 
> If you want any such information to make sense you must save the problem MOSEK actually gets in readable format (for example `save_file="something.opf"`, see https://docs.mosek.com/latest/faq/faq.html#cvxpy) and then relate the infeasibility reports, problem analyzer output, etc., with respect to that file.
> 
> If you need full control over this kind of things then use the solver's API directly.

@aszekMosek Hi, sorry to bother you again, I want to ask, is '-x<=-c' and 'x>=c' exactly the same in modelling a problem(even they are exactly the same thing theoretically)? does add lower bounds explicitly performs better than modelling all constraints as upper bounds? Can the conversion stabilize the computation in some degree when calling MOSEK as a solver, am I right?

**Comment by aszekMosek** [comment]
If the conversion has any numerical effect then it is accidental and solver-dependent. The conversions are for cvxpy's convenience. 

MOSEK has its own presolve that will anyway convert everything into some internal problem according to its own rules.

If you would like to discuss something specifically about MOSEK then I suggest https://groups.google.com/g/mosek may be a better place.
