### ISSUE TITLE
Question: is cvxpy thread-safe?

### ISSUE THREAD

**Issue by hzliu** [cvxpy/cvxpy#1602]
I have searched on the web, someone said cvxpy was not thread-safe on 2018. Now is 2022, any changes?

**Comment by rileyjmurray** [comment]
We haven't specifically worked on thread safety since then. However, I've used CVXPY in multiple processes by dispatching from Dask. This hasn't produced any problems to my knowledge. See my comment here: https://github.com/cvxpy/cvxpy/issues/1021#issuecomment-655612901.

**Comment by rileyjmurray** [comment]
I think this discussion should be moved to cvxpy's GitHub Discussions.
