### ISSUE TITLE
cvxpy pip package fails to install on M1 with python 3.9

### ISSUE THREAD

**Issue by si14** [cvxpy/cvxpy#1604]
**Describe the bug**

`cvxpy` pip package fails to install on M1 with python 3.9. The reason seems to be simple: `cvxpy` specifies a version of numpy https://github.com/cvxpy/cvxpy/blob/ac57b1ced831c319ea49de135c4a1c9477ca5292/pyproject.toml#L20 that is not compatible with M1 yet, 1.21.4 being the release they included M1 support in: https://github.com/numpy/numpy/releases/tag/v1.21.4

**To Reproduce**

Try to install `cvxpy` in a clean python 3.9 env on M1.

**Expected behavior**

It shouldn't fail.

**Output**
```
python-3.9.9 ❯ pip install cvxpy
Collecting cvxpy
  Using cached cvxpy-1.1.18.tar.gz (1.3 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/foobar/python-3.9.9/bin/python /private/var/folders/fs/ygypst711711048hd13tfhnr0000gn/T/pip-standalone-pip-wvesyd8j/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/fs/ygypst711711048hd13tfhnr0000gn/T/pip-build-env-wqa2kq5g/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.15,<1.16; python_version=='"'"'3.6'"'"'' 'numpy>=1.15,<1.16; python_version=='"'"'3.7'"'"'' 'numpy>=1.16,<1.17; python_version=='"'"'3.8'"'"'' 'numpy>=1.19,<1.20; python_version=='"'"'3.9'"'"'' 'numpy>=1.21,<1.22; python_version=='"'"'3.10'"'"'' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (910 lines):
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.10"' don't match your environment
  Collecting numpy<1.20,>=1.19
    Using cached numpy-1.19.5.zip (7.3 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting scipy>=1.1.0
    Using cached scipy-1.7.3-1-cp39-cp39-macosx_12_0_arm64.whl (27.0 MB)
  Collecting setuptools>=40.8.0
    Using cached setuptools-60.5.0-py3-none-any.whl (958 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Building wheels for collected packages: numpy
    Building wheel for numpy (pyproject.toml): started
    Building wheel for numpy (pyproject.toml): finished with status 'error'
    ERROR: Command errored out with exit status 1:
...
```

**Version**
 - OS: macOS Monterey 12.1
 - CVXPY Version: 1.1.18

**Additional context**

**Comment by SteveDiamond** [comment]
Relevant https://github.com/cvxpy/cvxpy/issues/1190

**Comment by h-vetinari** [comment]
Note that this works in conda-forge:
```
conda install -c conda-forge cvxpy
```
(where we patch out pyproject.toml for pretty much exactly this reason).

**Comment by vinas94** [comment]
I get the same error. I also run macOS Monterey 12.1.

**Comment by rileyjmurray** [comment]
I'd like for us to get this resolved before the end of the month. PyPA documentation says we can calculate build dependencies dynamically: https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#build-time-dependencies. I'll start looking into this.

**Comment by rileyjmurray** [comment]
This should be resolved by #1670. I'll post on the Discord asking some M1 owner to verify. Ping @si14 @vinas94.

**Comment by rileyjmurray** [comment]
I can confirm that this cause of the build failure was resolved by direct commit https://github.com/cvxpy/cvxpy/commit/c31e03c66aa6f77926bd7ff44621c57df38b6c4c. Basic ``pip install .`` can still fail on M1, but this is for reasons that relate to cvxpy's dependencies (OSQP and ECOS). I'll update the web documentation to mention how to overcome those issues.

**Comment by rileyjmurray** [comment]
Web documentation has been updated in direct commit https://github.com/cvxpy/cvxpy/commit/40caf4f4125d8329184575d12965782244852cef. Closing this issue for now. We can re-visit it if someone finds a problem with our ``pyproject.toml`` file, but otherwise M1 build issues should be reported and discussed on #1190.
