### ISSUE TITLE
failed to run code in flows

### ISSUE THREAD

**Issue by DrunkRandomWalker** [cvxpy/cvxpy#1609]
**Describe the bug**
I tried to run incidency_matrix.py  but got ValueError: All the input dimensions except for axis 0 must match exactly.

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

https://colab.research.google.com/drive/1B1JVWz8-nyhURckl5EgQtN6N0IPkYsm6?usp=sharing
**Expected behavior**

**Comment by phschiele** [comment]
@DrunkRandomWalker Could you explain in a bit more detail what you are trying to do?

As mentioned in the issue description, minimal code examples are ideal. I am also not able to open the colab link you have shared. Feel free to join the [Discord](https://discord.gg/4urRQeGBCr) server, as it is easiest to get some initial feedback to usage questions there.

**Comment by SteveDiamond** [comment]
Fixed
