### ISSUE TITLE
Add documentation for log_normcdf and loggamma.

### ISSUE THREAD

**Issue by SteveDiamond** [cvxpy/cvxpy#1610]
**Is your feature request related to a problem? Please describe.**
We have piecewise linear approximations for log_normcdf and loggamma. But these are not documented anywhere.

**Describe the solution you'd like**
The atoms should be listed here https://www.cvxpy.org/tutorial/functions/index.html
and in the API reference. We may also want to change ``loggamma`` to ``log_gamma`` for consistency with ``log_normcdf``.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rileyjmurray** [comment]
I think we should have ``log_gamma`` and have it appear in the web docs. We can keep ``loggamma``, not document it on the website, and raise a warning if it's called.

**Comment by rileyjmurray** [comment]
We ended up keeping ``loggamma`` since it's the SciPy convention. Documentation added in #1659.
