### ISSUE TITLE
How could constrain the values of the variable matrix to be in {-1, 1}?

### ISSUE THREAD

**Issue by LoveStPaul3** [cvxpy/cvxpy#1613]
I need to constrain the values of the variable matrix to be in {-1, 1}:
for example:
`x = cp.Variable(n,integer=True)  `
`n = 2  `
`P = np.random.randint(-5, 5,size=[n,n])  `
`prob = cp.Problem(cp.Minimize(cp.quad_form(x, P) + q.T @ x))  `

How could i constrain the values of the variable `x` to be in {-1, 1}

Thanks a lor!

**Comment by phschiele** [comment]
@LoveStPaul3 if you want `x` to be in `{-1,1}`, you can try the following:
`x = 2*(cp.Variable(n, boolean=True) - 0.5)` (note the change to `boolean`).

For shorter questions like this, feel free to check out the [Discord](https://discord.gg/4urRQeGBCr) channel.
