### ISSUE TITLE
Minor Typo in Documentation

### ISSUE THREAD

**Issue by rbassett3** [cvxpy/cvxpy#1618]
The documentation for the `get_problem_data` function includes an example which has a small typo. I suspect most folks who read it will be able to figure it out but it's probably worth fixing.

Here's the example from the [docs](https://www.cvxpy.org/api_reference/cvxpy.problems.html?highlight=get%20problem%20data#cvxpy.problems.problem.Problem.get_problem_data)

```
problem = cp.Problem(objective, constraints)
data, _, _ = problem.get_problem_data(cp.SCS)

import scs
probdata = {
  'A': data['A'],
  'b': data['b'],
  'c': data['c'],
}
cone_dims = data['dims']
cones = {
    "f": cone_dims.zero,
    "l": cone_dims.nonpos,
    "q": cone_dims.soc,
    "ep": cone_dims.exp,
    "s": cone_dims.psd,
}
soln = scs.solve(data, cones)
```

The typo is that, when using `SCS`, `data["dims"]` has a cone named `nonneg` but not `nonpos`. So (assuming the `"l"` cone in `SCS` refers to nonnegative variables--I'm not too familiar with its syntax) the correction should read:

```
problem = cp.Problem(objective, constraints)
data, _, _ = problem.get_problem_data(cp.SCS)

import scs
probdata = {
  'A': data['A'],
  'b': data['b'],
  'c': data['c'],
}
cone_dims = data['dims']
cones = {
    "f": cone_dims.zero,
    "l": cone_dims.nonneg,
    "q": cone_dims.soc,
    "ep": cone_dims.exp,
    "s": cone_dims.psd,
}
soln = scs.solve(data, cones)
```

This can be reproduced easily on my machine using cvxpy 1.1.10.

```
x = cp.Variable()
prob = cp.Problem(cp.Minimize(x), [x >= 0])
prob.get_problem_data(cp.SCS) #no nonpos cone
```

Thanks for the great project!

**Comment by SteveDiamond** [comment]
Good catch, thanks!
