### ISSUE TITLE
Is it possible to install CVXPY without QDLDL?

### ISSUE THREAD

**Issue by erelsgl** [cvxpy/cvxpy#1625]
**Is your feature request related to a problem? Please describe.**

The problem is that, when I try to install CVXPY on Windows 10 with the newest version of Python (3.10.2), I get an error when trying to install qdldl (https://github.com/osqp/qdldl-python/issues/19).

**Describe the solution you'd like**

If possible, I would like to be able to install CVXPY without using QDLDL (possibly using other solvers).

**Describe alternatives you've considered**

I tried to install OSQP version 0.6.1, which is said to not need QDLDL, but this failed too:
https://github.com/osqp/osqp/issues/385

**Comment by phschiele** [comment]
@erelsgl As a quick fix, you could install `cvxpy-base` (either from pip or conda) if some of the default solvers are giving you trouble during installation. https://www.cvxpy.org/install/index.html#install-without-default-solvers

**Comment by erelsgl** [comment]
This solved the problem. Thanks!
