### ISSUE TITLE
How to speed up GLPK_MI solver with integer variables? 

### ISSUE THREAD

**Issue by avshekhvatov** [cvxpy/cvxpy#1632]
Hi all, I've written a code which should solve a transportation problem. Size of the problem is following: ~60 warehouses, ~400 routes between them and ~900 orders (roughly, different products). Due to the fact I have "different products", a classic transportation problem converts into ~900 different problems which should be solved at once.

Some parts of my code:

               x = cp.Variable(shape=(roads_c, 1), name="x", integer=True) # flow on each route (roads_c = number of routes = 400 * 900)
               y = cp.Variable(shape=(m_1, 1), name="y", integer=True) # number of trucks on each route (m_1 = 400)
               z = cp.Variable(shape=(m_3, 1), name="z", boolean=True) # if we use a warehouse or not (m_3 = 60)

               q = cp.sum(cp.reshape(x, (m_1, m_5)), axis = 1, keepdims=True) # flow through each warehouse (m_5 = 900)

               constraints = [cp.matmul(A_ub, x) <= b_ub, # A_ub is a sparse matrix showing if flow x[i] is incoming (1) or outgoing (-1) to/from a warehouse, it has a size of ((60-1)*900, 400*900), b_ub is a numpy array showing stock of every product at each warehouse or 0 if it is a transit node ((60-1)*900, 1)

               cp.matmul(A_eq, x) == b_eq, # A_eq is a sparse matrix showing if flow x[i] is incoming (1) or outgoing (-1) to/from a warehouse, its size is (900, 400*900), b_eq is an array with demand (900, 1)

               cp.reshape(cp.multiply(A_ub_2, y), (m_1, 1)) >= q, # A_ub2 is an array with max truck capacity on each route (900, 1) 

               cp.matmul(A_transit, q) <=  cp.multiply(max_transit_qty, z), # A_transit is showing only incoming flows for each warehouse (60, 400), it's a constrain on max warehouse capacity

               cp.matmul(A_transit, q) >=  cp.multiply(min_transit_qty, z), # constrain on min warehouse capacity

               x >= 0,
               y >= 0,
               z >= 0]

`objective = cp.Minimize(cp.sum(cp.matmul(c_1, q)
                               + cp.matmul(c_2, y)
                               + cp.multiply(cp.matmul(A_transit, q), cp.reshape(c_3, (1, m_3)))))`

`problem = cp.Problem(objective, constraints)`
`solution = problem.solve(solver = 'GLPK_MI')`

On smaller datasets this code works perfectly, but with a dataset of the size above the solver step has already been running for 2 days and idk when (read if) it will last... So, the question is how to speed up the optimization? Can I change something? Is it due to a constrain on my variables to be integer?

**Comment by SteveDiamond** [comment]
You might want to use a more powerful MILP solver like Gurobi or SCIP. Generally you want to pass in a time limit as well. Often finding a good solution is fast, but proving it's optimal is quite slow.

**Comment by avshekhvatov** [comment]
> You might want to use a more powerful MILP solver like Gurobi or SCIP. Generally you want to pass in a time limit as well. Often finding a good solution is fast, but proving it's optimal is quite slow.

Thank you for the reply! So if i set a time limit then a solver will stop optimizing my problem after this time and save the best solution it's managed to find?

I need to add a parameter like this (now I'm trying to use MOSEK solver)? Have I changed the code correctly? I've found this parameter in MOSEK's [documentation](https://docs.mosek.com/8.0/toolbox/all-parameters.html#dparam.mio_max_time).
`solution = problem.solve(solver = 'MOSEK', mosek_params={'MSK_DPAR_MIO_MAX_TIME': 60})`

Solver should stop looking fo a solution after 60 seconds and I'll be able to get most suitable values with: `x.value`?

**Comment by rileyjmurray** [comment]
@avshekhvatov I'm not sure if MOSEK's exact semantics regarding the parameter you've mentioned. It might be that the solver only returns "as soon as possible" after the 60 second time limit. So for very large problems that might be longer than 60 seconds. You should ask MOSEK support for those kinds of details. But your general understanding is correct: specifying 60 for that parameter is the intended way to get the best-known solution after one minute.
