### ISSUE TITLE
partially initialized module 'cvxpy' has no attribute 'Variable' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Pallov** [cvxpy/cvxpy#1633]
import cvxpy as cp
import numpy
m = 30
n = 20
numpy.random.seed(1)
A = numpy.random.randn(m, n)
b = numpy.random.randn(m)
x = cp.Variable()
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)
result = prob.solve()
print(x.value)
print(constraints[0].dual_value)

i wrote the above code from the cvxpy tutorial and "partially initialized module 'cvxpy' has no attribute 'Variable' (most likely due to a circular import)" error is coming. What should I do?

**Comment by SteveDiamond** [comment]
Try uninstalling cvxpy and reinstalling. If that doesn't work, uninstall numpy and cvxpy, then reinstall numpy first, then cvxpy.

**Comment by Pallov** [comment]
For me, it was solved.

**Comment by ProgramAlchemist** [comment]
> I had the same problem, reinstall doesn't work. Have you solved it?

I apologize for making a mistake that I changed the name of the file to `cvxpy.py`. Everything is ok after I rename the file. 
So shamed about this mistake @_@

**Comment by Logrus12** [comment]
Had the same problem. It does not like when script 'steals' name of module.
