### ISSUE TITLE
Interface to OR-Tools/PDLP

### ISSUE THREAD

**Issue by mlubin** [cvxpy/cvxpy#1649]
[OR-Tools](https://github.com/google/or-tools) (master branch) now includes a C++ implementation of the PDLP algorithm that we presented at NeurIPS 2021 ([paper](https://proceedings.neurips.cc/paper/2021/hash/a8fbbd3b11424ce032ba813493d95ad7-Abstract.html)). In contrast to the Julia prototype used the paper, the C++ implementation is multithreaded and a bit faster in serial. Our experience is that it's the fastest LP solver among first-order solvers, especially when solving to high precision (we compared with SCS, haven't benchmarked with OSQP). It's not close to being uniformly better than simplex or barrier solvers, but it does outperform them on occasion. We think this solver would be a useful option for CVXPY users.

Could you provide some guidance on how to create a CVXPY interface?

Some relevant technical points:
- PDLP solves LPs and QPs with diagonal objective matrices (only). The underlying algorithm could be generalized to conic problems, but we're unlikely to implement that anytime soon.
- OR-Tools already has a python interface installable through pip and conda. (Though these releases don't include PDLP yet.)
- OR-Tools has its own solver abstraction. It may make sense to create an "or-tools" wrapper rather than a direct "PDLP" wrapper in order to enable users to access other solvers like Glop. Glop is a production-ready simplex-based solver that's used widely within Google.

CC @dapplegate @lperron @Mizux @bodono

**Comment by SteveDiamond** [comment]
Making an OR-Tools wrapper sounds like the way to go. For reference, here is our documentation on making interfaces: https://www.cvxpy.org/contributing/index.html#solver-interfaces

It's not going to be easy to target a standard form with specialized QP matrices. I would suggest just interfacing as an LP solver.

**Comment by rileyjmurray** [comment]
@mlubin LP solvers follow the conic interface. Support for only diagonal quadratics is interesting. We'd need to think a bit more about how we'd integrate that into CVXPY's reduction system.

If you want this functionality available soon then I suggest you go the LP route. We want to release CVXPY 1.2 before the end of Feb. We're also trying to adopt a stable release cadence, so CVXPY 1.3 won't be available for four to six months after 1.2.

**Comment by Mizux** [comment]
FYI once we release a new version of python `ortools` package with pdlp support, I'll post it here...

**Comment by mkoeppe** [comment]
> * OR-Tools has its own solver abstraction. It may make sense to create an "or-tools" wrapper

This would be very useful and could among other things provide a robust replacement for the current, `CyLP`-based CBC interface.
