### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by erelsgl** [cvxpy/cvxpy#1654]
This line:

https://github.com/cvxpy/cvxpy/blob/f93d6b24d2e51033f24e0fff4553e0cbd968d55c/cvxpy/interface/scipy_wrapper.py#L17

raises a warning:

```
cvxpy\cvxpy\interface\scipy_wrapper.py:17: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
```

This line:
https://github.com/cvxpy/cvxpy/blob/0eb50cdfdf1a0590bbb4b6efd8713dbeb52d6c00/cvxpy/reductions/solvers/conic_solvers/scipy_conif.py#L101

raises the following warning:
```
cvxpy\reductions\solvers\conic_solvers\scipy_conif.py:101: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```

I have Windows 10, in a virtual envirnoment based on Python 3.9. Scipy version is 1.8.0.

**Comment by rileyjmurray** [comment]
Resolved by #1665 and #1670.
