### ISSUE TITLE
CVXPY unable to detect MOSEK

### ISSUE THREAD

**Issue by avyavkumar** [cvxpy/cvxpy#1667]
**Describe the bug**
I have followed the instructions as mentioned [here](https://docs.mosek.com/latest/install/installation.html) for general setup of Mosek in Linux (ie: unpacking the folder into a folder within the same directory called `solver` and adding this to `$PATH`). I want to run Mosek in Google Colab for an optimisation problem.

**To Reproduce**
My code is as follows - 

```
objective = cp.Maximize(cp.sum(A@x)+cp.sum_smallest(A@x,2))
prob = cp.Problem(objective, constraints)
result = prob.solve(solver=cp.MOSEK, verbose=True)
```

**Expected behavior**
I expect the problem to be solved, or Mosek to be detected as I have followed the mentioned instructions. However, I am getting an exception.

**Output**
```
Traceback (most recent call last):
  File "<ipython-input-21-ce714799b272>", line 70, in <module>
    correct_soft_label_KNN, soft_label_points_KNN = classify_with_soft_label_KNN(lines, test_classifications, labeled_centroids, labeled_test_data)
  File "<ipython-input-14-443ac67806c7>", line 8, in classify_with_soft_label_KNN
    distX, distY = get_line_prototypes(line, labeled_centroids[0])
  File "<ipython-input-20-05aa8098d22d>", line 162, in get_line_prototypes
    result = prob.solve(solver=cp.MOSEK, verbose=True)
  File "/usr/local/lib/python3.7/dist-packages/cvxpy/problems/problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cvxpy/problems/problem.py", line 568, in _solve
    self._construct_chains(solver=solver, gp=gp)
  File "/usr/local/lib/python3.7/dist-packages/cvxpy/problems/problem.py", line 511, in _construct_chains
    raise e
  File "/usr/local/lib/python3.7/dist-packages/cvxpy/problems/problem.py", line 497, in _construct_chains
    gp=gp)
  File "/usr/local/lib/python3.7/dist-packages/cvxpy/problems/problem.py", line 434, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver MOSEK is not installed.
```

**Version**
 - OS: Linux
 - CVXPY Version: 1.0.31

**Comment by avyavkumar** [comment]
The directory structure looks like this - 

```
~# pwd
/root
~# ls -lhtr
total 8.0K
drwxr-xr-x 3 root root 4.0K Feb 20 14:16 solver
drwxr-xr-x 2 root root 4.0K Feb 20 14:16 mosek
~# cd mosek/
~/mosek# ls
mosek.lic
~/mosek# cd ../solver/
~/solver# ls
9.3
~/solver# echo $PATH
/root/solver/9.3/tools/platform/linux64x86/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin:/opt/bin
```

**Comment by SteveDiamond** [comment]
Did you install the mosek python interface as described on the mosek website? https://docs.mosek.com/latest/pythonapi/install-interface.html

**Comment by aszekMosek** [comment]
In Google Colab you can just do ``!pip install Mosek``.

**Comment by avyavkumar** [comment]
I can confirm that `!pip install mosek` seems to fix the issue. 

A bit strange considering that I am not using the `pip` distribution, rather I am installing my own version with my own license. So, essentially, even while installing the academic licensed version, `pip install mosek` seems to be a pre-requisite.
