### ISSUE TITLE
DCP error for LP with one parameter, which passes is_dcp(dpp=True))

### ISSUE THREAD

**Issue by ericlux** [cvxpy/cvxpy#1671]
I have constructed a minimal breaking example for an issue I have been running into trying to use parameters. In fact, I will just use the example from the cxvpy [website](https://www.cvxpy.org/tutorial/advanced/index.html?highlight=parameter) section on parameters

```
import cvxpy as cp
x = cp.Variable()
y = cp.Variable()
gamma = cp.Parameter(nonneg=True)
problem = cp.Problem(cp.Minimize(gamma * y), [y == gamma * x])
print("Is DPP? ", problem.is_dcp(dpp=True))
print("Is DCP? ", problem.is_dcp(dpp=False))
```

As stated on the website, this prints "True" and "True". However, if I instantiate the problem by setting the gamma parameter to have value 1, and then solve,

```
gamma.value=1
problem.solve()
```

 I get a DCP error:
![param_error](https://user-images.githubusercontent.com/41397826/155823838-7b55db61-a468-47ec-817b-c2ea01fd4dbb.png)
.

**Comment by SteveDiamond** [comment]
@ericlux what version of cvxpy are you using? I actually don't get any error when I run this.

**Comment by ericlux** [comment]
This was running 1.1.13. It looks like with 1.1.18 it goes away. Sorry, I didn't even realize I was on an out of date installation!

**Comment by SteveDiamond** [comment]
No problem, glad it's fixed!
