### ISSUE TITLE
Error after a fixed number of cvxpy runs

### ISSUE THREAD

**Issue by patziyiwang** [cvxpy/cvxpy#1674]
**Describe the bug**
I'm solving a SDP several times with changing parameters. The optimization fails after a certain number of runs but succeeds if I just ignore the error and run the same optimization one more time. I have tested the failed optimization parameters separately and they work fine.

**Output**
![image](https://user-images.githubusercontent.com/8838975/155618279-1bc2175e-e6ba-4403-87cf-6cd03e7e6ea4.png)

**Version**
 - OS: Ubuntu 16.04
 - CVXPY Version: 1.1.17

**Comment by SteveDiamond** [comment]
Try running it with the solve option ``warm_start = False``. That should be the same as running each problem in total isolation.

**Comment by aszekMosek** [comment]
It is an issue with repeatedly calling eigsh in scipy that has been around for a while. https://stackoverflow.com/questions/63960214/cvxpy-failing-randomly-on-basic-quadratic-problem#comment113142851_63960214
