### ISSUE TITLE
`prod` reports unexpected curvature

### ISSUE THREAD

**Issue by justinberi** [cvxpy/cvxpy#1696]
**Describe the bug**
`prod` reports unexpected curvature. 

For the below case we have a difference in the reported curvature.

**To Reproduce**
```
import cvxpy as cp
x1 = cp.Variable(pos=True)
x2 = cp.Variable(pos=True)
f = x1*x2
print(f.is_quasiconcave())

X = cp.Variable((2,), pos=True)
f = cp.prod(X, axis=0)
print(f.is_quasiconcave())
```

```
True
False
```

**Expected behavior**
Expected `prod(X)` to be interpreted as X[0]*X[1] which would give the same curvature as the first example above.

**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version: 1.2

**Additional context**
Not sure if this is due to an issue with specifying the domain of the vector `X`.

**Comment by justinberi** [comment]
`prod` is also undocumented in the user guide under atomics. https://www.cvxpy.org/tutorial/functions/index.html#

**Comment by SteveDiamond** [comment]
``prod`` is documented as a DGP atom (https://www.cvxpy.org/tutorial/dgp/index.html#scalar-functions). You've found a bit of an odd edge case. It is true that a product of two positive terms is quasi concave, but general products of ``n`` terms (which is what ``prod`` is for), are not quasiconcave. See below:
```
import cvxpy as cp 
x1 = cp.Variable(pos=True) 
x2 = cp.Variable(pos=True) 
x3 = cp.Variable(pos=True) 
f = x1*x2*x3 
print(f.is_quasiconcave()) 
 
X = cp.Variable((3,), pos=True) 
f = cp.prod(X, axis=0) 
print(f.is_quasiconcave()) 
```
Output:
```
False
False
```

**Comment by justinberi** [comment]
Ah thanks for the feedback. Closing as this is expected behabiour.
