### ISSUE TITLE
DOC: use https in all web links (as opposed to http or no prefix)

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1710]
>  For a thorough overview of quasiconvexity, see the paper [Disciplined quasiconvex programming](http://web.stanford.edu/~boyd/papers/dqcp.html).

```
ERROR
The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: http://web.stanford.edu/~boyd/papers/dqcp.html

    Read Error

The system returned: (104) Connection reset by peer

An error condition occurred while reading data from the network. Please retry your request.
```

On the other hand, https://web.stanford.edu/~boyd/papers/dqcp.html works!

**Comment by rileyjmurray** [comment]
@keithbriggs the link appears to work in Chrome and Firefox on my machine. Can you provide more information about how to reproduce this issue?

**Comment by keithbriggs** [comment]
I just clicked on the link!   However, this does work for me at home, whereas at work I have to use an http proxy.    If addresses don't have an explicit http:// or https://, it seems like the proxy is not applied.  I think it would be good practice to put https:// in all external addresses in the doc pages.

**Comment by rileyjmurray** [comment]
Ah, the proxy rears its head again! I agree that it would be good for all doc URLs to use https. I'll update the title of this issue accordingly.

**Comment by rileyjmurray** [comment]
I'm working on a PR that will fix this (at least for sites that can be accessed by HTTPS). I only applied the fixes to links in .rst files though.

**Comment by rileyjmurray** [comment]
Fixed!
