### ISSUE TITLE
DOC: add documentation for cvxpy.real

### ISSUE THREAD

**Issue by caitaozhan** [cvxpy/cvxpy#1713]
The [documentation](https://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html) for **real** in affine atoms is missing. The [real.py](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/atoms/affine/real.py) code exists, but there is no documentation for it.

This missing document wasted me a lot of time to find the API that I want, which is cp.real

**Comment by rileyjmurray** [comment]
Hi @caitaozhan. Thanks so much for reporting this! Getting better documentation together is a priority for us. We really appreciate you taking the time to bring this to our attention.

**Comment by rileyjmurray** [comment]
I'm working on a PR that will fix this. It will also add web documentation for ``imag``.

**Comment by rileyjmurray** [comment]
Done!
