### ISSUE TITLE
Huber regression and Quantile regression links are broken

### ISSUE THREAD

**Issue by mmusallam19** [cvxpy/cvxpy#1714]
**Describe the bug**
Huber regression and Quantile regression examples are not loading when I click the link. See below screenshot.

![image](https://user-images.githubusercontent.com/74632900/158944506-bab0cce9-1fb7-4715-a8a9-c7f3347914d3.png)

**Comment by SteveDiamond** [comment]
Good catch! This will be fixed when the web page updates. In the meantime you can find them here: https://github.com/cvxgrp/cvx_short_course/tree/master/applications
