### ISSUE TITLE
Add cvxpy.HIGHS as an alias of SCIPY (method='highs')

### ISSUE THREAD

**Issue by mkoeppe** [cvxpy/cvxpy#1721]
It would be convenient to have the HIGHS solver available under this name as a shortcut for `cvxpy.SCIPY, scipy_options={"method": "highs"}`

**Comment by SteveDiamond** [comment]
Great idea! We should definitely add these aliases. I wasn't aware of DSDP, so thanks for sharing that.

**Comment by rileyjmurray** [comment]
See my comment here about DSDP: https://github.com/cvxpy/cvxpy/pull/1719#discussion_r831687480

**Comment by ghorn** [comment]
I was going to add a feature request to add HIGHS as as solver, and i found this issue.

I noticed that the [HiGHs documentation](https://ergo-code.github.io/HiGHS/dev/interfaces/python/) points to https://pypi.org/project/highspy/, not to https://pypi.org/project/scikit-highs/.

HIGHS can solve QPs and MILPs. I'm not sure the SCIPY interface can do more than LPs. If that is the case, perhaps I should open a new feature request to add HIGHs as a first-class solver, based on the highspy package.

**Comment by SteveDiamond** [comment]
That sounds useful.

**Comment by Transurgeon** [comment]
closed with #2580
