### ISSUE TITLE
Allow -1 (negative one) in cp.reshape

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1723]
In NumPy, calling ``b = np.reshape(a, shape=s)`` for a tuple ``s`` permits one occurrence of -1 in ``s``. The index -1 is automatically replaced by whatever value is needed for ``s`` to specify valid axis dimensions in reshaping ``a``.

For example, ``np.reshape(a, (-1, 1))`` will reshape ``a`` into a column vector, and ``np.reshape(a, (1, -1))`` will reshape ``a`` into a row vector. More generally, ``np.reshape(a, (-1, k))`` will reshape ``a`` into a matrix of shape ``(a.size / k, k)`` if ``a.size / k`` is an integer and raise an error if ``a.size / k`` is not an integer.

CVXPY's reshape function should have the same behavior as NumPy's (in this regard).

This is minor syntactic sugar as CVXPY exists today, since we only support Expressions with at most two dimensions. This feature would become more important once CVXPY supports n-dimensional Expressions.

**Comment by rileyjmurray** [comment]
See also #1695

**Comment by phschiele** [comment]
[Here](https://github.com/scipy/scipy/blob/0dfb5d600299af16b1482731def7c91f7662ec28/scipy/sparse/_sputils.py#L279-L326) is the shape handling of scipy sparse, which might be a relevant starting point for the logic and error checks. It only works for two dimensions, though.

Another quite compact point of reference is the pydata/sparse implementation found [here](https://github.com/pydata/sparse/blob/07eeab2fe9de57904dc590da001bc2f83ba803b8/sparse/_coo/core.py#L1010-L1019).

**Comment by rileyjmurray** [comment]
This missed v1.3. It would be great to have in 1.4!
