### ISSUE TITLE
Atom for the "outer product"

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1724]
CVXPY should have an atom that computes outer products, akin to https://numpy.org/doc/stable/reference/generated/numpy.outer.html.

Here's a rough implementation of how that could work:
```
import cvxpy as cp

def outer(a, b):
    a = cp.Expression.cast_to_const(a)  # if a is an Expression, return it unchanged.
    assert a.ndim == 1
    b = cp.Expression.cast_to_const(b)
    assert b.ndim == 1
    a = cp.reshape(a, (a.size, 1))
    b = cp.reshape(b, (1, b.size))
    expr = a @ b
    return expr
```

**Comment by rileyjmurray** [comment]
This missed v1.3. It would be a shame to not get it into 1.4! Help very much appreciated on this.

**Comment by SteveDiamond** [comment]
In master.
