### ISSUE TITLE
Why is the optimal value given by CVXPY different from solver's log?

### ISSUE THREAD

**Issue by wtmkcl** [cvxpy/cvxpy#1730]
Dear all,

When using "problem.value" with CVXPY the returned value is different from the "Primal. Obj" of MOSEK. I tried to look in the documentation but no explanation is given.
In the following output, the difference is clear between "Primal.  obj: 7.5834843834e-01" and "Optimal value: -1.030e+00".
I appreciate a lot if anyone can clarify why CVXPY gives a different optimal value from the solver?

Best,

( Below is MOSEK interior point solver log.)

-----------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Mar 30 05:38:55 PM: Invoking solver MOSEK  to obtain a solution.

(CVXPY) Mar 30 05:38:55 PM: Problem
(CVXPY) Mar 30 05:38:55 PM:   Name                   :                 
(CVXPY) Mar 30 05:38:55 PM:   Objective sense        : max             
(CVXPY) Mar 30 05:38:55 PM:   Type                   : CONIC (conic optimization problem)
(CVXPY) Mar 30 05:38:55 PM:   Constraints            : 29              
(CVXPY) Mar 30 05:38:55 PM:   Cones                  : 5               
(CVXPY) Mar 30 05:38:55 PM:   Scalar variables       : 47              
(CVXPY) Mar 30 05:38:55 PM:   Matrix variables       : 0               
(CVXPY) Mar 30 05:38:55 PM:   Integer variables      : 0               
(CVXPY) Mar 30 05:38:55 PM: 
(CVXPY) Mar 30 05:38:55 PM: Optimizer started.
(CVXPY) Mar 30 05:38:55 PM: Presolve started.
(CVXPY) Mar 30 05:38:55 PM: Linear dependency checker started.
(CVXPY) Mar 30 05:38:55 PM: Linear dependency checker terminated.
(CVXPY) Mar 30 05:38:55 PM: Eliminator started.
(CVXPY) Mar 30 05:38:55 PM: Freed constraints in eliminator : 15
(CVXPY) Mar 30 05:38:55 PM: Eliminator terminated.
(CVXPY) Mar 30 05:38:55 PM: Eliminator started.
(CVXPY) Mar 30 05:38:55 PM: Freed constraints in eliminator : 0
(CVXPY) Mar 30 05:38:55 PM: Eliminator terminated.
(CVXPY) Mar 30 05:38:55 PM: Eliminator - tries                  : 2                 time                   : 0.00            
(CVXPY) Mar 30 05:38:55 PM: Lin. dep.  - tries                  : 1                 time                   : 0.00            
(CVXPY) Mar 30 05:38:55 PM: Lin. dep.  - number                 : 0               
(CVXPY) Mar 30 05:38:55 PM: Presolve terminated. Time: 0.00    
(CVXPY) Mar 30 05:38:55 PM: Problem
(CVXPY) Mar 30 05:38:55 PM:   Name                   :                 
(CVXPY) Mar 30 05:38:55 PM:   Objective sense        : max             
(CVXPY) Mar 30 05:38:55 PM:   Type                   : CONIC (conic optimization problem)
(CVXPY) Mar 30 05:38:55 PM:   Constraints            : 29              
(CVXPY) Mar 30 05:38:55 PM:   Cones                  : 5               
(CVXPY) Mar 30 05:38:55 PM:   Scalar variables       : 47              
(CVXPY) Mar 30 05:38:55 PM:   Matrix variables       : 0               
(CVXPY) Mar 30 05:38:55 PM:   Integer variables      : 0               
(CVXPY) Mar 30 05:38:55 PM: 
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - threads                : 8               
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - solved problem         : the primal      
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - Constraints            : 5
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - Cones                  : 5
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - Scalar variables       : 15                conic                  : 15              
(CVXPY) Mar 30 05:38:55 PM: Optimizer  - Semi-definite variables: 0                 scalarized             : 0               
(CVXPY) Mar 30 05:38:55 PM: Factor     - setup time             : 0.00              dense det. time        : 0.00            
(CVXPY) Mar 30 05:38:55 PM: Factor     - ML order time          : 0.00              GP order time          : 0.00            
(CVXPY) Mar 30 05:38:55 PM: Factor     - nonzeros before factor : 15                after factor           : 15              
(CVXPY) Mar 30 05:38:55 PM: Factor     - dense dim.             : 0                 flops                  : 2.17e+02        
(CVXPY) Mar 30 05:38:55 PM: ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME  
(CVXPY) Mar 30 05:38:55 PM: 0   2.9e+00  1.3e+00  9.3e+00  0.00e+00   -8.345695901e+00  0.000000000e+00   1.0e+00  0.00  
(CVXPY) Mar 30 05:38:55 PM: 1   4.0e-01  1.8e-01  5.7e-01  5.21e-01   1.061395706e-02   1.381107647e+00   1.4e-01  0.00  
(CVXPY) Mar 30 05:38:55 PM: 2   6.1e-02  2.7e-02  3.7e-02  1.25e+00   4.725851375e-01   6.583848137e-01   2.1e-02  0.00  
(CVXPY) Mar 30 05:38:55 PM: 3   1.1e-02  4.8e-03  4.0e-03  6.01e-01   7.465437179e-01   7.851463718e-01   3.7e-03  0.00  
(CVXPY) Mar 30 05:38:55 PM: 4   9.5e-05  4.2e-05  3.7e-06  9.60e-01   7.582460030e-01   7.585701504e-01   3.3e-05  0.00  
(CVXPY) Mar 30 05:38:55 PM: 5   2.2e-06  9.7e-07  1.3e-08  9.95e-01   7.583443037e-01   7.583516152e-01   7.5e-07  0.00  
(CVXPY) Mar 30 05:38:55 PM: 6   1.9e-08  8.3e-09  1.1e-11  9.99e-01   7.583483918e-01   7.583484546e-01   6.5e-09  0.00  
(CVXPY) Mar 30 05:38:55 PM: 7   1.1e-08  3.6e-10  1.0e-13  9.84e-01   7.583484383e-01   7.583484408e-01   3.2e-10  0.00  
(CVXPY) Mar 30 05:38:55 PM: Optimizer terminated. Time: 0.01    
(CVXPY) Mar 30 05:38:55 PM: 
(CVXPY) Mar 30 05:38:55 PM: 
(CVXPY) Mar 30 05:38:55 PM: Interior-point solution summary
(CVXPY) Mar 30 05:38:55 PM:   Problem status  : PRIMAL_AND_DUAL_FEASIBLE
(CVXPY) Mar 30 05:38:55 PM:   Solution status : OPTIMAL
(CVXPY) Mar 30 05:38:55 PM:   Primal.  obj: 7.5834843834e-01   nrm: 1e+00    Viol.  con: 8e-09    var: 0e+00    cones: 0e+00  
(CVXPY) Mar 30 05:38:55 PM:   Dual.    obj: 7.5834844083e-01    nrm: 1e+07    Viol.  con: 0e+00    var: 2e-09    cones: 0e+00  
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Mar 30 05:38:55 PM: Problem status: optimal
(CVXPY) Mar 30 05:38:55 PM: Optimal value: -1.030e+00
(CVXPY) Mar 30 05:38:55 PM: Compilation took 1.867e-02 seconds
(CVXPY) Mar 30 05:38:55 PM: Solver (including time spent in interface) took 1.682e-02 seconds

===================
**Version**
 - OS: OSX 12.2
 - CVXPY Version: v1.1.18

**Comment by wtmkcl** [comment]
Thank you @SteveDiamond for the quick reply. 
By the way, This discrepancy in the objective value between the solver and CVXPY happens with MOSEK, ECOS and SCS, even with trivial examples from the documentation.
Walt,

**Comment by SteveDiamond** [comment]
Ok that is normal if there are constant offsets. I don't see that as an issue.
