### ISSUE TITLE
Unboundedness detection can fail for the exponential cone

### ISSUE THREAD

**Issue by FlorianSchwendinger** [cvxpy/cvxpy#1755]
# Unboundedness detection often fails for the exponential cone

[Silvapulle (1981)](https://doi.org/10.1111/j.2517-6161.1981.tb01676.x) gives simple criteria under which the MLE does not exist for the logistic regression model. In this context it is said that the MLE exists, if it is finite and unique. Since in the example given by Silavpulle (1981) the data is separated, the problem is unbounded. The example is chosen to demonstrate that the unboundedness detection for the exponential cone often fails.

- **y** a factor with the levels `case` and `none-case`, giving the outcome of a standardized psychiatric interview.
- **ghqs** an integer giving the general health questionnaire score.

## Example
```py
import cvxpy as cp
import cvxpy.settings as s
import numpy as np
```

### Generate data
```py
X = np.matrix("1 2 ; 1 4 ; 1 5 ; 1 5 ; 1 5 ; 1 7 ; 1 7 ; 1 10 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 0 ; 1 1 ; 1 1 ; 1 1 ; 1 1 ; 1 1 ; 1 1 ; 1 1 ; 1 1 ; 1 2")
Y = np.array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[X.shape, Y.shape]
```

### Logistic regression
```py
beta = cp.Variable(X.shape[1])
log_likelihood = cp.sum(cp.multiply(Y, X @ beta) - cp.logistic(X @ beta))
problem = cp.Problem(cp.Maximize(log_likelihood))

# EOCS
problem.solve(solver = "ECOS", reltol = 1e-32)
problem.status
#py> 'optimal'
beta_ecos = beta.value
beta_ecos
#py> array([-38.28689184,  19.14344586])

# SCS
problem.solve(solver = "SCS", max_iters = 200000)
problem.status
#py> 'optimal'
beta_scs = beta.value
beta_scs
#py> array([-23.73555382,  11.86772503])

# MOSEK
problem.solve(solver = "MOSEK")
problem.status
#py> 'optimal'
beta_mosek = beta.value
beta_mosek
#py> array([-40.10371589,  20.05185876])
```

## Expected behavior
Based on the GLM theory, I would expect that the solvers signal unboundedness.
But since the log-likelihood becomes very flat values of the type `[-2 * a, a]` with `a` big enough will be detected as solution.

## Version
 - OS: Debian GNU/Linux 11 (bullseye)
 - CVXPY Version: `1.2.0`

## Additional context
For logistic regression a linear problem can be formulated to detect if the MLE exists [Konis, K. 2016.](https://ora.ox.ac.uk/objects/uuid:8f9ee0d0-d78e-4101-9ab4-f9cbceed2a2a).
But the same problem, also exists for log-binomial regression (where again another LP
can be formulated to check if [the MLE exits for the log-binomial regression model](https://doi.org/10.1007/s00180-021-01084-5)).
Since the problem is present in both models, I would guess this is a general issue, for the exponential cone.
I don't have a solution to the issue.

Is this behavior expected?

**Comment by rileyjmurray** [comment]
@FlorianSchwendinger I can look into this more later. But, I can say that numerical optimization solvers accessible from cvxpy only support double-precision numbers, which cannot accurately represent numbers below 1e-16. Moreover, convex optimization algorithms require taking products of values that are stored as double-precision numbers, therefore the best that one can really hope for is a solution that's accurate to within 1e-8.

You can also try this problem with MOSEK.

**Comment by keithbriggs** [comment]
Why does the second call to ECOS give a different answer?

**Comment by FlorianSchwendinger** [comment]
I tried MOSEK, the second ECOS are the results of MOSEK (copy paste error) from the [notebook](https://github.com/FlorianSchwendinger/ipynb/blob/main/CVXPY_unboundedness.ipynb) I created the example.

Typically, I write the matrices my self in **R** and use the solvers directly, but since most of the solver authors is the CVXPY group I thought here is best forum to ask this question.

**Comment by FlorianSchwendinger** [comment]
> @FlorianSchwendinger I can look into this more later. But, I can say that numerical optimization solvers accessible from cvxpy only support double-precision numbers, which cannot accurately represent numbers below 1e-16. Moreover, convex optimization algorithms require taking products of values that are stored as double-precision numbers, therefore the best that one can really hope for is a solution that's accurate to within 1e-8.
> 
> You can also try this problem with MOSEK.

Thank you!
This would mean, unboundedness can't be detected for logistic regression?
From my experience the answer is currently yes. This raises the question, is it impossible or can the criteria be changed in a meaningful way that it works again. And is this a problem which only is occurring in logistic regression and log-binomial regression or is this a general problem and only for this cases it is easy to check if a solution exists?

**Comment by FlorianSchwendinger** [comment]
Thank you very much for the answer!

**Comment by rileyjmurray** [comment]
Closing since this isn't a bug in CVXPY or the numerical solvers.
