### ISSUE TITLE
cvxpy.length and minimum_length_least_squares example

### ISSUE THREAD

**Issue by abyvinodm** [cvxpy/cvxpy#1760]
**Describe the bug**
cvxpy.length(x) function is not working as expected.

I tried running the example https://www.cvxpy.org/examples/dqcp/minimum_length_least_squares.html and got the output of 10, instead of 8. 

**To Reproduce**

> n = 10
> np.random.seed(1)
> A = np.random.randn(n, n)
> x_star = np.random.randn(n)
> b = A @ x_star
> epsilon = 1e-2
> x = cp.Variable(n)
> mse = cp.sum_squares(A @ x - b)/n
> problem = cp.Problem(cp.Minimize(cp.length(x)), [mse <= epsilon])
> print("Is problem DQCP?: ", problem.is_dqcp())
> 
> problem.solve(qcp=True)
> print("Found a solution, with length: ", problem.value)
> print("Solution: ", x.value)

**Expected behavior**
The desired output is given in https://www.cvxpy.org/examples/dqcp/minimum_length_least_squares.html. Specifically, the following output on the second line was not reproduced. The webpage says the second line should have been
> Found a solution, with length:  8.0

Instead, I got

> Found a solution, with length:  10.0

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.
> Is problem DQCP?:  True
> Found a solution, with length:  10.0
> MSE:  0.009260093288136631
> x:  [-2.58366030e-01  1.38434327e+00  2.10714108e-01  9.44811159e-01
>  -1.14622208e+00  1.51283929e-01  6.62931941e-01 -1.16358584e+00
>   2.78132907e-13 -1.76314786e-13]
> x_star:  [-0.44712856  1.2245077   0.40349164  0.59357852 -1.09491185  0.16938243
>   0.74055645 -0.9537006  -0.26621851  0.03261455]

**Version**
 - OS: Windows 11
 - CVXPY Version: CVXPY 1.2.0 installed using pip

**Comment by SteveDiamond** [comment]
I think I know why this is happening. Everything is fine, if you look at the actual value of x you can see it's the same as before. It's just about how the optimal value is reported/how length is calculated.

**Comment by SteveDiamond** [comment]
We need to update the ``length`` atom to have a numerical tolerance.

**Comment by abyvinodm** [comment]
That makes sense. Thanks for a quick response.
