### ISSUE TITLE
w.T@V@w is rejected but quad_from is not

### ISSUE THREAD

**Issue by BrannonKing** [cvxpy/cvxpy#1762]
I attempted to use w.T@V@w for a quadratic objective. This gets rejected as violating DCP rules. After looking online, I replaced that with quad_form(w, V). The quad_form method runs fast and fine. Why the difference? Can we make the matrix multiplication approach work?

 - OS: Linux
 - CVXPY Version: 1.2.0

**Comment by phschiele** [comment]
Hi @BrannonKing, 

thanks for taking the time to create the issue even though you found the currently supported way of doing it using `quad_form`. 

Better handling of such quadratic forms was recently suggested by @SteveDiamond on Discord ([here](https://discord.com/channels/845323972962549790/845327242456203295/916038778085343282)). 

Would you be interested in contributing this feature?

**Comment by rileyjmurray** [comment]
Resolved in PR #1986 and available in CVXPY 1.3.
