### ISSUE TITLE
DCP issue with norm

### ISSUE THREAD

**Issue by lorenzosteccanella** [cvxpy/cvxpy#1771]
Hi all, 

I'm new to CVXPY I was trying to set the following problem:

```
import cvxpy as cvx
from Utils.Utils import *

X = cvx.Parameter((2, 2), name="X")
Y = cvx.Parameter((2, 2), name="Y")
C = cvx.Parameter(2, name="C")
W = cvx.Variable((2, 2), pos=False, name="W")

X.value = np.array([[1, 1], [1, 1]])
Y.value = np.array([[1, 1], [1, 1]])
C.value = np.array([1, 1])
W.value = np.random.rand(2, 2)

obj = cvx.Minimize(cvx.sum((cvx.norm((X@W.T - Y@W.T), 2, axis=1) - C)**2, axis=0))
constr = []
myprob = cvx.Problem(obj, constr)
print(myprob.is_dcp())

myprob.solve()
```

but I'm getting the error:

`cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
power(Pnorm(X @ W.T + -Y @ W.T, 2) + -C, 2.0)`

I'm not sure how I could rewrite the function to accomplish with the DCP, moreover, I believe the objective is convex but I'm not sure about it!

Thanks in advance for your help.

**Comment by SteveDiamond** [comment]
The objective is not convex. Specifically ``cvx.norm((X@W.T - Y@W.T), 2, axis=1) - C)**2`` is not convex.

**Comment by lorenzosteccanella** [comment]
Thanks a lot for your quick reply!

Can you give me some intuitive hints on why this function is not convex? Moreover, do you suggest how to make it convex?

Thanks a lot for your help!

**Comment by SteveDiamond** [comment]
Unfortunately it can't be made convex. You could try DCCP (https://github.com/cvxgrp/dccp) or a general nonlinear solver like SciPy optimize https://docs.scipy.org/doc/scipy/reference/optimize.html
