### ISSUE TITLE
Make patch releases: 1.1.20 and 1.2.1.

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#1778]
We've accumulated a few important bugfixes since the releases of 1.1.19 and 1.2.0. I just finished propagating those bugfixes to release/1.1.x and release/1.2.x branches. At this point, all we need to do to make the new releases is described in ``PROCEDURES.md``.

@SteveDiamond could you please try to make the release of 1.1.19? If that goes well then you can go ahead and do 1.2.1 as well. If you run into issues then we can discuss them here. I think it's valuable for more than one project maintainer to have hands-on experience with the release procedures.

**Comment by SteveDiamond** [comment]
Success! The new process is very simple/clean!!

**Comment by rileyjmurray** [comment]
Thanks again to @phschiele for doing a great job setting up CI and deployment infrastructure!
