### ISSUE TITLE
Why exp(x)-x not follow DCP rules?

### ISSUE THREAD

**Issue by yllgl** [cvxpy/cvxpy#1779]
**To Reproduce**

```python
import cvxpy  as cp
x = cp.Variable(1)
cp.Problem(cp.Minimize(x),[cp.exp(x)-x>=0]).solve()
```
**Output**
```
cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically:
The following constraints are not DCP:
0.0 <= exp(var1) + -var1 , because the following subexpressions are not:
|--  0.0 <= exp(var1) + -var1
```
**Version**
 - OS: 
 - CVXPY Version:1.2.0

**Comment by phschiele** [comment]
From the [DCP rules](https://www.cvxpy.org/tutorial/dcp/index.html):

The only valid constraints under the DCP rules are

affine == affine
convex <= concave
concave >= convex

**Comment by yllgl** [comment]
> From the [DCP rules](https://www.cvxpy.org/tutorial/dcp/index.html):
> 
> The only valid constraints under the DCP rules are
> 
> affine == affine convex <= concave concave >= convex

Thanks a lot! But How could I solve "cp.exp(x)-x" constrain if it not follow DCP rules, any possible idea?

**Comment by rileyjmurray** [comment]
Philipp's response is correct. Closing.
