### ISSUE TITLE
Saving DPP compilation time

### ISSUE THREAD

**Issue by jfpios** [cvxpy/cvxpy#1781]
**Is your feature request related to a problem? Please describe.**
The first compilation takes a lot of time when I need to solve the DPP problem repeatedly.

**Describe the solution you'd like**
I want to save the DPP compilation result and load it directly the next time I run the same code.

**Describe alternatives you've considered**
I hope I can output a file to save the compilation result so that I can load the file directly next time.

**Additional context**
Thanks a lot for your work.

**Comment by SteveDiamond** [comment]
You could use CVXPYgen (https://github.com/cvxgrp/cvxpygen). This will compile the problem into C code (using DPP), in a way that's easy to call from Python. Alternatively, you could pickle the problem after you solve it once and load it from the pickle file.

**Comment by phschiele** [comment]
@jfpios we are in the process of building a benchmarking tool and collect real world examples for that. It would be great if you could provide the code that produces the slow compiling problem, if possible.

**Comment by jfpios** [comment]
Thank you for your kind reply. I will try to use CVXPYgen. I am working on a project now, and there is still a long way from finishing it. I will share my code after I get a satisfying result.
