### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by nicomignoni** [cvxpy/cvxpy#1786]
In the example page [Maximizing the volume of a box](https://cvxpy.readthedocs.io/en/latest/examples/dgp/max_volume_box.html) there is a typo at the beginning: 

> [...] and depth w [...]

which I believe should be "_and depth d_".

**Comment by SteveDiamond** [comment]
I had forgotten the readthedocs still existed. I went and deleted it, so that confusion shouldn't arise again.

**Comment by SteveDiamond** [comment]
Resolved.
