### ISSUE TITLE
Visual Studio installation guide is in Google Drive folder without access rights

### ISSUE THREAD

**Issue by rybindmitry** [cvxpy/cvxpy#1788]
**Describe the bug**
To install your package I need to wait until someone gives me permission in some google drive folder https://drive.google.com/file/d/0B4GsMXCRaSSIOWpYQkstajlYZ0tPVkNQSElmTWh1dXFaYkJr/view?usp=sharing

**To Reproduce**
Go to https://www.cvxpy.org/install/index.html and click 'install instruction' for Visual Studio build tools. 

**Expected behavior**
No waiting time to install a package.
![pic](https://user-images.githubusercontent.com/42006378/170689268-4f64d61b-fea5-420b-87e1-85fb598d0a8a.JPG)

**Version**
 - OS: Windows
 - CVXPY Version: Any

**Comment by SteveDiamond** [comment]
Where are you finding this link?

**Comment by SteveDiamond** [comment]
Could you try the link again? Should be fixed.

**Comment by rybindmitry** [comment]
> Could you try the link again? Should be fixed.

Now it works. Thank you.

**Comment by ejwyers** [comment]
hello, I'm having the same issue mentioned above -- the visual studio install instructions at the google docs link requires me to ask for access, and when I type a message and click "request access" it tells me that I need to try again. this is on windows 10. thanks in advance.

**Comment by SteveDiamond** [comment]
The webpage has been updated.
