### ISSUE TITLE
Function handle in solvers

### ISSUE THREAD

**Issue by AnujF1005** [cvxpy/cvxpy#1795]
Add a feature to use the function handles in the objective expression. For e.g. A is matrix of nxn but n is too large. So instead of A, we can able to pass object of class which has overloaded functions for matrix multiplication, transpose, etc. which are efficient than normal matrix multiplication, transpose, etc.

**Comment by SteveDiamond** [comment]
Good idea! I worked on this before (https://web.stanford.edu/~boyd/papers/abs_ops.html), but it's not supported by any solvers currently. It's possible @PTNobel has looked at something similar.

**Comment by AnujF1005** [comment]
Thank you for the link! I'll check it out. But still consider function handles for cvxpy.

**Comment by rileyjmurray** [comment]
@AnujF1005 the problem is that we need a numerical solver that supports function handles. If we had an interface to such a solver then we could talk about having cvxpy expose that feature to users.

**Comment by AnujF1005** [comment]
Okay. Hope that solvers will support the function handles in future for bigger problems. Thank you for the response. I am closing this issue.
