### ISSUE TITLE
examples should not be installed at the top level of the Python library hierarchy

### ISSUE THREAD

**Issue by juliangilbey** [cvxpy/cvxpy#1801]
**Describe the bug**
I ran `pip install --user cvxpy` (or rather, it was pulled in by another package), and I found a directory called `examples` in my Python library directory. 

**Expected behavior**
Such a directory should clearly indicate what it belongs to, either by being called `cvxpy_examples` or `cvxpy/examples`, or should not be installed at all, as it is not a necessary part of the package functionality.

**Version**
 - OS: Debian testing
 - CVXPY Version: 1.2.1

**Comment by juliangilbey** [comment]
As you say, it's really odd.  There's just an `examples` directory.  I just downloaded all four wheel files for Python 3.10 from PyPI, and they all have an `examples` directory at the top level. However, building it from source does not include this directory. So maybe it's something about a newer or older version of setuputils or something like that causing this issue? But in this case it's probably fine to ignore it.

**Comment by phschiele** [comment]
In `setup.py`, the following directories are excluded:
```
exclude=["doc", "examples", "cvxpy.performance_tests"])
```
However, since there are subdirectories in `examples`, these are included again. We need to exclude `examples*`. I'll create a PR for that.

**Comment by rileyjmurray** [comment]
Closed by #1804.
