### ISSUE TITLE
Suppressing SCIP warning

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1805]
Is there any way to suppress this warning? 

```
(CVXPY) Jun 20 04:37:03 PM: Encountered unexpected exception importing solver SCIP:
NotImplementedError("PySCIPOpt (SCIP's Python wrapper) is installed and itsversion is 4.0.0. 
CVXPY only supports PySCIPOpt < 4.0.0.")
```

I'm not using SCIP, so I don't want to see this over and over again.  Also, there's a typo "itsversion".

Alternatively, to actually support SCIP 4.0.0 would be nice!

**Comment by SteveDiamond** [comment]
Could you checkout PR #1807 and see if that fixes the issue?
