### ISSUE TITLE
ECOS seems get invalid results

### ISSUE THREAD

**Issue by essence16** [cvxpy/cvxpy#1806]
**Describe the bug**
When I solve a simple positive semidefinite quadratic programming question: 
```

func.name()
'[-0.06  0.03 -0.04] @ var88 + 0.04 @ QuadForm(var88, [[1. 0. 0.]\n [0. 1. 0.]\n [0. 0. 1.]]) + [1.70309395e-06 7.49063670e-07 5.46946217e-06] @ power(var88 + -param89, 2.0) + [2.85123905e-07 1.15367631e-07 1.89468975e-07] @ power(var88 + -param89, 2.0)'
ipdb> func
Expression(CONVEX, UNKNOWN, (1, 1))
ipdb> t =  cp.Problem(cp.Minimize(func))
ipdb> t
Problem(Minimize(Expression(CONVEX, UNKNOWN, (1, 1))), [])
ipdb> t.solve(solver = 'ECOS')
inf

t.solve(solver = 'OSQP')
10694.424625159516

```
**To Reproduce**
The above easily express the issue.

**Expected behavior**
The question is quadratic and should have a minimum value rather than -inf for ECOS solver. OSQP solver gives a valid answer. 'SCS' also gives inf, which is difficult to understand. For this question, inf is not possible..

**Version**
 - OS: MACOS
 - CVXPY Version: 1.12

**Additional context**

**Comment by SteveDiamond** [comment]
Not sure if you fixed your issue, but if not please post a code snippet that we can run.
