### ISSUE TITLE
ERROR: No matching distribution found for numpy<1.20,>=1.19

### ISSUE THREAD

**Issue by datatravelgit** [cvxpy/cvxpy#1809]
When installing cvxpy using pip proxy options, the step to build dependencies is failing :

ERROR: No matching distribution found for numpy<1.20,>=1.19

Note that I started with a new virtual environment.
Python version 3.9.12
I also installed all the cvxpy dependencies:
- osqp
- ecos
- scs
- numpy
- scipy
And tried again to install cvxpy with the same result.

I do believe that the installation using the pip --proxy option may be the issue here.  For certain restrictions where I am testing this installation, I cannot try without proxy.

**Comment by datatravelgit** [comment]
Hi,

The pip instruction that is failing is 
```
pip --proxy http://user:password@theproxyurl.com:8080 install cvxpy
```

I managed to take cvxpy of the quarentine status in the local repo, and after that I did manage to install cvxpy
```
pip install cvxpy
```

Would it be possible that the cvxpy package may have some limitations regarding the use of a proxy in pip?

**Comment by phschiele** [comment]
@datatravelgit CVXPY does not do anything specific to limit the usage of a proxy.
It looks like the error you see is happening during the build when a pinned version of numpy is being fetched.
What operating system are you on?

**Comment by rileyjmurray** [comment]
Closing since this issue is stale.
