### ISSUE TITLE
XPRESS version 8.14.1 introduces test failure

### ISSUE THREAD

**Issue by phschiele** [cvxpy/cvxpy#1815]
**Describe the bug**
The newest version of XPRESS ([8.14.1](https://pypi.org/project/xpress/#history), released June 24th) breaks the simple boolean test below:

https://github.com/cvxpy/cvxpy/blob/ec1f918d71f55d203c0797943c73fa3f27b3043c/cvxpy/tests/test_mip_vars.py#L109-L117

It's working under 8.14.0, so an interface change seems rather unlikely. 

**Version**
 - OS: All
 - CVXPY Version: master

Note: XPRESS is now available for Python 3.10, will include it in the test suite.

**Comment by rileyjmurray** [comment]
@phschiele have you reported this to XPRESS devs?

**Comment by rileyjmurray** [comment]
Ping @merraksh, since you may know who at XPRESS should be informed about this.

**Comment by phschiele** [comment]
@rileyjmurray Yes, we reached out to @merraksh via mail :+1:

**Comment by merraksh** [comment]
Just left a note for the Xpress team.

**Comment by rileyjmurray** [comment]
Resolved on our end in #1838.
