### ISSUE TITLE
Portfolio optimization problem

### ISSUE THREAD

**Issue by mlbhl** [cvxpy/cvxpy#1826]
Among examples, 'portfolio optimization' below is not working. 

https://colab.research.google.com/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb

I guess it's about Problem setting. 

'prob.solve()' encountered following error messages:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-6-0bf8cc09dc2c>](https://localhost:8080/#) in <module>()
      6 for i in range(SAMPLES):
      7     gamma.value = gamma_vals[i]
----> 8     prob.solve()
      9     risk_data[i] = cp.sqrt(risk).value
     10     ret_data[i] = ret.value

6 frames
[/usr/local/lib/python3.7/dist-packages/scipy/sparse/construct.py](https://localhost:8080/#) in block_diag(mats, format, dtype)
    691     row = np.concatenate(row)
    692     col = np.concatenate(col)
--> 693     data = np.concatenate(data)
    694     return coo_matrix((data, (row, col)),
    695                       shape=(r_idx, c_idx),

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

**Comment by SteveDiamond** [comment]
Also make sure you're using the lates cvxpy.

**Comment by phschiele** [comment]
@rileyjmurray and @rileyjmurray had a good gut feeling here!
Colab uses cvxpy version 1.0.31.
Just create new cell, run `!pip install --upgrade cvxpy`, restart the runtime as prompted and you should be good to go!

(Perhaps we can create a PR to upgrade the dependencies on colab, but I'm not sure where these are defined, or even open source at all)

**Comment by mlbhl** [comment]
Thank you all! It was a cvxpy version issue at Colab, as @phschiele pointed out. It was solved by upgrading cvxpy version!
