### ISSUE TITLE
Incorrect solution from quasilinear constraint

### ISSUE THREAD

**Issue by nicklar** [cvxpy/cvxpy#1828]
**Describe the bug**
cp.sum(cp.sign(x)) constraints not being enforced in a DQCP.

**To Reproduce**
x = cp.Variable(2)
obj = cp.sum_squares(np.ones(2) - x)
constr = [cp.sum(cp.sign(x)) <= 1]
prob = cp.Problem(cp.Minimize(obj), constr)
prob.solve(qcp = True)

Also try this with <= 0 instead of 1 and it will raise a recursion error.

**Expected behavior**
The optimal solution of this problem should be (0, 1) but x.value returns (1, 1)

**Version**
 - OS: M1 Mac monterey
 - CVXPY Version: 1.2.0

**Comment by SteveDiamond** [comment]
Your problem should not be ``qcp``. It's a bug in the problem validation. QCP is only supposed to handle ``sign`` applied to scalars. @akshayka can you confirm?
