### ISSUE TITLE
diff fails on 2-D arrays with 1 row

### ISSUE THREAD

**Issue by sunnyxxchen** [cvxpy/cvxpy#1834]
**Describe the bug**
The `diff` command raises the ValueError `"Must have k >= 0 and X must have < k elements along "axis"` when attempting to calculate discrete differences for a 1-by-N array across the row.

**To Reproduce**
```
import cvxpy as cp

x1 = np.array([[1, 2, 3, 4, 5]])
x2 = cp.Variable((1, 5))

cp.diff(x1, axis=1)
cp.diff(x2, axis=1)
```

**Expected behavior**
`cp.diff` should be able to calculate the discrete difference for these examples. The corresponding numpy command works correctly on these examples.

**Version**
 - OS: macOS 12.4
 - CVXPY Version: 1.2.1

**Comment by SteveDiamond** [comment]
This is fixed on master.
