### ISSUE TITLE
Visual Studio installation guide is in Google Drive folder without access rights

### ISSUE THREAD

**Issue by ejwyers** [cvxpy/cvxpy#1848]
**Describe the bug**
Hello, I am looking to view the Visual Studio instructions in this google drive folder:

https://drive.google.com/file/d/0B4GsMXCRaSSIOWpYQkstajlYZ0tPVkNQSElmTWh1dXFaYkJr/view?usp=sharing

but I cannot access it.

**To Reproduce**
Go to https://www.cvxpy.org/install/index.html and click 'install instruction' for Visual Studio build tools.

**Expected behavior**
No waiting time to install a package.

**Output**
https://user-images.githubusercontent.com/42006378/170689268-4f64d61b-fea5-420b-87e1-85fb598d0a8a.JPG

**Version**
 - OS: Windows 10
 - CVXPY Version: Any

**Additional context**
This issue I'm having was already opened and closed earlier this year -- see https://github.com/cvxpy/cvxpy/issues/1788 
I wasn't sure if commenting on the original thread would elevate this to the level of getting this issue resolved, so I made this new issue post. Apologies in advance if this goes against the norms of this site.

**Comment by SteveDiamond** [comment]
I don't know what to tell you. The sharing settings are anyone with a link can view. I've uploaded the slides here as well.
[CVXPY windows work through.pptx](https://github.com/cvxpy/cvxpy/files/9227081/CVXPY.windows.work.through.pptx)
.

**Comment by ejwyers** [comment]
Just tried to access the instructions through Google Drive, and this time I was able to submit a request, but still not able to view the instructions on there. 

I do know what to tell you, though: thanks for the link.

**Comment by SteveDiamond** [comment]
Can you tell me if this link works? https://docs.google.com/presentation/d/0B4GsMXCRaSSIOWpYQkstajlYZ0tPVkNQSElmTWh1dXFaYkJr/edit?resourcekey=0-HEezB2NFstz1GjKDkroJSQ#slide=id.p1

**Comment by ejwyers** [comment]
Success! 

Note though that the install wizard for Visual Studio from the link given on the cvxpy install page looks a bit different than what is shown in the google doc. It's still not too hard to figure out, but just wanted to mention it.

Thanks again!

**Comment by SteveDiamond** [comment]
The webpage has been updated.
