### ISSUE TITLE
"cvxpy.error.SolverError: The solver XPRESS is not installed." 

### ISSUE THREAD

**Issue by erelsgl** [cvxpy/cvxpy#1850]
**Describe the bug**
I [installed XPRESS ](https://content.fico.com/xpress-optimization-community-license?utm_source=FICO-Community&utm_medium=optimization-homepage) for Windows 10, with their community license.
Still, when I try to solve a problem with solver=cvxpy.XPRESS, I get this error:

   cvxpy.error.SolverError: The solver XPRESS is not installed

**To Reproduce**

    problem = cvxpy.Problem(cvxpy.Maximize(1), constraints = [])
    problem.solve(solver=cvxpy.XPRESS)

**Expected behavior**
Problem should be solved.

**Output**

   cvxpy.error.SolverError: The solver XPRESS is not installed

**Version**
 - OS: Windows 10
 - CVXPY Version: cvxpy-base 1.2.1

**Comment by rileyjmurray** [comment]
Hi @erelsgl. Can you please provide more information? What happens when you try ``import xpress``?

**Comment by erelsgl** [comment]
Ah, I see my mistake - I installed XPRESS on my Windows system, but did not `pip install xpress`.
