### ISSUE TITLE
Not concave when given 0<p<1 as a parameter for the power

### ISSUE THREAD

**Issue by k-kawakami213** [cvxpy/cvxpy#1855]
**Describe the bug**
If p, 0<p<1 is given as the parameter of the power, it is not concave, but if given as a floating point, it becomes concave, why?

**To Reproduce**

```
import cvxpy as cp
x = cp.Variable(nonneg=True)
res = cp.power(x, 0.5)
```
This gives `Expression(CONCAVE, NONNEGATIVE, ())`, which is as I expected.

```
import cvxpy as cp
x = cp.Variable(nonneg=True)
p = cp.Parameter(nonneg=True, value=0.5)
res = cp.power(x, p)
```
This gives `Expression(QUASILINEAR, NONNEGATIVE, ())`

**Expected behavior**
I thought the latter example would also be concave.

**Version**
 - OS: macOS Monterey 12.4
 - CVXPY Version: 1.1.13

**Comment by SteveDiamond** [comment]
Curvature does not depend on the value of parameters, only their sign. The reason for this is that the curvature must be the same even if you change the value of the parameter. Whereas constants cannot change so the curvature uses more information.

**Comment by k-kawakami213** [comment]
@SteveDiamond 
Thanks for the quick response. So, in power(x, p), if I use p as a parameter, can I formulate it as DCP/DPP? Is there some way around this?

**Comment by SteveDiamond** [comment]
No it is impossible. That's part of the restrictions of DPP. Why do you need the power to be a parameter?

**Comment by SteveDiamond** [comment]
The one exception is you could solve a geometric program.

**Comment by k-kawakami213** [comment]
Thank you. I was hoping to solve it end-to-end using cvxpylayers, etc., but getting it into DPP seems complicated so I will consider a different approach.

**Comment by SteveDiamond** [comment]
What precisely is your optimization problem? It might be GP compatible in which case you can use cvxpylayers.

**Comment by k-kawakami213** [comment]
@SteveDiamond 
I'd like to solve the bidding optimization problem for real-time bidding described in this [article](https://arxiv.org/pdf/1603.01055.pdf). I am trying to solve a problem in which Equation 14 is substituted into Equations 6 and 7.

The pseudo-code is as below:
```
import cvxpy as cp
import numpy as np
from cvxpylayers.torch import CvxpyLayer
import torch

# Generate data
torch.manual_seed(1)
np.random.seed(1)

# num of ads
n = 3

# Construct CVXPY problem and layer
a_cvxpy = [cp.Parameter(nonneg=True, name=f'a_{i}') for i in range(n)]
# a_cvxpy = [1, 1, 1]
b_cvxpy = [cp.Parameter(nonneg=True, name=f'b_{i}') for i in range(n)]
bp_cvxpy = [cp.Parameter(nonneg=True, name=f'bp_{i}') for i in range(n)]
# b_cvxpy = [0.5, 0.5, 0.5]
B = cp.Parameter(nonneg=True, name=f'B')
# B = 10
avg_cpc = [cp.Parameter(nonneg=True, name=f'avg_cpc_{i}') for i in range(n)]
# avg_cpc = np.array([10, 10, 10])
avg_click = [cp.Parameter(nonneg=True, name=f'avg_click_{i}') for i in range(n)]
# avg_click = np.array([10, 10, 10])

x_cvxpy = cp.Variable((n, 1), nonneg=True, name=f'x')

objective = cp.sum([a_cvxpy[i] * avg_click[i]
                    * cp.power(x_cvxpy[i] / avg_cpc[i], b_cvxpy[i]) for i in range(n)])
constraints = [
    x_cvxpy >= 0,
    cp.sum([a_cvxpy[i] * avg_click[i] * cp.power(x_cvxpy[i], bp_cvxpy[i])
            * cp.power(1 / avg_cpc[i], b_cvxpy[i]) for i in range(n)]) <= B
]
problem = cp.Problem(cp.Maximize(objective), constraints)
for i in range(n):
    a_cvxpy[i].value = 1.0
    b_cvxpy[i].value = 0.5
    bp_cvxpy[i].value = 1.5
    avg_cpc[i].value = 10
    avg_click[i].value = 100
B.value = 1000
problem.solve()
policy = CvxpyLayer(
    problem, [a_cvxpy, b_cvxpy, bp_cvxpy, B, avg_cpc, avg_click], [x_cvxpy])
print(policy([1.0, 1.0], [0.5, 0.5], [1.5, 1.5],  1000, [10, 10], [100, 100]))
```

**Comment by SteveDiamond** [comment]
That looks DGP to me (https://web.stanford.edu/~boyd/papers/diff_dgp.html, https://www.cvxpy.org/tutorial/dgp/index.html). You should define parameters as vectors rather than scalars. Also if you want to use cvxpylayers you need to be a bit more careful about what you choose as your parameters. Hopefully the linked paper will clarify.

**Comment by k-kawakami213** [comment]
Thanks a lot for the advice! I will try it.
