### ISSUE TITLE
How to install cvxpy 0.4 in 2022?

### ISSUE THREAD

**Issue by realgump** [cvxpy/cvxpy#1860]
Hi, I am currently running an old python2 code, which requires cvxpy==0.4.11. It's really hard to match the version of cvpxy, python, numpy... How to correctly install cvxpy 0.4?

**Comment by rileyjmurray** [comment]
Hi @realgump, thanks for coming by.

We don't officially support CVXPY 0.4 anymore. The best I can do is to point you to the testing configurations we used back when we did support CVXPY 0.4: https://github.com/cvxpy/cvxpy/blob/0.4/.travis.yml. Assuming the builds were working at the time then you'd want to install NumPy 1.10.4 and SciPy 0.17.0. I suggest you install these only by pip. Trying with conda will probably result in some packages getting updated in unexpected ways.

I'm going to close this issue, but please feel free to post more information here if you think that others might benefit from things you learn in this process.
