### ISSUE TITLE
Add the OpenSSF Scorecard Github Action 

### ISSUE THREAD

**Issue by joycebrum** [cvxpy/cvxpy#1891]
**Is your feature request related to a problem? Please describe.**
Hello, I'm Joyce Brum, this issue is not related to any specific problem, but to overall security of the project.

I am working on behalf of Google and the [OpenSSF][ossf] to help essential open-source projects improve their supply-chain security. The OpenSSF is a non-profit foundation dedicated to improving the security of the open-source community. It counts GitHub as a founding [member][ossf-membership].

The [Scorecard][sc] system combines dozens of automated checks to let maintainers better understand their project's supply-chain security posture. It is developed by the OpenSSF, with [direct support from GitHub][sc-blog].

Considering te CVXPY relevance within python community, the OpenSSF has included it in its list of the 100 most critical open-source projects.

However, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha], which adds the results of its checks to the project's [security dashboard](https://github.com/cvxpy/cvxpy/security), as well as suggestions on how to solve any issues (see examples below). This Action has been adopted by 1600+ projects already.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[ossf-membership]: https://openssf.org/about/members/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Describe the solution you'd like**

Would you be interested in a PR which adds this Action? Optionally, it can also publish your results to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

**Comment by SteveDiamond** [comment]
Thanks for reaching out Joyce! This sounds very helpful, and I appreciate the PR! I will discuss with the other maintainers and get back to you.
