### ISSUE TITLE
type(cp.sum([])) is int

### ISSUE THREAD

**Issue by songyesog2000** [cvxpy/cvxpy#1904]
**Describe the bug**
cp.sum(list),
when list is empty, it will return 0, otherwise a linear expression
linear expression class has attribute value
try to use "if cp.sum(list)!=0 " to exclude the list empty case,
but still fail when list is not empty anymore

**Expected behavior**
cp.sum([]) still return a linear expression but with value 0.

**Comment by SteveDiamond** [comment]
When you run ``cp.sum`` on a list, it actually just calls the Python built-in ``sum``. The built-in sum works by starting with 0 then adding elements one by one from the list. So the behavior you're seeing is expected. If you want to check if the list is empty you can check ``len(list)``.

**Comment by songyesog2000** [comment]
Yep, I did so, but i just don't like this solution. kinda not elegant and may use more memory and calculation to assign a system variable to the list and check the list. I know it's very small and no difference at all

**Comment by SteveDiamond** [comment]
Gotcha. Yeah the behavior is a bit weird, a Python quirk.
