### ISSUE TITLE
AD of exponential cones in ECOS

### ISSUE THREAD

**Issue by AxelBreuer** [cvxpy/cvxpy#1915]
I try to calibrate the parameters of a simple convex problem (constraints are linear & cost function is linear - log(linear)).
To do so, I use cvxpylayers which calls cvxpy.

SCS is the default solver used by cvxpylayers to solve exponential cone problems.

Unfortunately SCS is not robust enough, and the parametric gradients are unreliable (they are way off their finite difference approximations). I tried all the tricks I found here and there (eps=1e-8, mode=’dense’, acceleration_lookback=0) but none fixed the issue.

I hence decided to switch to ECOS, but unfortunately I got the following error message:

  _File "C:/Users/GD5264/OneDrive - ENGIE/Projects/Sendout/test_grad_2.py", line 76, in <module>
    Sqty_star_tch, = Scvxpylayer(Sfee_tch, solver_args={'solve_method': 'ECOS', 'mode':'dense'})

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\cvxpylayers\torch\cvxpylayer.py", line 152, in forward
    sol = f(*params)

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\cvxpylayers\torch\cvxpylayer.py", line 288, in forward
    xs, _, _, _, ctx.DT_batch = diffcp.solve_and_derivative_batch(

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\diffcp\cone_program.py", line 80, in solve_and_derivative_batch
    x, y, s, D, DT = solve_and_derivative(As[i], bs[i], cs[i],

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\diffcp\cone_program.py", line 216, in solve_and_derivative
    result = solve_and_derivative_internal(

  File "C:\Users\GD5264\Anaconda3\lib\site-packages\diffcp\cone_program.py", line 314, in solve_and_derivative_internal
    raise NotImplementedError("Exponential cones not supported yet.")_

**Do you know when AD for Exponential cones will be supported for ECOS ? for MOSEK ?**

This feature would be invaluable as, for the moment, I have to stick to finite differences which hinders me to scale up the parameter space. (Not mentioning the fact that combining finite differences and cvxpylayers is a kind of heresy...)

**Comment by SteveDiamond** [comment]
This is not really on the agenda right now, but maybe something you could contribute to? @akshayka is adding exponential cone support for ECOS a feasible thing to contribute to?

**Comment by akshayka** [comment]
I think it's feasible (it's just understanding the affine map from from the SCS standard form to ECOS) but I don't remember the details. @rileyjmurray had some ideas a while back, but he likely does not have the time right now.

It would require modifications to diffcp, and likely would not be many lines of code.

**Comment by akshayka** [comment]
The high-level idea: https://github.com/cvxgrp/diffcp/issues/31#issuecomment-576492277

**Comment by AxelBreuer** [comment]
Thank you very much for your comments @SteveDiamond and @akshayka !
They turned out to be extremely useful, as I think I found a working solution. 

Here is what I did (2 lines of extra code):

In diffcp\cone_program.py, I replaced (around l.338):

        cone_dict_ecos = {}
        if 'l' in cone_dict:
            cone_dict_ecos['l'] = cone_dict['l']
        if 'q' in cone_dict:
            cone_dict_ecos['q'] = cone_dict['q']

by

        cone_dict_ecos = {}
        if 'l' in cone_dict:
            cone_dict_ecos['l'] = cone_dict['l']
        if 'q' in cone_dict:
            cone_dict_ecos['q'] = cone_dict['q']
        if 'ep' in cone_dict:
            cone_dict_ecos['e'] = cone_dict['ep']

(The naming convention for exponential cones in cvxpy (found in function dims_to_solver_dict of cvxpy\reductions\solvers\conic_solvers\conic_solver.py) is 'ep' wheras it is 'e' in ecos)

If you agree with this fix, then the sanity check in diffcp\cone_program.py (around l.315)

        if ('ep' in cone_dict) and (cone_dict['ep'] != 0):
            raise NotImplementedError("Exponential cones not supported yet.")
            pass

should be removed.

Futhermore, we could replace in diffcp\cone_program.py (around l.315)

    if solve_method is None:
        psd_cone = ('s' in cone_dict) and (cone_dict['s'] != [])
        ep_cone = ('ep' in cone_dict) and (cone_dict['ep'] != 0)
        ed_cone = ('ed' in cone_dict) and (cone_dict['ed'] != 0)
        if psd_cone or ep_cone or ed_cone:
            solve_method = "SCS"
        else:
            solve_method = "ECOS"

by

    if solve_method is None:
        psd_cone = ('s' in cone_dict) and (cone_dict['s'] != [])
        ed_cone = ('ed' in cone_dict) and (cone_dict['ed'] != 0)
        if psd_cone or ed_cone:
            solve_method = "SCS"
        else:
            solve_method = "ECOS"

The fix is very short, and I cannot convince myself that it was that 'simple'. I would be very happy to read your feedback on that.

**Comment by SteveDiamond** [comment]
The fix might be so simple. Can you write a PR for diffcp with your proposed changes and also test cases for ECOS with exponential cone that compare finite difference computation of the gradient with diffcp's computation?

**Comment by akshayka** [comment]
@sbarratt does this look right to you / do you remember what was needed to support the exponential cone for ECOS?

**Comment by AxelBreuer** [comment]
Hi, following @SteveDiamond 's recommendation, I wrote a simple test case (along the lines of https://www.cvxgrp.org/scs/examples/python/entropy.html#py-entropy).
This allowed me to spot an extra fix to add to make things really work:
As previously noted in https://github.com/embotech/ecos/issues/126 there are different conventions of mapping (x,y,z) to the exponential cone K.
In ECOS:
`K = cl{(x,y,z) | exp(x/z) <= y/z, z > 0}`
In SCS (hence diffcp):
`K = {(x,y,z) | y*exp(x/y) <= z, y > 0} ∪ {(x,y,z)∣x ≤ 0, y = 0, z ≥ 0}`
The role of y and z are swapped.
When adding this swapping, I obtain excellent results.
I am now preparing a pull request.

**Comment by AxelBreuer** [comment]
closed by https://github.com/cvxgrp/diffcp/pull/55
