### ISSUE TITLE
M1 - able to installed on Miniconda, no success with Anaconda  (M1)

### ISSUE THREAD

**Issue by thayerst2012** [cvxpy/cvxpy#1919]
**Describe the bug**
(1) Was able to install CVXPY on miniconda, and realized should have installed on the Anaconda directory after failing to import CVXPY (apologies, python newbie here!)

(2) Tried various commands to install on Anaconda, and been getting the same error at the step of '**Getting requirements to build wheel** ... error'   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]

**To Reproduce**
```
Installation commands tried:
!/opt/anaconda3/bin/python -m pip install cvxpy
```

```
import sys
!{sys.executable} -m pip install cvxpy
```

`!/opt/anaconda3/bin/python -m conda install cvxpy
`

**Output**

Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]

....

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  

**Version**
 - OS: Big Sur

**Comment by SteveDiamond** [comment]
Is ``python -m pip install cvxpy`` the same as ``pip install cvxpy``? I've never done the former.

**Comment by phschiele** [comment]
`python -m pip` simply means use the pip module of the `python` executable. I sometimes use this to ensure there is no ambiguity to which Python version the pip command refers to.

**Comment by phschiele** [comment]
@thayerst2012 it looks like the install fails while trying to install a dependency. Can you try installing `cvxpy-base` instead of `cvxpy`? This will not install any solver yet, so we can narrow down which dependency is causing the issue.

**Comment by thayerst2012** [comment]
@phschiele  thanks! I was able to install to miniconda environment using pip (still doesn't work for anaconda, but I guess it indicated that the issue was not with the M1 chip then).
