### ISSUE TITLE
DPP with indices as parameters

### ISSUE THREAD

**Issue by FilippoVannella** [cvxpy/cvxpy#1920]
I am trying to use indices as parameters in a DPP. I crafted this simple example which is similar to my original problem to clarify the problem. 

    import cvxpy as cp
    import numpy as np
    N = 10
    c = np.random.rand(N)
    x = cp.Variable(N,nonneg = True)
    idx = cp.Parameter()
    z = cp.Variable()

    constraints = [cp.sum(x) == 1]
    for i in range(N):
        if i != idx.value:
            constraints.append(z >= (cp.inv_pos(x[i]) + cp.inv_pos(x[idx]))/c[i])
    obj = cp.Minimize(z)
    prob = cp.Problem(obj,constraints)
    prob.solve()

Since cvxpy parameters cannot be used as numpy indices, the error raised is 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices.

Note that, If I remove the parameter with an integer (e.g. 1 in the example below), I obtain a solution 

    import cvxpy as cp
    import numpy as np
    N = 10
    c = np.random.rand(N)
    x = cp.Variable(N,nonneg = True)
    idx = 1
    z = cp.Variable()

    constraints = [cp.sum(x) == 1]
    for i in range(N):
        if i != idx:
            constraints.append(z >= (cp.inv_pos(x[i]) + cp.inv_pos(x[idx]))/c[i])
    obj = cp.Minimize(z)
    prob = cp.Problem(obj,constraints)
    prob.solve()

The problem is that I need to solve this program many times and hence I need a parametric representation of it. 

I tried using boolean variables and using the fact that $x[i] = x^\top 1_i$, where $1_i$ is the standard basis vector in $N$ dimensions (modeled as a cvxpy Parameter), but nothing worked.

Is there any trick to use cvxpy parameters as indices that can be used in numpy arrays or there is no hope at all?

**Comment by SteveDiamond** [comment]
The short answer is cvxpy parameters are not supposed to be used as indices. The longer answer is that you could maybe do something with a binary mask as a parameter instead of indexing, but honestly I think it will be easier to vectorize your code and make the normal non-DPP compilation path faster. You can see the compilation time if you solve with ``verbose=True``.

**Comment by FilippoVannella** [comment]
I tried the binary mask:

"I tried using boolean variables and using the fact that $w[i] = w^\top 1_i$, where $1_i$ is the standard basis vector in $N$ dimensions (modeled as a CVXPY Parameter), but nothing worked." 

Is this what you were suggesting?

The code needs to run as a DPP since I have large problems with thousands of variables that need to run repeatedly. I tried the other way and the running time is significantly larger

**Comment by SteveDiamond** [comment]
> I tried the binary mask:
> 
> "I tried using boolean variables and using the fact that x[i]=x⊤1i, where 1i is the standard basis vector in N dimensions (modeled as a CVXPY Parameter), but nothing worked."
> 
> Is this what you were suggesting?
> 
> The code needs to run as a DPP since I have large problems with thousands of variables that need to run repeatedly. I tried what you suggested and the running time is significantly larger.

What do you mean by ``nothing worked``? This should work:

```
# x[i]
e_i = cp.Parameter(boolean=True)
e_i.value = ...
x_i  = e_i @ x
```

**Comment by FilippoVannella** [comment]
You are right, this works on this probelem. My original problem was a geometric program of this type 

import cvxpy as cp
import numpy as np
np.random.seed(1)
N = 10
c = np.random.rand(N)
x = cp.Variable(N,pos = True)
y = cp.Variable(N,pos = True)
idx = cp.Parameter()
z = cp.Variable(pos = `True)`
e_i = cp.Parameter(N,boolean = True)

constraints = [cp.sum(x) <= 1]
constraints = [cp.sum(y) <= 1]
for i in range(N):
    if i != idx.value:
        constraints.append(z >= (cp.inv_pos(x[i]*y[i]) + (cp.inv_pos(x[idx]*y[idx]))/c[i]))
e_i.value = np.eye(1,N,5).flatten()
obj = cp.Minimize(z)
prob = cp.Problem(obj,constraints)
prob.solve(gp = True)``

In this case if I use this trick:

constraints.append(z >= (cp.inv_pos(x[i]*y[i]) + (cp.inv_pos(x@e_i*y@e_i))/c[i]))
it says that the problem does not follow DGP rules.

**Comment by SteveDiamond** [comment]
Yes you can use geometric matrix multiplication instead of matrix multiplication:
https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#gmatmul
(i.e., ``gmatmul(e_i, x)*gmatmul(e_i,y)``).

**Comment by FilippoVannella** [comment]
Amazing, many thanks!
