### ISSUE TITLE
pytest

### ISSUE THREAD

**Issue by BarGoldman** [cvxpy/cvxpy#1923]
**Describe the bug**
im trying to run the paytest of the libary, and every time i get :
"pytest : The term 'pytest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again."
i already installed the pytest's libary and still nothing work

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**
that the tests will work

**Output**
"pytest : The term 'pytest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again."

**Version**
 - OS: windows 10
 - CVXPY Version: 1.3.0
 - 
**Additional context**

**Comment by SteveDiamond** [comment]
This is not a cvxpy bug. You should look on stackoverflow: https://stackoverflow.com/questions/35998992/py-test-command-not-found-but-library-is-installed
