### ISSUE TITLE
It is that possible to solve a "wired" opjective which is actually proved to be convex?

### ISSUE THREAD

**Issue by wadmes** [cvxpy/cvxpy#1924]
I try to implement a paper, and the objective is like this:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/20320821/198936655-2fd4024d-df49-464b-b64b-00896e6ce46d.png">

Here, dij is the geometric distance, (xi,yi) is the coordinate. It is proved that the hessian matrix of this objective is PSD, and there convex. But it is not easy to let CVXPY knows this... is there any suggestion?

Thanks!

**Comment by wadmes** [comment]
Here is the paper title:UFO: Unified Convex Optimization Algorithms for Fixed-Outline Floorplanning Considering Pre-Placed
Modules

**Comment by wadmes** [comment]
> Are you certain it's convex? I checked numerically and found it wasn't convex, but maybe I used the wrong constants:
> 
> ```
> import cvxpy as cp
> from analyzer import might_be_convex
> 
> x1 = cp.Variable()
> x2 = cp.Variable()
> y1 = cp.Variable()
> y2 = cp.Variable()
> c = 1
> s = 1
> b = 1
> coord = cp.hstack([x1 - x2, y1 - y2])
> d = cp.norm(coord)
> expr = c*d + s*(b/d - 1)
> prob = cp.Problem(cp.Minimize(expr))
> 
> print(might_be_convex(prob, niter=100_000))
> ```
> 
> analyzer is this package: https://github.com/cvxpy/cvxpyanalyzer

Thanks for the reply!

I guess the reason is  only properties defined in cp.Variable() are used to check convexity.
For example, the following commands gives True:

```
import cvxpy as cp
from analyzer import might_be_convex

x1 = cp.Variable(pos = True)
constrains = []
constrains.append(x1 >= 1)
expr = x1 + cp.inv_pos(x1)
prob = cp.Problem(cp.Minimize(expr), constrains)
print(might_be_convex(prob, niter=1000))
```

But if we remove `pos=True` in cp.Variable()` , and keep `x1 >= 1` as a constraint, it still reports False
 ```
import cvxpy as cp
from analyzer import might_be_convex

x1 = cp.Variable()
constrains = []
constrains.append(x1 >= 1)
expr = x1 + cp.inv_pos(x1)
prob = cp.Problem(cp.Minimize(expr), constrains)
print(might_be_convex(prob, niter=1000))
```

**Comment by aszekMosek** [comment]
``1/cp.norm(coord)`` appearing in @SteveDiamond post, if that is what your objective requires, is non-convex. Just look at the plot of $(a,b)\to1/\sqrt{a^2+b^2}$.

**Comment by wadmes** [comment]
Thank you for the reply! You should be right, after re-checking the paper, I noticed that the paper formulation is not convex unless a > 0 (or a<0) and b>0 (or b<0) always hold.

I need to discuss with others, to make sure that the paper is wrong from the convexity proof. This is a huge mistake, and surprised that reviewers even did not notice them,


> `1/cp.norm(coord)` appearing in @SteveDiamond post, if that is what your objective requires, is non-convex. Just look at the plot of (a,b)→1/a2+b2. Adding any amount of |(a,b)| to it won't help because you still explode to infinity around 0. And if the sum even becomes convex somewhere on a bounded subregion of its natural domain then it is usually something impossible to make DCP representable. Perhaps seeing the full problem you want to model and not just this one snippet would shed some more light on it.

**Comment by rileyjmurray** [comment]
It sounds like there isn't any problem on CVXPY's side here. I'll close this issue for now. Feel free to comment here and I will re-open if necessary.
