### ISSUE TITLE
Fix Error on Scorecard Github Action 

### ISSUE THREAD

**Issue by joycebrum** [cvxpy/cvxpy#1925]
**Describe the bug**

The Scorecard Github Action started to throw this error  "error signing scorecard json results: error signing payload: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key", as can be seen at https://github.com/cvxpy/cvxpy/actions/runs/3358289723/jobs/5565048392.

It is related to this issue https://github.com/ossf/scorecard-action/issues/998 and was solved in the version 2.0.6 (https://github.com/joycebrum/cvxpy/actions/runs/3371531776).

Can I open the PR to fix this issue?

**Comment by SteveDiamond** [comment]
Sure, I'd appreciate fixing this.
