### ISSUE TITLE
Flows example out of date

### ISSUE THREAD

**Issue by choltz95** [cvxpy/cvxpy#1926]
Hi, the `commodity_flow` example seems to be a bit out of date with several simple errors making the example fail on a standard colab instance- could be related to #1609.

I give one example of a simple error:

When constructing the mcf data structure [commodity_flow#L83](https://github.com/cvxpy/cvxpy/blob/master/examples/flows/commodity_flow.py#L83), `edges[-1].connect(nodes[n1], nodes[n2]))` will fail since `edges[-1]` never instantiates a `flow` variable. `MultiEdge` should implement a `connect` function that overwrites the base `Node` class and references `in_flow` and `out_flow`. e.g.:
```
# Connects two nodes via the edge.
def connect(self, in_node, out_node):
    in_node.edge_flows.append(-self.in_flow)
    out_node.edge_flows.append(self.out_flow)
```

There are also other things that I am less sure of- like missing square brackets for iterable arguments, using sum / abs instead of cp.sum / cp.abs, etc. I believe there are other errors like this. I have made one implementation here that no longer errors out, but did not verify correctness of the result:
[colab](https://colab.research.google.com/drive/1u2UdaqW_vjRHm4dsWQ3iJ5bJ7MV3jh_M?usp=sharing)

**Comment by SteveDiamond** [comment]
Would you be up for making a PR to fix the example? Don't worry about correctness, you could just rewrite the commodity_flow file with your fixes.

**Comment by mmusallam19** [comment]
Hi, 
Is there a link to the example of the commodity flow problem? Usually all the examples are here https://www.cvxpy.org/examples/index.html. I would like to review this first I may try and fix this issue.

**Comment by SteveDiamond** [comment]
It's not on the website. It's in an examples file. If you install CVXPY from source. Maybe if it's fixed, we could put it on the website.

**Comment by mmusallam19** [comment]
I already have CVXPY installed via conda install from last year. Maybe I should just clone the repo or just create my own file to see if I can replicate the error.

**Comment by choltz95** [comment]
Hey @mmusallam19, the issue is sum from `accumulation` and `capacity` aren't the same shape. You can try adjusting the loop in [main#L67](https://github.com/cvxpy/cvxpy/blob/master/examples/flows/commodity_flow.py#L67) and also remove the dependency on cvxopt or just ensure the shapes match - e.g. `self.capacity` --> `self.capacity.flatten()`.

I'm sorry I couldn't be more help at the moment.

**Comment by mmusallam19** [comment]
I tried running the colab link although I got a completely different error. So I figured I would start with the original setup by cloning the files and trying to run it then. @choltz95 So I took what you said into consideration about using flatten() although I had to make another change to self.capacity by assigning it to a np.array. From there it seemed to run fine. Do you know what the expected output should be ? Below is a copy of the commodity_flow file with the minor changes I made and a copy of the output. Not sure if this is correct or not.

`class MultiEdge(Edge):
    """ An undirected, capacity limited edge with multiple commodities. """
    def __init__(self, capacity) -> None:
        self.capacity = capacity
        self.in_flow = Variable(COMMODITIES)
        self.out_flow = Variable(COMMODITIES)
    #add connect function similar to max_flow.py    
    def connect(self, in_node, out_node):
        in_node.edge_flows.append(-self.in_flow)
        out_node.edge_flows.append(self.out_flow)

    # Returns the edge's internal constraints.
    def constraints(self):
        return [self.in_flow + self.out_flow == 0,
                sum(cp.abs(self.in_flow)) <= self.capacity]  #changed abs to cp.abs

class MultiNode(Node):
    """ A node with a target flow accumulation and a capacity. """
    def __init__(self, capacity: float = 0.0) -> None:
        self.capacity = np.array(capacity) #use np.array instead of just using capacity
        self.edge_flows = []

    # The total accumulation of flow.
    def accumulation(self):
        return sum(f for f in self.edge_flows)

    def constraints(self):
        return [cp.abs(self.accumulation()) <= self.capacity.flatten()] #use cp.abs and capacity.flatten()`

`[<__main__.MultiNode object at 0x00000223A86BBD60>, <__main__.MultiNode object at 0x00000223A86BB910>, <__main__.MultiNode object at 0x00000223A86BB7C0>, <__main__.MultiNode object at 0x00000223A86DFB80>, <__main__.MultiNode object at 0x00000223A86DFBE0>, <__main__.MultiNode object at 0x00000223A86DFC70>, <__main__.MultiNode object at 0x00000223A86DFE80>, <__main__.MultiNode object at 0x00000223A86DFEE0>, <__main__.MultiNode object at 0x00000223A86DFF10>, <__main__.MultiNode object at 0x00000223A943FAC0>, <__main__.MultiNode object at 0x00000223A943FB20>, <__main__.MultiNode object at 0x00000223A943FB80>, <__main__.MultiNode object at 0x00000223A943FBE0>, <__main__.MultiNode object at 0x00000223A943FC40>, <__main__.MultiNode object at 0x00000223A943FCA0>, <__main__.MultiNode object at 0x00000223A943FD00>, <__main__.MultiNode object at 0x00000223A943FD60>, <__main__.MultiNode object at 0x00000223A943FDC0>, <__main__.MultiNode object at 0x00000223A943FE20>, <__main__.MultiNode object at 0x00000223A943FE80>]
Objective value = 801.7519662485347
Accumulation of commodity 0 = 161.79428716464827
Accumulation of commodity 1 = 168.39437027935952
Accumulation of commodity 2 = 8.12227701785644e-11
Accumulation of commodity 3 = 149.39947846993144
Accumulation of commodity 4 = 172.7643518634299`

**Comment by SteveDiamond** [comment]
Fixed
