### ISSUE TITLE
How to set time limit or iteration limit for solver?

### ISSUE THREAD

**Issue by SightVanish** [cvxpy/cvxpy#1928]
I am using `ECOS_BB` solver. I am working on a large problem, so I want to know how to set the time limit for solver. The solver need to early stop.

**Comment by SteveDiamond** [comment]
``ECOS_BB`` has known correctness issues and in general has not been developed at all in many years. I would strongly recommend switching to another solver like SCIP, which will also support time limits. You may need to install from cvxpy master to get the latest SCIP interface.

**Comment by SightVanish** [comment]
> `ECOS_BB` has known correctness issues and in general has not been developed at all in many years. I would strongly recommend switching to another solver like SCIP, which will also support time limits. You may need to install from cvxpy master to get the latest SCIP interface.

Thanks for ur reply. I switched to `SCIP`. But the time limit does not seem to work. It takes much more time than expected. Here is what I did.

`prob.solve(solver=cp.SCIP, verbose=True, scip_params={"limits/time": timeLimit})`

`"limits/time"` is found [HERE](https://www.scipopt.org/doc-5.0.1/html/PARAMETERS.php). Did I mistook anything?

**Comment by SightVanish** [comment]
> > `ECOS_BB` has known correctness issues and in general has not been developed at all in many years. I would strongly recommend switching to another solver like SCIP, which will also support time limits. You may need to install from cvxpy master to get the latest SCIP interface.
> 
> Thanks for ur reply. I switched to `SCIP`. But the time limit does not seem to work. It takes much more time than expected. Here is what I did.
> 
> `prob.solve(solver=cp.SCIP, verbose=True, scip_params={"limits/time": timeLimit})`
> 
> `"limits/time"` is found [HERE](https://www.scipopt.org/doc-5.0.1/html/PARAMETERS.php). Did I mistook anything?

Oops, it worked! I will leave this comment here in case someone want to take a look.

**Comment by SightVanish** [comment]
> > > `ECOS_BB` has known correctness issues and in general has not been developed at all in many years. I would strongly recommend switching to another solver like SCIP, which will also support time limits. You may need to install from cvxpy master to get the latest SCIP interface.
> > 
> > 
> > Thanks for ur reply. I switched to `SCIP`. But the time limit does not seem to work. It takes much more time than expected. Here is what I did.
> > `prob.solve(solver=cp.SCIP, verbose=True, scip_params={"limits/time": timeLimit})`
> > `"limits/time"` is found [HERE](https://www.scipopt.org/doc-5.0.1/html/PARAMETERS.php). Did I mistook anything?
> 
> Oops, it worked! I will leave this comment here in case someone want to take a look.

Time limit works fine. But when the solver encounters time limit, the solver will be interrupted, so is the python script. 

What I want is to get the intermediate result (instead of spending too much time on finding the 'optimal' one), but the python script will stop with the solver now? What should I do?

**Comment by SteveDiamond** [comment]
Ok. Clone the cvxpy repo, go into this file here: https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/scip_conif.py#L54
and change ``s.SOLVER_ERROR`` everywhere to ``s.USER_LIMIT``.

**Comment by SteveDiamond** [comment]
RE @NEd88 and @SightVanish Now that I look more closely, I'm not certain the change is needed. I hadn't noticed line 349 but that seems like the interface is already returning a solution when a solution exists.

**Comment by SightVanish** [comment]
Solved by switching to CBC solver.
