### ISSUE TITLE
DOC: typo in https://github.com/cvxpy/cvxpy/blob/master/doc/source/tutorial/advanced/index.rst

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#1940]
`:param ignore_dpp : When True, DPP problems will be treated as non-DPP,`

should be 

`:param ignore_dpp: When True, DPP problems will be treated as non-DPP,`

This error messes up https://www.cvxpy.org/tutorial/advanced/index.html.

**Comment by SteveDiamond** [comment]
Fixed.
