### ISSUE TITLE
Install is failing due to Ecos dependency

### ISSUE THREAD

**Issue by Vaiber-github** [cvxpy/cvxpy#1980]
**Describe the bug**
CVXPY install is failing due to Ecos install

**To Reproduce**
install CVXPY
**Expected behavior**
install fails with FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - CVXPY Version: cvxpy==1.0.21

**Additional context**
There is an open issue in Ecos for same https://github.com/embotech/ecos/issues/215

**Comment by phschiele** [comment]
@Vaiber-github I think you mean `ecos==1.0.21` above. This has been fixed:
https://github.com/embotech/ecos-python/issues/46

Feel free to reopen otherwise.
