### ISSUE TITLE
Building wheel for cvxpy did not run successfully during installation

### ISSUE THREAD

**Issue by emilyziech** [cvxpy/cvxpy#1989]
Using the pip install method in the command prompt in Windows 11, I get an error while pip is trying to build the wheels for cvxpy.

**To Reproduce**
python -m pip install cvxpy

**Expected behavior**
cvxpy should be installed with no issues.

**Output**
Full Output: [cvxpy pip install error output.txt](https://github.com/cvxpy/cvxpy/files/10323091/cvxpy.pip.install.error.output.txt)
Abbreviated Output:

Building wheels for collected packages: cvxpy
  Building wheel for cvxpy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cvxpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [407 lines of output]

...

      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Icvxpy/cvxcore/src/ -Icvxpy/cvxcore/python/ -Icvxpy/cvxcore/include/ -IC:\Users\emily\AppData\Local\Programs\Python\Python311\include -IC:\Users\emily\AppData\Local\Programs\Python\Python311\Include -IC:\Users\emily\AppData\Local\Temp\pip-build-env-jy51ojh_\overlay\Lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tpcvxpy/cvxcore/python/cvxcore_wrap.cxx /Fobuild\temp.win-amd64-cpython-311\Release\cvxpy/cvxcore/python/cvxcore_wrap.obj -O3 -std=c++11 -Wall -pedantic "" ""
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-pedantic'
      cl : Command line warning D9024 : unrecognized source file type '', object file assumed
      cl : Command line warning D9027 : source file '' ignored
      cl : Command line warning D9024 : unrecognized source file type '', object file assumed
      cl : Command line warning D9027 : source file '' ignored
      cvxcore_wrap.cxx
      C:\Users\emily\AppData\Local\Programs\Python\Python311\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cvxpy
Failed to build cvxpy
ERROR: Could not build wheels for cvxpy, which is required to install pyproject.toml-based projects

**Version**
 - OS: Windows 11
 - CVXPY Version: 1.2
 
[cvxpy pip install error output.txt](https://github.com/cvxpy/cvxpy/files/10323091/cvxpy.pip.install.error.output.txt)

**Comment by phschiele** [comment]
@emilyziech we just released CVXPY 1.3, which includes precompiled wheels for Python 3.11.
Could you try the installation again?

**Comment by deepbIue** [comment]
@phschiele thank you - cvxpy 1.3 worked for me
