### ISSUE TITLE
Scipy>=1.8 fails per API changes

### ISSUE THREAD

**Issue by leo-mansini** [cvxpy/cvxpy#2000]
**Describe the bug**
When running `from cvxpy.atoms.elementwise.exp import exp` while having `scipy==1.10.0` an error ocurred:

```
...
----> 4 from cvxpy.atoms.elementwise.exp import exp
      5 import numpy as np
      6 import pandas as pd

      1 """
      2 Copyright, the CVXPY authors
      3 
   (...)
     14 limitations under the License.
     15 """
     17 __version__ = "1.1.11"
---> 18 from cvxpy.atoms import *
     19 from cvxpy.constraints import NonPos, Zero, SOC, PSD
     20 from cvxpy.expressions.expression import Expression

...
      1 """
      2 Copyright 2013 Steven Diamond
      3 
   (...)
     14 limitations under the License.
     15 """
---> 17 from cvxpy.atoms.cummax import cummax
     18 from cvxpy.atoms.dist_ratio import dist_ratio
     19 from cvxpy.atoms.eye_minus_inv import eye_minus_inv, resolvent

...
      1 """
      2 Copyright 2017 Steven Diamond
      3 
   (...)
     14 limitations under the License.
     15 """
---> 17 from cvxpy.atoms.atom import Atom
     18 from cvxpy.atoms.axis_atom import AxisAtom
     19 import numpy as np

...
     19 from cvxpy import interface as intf
     20 from cvxpy.expressions import cvxtypes
---> 21 from cvxpy.expressions.constants import Constant
     22 from cvxpy.expressions.expression import Expression
     23 import cvxpy.lin_ops.lin_utils as lu

...
      1 """
      2 Copyright 2013 Steven Diamond
      3 
   (...)
     14 limitations under the License.
     15 """
---> 17 from .constant import Constant
     18 from .callback_param import CallbackParam
     19 from .parameter import Parameter

...
     21 from cvxpy.utilities import performance_utils as perf
     22 from scipy.sparse.linalg import eigsh
---> 23 from scipy.sparse.linalg.eigen.arpack.arpack import ArpackError
     24 import numpy as np
     27 class Constant(Leaf):

ModuleNotFoundError: No module named 'scipy.sparse.linalg.eigen.arpack'; 'scipy.sparse.linalg.eigen' is not a package
```
 

**To Reproduce**
Run 
```
from cvxpy.atoms.elementwise.exp import exp
```
With `scipy==1.10.0`.

**Expected behavior**
The import should succeed but instead the import path fails.

**Version**
 - OS: Ubuntu 20.04.5 LTS
 - CVXPY Version: 1.1.11

**Additional context**

`scipy.sparse.linalg.eigen` is not a package anymore. 

Scipy has changed its API since release 1.8 ([source](https://docs.scipy.org/doc/scipy/release.1.8.0.html#clear-split-between-public-and-private-api)). 

As with others, the `eigen` package was supposed to be private, and has now been replaced with the `_eigen` package. However all public functions are accessible from the `scipy.sparse.linalg` package ([release notes](https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/__init__.py#L123)).

Consider updating [scipy version](https://github.com/cvxpy/cvxpy/blob/master/setup.py#L233) to `>=1.8` and changing references to scipy private packages to its underscored version, or just pinning the version to `>= 1.1.0, <=1.7.3`.

**Comment by phschiele** [comment]
@leo-mansini This has already been fixed. Can you try updating your CVXPY version?

**Comment by leo-mansini** [comment]
You're right! Sorry, closing this.
