### ISSUE TITLE
The solver GUROBI is not installed

### ISSUE THREAD

**Issue by ximeng96** [cvxpy/cvxpy#2002]
I have installed Groubi and got the license, and it was successfully launched as follows:
![image](https://user-images.githubusercontent.com/56058520/211130233-3b0d1bc1-4748-4bfa-847d-0ddd9d4de984.png)
However, when I use cp.GROUBI, it returned error as follows:
![image](https://user-images.githubusercontent.com/56058520/211130252-366ad2fd-1238-42a2-bd17-4ae29f4b1d2e.png)
While I am sure that I have installed it:
![image](https://user-images.githubusercontent.com/56058520/211130261-da79dff7-f56c-4477-b11d-86adc24c07c9.png)
Does anyone has experience like this?

**Comment by rileyjmurray** [comment]
What version of CVXPY do you have installed?

**Comment by ximeng96** [comment]
> 

I use cvxpy 1.1.22, as below:
![image](https://user-images.githubusercontent.com/56058520/211133432-e2dc3470-78c1-4d44-8ac0-a36c003d3108.png)
