### ISSUE TITLE
Cannot install cvxpy via pip. Main Error: Metadata did not run successfully

### ISSUE THREAD

**Issue by Qatarik** [cvxpy/cvxpy#2004]
**Describe the bug**

I am unable to install cvxpy via pip. I have the Visual Studio build tools installed via instructions from https://www.cvxpy.org/install/

**To Reproduce**
I am running: {python 3.8 directory} -m pip install cvxpy in the command line in admin mode 

**Expected behavior**
I have used the above input to install many other packages and they have worked

**Output**
Collecting cvxpy
  Using cached cvxpy-1.3.0.tar.gz (1.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [108 lines of output]
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
      Ignoring numpy: markers 'python_version == "3.11"' don't match your environment
      Collecting numpy<1.17,>=1.16
        Using cached numpy-1.16.6.zip (5.1 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=1.1.0
        Using cached scipy-1.10.0.tar.gz (42.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [71 lines of output]
        + meson setup --prefix=C:\Users\sraof\AppData\Local\Programs\Python\Python38-32 C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build --native-file=C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
        The Meson build system
        Version: 1.0.0
        Source dir: C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb
        Build dir: C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build
        Build type: native build
        Project name: SciPy
        Project version: 1.10.0
        Activating VS 16.11.22
        C compiler for the host machine: cl (msvc 19.29.30147 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64")
        C linker for the host machine: link link 14.29.30147.0
        C++ compiler for the host machine: cl (msvc 19.29.30147 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64")
        C++ linker for the host machine: link link 14.29.30147.0
        Host machine cpu family: x86_64
        Host machine cpu: x86_64
        Compiler for C supports arguments -Wno-unused-but-set-variable: NO
        Compiler for C supports arguments -Wno-unused-function: NO
        Compiler for C supports arguments -Wno-conversion: NO
        Compiler for C supports arguments -Wno-misleading-indentation: NO
        Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
        Library m found: NO

        ..\..\meson.build:63:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
        The following exception(s) were encountered:
        Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
        Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
        Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
        Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
        Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
        Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
        Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
        Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
        Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
        Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

        A full log can be found at C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build\meson-logs\meson-log.txt
        Traceback (most recent call last):
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
            hook = backend.prepare_metadata_for_build_wheel
        AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
            main()
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 1060, in build_wheel
            with _project(config_settings) as project:
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 113, in __enter__
            return next(self.gen)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 975, in _project
            with Project.with_temp_working_dir(
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 113, in __enter__
            return next(self.gen)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 750, in with_temp_working_dir
            yield cls(source_dir, tmpdir, build_dir, meson_args)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 632, in __init__
            self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 680, in _configure
            self._meson('setup', *setup_args)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 657, in _meson
            return self._proc('meson', *args)
          File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 652, in _proc
            subprocess.check_call(list(args), env=self._env)
          File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=C:\\Users\\sraof\\AppData\\Local\\Programs\\Python\\Python38-32', 'C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb', 'C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb\\.mesonpy-ngtyec5v\\build', '--native-file=C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> [108 lines of output]
    Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
    Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
    Ignoring numpy: markers 'python_version == "3.9" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
    Ignoring numpy: markers 'python_version == "3.10" and (platform_machine != "arm64" or platform_system != "Darwin")' don't match your environment
    Ignoring numpy: markers 'python_version == "3.10" and (platform_machine == "arm64" and platform_system == "Darwin")' don't match your environment
    Ignoring numpy: markers 'python_version == "3.11"' don't match your environment
    Collecting numpy<1.17,>=1.16
      Using cached numpy-1.16.6.zip (5.1 MB)
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'done'
    Collecting scipy>=1.1.0
      Using cached scipy-1.10.0.tar.gz (42.4 MB)
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
      error: subprocess-exited-with-error

      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1

      [71 lines of output]
      + meson setup --prefix=C:\Users\sraof\AppData\Local\Programs\Python\Python38-32 C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build --native-file=C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      The Meson build system
      Version: 1.0.0
      Source dir: C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb
      Build dir: C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      Activating VS 16.11.22
      C compiler for the host machine: cl (msvc 19.29.30147 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64")
      C linker for the host machine: link link 14.29.30147.0
      C++ compiler for the host machine: cl (msvc 19.29.30147 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64")
      C++ linker for the host machine: link link 14.29.30147.0
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: NO
      Compiler for C supports arguments -Wno-conversion: NO
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: NO
      Library m found: NO

      ..\..\meson.build:63:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang'], ['pgfortran'], ['g95']]
      The following exception(s) were encountered:
      Running `ifort --version` gave "[WinError 2] The system cannot find the file specified"
      Running `ifort -V` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `flang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `flang -V` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran --version` gave "[WinError 2] The system cannot find the file specified"
      Running `pgfortran -V` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 --version` gave "[WinError 2] The system cannot find the file specified"
      Running `g95 -V` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\sraof\AppData\Local\Temp\pip-install-z44nbhlu\scipy_3383f816004443089be7684270936cfb\.mesonpy-ngtyec5v\build\meson-logs\meson-log.txt
      Traceback (most recent call last):
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "C:\Users\sraof\AppData\Local\Temp\pip-build-env-wl0h9lfc\overlay\Lib\site-packages\mesonpy\__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "C:\Users\sraof\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=C:\\Users\\sraof\\AppData\\Local\\Programs\\Python\\Python38-32', 'C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb', 'C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb\\.mesonpy-ngtyec5v\\build', '--native-file=C:\\Users\\sraof\\AppData\\Local\\Temp\\pip-install-z44nbhlu\\scipy_3383f816004443089be7684270936cfb\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]

      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    Encountered error while generating package metadata.

    See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Version**
 - OS: Windows 10, running python 3.8.5
 - CVXPY Version: 1.3.0

**Comment by phschiele** [comment]
@Qatarik It looks like you are using a 32-bit version of Python. Can you install the 64-bit version?
We can look further into the failure if that's not possible on your end, but it would be my recommended option as you might have difficulties installing other packages as well when using the 32-bit version.

**Comment by Qatarik** [comment]
Downloading python 3.10 64 bit did the trick. Thank you so much!

**Comment by eli-schwartz** [comment]
The issue is, fundamentally, two things, both related to the SciPy dependency -- not to cvxpy at all:
- SciPy does not provide 32-bit Windows wheels anymore, only 64-bit ones
- without a wheel, you need to compile your own wheels from source code, however
  > I have the Visual Studio build tools installed via instructions from https://www.cvxpy.org/install/

  is not sufficient, because SciPy, unlike cvxpy, requires a Fortran compiler too -- which is not provided by Visual Studio.
