### ISSUE TITLE
Constraints with condition

### ISSUE THREAD

**Issue by SightVanish** [cvxpy/cvxpy#2006]
Hi, I want to add constraints like this:

```python
constraint = cp.sum(cp.multiply(x, a)) > 10 if x*a != 0
```

where `x` is decision variable and a is constant. I know `if` condition and chain constraints are not allowed. But how can I implement this condition?

**Comment by rsemenoff** [comment]
The way you do it is through binary variables, and it's not documented per se, but from skimming thru the example codes , it can be figured out. 
    On Tuesday, January 10, 2023 at 07:20:25 PM PST, SightVanish ***@***.***> wrote:  
 
 


Hi, I want to add constraints like this:
constraint = cp.sum(cp.multiply(x, a)) > 10 if x*a != 0

where x is decision variable and a is constant. I know if condition and chain constraints are not allowed. But how can I implement this condition?

**Comment by SightVanish** [comment]
> The way you do it is through binary variables, and it's not documented per se, but from skimming thru the example codes , it can be figured out.  On Tuesday, January 10, 2023 at 07:20:25 PM PST, SightVanish ***@***.***> wrote: Hi, I want to add constraints like this: constraint = cp.sum(cp.multiply(x, a)) > 10 if x*a != 0 where x is decision variable and a is constant. I know if condition and chain constraints are not allowed. But how can I implement this condition? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

yep, you are right. Here is a brief example:
```python
x = cp.Variable(shape=10, boolean=True)
a = np.array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0])
```

**Comment by SightVanish** [comment]
solved, see [here](https://stackoverflow.com/questions/75078053/constraints-with-condition-in-cvxpy).
