### ISSUE TITLE
How can I insert an Input Convex Nerual Network as an objective function?

### ISSUE THREAD

**Issue by lk1983823** [cvxpy/cvxpy#2010]
**Is your feature request related to a problem? Please describe.**

The cvxpy uses an analytical form of  objective function, such as:

```
objective = cp.Minimize(cp.sum_squares(A @ x - b))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)
```
However, I want to use a more complicated convex objective to do the optimization. For example, a trained input convex neural network with pytorch code may be a suitable objective function. So how can I insert it into the cvxpy?
Thanks for the help.

**Comment by phschiele** [comment]
That's generally not possible, but the other way around is.
That is, you can put a convex optimization problem in a neural network as a layer.
Check out https://github.com/cvxgrp/cvxpylayers

**Comment by lk1983823** [comment]
> That's generally not possible, but the other way around is. That is, you can put a convex optimization problem in a neural network as a layer. Check out https://github.com/cvxgrp/cvxpylayers

Thanks, but the objective in cvxpylayer should also be a cvxpy form, like:
```
import cvxpy as cp
import torch
from cvxpylayers.torch import CvxpyLayer

n, m = 2, 3
x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
constraints = [x >= 0]
objective = cp.Minimize(0.5 * cp.pnorm(A @ x - b, p=1))
problem = cp.Problem(objective, constraints)
assert problem.is_dpp()

cvxpylayer = CvxpyLayer(problem, parameters=[A, b], variables=[x])
A_tch = torch.randn(m, n, requires_grad=True)
b_tch = torch.randn(m, requires_grad=True)

# solve the problem
solution, = cvxpylayer(A_tch, b_tch)

# compute the gradient of the sum of the solution with respect to A, b
solution.sum().backward()
```
What I want is to make the objective a Torch model, like input convex nn.

**Comment by rileyjmurray** [comment]
Hi, @lk1983823. Sadly it probably isn't possible to do what you mentioned in your last comment. I'm going to close this issue for now. You can continue to seek advice on handling this situation on our Discord or our GitHub Discussions board.
