### ISSUE TITLE
Adjust precise of variables

### ISSUE THREAD

**Issue by ximeng96** [cvxpy/cvxpy#2030]
**Describe the bug**
I am using cvxpy to solve a quadratic programming, I wonder whether there is anyway to limit the variable to 7 decimals, currently there are too many decimals. Idealy, I think I should get the same result when I choose sum_squares(x) and norm(x,2) as the objective function, but I got different results currently.  I think this may because the precise of the variables.

**Version**
 - OS: Windows
 - CVXPY Version:  1.3.0

**Additional context**

**Comment by SteveDiamond** [comment]
The solution is only accurate up to a certain number of decimals.  So for example if the sum_squares(x) solution gives 1.457858 and the norm(x,2) solution gives 1.458201 we consider those the same solution. If you want to hear more you can post the output with ``problem.solve(verbose=True)``.

**Comment by ximeng96** [comment]
Thank you so much for the elaboration, is there any way to adjust the precision. Also, I try to solve the problem using Gurobi and Mosek (with the same objective and constraints), and I get different answers with them.

**Comment by SteveDiamond** [comment]
That's interesting to hear. Could you post examples of answers that are different? How big is the difference numerically?

**Comment by ximeng96** [comment]
Sure, I print out the result. 
Here is the result using MOSEK:
![image](https://user-images.githubusercontent.com/56058520/217681818-92e9577b-8363-4080-b221-08bf2738331a.png)
Here is the result using GUROBI:
![image](https://user-images.githubusercontent.com/56058520/217681889-5c3c2c31-6ed1-46cf-9295-4a5a97b2ccb0.png)
The value of the objective function differs by about 0.0001, but I set the accuracy of the objective function to be 10^(-6).
Also, at the last line from the screenshoot, "pos error" is the reflection of the variables (I have about 700 variables in the optimization problem). 
From this actually you can see that the values of the variables returned by these two solvers differ a lot. The values of variables are from 0-500, this are a part of constraints I have. 
Hope I have explained my confusion clearly. If there is anything unclear, please let me know.

**Comment by aszekMosek** [comment]
There is no such thing as setting the accuracy of the objective to anything, at least not in Mosek and not really in any solver. The termination criteria are more involved than that. Every solution you get is always to some extent approximate. You may also have a very flat problem where there are many almost equally optimal points. We didn't see full log outputs of the solvers, either.

These outputs you share do not indicate any obvious issue. It seems like both solvers give you pretty much the same objective. I suggest you check your problem and full log output using sections 8.1, 8.2 from https://docs.mosek.com/latest/pythonapi/debugging-tutorials.html and if that doesn't help/resolve the doubts then please contact Mosek for example via https://groups.google.com/g/mosek or directly write to support and we will take it from there.

**Comment by ximeng96** [comment]
Thank you for your suggection. I checked the manual you mentioned.
Here I have one thought for my case: whether it is possible to set the variable to keep 3 or 4 decimals, since I check the solusions of the variebles, say it is a vector [x1,x2,x3,x4,x5,.......,xn]. At the beginning, the solusions of x using GUROBI and MOSEK return the similar values (differ by about 0.00001). However, when I check x_200 and x_500, the difference can be about 0.6 and 0.8. 
Is there anyway that I can round the variables and keep 4 decimals. I carefully read the manual https://www.cvxpy.org/tutorial/advanced/index.html#sensitivity-analysis-and-gradients but I did not find a way to do that.
Thank you again.

**Comment by ximeng96** [comment]
Also, isn't that said strictly convex quadratic programming problems are supposed to have analytical solutions?

**Comment by rsemenoff** [comment]
> Thank you for your suggection. I checked the manual you mentioned. Here I have one thought for my case: whether it is possible to set the variable to keep 3 or 4 decimals, since I check the solusions of the variebles, say it is a vector [x1,x2,x3,x4,x5,.......,xn]. At the beginning, the solusions of x using GUROBI and MOSEK return the similar values (differ by about 0.00001). However, when I check x_200 and x_500, the difference can be about 0.6 and 0.8. Is there anyway that I can round the variables and keep 4 decimals. I carefully read the manual https://www.cvxpy.org/tutorial/advanced/index.html#sensitivity-analysis-and-gradients but I did not find a way to do that. Thank you again.

Do I understand correctly, that you want to quantize the inputs to step values of 1e-4 ?

**Comment by ximeng96** [comment]
> > Thank you for your suggection. I checked the manual you mentioned. Here I have one thought for my case: whether it is possible to set the variable to keep 3 or 4 decimals, since I check the solusions of the variebles, say it is a vector [x1,x2,x3,x4,x5,.......,xn]. At the beginning, the solusions of x using GUROBI and MOSEK return the similar values (differ by about 0.00001). However, when I check x_200 and x_500, the difference can be about 0.6 and 0.8. Is there anyway that I can round the variables and keep 4 decimals. I carefully read the manual https://www.cvxpy.org/tutorial/advanced/index.html#sensitivity-analysis-and-gradients but I did not find a way to do that. Thank you again.
> 
> Do I understand correctly, that you want to quantize the inputs to step values of 1e-4 ?

I want to have a try to round the variables. Let's say that x = cp.Varieble(200), is there anyway to make x keep 4 decimals during the entire process of the optimization? The the expected result is that when I print v.values, all the data will have no more than 4 decimals.

**Comment by aszekMosek** [comment]
I suggest you post the complete log output from using one or more solvers, not just the final part (use ``verbose=True``)

**Comment by rsemenoff** [comment]
But variables are binary number when they are computed. Are you trying to speed up execution by using 16 bits instead of 64? I doubt it would make any difference. Decimals points are a figment of base-10 which is just how values are presented on your screen, the algorithm itself knows nothing about it, you have to apply integer constraints on the problem itself
    On Sunday, February 12, 2023 at 03:14:40 PM PST, Ximeng ***@***.***> wrote:  
 
 




Thank you for your suggection. I checked the manual you mentioned. Here I have one thought for my case: whether it is possible to set the variable to keep 3 or 4 decimals, since I check the solusions of the variebles, say it is a vector [x1,x2,x3,x4,x5,.......,xn]. At the beginning, the solusions of x using GUROBI and MOSEK return the similar values (differ by about 0.00001). However, when I check x_200 and x_500, the difference can be about 0.6 and 0.8. Is there anyway that I can round the variables and keep 4 decimals. I carefully read the manual https://www.cvxpy.org/tutorial/advanced/index.html#sensitivity-analysis-and-gradients but I did not find a way to do that. Thank you again.


Do I understand correctly, that you want to quantize the inputs to step values of 1e-4 ?


I want to have a try to round the variables. Let's say that x = cp.Varieble(200), is there anyway to make x keep 4 decimals during the entire process of the optimization? The the expected result is that when I print v.values, all the data will have no more than 4 decimals.

**Comment by ximeng96** [comment]
Thank you so much for the respond. I think I somehow understand how the algorithms work. I will close this issue.
