### ISSUE TITLE
How to implement a Charnes-Cooper tansformation in CVXPY?

### ISSUE THREAD

**Issue by SightVanish** [cvxpy/cvxpy#2032]
I am handling a MILFP problem like
`max(sum(A*x)/sum(B*x)) subject to sum(C*x) <= d`.
How can I solve such a MILFP problem in CVXPY?

**Comment by phschiele** [comment]
You can either solve it via [DQCP](https://www.cvxpy.org/tutorial/dqcp/index.html).
I assume you restrict the domain to `cp.sum(B@x) > 0`.
You can then do the following:
```
class pos_wrap(Wrap):
    """Asserts argument is nonneg.
    """

    def is_nonneg(self) -> bool:
        return True

    def is_nonpos(self) -> bool:
        return False


((cp.sum(A@x)) / pos_wrap(cp.sum(B@x))).is_quasilinear()
>>> True
```
You need to add the constraint `cp.sum(B@x) >= 0` to the final problem to make sure the wrap is actually valid.
This is not super elegant but should work.

Alternatively, you can apply Chanes-Cooper manually and solve a single LP.
If you're up for it, we could also think about ways to do this in a more automated way.

**Comment by SightVanish** [comment]
> 
Sorry for asking a dumb question: what is `Wrap`.
I tried this but it didnot work.
```
class pos_wrap(functools.wraps):
    """Asserts argument is nonneg.
    """
    def is_nonneg(self) -> bool:
        return True

    def is_nonpos(self) -> bool:
        return False
```

**Comment by SightVanish** [comment]
> You can either solve it via [DQCP](https://www.cvxpy.org/tutorial/dqcp/index.html). I assume you restrict the domain to `cp.sum(B@x) > 0`. You can then do the following:
> 
> ```python
> class pos_wrap(Wrap):
>     """Asserts argument is nonneg.
>     """
> 
>     def is_nonneg(self) -> bool:
>         return True
> 
>     def is_nonpos(self) -> bool:
>         return False
> 
> 
> ((cp.sum(A@x)) / pos_wrap(cp.sum(B@x))).is_quasilinear()
> >>> True
> ```
> 
> You need to add the constraint `cp.sum(B@x) >= 0` to the final problem to make sure the wrap is actually valid. This is not super elegant but should work.
> 
> Alternatively, you can apply Chanes-Cooper manually and solve a single LP. If you're up for it, we could also think about ways to do this in a more automated way.

Sorry for asking a dumb question: what is Wrap.
I tried this but it didnot work.
```
class pos_wrap(functools.wraps):
    """Asserts argument is nonneg.
    """
    def is_nonneg(self) -> bool:
        return True

    def is_nonpos(self) -> bool:
        return False
```

**Comment by phschiele** [comment]
> > You can either solve it via [DQCP](https://www.cvxpy.org/tutorial/dqcp/index.html). I assume you restrict the domain to `cp.sum(B@x) > 0`. You can then do the following:
> > ```python
> > class pos_wrap(Wrap):
> >     """Asserts argument is nonneg.
> >     """
> > 
> >     def is_nonneg(self) -> bool:
> >         return True
> > 
> >     def is_nonpos(self) -> bool:
> >         return False
> > 
> > 
> > ((cp.sum(A@x)) / pos_wrap(cp.sum(B@x))).is_quasilinear()
> > >>> True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You need to add the constraint `cp.sum(B@x) >= 0` to the final problem to make sure the wrap is actually valid. This is not super elegant but should work.
> > Alternatively, you can apply Chanes-Cooper manually and solve a single LP. If you're up for it, we could also think about ways to do this in a more automated way.
> 
> @phschiele Thanks for your help, it did work and performed much better than the Chanes-Cooper transform I manally implemented.
> 
> And sorry for asking a dumb question: what is Wrap. Here is my code

Not a dumb question at all, I should have linked it. It's a helper class that lets you overwrite specific attributes of an expression, for example, if they cannot be derived from DCP analysis but you know that they hold, or enforce them through another constraint. 
https://github.com/cvxpy/cvxpy/blob/master/cvxpy/atoms/affine/wraps.py

> 
> ```
> class pos_wrap(functools.wraps):
>     """Asserts argument is nonneg.
>     """
>     def is_nonneg(self) -> bool:
>         return True
> 
>     def is_nonpos(self) -> bool:
>         return False
> ```
> 
> BTW, what about an objective function like this: `min|sum(A*x)/sum(B*x) - a| subject to sum(C*x) <= d, where a is a constant`. I also post this question in [math stackexchange](https://math.stackexchange.com/questions/4635485/how-to-minimize-the-gap-between-a-fractional-linear-expression-with-a-constant-v)

Do you mean if the negative offset of `a` changes anything? This should not cause any issues. Since it is constant, you can think of it as keeping track of any constant offsets, then solving the problem without them, and adding them back to the solution.

**Comment by SightVanish** [comment]
> > > You can either solve it via [DQCP](https://www.cvxpy.org/tutorial/dqcp/index.html). I assume you restrict the domain to `cp.sum(B@x) > 0`. You can then do the following:
> > > ```python
> > > class pos_wrap(Wrap):
> > >     """Asserts argument is nonneg.
> > >     """
> > > 
> > >     def is_nonneg(self) -> bool:
> > >         return True
> > > 
> > >     def is_nonpos(self) -> bool:
> > >         return False
> > > 
> > > 
> > > ((cp.sum(A@x)) / pos_wrap(cp.sum(B@x))).is_quasilinear()
> > > >>> True
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You need to add the constraint `cp.sum(B@x) >= 0` to the final problem to make sure the wrap is actually valid. This is not super elegant but should work.
> > > Alternatively, you can apply Chanes-Cooper manually and solve a single LP. If you're up for it, we could also think about ways to do this in a more automated way.
> > 
> > 
> > @phschiele Thanks for your help, it did work and performed much better than the Chanes-Cooper transform I manally implemented.
> > And sorry for asking a dumb question: what is Wrap. Here is my code
> 
> Not a dumb question at all, I should have linked it. It's a helper class that lets you overwrite specific attributes of an expression, for example, if they cannot be derived from DCP analysis but you know that they hold, or enforce them through another constraint. https://github.com/cvxpy/cvxpy/blob/master/cvxpy/atoms/affine/wraps.py
> 
> > ```
> > class pos_wrap(functools.wraps):
> >     """Asserts argument is nonneg.
> >     """
> >     def is_nonneg(self) -> bool:
> >         return True
> > 
> >     def is_nonpos(self) -> bool:
> >         return False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BTW, what about an objective function like this: `min|sum(A*x)/sum(B*x) - a| subject to sum(C*x) <= d, where a is a constant`. I also post this question in [math stackexchange](https://math.stackexchange.com/questions/4635485/how-to-minimize-the-gap-between-a-fractional-linear-expression-with-a-constant-v)
> 
> Do you mean if the negative offset of `a` changes anything? This should not cause any issues. Since it is constant, you can think of it as keeping track of any constant offsets, then solving the problem without them, and adding them back to the solution.

Thanks for replying and I want to briefly my second question. For the objective of  `min|sum(A*x)/sum(B*x) - a|`, I want the ratio of `sum(A*x)/sum(B*x)` as close to `a` as possible. So `a`  is a positive number

**Comment by phschiele** [comment]
Looks like the modeling question has been answered on math StackExchange above.
