### ISSUE TITLE
Error occurs when running the test suite

### ISSUE THREAD

**Issue by DS-Liu** [cvxpy/cvxpy#2040]
When running the test suite after installing cvxpy, the following error occurs:
"Encountered unexpected exception importing solver SCS:
ImportError('DLL load failed while importing _scs_direct: The specified module could not be found.')"
![image](https://user-images.githubusercontent.com/67493438/219829533-260343ee-5658-41d9-aa70-ed9f12febd3e.png)

**Comment by phschiele** [comment]
Hi @DS-Liu. How did you install `cvxpy`? 
There seems to be a related issue and a potential solution here:
https://github.com/bodono/scs-python/issues/47

**Comment by rileyjmurray** [comment]
Closing because of insufficient information needed to reproduce and lack of activity.
