### ISSUE TITLE
Support aarch64 wheels

### ISSUE THREAD

**Issue by phschiele** [cvxpy/cvxpy#2048]
Supporting `aarch64` wheels makes CVXPY easier to install on a [raspberry Pi](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) or ARM servers like [AWS Gravitron](https://aws.amazon.com/ec2/graviton/) (my use case).

These wheels are provided by many packages in the scientific Python stack, including [NumPy](https://pypi.org/project/numpy/#files) and [SciPy](https://pypi.org/project/scipy/#files).

They are also available for many solvers (e.g. [OSQP](https://pypi.org/project/osqp/#files), [Mosek](https://pypi.org/project/Mosek/10.0.36/#files), [Gurobi](https://pypi.org/project/gurobipy/#files), and [Xpress](https://pypi.org/project/xpress/#files)).

I tried building them in my fork, and it only a simple change to our CI. I can open a PR if there is consensus that we want to support this architecture.

**Comment by SteveDiamond** [comment]
Sounds good to me!

**Comment by SteveDiamond** [comment]
Done
