### ISSUE TITLE
Change quad_form shape

### ISSUE THREAD

**Issue by phschiele** [cvxpy/cvxpy#2070]
**Describe the bug**
`cp.quad_form` currently has shape `(1,1)`, but should be scalar, i.e., `()`. 
#2067 Fixes a special case for subsequent matrix multiplication, but the proper fix is to correct the shape with the next major release. 

**To Reproduce**
```py
import cvxpy as cp
import numpy as np

x = cp.Variable(2)
P = np.eye(2)
print(cp.quad_form(x, P).shape)
>>> (1,1)

y = np.arange(2)
print((y.T @ P @ y).shape)
>>> ()
```

Note: PR should also remove the comment about the wrong shape of `quad_form` added in #2067.

**Comment by SteveDiamond** [comment]
Fixed
