### ISSUE TITLE
cvxpy fails to install on Apple Silicon under Rosetta2 Homebrew Python

### ISSUE THREAD

**Issue by shadibeh** [cvxpy/cvxpy#2075]
Hi everyone!

I am not able to install cvxpy on my Mac.

I applied the solutions mentioned in: https://github.com/cvxpy/cvxpy/issues/1190.

However, the command "pip install cvxpy-1.3.0-cp38-cp38-macosx_10_9_universal2.whl" gives me the following error:
WARNING: Requirement 'cvxpy-1.3.0-cp38-cp38-macosx_10_15_universal2.whl' looks like a filename, but the file does not exist
ERROR: cvxpy-1.3.0-cp38-cp38-macosx_10_15_universal2.whl is not a supported wheel on this platform

Could anyone help me resolve this issue.
Thanks

**Comment by phschiele** [comment]
Hi @shadibeh,

The issue you are referring to has been resolved. You should be able to install via
```
pip install cvxpy
```
If you tried that before, what error did you get?

**Comment by phschiele** [comment]
@shadibeh can you post the full logs of the pip command?

**Comment by shadibeh** [comment]
Thanks for the reply.
pip install cvxpy
gives me the following error:

Collecting cvxpy
  Using cached cvxpy-1.3.1-cp39-cp39-macosx_10_9_universal2.whl (1.2 MB)
Requirement already satisfied: numpy>=1.15 in ./myenv_quimb/lib/python3.9/site-packages (from cvxpy) (1.21.6)
Collecting ecos>=2
  Using cached ecos-2.0.12-cp39-cp39-macosx_12_0_arm64.whl
Requirement already satisfied: setuptools>65.5.1 in ./myenv_quimb/lib/python3.9/site-packages (from cvxpy) (67.3.2)
Collecting osqp>=0.4.1
  Using cached osqp-0.6.2.post8.tar.gz (227 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scs>=1.1.6
  Using cached scs-3.2.2-cp39-cp39-macosx_12_0_arm64.whl
Requirement already satisfied: scipy>=1.1.0 in ./myenv_quimb/lib/python3.9/site-packages (from cvxpy) (1.8.1)
Collecting qdldl
  Using cached qdldl-0.1.5.post3-cp39-cp39-macosx_12_0_arm64.whl
Building wheels for collected packages: osqp
  Building wheel for osqp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for osqp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      Disabling LONG
      Remove long integers for numpy compatibility. See:
       - https://github.com/numpy/numpy/issues/5906
       - https://github.com/ContinuumIO/anaconda-issues/issues/3823
      You can reenable long integers by passing: --osqp --long argument.
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-cpython-39
      creating build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/interface.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/_osqp.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      copying src/osqppurepy/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqppurepy
      creating build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/_version.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/interface.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      copying src/osqp/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp
      creating build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/mkl_pardiso_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/warm_start_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/polishing_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/derivative_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/codegen_matrices_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/update_matrices_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/primal_infeasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/codegen_vectors_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/non_convex_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/unconstrained_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/dual_infeasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/basic_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/feasibility_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      copying src/osqp/tests/multithread_test.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/utils.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/codegen/code_generator.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      creating build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/__init__.py -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/setup.py -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      running egg_info
      writing src/osqp.egg-info/PKG-INFO
      writing dependency_links to src/osqp.egg-info/dependency_links.txt
      writing requirements to src/osqp.egg-info/requires.txt
      writing top-level names to src/osqp.egg-info/top_level.txt
      listing git files failed - pretending there aren't any
      reading manifest file 'src/osqp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'src/osqp.egg-info/SOURCES.txt'
      creating build/lib.macosx-12-arm64-cpython-39/extension
      creating build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpinfopy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpmodulemethods.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpobjectpy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpresultspy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqputilspy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      copying src/extension/include/osqpworkspacepy.h -> build/lib.macosx-12-arm64-cpython-39/extension/include
      creating build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/extension/src/.gitignore -> build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/extension/src/osqpmodule.c -> build/lib.macosx-12-arm64-cpython-39/extension/src
      copying src/osqp/codegen/.gitignore -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen
      copying src/osqp/tests/solutions/test_basic_QP.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_feasibility_problem.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_random.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_simple.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_polish_unconstrained.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_solve.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_unconstrained_problem.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_A.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_A_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indA.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indP.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_A_indP_indA.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_P_allind.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_bounds.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_l.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_q.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/tests/solutions/test_update_u.npz -> build/lib.macosx-12-arm64-cpython-39/osqp/tests/solutions
      copying src/osqp/codegen/files_to_generate/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/emosqpmodule.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      copying src/osqp/codegen/files_to_generate/example.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/files_to_generate
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      copying src/osqp/codegen/sources/configure/osqp_configure.h.in -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      copying src/osqp/codegen/sources/configure/qdldl_types.h.in -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/configure
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/auxil.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/constants.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/error.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/glob_opts.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/kkt.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/lin_alg.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/osqp.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/proj.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/qdldl.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/qdldl_interface.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/scaling.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/types.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      copying src/osqp/codegen/sources/include/util.h -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/include
      creating build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/CMakeLists.txt -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/auxil.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/error.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/kkt.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/lin_alg.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/osqp.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/proj.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/qdldl.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/qdldl_interface.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/scaling.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      copying src/osqp/codegen/sources/src/util.c -> build/lib.macosx-12-arm64-cpython-39/osqp/codegen/sources/src
      running build_ext
      Traceback (most recent call last):
        File "/Users/radr2801/myenv_quimb/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "/Users/radr2801/myenv_quimb/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/radr2801/myenv_quimb/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/radr2801/myenv_quimb/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 260, in <module>
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/private/var/folders/z6/4vq2qqgs2078v53wjbxszb8h0000gn/T/pip-build-env-9jalizs8/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 220, in build_extensions
        File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for osqp
Failed to build osqp
ERROR: Could not build wheels for osqp, which is required to install pyproject.toml-based projects

**Comment by phschiele** [comment]
@shadibeh There are a few options:
1. Install via conda
2. Run `xcode-select --install` and `brew install cmake` and try to install via pip again
3. Run `pip install cvxpy-base scs ecos` (this would leave you without a QP solver, though).

**Comment by madeline13** [comment]
Try `conda install conda-forge::dowhy`

**Comment by phschiele** [comment]
I believe this has been resolved by various new releases of CVXPY and dependencies since.
