### ISSUE TITLE
GUROBI and CPLEX: LP treated as a QP when sent to the solver

### ISSUE THREAD

**Issue by TomasMiskov** [cvxpy/cvxpy#2082]
**Describe the bug**
I am creating a very basic LP and sending it to the Gurobi solver. Upon inspection of the problem with `problem.get_problem_data(solver = 'GUROBI'`, the solver seems to treat the problem as a QP instead of LP. In this particular case, the solution is correct, however, I suspect that in a bigger problem that I am trying to solve, this is causing an issue (I might be wrong though). Nonetheless, I am still addressing this as I have not found a conversation on this topic. Why is this happening? For what reason does the reduction chain treat this problem as a QP?

**To Reproduce**
```
import cvxpy as cp
import gurobipy
import numpy as np

n = 2
c = np.array([[8], [2]])
A = np.array([[5, 6],
              [2, 8]])
b = np.array([80, 200])

x = cp.Variable(n)
obj = cp.Maximize(c.T @ x)
constraints = [A @ x <= b, x >= 0]
m = cp.Problem(obj, constraints)
res = m.solve(solver = 'GUROBI')

print(f"The optimal objective value of {round(res, 2)} was achieved \
with x1 = {round(x[0].value, 2)}, x2 = {round(x[1].value, 2)}")

m.get_problem_data(solver = 'GUROBI')
```

**Expected behavior**
To feed the problem into Gurobi, CVXPY uses `cvxpy.reductions.qp2quad_form.qp_matrix_stuffing.ParamQuadProg`, which then yields the output below where the matrix 'A' and vector 'b' are empty, while matrices/vectors 'P', 'q', 'F', and 'G' are used instead. I would expect the matrices/vectors 'A' and 'b' to be utilized and the problem to be recognized as LP instead of a QP.

**Output**
```
The optimal objective value of 128.0 was achieved with x1 = 16.0, x2 = 0.0
({'dims': (zero: 0, nonpos: 4, exp: 0, soc: [], psd: []),
  'param_prob': <cvxpy.reductions.qp2quad_form.qp_matrix_stuffing.ParamQuadProg at 0x2b4ff86a490>,
  'P': <2x2 sparse matrix of type '<class 'numpy.float64'>'
  	with 0 stored elements in Compressed Sparse Column format>,
  'q': array([-8., -2.]),
  'A': <0x2 sparse matrix of type '<class 'numpy.float64'>'
  	with 0 stored elements in Compressed Sparse Column format>,
  'b': array([], dtype=float64),
  'F': <4x2 sparse matrix of type '<class 'numpy.float64'>'
  	with 6 stored elements in Compressed Sparse Column format>,
  'G': array([ 80., 200.,  -0.,  -0.]),
  'bool_vars_idx': [],
  'int_vars_idx': [],
  'n_var': 2,
  'n_eq': 0,
  'n_ineq': 4,
  'init_value': array([16.,  0.])},
 Chain(reductions=[<cvxpy.reductions.flip_objective.FlipObjective object at 0x000002B4FF8613D0>, <cvxpy.reductions.cvx_attr2constr.CvxAttr2Constr object at 0x000002B4FF8610A0>, <cvxpy.reductions.qp2quad_form.qp2symbolic_qp.Qp2SymbolicQp object at 0x000002B4FF861550>, <cvxpy.reductions.qp2quad_form.qp_matrix_stuffing.QpMatrixStuffing object at 0x000002B4FF86A370>, <cvxpy.reductions.solvers.qp_solvers.gurobi_qpif.GUROBI object at 0x000002B4C72FC940>]),
 [[],
  (),
  <cvxpy.reductions.inverse_data.InverseData at 0x2b4ff86a430>,
  <cvxpy.reductions.inverse_data.InverseData at 0x2b4ff8611c0>,
  {'var_id': 127,
   'dims': (zero: 0, nonpos: 4, exp: 0, soc: [], psd: []),
   'IS_MIP': [],
   'offset': array(0.)}])
```

**Version**
 - OS: Windows 11
 - CVXPY Version: 1.3.1
 - Python: 3.9.0

**Comment by SteveDiamond** [comment]
A and b are used to express equality constraints. You don't have any equality constraints in your problem, so they are empty.

**Comment by SteveDiamond** [comment]
For Gurobi the QP interface is more efficient than the conic interface and so is preferred for LPs.

Here are our notes on this:
# GUROBI and CPLEX QP/LP interfaces are more efficient
#   -> Use them instead of conic if applicable.

**Comment by rileyjmurray** [comment]
Closing since the data produced is mathematically correct and comes with some practical justification.
