### ISSUE TITLE
Improve string representations

### ISSUE THREAD

**Issue by phschiele** [cvxpy/cvxpy#2089]
Going through some of the major classes and improving their string representations.
Two examples:
```py
cp.Variable(2, name='x').__str__()
>>> 'x'
cp.Variable(2, name='x').__repr__()
>>> 'Variable((2,))' 
```
Maybe the latter could still show the variable name.

```py
cp.Constant(np.ones((3,3))).__str__()
>>> '[[1. 1. 1.]\n [1. 1. 1.]\n [1. 1. 1.]]'
cp.Constant(np.ones((3,3))).__repr__()
>>> 'Constant(CONSTANT, NONNEGATIVE, (3, 3))'
```
Maybe the former could print only a few elements, as it gets hard to read when the arrays contain many elements.

**Comment by Transurgeon** [comment]
Hey @phschiele , I tried some fixes for this issue and just wanted to make sure they were in-line with what you wanted.
Here is what I get for the two changes you mentioned.
```
cp.Variable(2, name='x').__repr__()
'Variable((2,), x)'
cp.Constant(np.ones((3,3))).__str__()
'[[1. 1. 1.]\n [1. 1. 1.]\n  ...]'
```

**Comment by phschiele** [comment]
@Transurgeon That's already looking good! What about the number of columns when the data matrix gets larger? Will they also be partially hidden?

**Comment by Transurgeon** [comment]
@phschiele No, but I can try to work on that. I think for more than 5 columns we should add some '...' to hide the rest of the data. 
```
cp.Constant(np.ones((5,5))).__str__()
'[[1. 1. 1. 1. 1.]\n [1. 1. 1. 1. 1.]\n  ...]'
```
But for more it would look like this (I think adding a comma helps to visually separate the "1." from the three dots)
```
cp.Constant(np.ones((1,7))).__str__()
'[[1. 1. 1. 1. 1. , ... ]]'
```

**Comment by phschiele** [comment]
Are you using the numpy functionality for this?
```py
np.set_printoptions(edgeitems=3)
print(np.arange(60).reshape((6, 10)))
# [[ 0  1  2 ...  7  8  9]
#  [10 11 12 ... 17 18 19]
#  [20 21 22 ... 27 28 29]
#  [30 31 32 ... 37 38 39]
#  [40 41 42 ... 47 48 49]
#  [50 51 52 ... 57 58 59]]

np.set_printoptions(edgeitems=2)
print(np.arange(60).reshape((6, 10)))
# [[ 0  1 ...  8  9]
#  [10 11 ... 18 19]
#  ...
#  [40 41 ... 48 49]
#  [50 51 ... 58 59]]
```

**Comment by Transurgeon** [comment]
No I am not, im doing some string parsing on self.name(). Do you want me to base the output like np.print with edgeitems=2?
