### ISSUE TITLE
New test for diag offset is not passing.

### ISSUE THREAD

**Issue by Transurgeon** [cvxpy/cvxpy#2090]
**Describe the bug**
The following unit test is not passing when running pytest : TestProblem::test_diag_offset_problem
The error is as follows: AssertionError: inf != 12 within 5 places (inf difference)

**To Reproduce**
Run "pytest tests/test_problem.py" from the cvxpy directory.

**Output**
<img width="675" alt="image" src="https://user-images.githubusercontent.com/89562186/229314053-d88faa88-bbb9-427f-8e98-7b6ff29b0668.png">

**Version**
 - OS: MacOS 12.5.1
 - CVXPY Version: 1.3.0

**Additional context**
I noticed that this test has been added in the most recent commit, maybe we need to double check the implementation for adding the diag_offset parameter.

**Comment by SteveDiamond** [comment]
Are you sure you re-compiled cvxpy? There was a change to the C++ code.

**Comment by Transurgeon** [comment]
@SteveDiamond No, sorry about that. 
I didn't know I had to re-compile cvxpy. I'll remember for next time

I'll close this issue now
