### ISSUE TITLE
Error with `tr_inv` when using default solver

### ISSUE THREAD

**Issue by robot-dreams** [cvxpy/cvxpy#2092]
**Describe the bug**
I get an error when solving a problem that uses `tr_inv` in the objective. The error is no longer present if I either (i) use a different solver, or (ii) slightly modify the formulation of the constraint.

**To Reproduce**
```python
import cvxpy as cp

X = cp.Variable(2)

obj = cp.Minimize(cp.tr_inv(cp.diag(X)))
constraints = [X >= 0, cp.sum(X) == 1]

prob = cp.Problem(obj, constraints)
prob.solve()
assert prob.status == cp.OPTIMAL

print("optimal value:", round(prob.value))
print("solution:", X.value)
```

**Expected behavior**
```
optimal value: 4
solution: [0.5 0.5]
```

**Output**
```
Traceback (most recent call last):
  File ".../example.py", line 7, in <module>
    prob.solve()
  File ".../cvxpy/cvxpy/problems/problem.py", line 502, in solve
    return solve_func(self, *args, **kwargs)
  File ".../cvxpy/cvxpy/problems/problem.py", line 1073, in _solve
    solution = solving_chain.solve_via_data(
  File ".../cvxpy/cvxpy/reductions/solvers/solving_chain.py", line 423, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File ".../cvxpy/cvxpy/reductions/solvers/conic_solvers/ecos_conif.py", line 137, in solve_via_data
    solution = ecos.solve(data[s.C], data[s.G], data[s.H],
  File "/opt/homebrew/lib/python3.10/site-packages/ecos/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
ValueError: Number of rows of G does not match dims.l+sum(dims.q)+dims.e
```

**Version**
 - OS: MacOS 13.1 (22C65), Apple M1
 - CVXPY Version: Tested against cbb0f6775e58faedea5fd525f0a8aee6da1929de and v1.3.1 (2a135d214253a14c50a94c2348776867a31d04e9); also tried v1.2.4 but that version doesn't have `tr_inv`
 - ECOS Version: 2.0.12
 - Python version: 3.10.9

**Additional context**
 - I found a similar error message in #301 but the suggested fix (upgrade both CVXPY and ECOS) didn't seem to work for me.
 - The example works if I change `prob.solve()` to `prob.solve(solver='SCS')`
 - The example works if I change the constraint `X >= 0` to `cp.diag(X) >> 0`

**Comment by rileyjmurray** [comment]
Thanks for reporting, @robot-dreams! You've found an interesting bug. It shouldn't be possible to use ECOS on this problem since [the implementation](https://github.com/cvxpy/cvxpy/blob/master/cvxpy/reductions/dcp2cone/canonicalizers/tr_inv_canon.py) of the ``tr_inv`` atom requires PSD matrix constraints.

I'm looking into this now.
