### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'Equality'

### ISSUE THREAD

**Issue by GMfatcat** [cvxpy/cvxpy#2093]
Hi there, I am new to here and want to use cvxpy's interger programming to solve a work schedule problem.
My variable is a (30,15) numpy array.
I've tried for hours and still got the error among define the constraints part as bellow:
```py
# day >= 9, night = 2, late night = 2
day = cp.Parameter(integer=True)
night = cp.Parameter(integer=True)
late_night = cp.Parameter(integer=True)

day.value = int(9)
night.value = int(2)
late_night.value = int(2)

N = 30
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 1, np.ones((N,)))).value >= day.value for j in range(N)]
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 2, np.ones((N,)))).value == night.value for j in range(N)]
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 3, np.ones((N,)))).value == late_night.value for j in range(N)]
```

And the error is 
```
Traceback (most recent call last):
  File "D:\Optimization\Midterm\bonus\int_programming.py", line 47, in <module>
    constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 1, np.ones((N,)))).value >= day.value for j in range(N)]
  File "D:\Optimization\Midterm\bonus\int_programming.py", line 47, in <listcomp>
    constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 1, np.ones((N,)))).value >= day.value for j in range(N)]
  File "C:\Users\GMfatcat\anaconda3\lib\site-packages\cvxpy\atoms\affine\binary_operators.py", line 240, in __init__
    lh_expr, rh_expr = self.broadcast(lh_expr, rh_expr)
  File "C:\Users\GMfatcat\anaconda3\lib\site-packages\cvxpy\expressions\expression.py", line 532, in broadcast
    lh_expr = Expression.cast_to_const(lh_expr)
  File "C:\Users\GMfatcat\anaconda3\lib\site-packages\cvxpy\expressions\expression.py", line 526, in cast_to_const
    return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
  File "C:\Users\GMfatcat\anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py", line 48, in __init__
    self._value = intf.DEFAULT_INTF.const_to_matrix(value)
  File "C:\Users\GMfatcat\anaconda3\lib\site-packages\cvxpy\interface\numpy_interface\ndarray_interface.py", line 53, in const_to_matrix
    return result.astype(numpy.float64)
TypeError: float() argument must be a string or a number, not 'Equality'
```

My full code
```py
import cvxpy as cp
import numpy as np

# Variables
SCHEDULE = cp.Variable((30, 15), integer=True)

# print(np.zeros((30, 15)))
# Constants day = 1, night = 2, late night = 3, holiday = 4
constraints = [SCHEDULE >= 1, SCHEDULE <= 4]
# GIVE SPECIFIC HOLIDAYS
# key:val = worker : days
must_holidays = {
                 0:[5,6,24],
                 1:[8],
                 2:[13,14],
                 3:[8],
                 4:[18,19],
                 5:[24,25],
                 6:[23,25],
                 7:[11],
                 8:[22,23],
                 9:[14,20],
                 10:[9,10],
                 11:[15],
                 12:[18,19],
                 13:[9,10],
                 14:[3]
                 }
# Holiday: day index = day - 1
for worker,days in must_holidays.items():
	for day in days:
		constraints += [SCHEDULE[day-1,worker] == 4]

# day >= 9, night = 2, late night = 2
day = cp.Parameter(integer=True)
night = cp.Parameter(integer=True)
late_night = cp.Parameter(integer=True)

day.value = int(9)
night.value = int(2)
late_night.value = int(2)

N = 30
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 1, np.ones((N,)))).value >= day.value for j in range(N)]
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 2, np.ones((N,)))).value == night.value for j in range(N)]
constraints += [cp.sum(cp.multiply(SCHEDULE[:, j] == 3, np.ones((N,)))).value == late_night.value for j in range(N)]

# Objective functions
objective = 0
for i in range(15):
	evening_days = np.where((SCHEDULE[:, i] == 2) | (SCHEDULE[:, i] == 3))[0]
	for j in range(len(evening_days) - 1):
		interval = evening_days[j + 1] - evening_days[j] - 1
		f = -((interval - 11) ** 2)

		# FC
		consecutive_shifts = 0
		consecutive_pattern = ''
		for k in range(evening_days[j], evening_days[j+1]):
			if SCHEDULE[k,i] in [2,3]:
				consecutive_shifts += 1

				if consecutive_shifts > 4:
					f -= (consecutive_shifts - 4)*100

				if consecutive_shifts >= 2:
					if '3322' in consecutive_pattern:
						f += 0
					elif '332' in consecutive_pattern or '322' in consecutive_pattern:
						f -= 40
					elif '32' in consecutive_pattern:
						f -= 60
					else:
						f -= 120

			else:
				consecutive_shifts = 0
				consecutive_pattern = ''
		# Add to objective function
		objective += f

objective = cp.Maximize(objective)

# Solver
# Create optimization problem and solve
problem = cp.Problem(objective, constraints)
problem.solve(solver=cp.GLPK_MI)
print("Best score: ", problem.value)
print("Best schedule", SCHEDULE.value)
```

**Comment by phschiele** [comment]
@GMfatcat If I read this correctly you're saying there must be at least 9 people working during the day, 2 at night and 2 late at night?
Conceptually, the issue is that you have a constraint of the form `expression.value >= constant`. 
But because the variables do not have values yet (those are to be found during the optimization), you cannot query the values to build the constraints.

I have solved a similar problem before and what I did was to have 3 boolean matrices, one for each schedule.

```py
schedule_day = cp.Variable((30, 15), boolean=True)
schedule_night = cp.Variable((30, 15), boolean=True)
schedule_late_night = cp.Variable((30, 15), boolean=True)
```
You can then ensure that every person only has an entry in one of them at any given time:
```py
constraints += [schedule_day + schedule_night + schedule_late_night <= 1]  # elementwise
```

You can further ensure the minimum attendance:
```py
constraints += [cp.sum(schedule_day, axis=1) >= day.value]  # notice how the axis keyword removes the need for the loop
...
```

You'll have to rewrite your objective as well. Again, you cannot check the values using equalities before solving the problem.

**Comment by GMfatcat** [comment]
> @GMfatcat If I read this correctly you're saying there must be at least 9 people working during the day, 2 at night and 2 late at night? Conceptually, the issue is that you have a constraint of the form `expression.value >= constant`. But because the variables do not have values yet (those are to be found during the optimization), you cannot query the values to build the constraints.
> 
> I have solved a similar problem before and what I did was to have 3 boolean matrices, one for each schedule.
> 
> ```python
> schedule_day = cp.Variable((30, 15), boolean=True)
> schedule_night = cp.Variable((30, 15), boolean=True)
> schedule_late_night = cp.Variable((30, 15), boolean=True)
> ```
> 
> You can then ensure that every person only has an entry in at most one of them at any given time:
> 
> ```python
> constraints += [schedule_day + schedule_night + schedule_late_night <= 1]  # elementwise
> ```
> 
> You can further ensure the minimum attendance:
> 
> ```python
> constraints += [cp.sum(schedule_day, axis=1) >= day.value]  # notice how the axis keyword removes the need for the loop
> ...
> ```
> 
> You'll have to rewrite your objective as well. Again, you cannot check the values using equalities before solving the problem.

Thanks, I think my program works. However the result get quite different while the solver is **CBC** or **GLPK_MI**, and the former is much better. I do some research and realize that these 2 solver are not similiar in searching algorithm. Can you share your experience of using these 2 solvers in mixed -integer programming?

**Comment by phschiele** [comment]
@GMfatcat What do you mean your program works? It does give the error in the title.

For a general performance comparison between solvers, you can check out https://mattmilten.github.io/mittelmann-plots/
But if one works better for your particular problem, I'd use that.

**Comment by GMfatcat** [comment]
> @GMfatcat What do you mean your program works? It does give the error in the title.
> 
> For a general performance comparison between solvers, you can check out https://mattmilten.github.io/mittelmann-plots/ But if one works better for your particular problem, I'd use that.

After I modifed the code as your suggestion, I finished the rest of part and it can now work. I will check on the link you provide, thanks a lot.
