### ISSUE TITLE
MOSEK is not running in Google Colab

### ISSUE THREAD

**Issue by gabrielawad** [cvxpy/cvxpy#2100]
Hi!!!

**Describe the bug**
I am getting this error message whent trying to run cvxpy with Mosek:

SolverError: The solver MOSEK is not installed.

**To Reproduce**
I already run:
!pip install mosek

and get this answer:
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: Mosek in /usr/local/lib/python3.9/dist-packages (10.0.40)

But I got a error message when I run this code
**This is the code I am trying to run**
import cvxpy as cvx
from mosek.fusion import *

x = cvx.Variable(integer=True)
y = cvx.Variable(integer=True)

obj = cvx.Maximize(8\*x + 5\*y)

restricciones_int = [
x + y <= 6,
9\*x + 5\*y <= 45,
x >= 0,
y >= 0
]

prob_int = cvx.Problem(obj, restricciones_int)

prob_int.solve(solver=cvx.MOSEK)

print(prob_int.status)

print(prob_int.value)

**Expected behavior**
The status of the solution and the value of the solution

**Output**
---------------------------------------------------------------------------
SolverError                               Traceback (most recent call last)
[<ipython-input-35-4c1e34848823>](https://localhost:8080/#) in <cell line: 18>()
     16 prob_int = cvx.Problem(obj, restricciones_int)
     17 
---> 18 prob_int.solve(solver=cvx.MOSEK)
     19 
     20 print(prob_int.status)

4 frames
[/usr/local/lib/python3.9/dist-packages/cvxpy/problems/problem.py](https://localhost:8080/#) in _find_candidate_solvers(self, solver, gp)
    742         if solver is not None:
    743             if solver not in slv_def.INSTALLED_SOLVERS:
--> 744                 raise error.SolverError("The solver %s is not installed." % solver)
    745             if solver in slv_def.CONIC_SOLVERS:
    746                 candidates['conic_solvers'] += [solver]

SolverError: The solver MOSEK is not installed.

**Version**
 - OS: Google Golab on Windows 11
 - CVXPY Version: v1.3.1   

**Additional context**

Thanks in advance

**Comment by phschiele** [comment]
@gabrielawad can you try restarting the runtime?

**Comment by gabrielawad** [comment]
> @gabrielawad can you try restarting the runtime?

Hi, Phillipp!!!

Problem solved!!!

Thanks for your suggestion.
