### ISSUE TITLE
Make `Objective` available in top-level namespace

### ISSUE THREAD

**Issue by jonathanberthias** [cvxpy/cvxpy#2109]
Most (all?) constraints were added to the top-level namespace in #1909, as well as the `Constraint` class itself, making type hints for code that uses cvxpy much easier to write.

Could the same be done for the `cvxpy.problems.objective.Objective` base class? I use it quite a bit when an argument can be either `Minimize` or `Maximize`.

Thanks!

**Comment by SteveDiamond** [comment]
Done in master.
