### ISSUE TITLE
why is output(w_opt) a zero matrix? can someone assist me here. because optimal value of the objective function is correct but output matrix is printed as a 2x3 zero matrix yet it shouldnot be a zero matrix.Thanks

### ISSUE THREAD

**Issue by balexx2** [cvxpy/cvxpy#2121]
import cvxpy as cp
import numpy as np

# Define problem parameters
I = 3  # Number of users
J = 2  # Number of antennas
P_max_t = 20  # Maximum transmit power
Gamma_th = 5.0  # Interference threshold
g = np.random.rand(I, J)  # Channel gain matrix
eta = np.random.rand(I, 1)  # Weighting factor for each user (reshaped to column vector)
xi = np.random.rand(I, 1)  # Satisfaction level for each user (reshaped to column vector)

# Define optimization variables
w = cp.Variable((J, I), complex=True)
z = cp.Variable((I, 1))

# Define optimization objective
objective = cp.Maximize(cp.sum(cp.multiply(eta, cp.multiply(xi, cp.log(z)))))

# Define constraints for z
z_constraints = [z[i] >= 1 + cp.abs(g[i, :] @ w[:, i])**2 for i in range(I)]

# Define optimization constraints
constraints = [
    cp.sum_squares(cp.norm(w, axis=0)) <= P_max_t,
    cp.sum([cp.sum_squares(cp.multiply(g[i, :][:, np.newaxis], w[:, np.arange(I) != i])) for i in range(I)]) <= Gamma_th,
] + z_constraints

# Solve optimization problem
problem = cp.Problem(objective, constraints)
# problem.solve()
problem.solve(solver=cp.SCS)
# Extract optimal solution
w_opt = w.value
print("Optimal value:", objective.value)
print(w_opt)

**Comment by rileyjmurray** [comment]
Hi, @balexx2! If it's not too much trouble, please ask these kinds of questions on GitHub Discussions or our Discord. It seems off-topic for GitHub Issues, so I'll be closing it for now.
