### ISSUE TITLE
Add support for ortools 9.6.2535

### ISSUE THREAD

**Issue by nickcorona** [cvxpy/cvxpy#2135]
**Is your feature request related to a problem? Please describe.**
I am currently using ortools version 9.6.2535, but when I try to use it with cvxpy, I get the following error message: "RuntimeError('Unrecognized new version of ortools (9.6.2534). Expected < 9.5.0. Please open a feature request on cvxpy to enable support for this version.')". This prevents me from using cvxpy with ortools 9.6.2535.

**Describe the solution you'd like**
I want cvxpy to support ortools version 9.6.2535 so I can use it with my current setup.

**Describe alternatives you've considered**
I have considered downgrading to ortools version 9.5.0, but this would require me to modify my code and potentially sacrifice some of the new features and improvements in the latest version.

**Additional context**
Thank you for your attention to this matter. Please let me know if you need any additional information or if there is anything else I can do to help expedite the process of adding support for ortools 9.6.2535 in cvxpy.

**Comment by rileyjmurray** [comment]
Ping @mlubin.
