### ISSUE TITLE
Bug in test_diag_offset_problem

### ISSUE THREAD

**Issue by Paulnkk** [cvxpy/cvxpy#2138]
**Describe the bug**
When I run the tests on my machine (Mac OS M1, version 12.3), I have been getting the same error with the test from the screenshot for some time.

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.
The error occurs on my machine as soon as I run the tests, it seems that the error does not always occur.

**Expected behavior**
I expect this test not to fail.

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.
<img width="1386" alt="Screenshot 2023-05-26 at 16 47 30" src="https://github.com/cvxpy/cvxpy/assets/93285862/0fc2f0ad-8315-4b8d-8a2a-9728e99ffd49">

**Version**
 - OS: 12.3
 - CVXPY Version: 1.4.0

**Additional context**

**Comment by Transurgeon** [comment]
Hi @Paulnkk I also encountered this issue before.
see #2090 
you simply need to recompile cvxpy as I am guessing there were new changes made to cvxcore
```
pip install -e .
``` 
I think you can just run the command above from the cvxpy repo, please refer to the [documentation](https://www.cvxpy.org/install/index.html#install-from-source)

**Comment by Paulnkk** [comment]
Hey @Transurgeon thanks for the response, that works for me!:)
