### ISSUE TITLE
Why (Relu(x)-y)**2 not convex?

### ISSUE THREAD

**Issue by SicongChen1024** [cvxpy/cvxpy#2148]
<img width="505" alt="CleanShot 2023-06-15 at 19 25 25@2x" src="https://github.com/cvxpy/cvxpy/assets/64960000/892b23e8-c83e-4b59-8cec-a247af538422">

**Comment by phschiele** [comment]
@SicongChen1024 You have a convex function (`sum_squares`) that you want to compose with another convex function (`pos(X@beta) - y`). For this to be valid according to the DCP rule set, sum_squares needs to be increasing in that argument. The square function is only increasing for nonnegative x. While `pos(X@beta)` is nonnegative, `pos(X@beta) - y` need not be.

**Comment by SicongChen1024** [comment]
> @SicongChen1024 You have a convex function (`sum_squares`) that you want to compose with another convex function (`pos(X@beta) - y`). For this to be valid according to the DCP rule set, sum_squares needs to be increasing in that argument. The square function is only increasing for nonnegative x. While `pos(X@beta)` is nonnegative, `pos(X@beta) - y` need not be.
> 
> Small addendum: For usage questions, ideally, you can use the Discussions panel on GitHub or join our Discord! :)

Thanks for your reply. By the way, do you have any ideas how to make it convex

**Comment by rileyjmurray** [comment]
Closing as partially resolved and partially off-topic. As Philipp mentioned, we're happy to help with these kinds of things on our Discord server!
