### ISSUE TITLE
Why are both max_iters and max_iter used.

### ISSUE THREAD

**Issue by jckkvs** [cvxpy/cvxpy#2149]
Is there any meaning in the two usages?
If not, I would like to propose to unify to max_iter like sklearn and torch.

e.g.

https://github.com/cvxpy/cvxpy/blob/173604ef0760032689da91c482887baea8e45677/examples/expr_trees/1D_convolution.py#L59

https://github.com/cvxpy/cvxpy/blob/173604ef0760032689da91c482887baea8e45677/examples/extensions/tsp.py#L17

There are many codes where max_iter and max_iters are not unified.

sklearn
 https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html

pytorch
 https://pytorch.org/docs/stable/generated/torch.optim.LBFGS.html

**Comment by rileyjmurray** [comment]
I'll start with a short but potentially-confusing answer.
> There is no conceptual difference in these settings, but there may be a programmatic difference.

Here's a more detailed answer.
> CVXPY's goal is to make it easy to use numerical optimization libraries. Notably, CVXPY does not perform numerical optimization itself. Most settings that a user passes to CVXPY are handed directly to the numerical solver. Different solvers use different names for the same settings (e.g., ``MAX_ITERS`` or ``MAX_ITER`). With few exceptions, CVXPY does not create aliases for these settings. So it's the user's responsibility to use the correct setting name for the solver they're working with. You can find a list of supported solver settings here: https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options.

I think we'd be open to making aliases for some very common solver settings, but this would require discussion and should happen on the GitHub Discussions board. I'll close this issue for now.
