### ISSUE TITLE
Scipy 1.11.0 broke importing `scipy.sparse.spmatrix`

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [cvxpy/cvxpy#2163]
**Describe the bug**
The new version of scipy (1.11.0, released 6/25/23) broke `spmatrix` import in `scipy_wrapper.py`

**To Reproduce**
```python
import cvxpy
```

**Expected behavior**
No error

**Output**
```
Traceback (most recent call last):
  File "C:\Users\tikum\Documents\xxx\test.py", line 1, in <module>
    import cvxpy
  File "C:\Users\tikum\Documents\xxx\.venv\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
    import cvxpy.interface.scipy_wrapper
  File "C:\Users\tikum\Documents\xxx\.venv\lib\site-packages\cvxpy\interface\scipy_wrapper.py", line 37, in <module>
    method = getattr(spmatrix, method_name)
AttributeError: type object 'spmatrix' has no attribute '__div__'. Did you mean: '__dir__'?
```

**Version**
 - OS: Win10
 - CVXPY Version: 1.3.1

**Additional context**
The scipy release note [https://docs.scipy.org/doc/scipy/reference/sparse.html#module-scipy.sparse] lists one of its improvements as "Division of sparse arrays by a dense array now returns sparse arrays." This seems to be the reason.

**Comment by rileyjmurray** [comment]
We're aware of this (see #2158) and have adopted a fix. We'll release a patch asap to resolve.

**Comment by tikuma-lsuhsc** [comment]
oops. Sorry I missed that. Looking forward to the patch! Thanks for the great work! -Kesh

**Comment by phschiele** [comment]
The patch is now available on PyPI: https://pypi.org/project/cvxpy/1.3.2/
Patches for 1.2 and 1.1 will follow shortly.

**Comment by tikuma-lsuhsc** [comment]
Awesome. Thank you for a quick resolution!
