### ISSUE TITLE
Derived parameter

### ISSUE THREAD

**Issue by phschiele** [cvxpy/cvxpy#2211]
**Is your feature request related to a problem? Please describe.**
When writing a library based on CVXPY, using `cp.Parameter` can be a nice way of creating a user interface.
Ideally, the problem in the background remains DPP for fast subsequent compilations.

Consider the following example:
```py
x, y, z = cp.Variable(), cp.Variable(), cp.Variable()
p, q = cp.Parameter(), cp.Parameter()
constraints = [
    x <= p,
    y <= q,
    z <= p * q
]
```
This is not DPP, but we know that we can replace `p * q` with a new parameter `d`, which we update using `d.value = p.value * q.value` whenever we update either `p` or `q`. As only `p` and `q` should be exposed to the user, this can make it harder to provide a clean user interface.

**Describe the solution you'd like**
One option would be to introduce a _derived parameter_, which would look something like this:
```py
class DerivedParameter(cp.Parameter):

    def __init__(self, *args, **kwargs):
        self._expr = kwargs.pop("expr")
        super().__init__(*args, **kwargs)

    @property
    def value(self):
        """NumPy.ndarray or None: The numeric value of the parameter.
        """
        self._value = self._validate_value(self._expr.value)
        return self._value

    @value.setter
    def value(self, val):
        raise NotImplementedError("Cannot set the value of a derived parameter")
```
Now, I can write the original problem as:
```py
x, y, z = cp.Variable(), cp.Variable(), cp.Variable()
p, q = cp.Parameter(), cp.Parameter()
d = DerivedParameter(expr = p * q)
constraints = [
    x <= p,
    y <= q,
    z <= d
]
```
Now I can expose `p` and `q` to the user and solve a DPP problem.

**Additional context**
Happy to hear alternative ideas!

**Comment by SteveDiamond** [comment]
There is currently a somewhat hidden ``CallbackParam`` class that might support this use case.
