### ISSUE TITLE
Proposal: remove ``XpressProblem`` class (keep XPRESS solver support!)

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#2214]
We have a class called ``XpressProblem`` defined in [cvxpy/problems/xpress_problem.py](https://github.com/cvxpy/cvxpy/blob/fa70b28a2fbd467ed18fca523bf8eb974f492f39/cvxpy/problems/xpress_problem.py#L4). This class is basically dead code. From what I can tell, it's only used in one place, and that place is an odd example: [examples/advanced/xpress_example.py](https://github.com/cvxpy/cvxpy/blob/fa70b28a2fbd467ed18fca523bf8eb974f492f39/examples/advanced/xpress_example.py#L14). 

I'd like for CVXPY 1.4 to mark this class as deprecated with a notice that it's slated for removal in CVXPY 1.5. I know that this could _in principle_ be a breaking change, but I seriously doubt that it will affect anyone.

@cvxpy/maintainers, what do you think?

**Comment by SteveDiamond** [comment]
Sounds good to me.

**Comment by phschiele** [comment]
@rileyjmurray agree with your proposal and playing it safe. While it _could_ be breaking, it is also not part of the public API.

**Comment by rileyjmurray** [comment]
... we didn't get around to doing this, did we?
