### ISSUE TITLE
Encountered unexpected exception importing solver GLOP because of unrecognized new version of ortools (9.7.2996)

### ISSUE THREAD

**Issue by littlethree17** [cvxpy/cvxpy#2216]
So i just installed anaconda3 in my new laptop. I tried to import optbinning, the optbinning package needs cvxpy to be function and also need ortools as 1 of the package(optbinning already installed and also all the package for the optbinning). But suddenly have and error say
 "Encountered unexpected exception importing solver GLOP:
RuntimeError('Unrecognized new version of ortools (9.7.2996). Expected < 9.5.0.Please open a feature request on cvxpy to enable support for this version.')". 
My python version is 3.11 and i can't install ortools below 9.5.0 because of my python version. Can cvxpy make the newest cvxpy to support the ortools > 9.5.0?

Additional context
I just newbie and love to hear any solution

**Comment by SteveDiamond** [comment]
ortools 9.5 and 9.6 are supported on master. So you can install from source. We will release a new version with the or tools support in september as well.

**Comment by jadecranberry** [comment]
Hi Steve, is the support for ortools (9.7.2996) available now? I had the same issue with Littlethree17

**Comment by SteveDiamond** [comment]
9.7 is not supported right now.

**Comment by rileyjmurray** [comment]
@jadecranberry if you want to use ortools 9.7, then you need to install cvxpy from source on the master branch. (This functionality was added in #2252.)
