### ISSUE TITLE
How to disable the userwarning when setting the Clarabel solver in CVXPY

### ISSUE THREAD

**Issue by SteamerLee** [cvxpy/cvxpy#2227]
Hi, is there way to disable the warnings like "warnings.warn(/opt/conda/lib/python3.8/site-packages/cvxpy/problems/problem.py:1385: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.)" when using Clarabel? 

Thanks!

**Comment by SteveDiamond** [comment]
The top answer here seems helpful: https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

**Comment by rileyjmurray** [comment]
Steven's comment looks like the answer. Regardless, suppressing warnings isn't CVXPY's responsibility _per se_. So I'll close this for now. If we messed up how the warning is issued then feel free to follow up and we can revisit.
