### ISSUE TITLE
https://www.cvxpy.org/ is unavailable

### ISSUE THREAD

**Issue by andrewinston** [cvxpy/cvxpy#2228]
**Describe the bug**
I can't access the website

**To Reproduce**
Open https://www.cvxpy.org/

**Expected behavior**
The website should appear

**Output**
<img width="634" alt="image" src="https://github.com/cvxpy/cvxpy/assets/11844077/1a924180-68f3-46a6-84cf-fd265531b050">

**Additional context**
Not sure if this is the right place to report this, so feel free to redirect me to the correct place.

**Comment by SteveDiamond** [comment]
Weird, thanks for reporting. It works for me so hopefully github (who hosts the site) will resolve their outage and get it back up in all regions.

**Comment by andrewinston** [comment]
it is now available, probably a hiccup on github's end. Thank you!
