### ISSUE TITLE
osqp_qif.OSQP.solve_via_data - l and u and OSQP scaling problem

### ISSUE THREAD

**Issue by 3kwa** [cvxpy/cvxpy#2235]
**Describe the bug**

With a DPP problem, post parameters update, solve_via_data is used and calls solver.update with only new_args i.e. those affected by the parameters change.

(https://github.com/cvxpy/cvxpy/blob/v1.3.2/cvxpy/reductions/solvers/qp_solvers/osqp_qpif.py#L74-L76)

For `l` and `u` in particular, when OSQP uses scaling ([default 10](https://osqp.org/docs/interfaces/solver_settings.html)), values of `l` and `u` are modified in place hence ... 

.. If only one of `l` or `u` makes it into new args, it is possible that a `i` exist such as $l_i > u_i$  and the underlying call to osqp_update_upper_bound or osqp_update_lower_bound fails and cvxpy raises a ValueError.

See https://github.com/osqp/osqp-python/issues/119 for the related issue in in the osqp-python project.

**Expected behavior**

Checking the value of scaling in solver_opts in solve_via_data and if one of `l` or `u` are in new_args include the other would prevent the problem from occuring.

```python
            if solver_opts.get("scaling", 10) != 0:
                if "u" in new_args and "l" not in new_args:
                    new_args["l"] = data["l"]
                elif "l" in new_args and "u" not in new_args:
                    new_args["u"] = data["u"]
```

**Version**
 - OS: Ventura 13.5.2
 - CVXPY Version: 1.3.2

**Comment by 3kwa** [comment]
Thanks @SteveDiamond - I am not very familiar with the cvxpy release process - when would you expect this to be released in a pip / conda installable version if ever?

**Comment by SteveDiamond** [comment]
We are doing a new minor release soon, which should include this. It will come out in a couple weeks or sooner.

**Comment by phschiele** [comment]
@3kwa Can you give a minimum example of this issue? Which version of OSQP did you use?

**Comment by SteveDiamond** [comment]
The OSQP devs say this issue was fixed and doesn't exist in the latest OSQP version.

**Comment by 3kwa** [comment]
Almost had an example ready :) Thanks for your help. Will keep monkey patching cvxopt until I can upgrade to the latest OSQP
