### ISSUE TITLE
Add sum / max / min methods to cp.Expression

### ISSUE THREAD

**Issue by carlosgmartin** [cvxpy/cvxpy#2237]
**Is your feature request related to a problem? Please describe.**

Suppose I need a function that takes array-like inputs and outputs a complicated expression involving sum / max / min operations. An array-like input could be one of the following:
- a [numpy](https://github.com/numpy/numpy) array
- a [JAX](https://github.com/google/jax) array
- a [cvxpy](https://github.com/cvxpy/cvxpy) expression

To make the function [polymorphic](https://en.wikipedia.org/wiki/Ad_hoc_polymorphism) in its arguments, I must write something like the following:

```python3
def polymorphic_sum(x):
    if isinstance(x, cp.Expression):
        return cp.sum(x)
    else:
        return x.sum()

def polymorphic_max(x):
    if isinstance(x, cp.Expression):
        return cp.max(x)
    else:
        return x.max()

def polymorphic_min(x):
    if isinstance(x, cp.Expression):
        return cp.min(x)
    else:
        return x.min()

def complicated_function(x):
   return polymorphic_sum(x), polymorphic_max(x), polymorphic_min(x)
```

**Describe the solution you'd like**

I'd like to be able to call `sum` / `max` / `min` on a [`cp.Expression`](https://www.cvxpy.org/api_reference/cvxpy.expressions.html) as a _method_ (i.e. through dot syntax), so that I can write such polymorphic functions more easily:
```python3
def complicated_function(x):
  return x.sum(), x.max(), x.min()
```

This can be done by adding `sum` / `max` / `min` methods to `cp.Expression` that call [`cp.sum`](https://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html#sum) / [`cp.max`](https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#max) / [`cp.min`](https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#min), respectively.

I'm also very much open to adding other [atomic functions](https://www.cvxpy.org/tutorial/functions/index.html)—such as [`abs`](https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#abs), [`log`](https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#log), [`exp`](https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#exp), etc.—as methods to `cp.Expression` for convenience. But that is perhaps a separate issue.

**Comment by SteveDiamond** [comment]
This is interesting. In the long run our goal is to match NumPy syntax. I will share this internally with the dev team.
