### ISSUE TITLE
CVXPY 1.4 is not available on conda-forge

### ISSUE THREAD

**Issue by ilyanoskov** [cvxpy/cvxpy#2256]
Dear Maintainers, congratulations on your new release!

Could you please make CVXPY 1.4 also available on conda-forge? Thank you very much in advance.

**Comment by rileyjmurray** [comment]
Sorry, Clarabel has been addressed, CVXPY 1.4 hasn't yet been addressed.

**Comment by phschiele** [comment]
CVXPY 1.4.1 is available on conda: 
https://anaconda.org/conda-forge/cvxpy
