### ISSUE TITLE
Almost all links are broken in the documentation

### ISSUE THREAD

**Issue by pochtar** [cvxpy/cvxpy#2263]
**Describe the bug**
See: https://www.cvxpy.org/examples/index.html

Most links that don't have [.ipynb] at the end, don't work (Control, Portfolio optimization, Worst-case risk analysis, everything in Finance, etc).

It appears they should lead to notebooks in https://github.com/cvxpy/cvxpy/tree/master/examples/notebooks/WWW instead.

**To Reproduce**
See: https://www.cvxpy.org/examples/index.html

**Comment by SteveDiamond** [comment]
They are intended to link to the cvx_short_course (https://github.com/cvxgrp/cvx_short_course). That repo was reorganized recently so the links were broken.

**Comment by SteveDiamond** [comment]
Fixed.
