### ISSUE TITLE
Why is this convex expression not DCP?

### ISSUE THREAD

**Issue by ktattan** [cvxpy/cvxpy#2271]
I'm trying to minimize the function $(x^T \Sigma x - 1)^2$ which is convex, where $x$ is a the optimization variable, a vector, and $\Sigma$ is a covariance matrix. The expression $(x^T \Sigma x)^2$ is DCP and can be optimized, but the expression $(x^T \Sigma x - 1)^2$ is not DCP. I don't understand why this is, because $x^T \Sigma x$ resolves down to a scalar, so essentially we have $(scalar - 1)^2=scaler$ which I believe is still convex.

If we expand the brackets in the expression $(x^T \Sigma x - 1)^2$, let $u=x^T\Sigma x$, then we have

$$
(x^T \Sigma x - 1)^2 = (u - 1)^2 = (u - 1)(u - 1) = u^2 - 2u + 1
$$

Again, the expression $u^2 - 2u + 1$ is not DCP, but the expression $u^2 + 2u + 1$ is DCP (note the sign change on the $2u$). Why is this the case and is there a way to resolve it? Thank you

**Comment by aszekMosek** [comment]
Your not function is not convex to begin with, even in $1$ dimension, just plot the graph of $(x^2-1)^2$ to see the problem.

The "other" function, $(x^T\Sigma x+1)^2$ is convex.

**Comment by ktattan** [comment]
Thanks for explaining it to me. I failed to see that $x^T \Sigma x$ is like having $x^2$, and so $(x^T\Sigma x - 1)^2$ is like having $(x^2-1)^2$ which of course isn't convex.
As for the argument about $f(x)$ resolving to a scalar, that also makes sense.

**Comment by rileyjmurray** [comment]
Looks like the misunderstanding's been resolved. Thanks, @aszekMosek!
