### ISSUE TITLE
Cannot access to variable.value

### ISSUE THREAD

**Issue by Alex-Hache** [cvxpy/cvxpy#2272]
Hello everyone ! 
**Description**
I run into an error trying to access a variable value after solving an optimisation problem with linear matrix inequalities :

![LMI_problem](https://github.com/cvxpy/cvxpy/assets/73585075/56124e71-fb5b-4fee-9ef0-70f6d76e9827)

the matrix $T>0$ here is diagonal and is a decision variable
The problem status is okay and the value of the objective I am trying to minimize (here the value of L) is the correct one on a dummy example.

Now when I want to access $M_l (L^2, W)$ I have the following error : 

![bug_cvxpy](https://github.com/cvxpy/cvxpy/assets/73585075/0b05205e-aea5-42e3-a700-13551e1a1c8f)

It seems to be caused by one part of the matrix which is stored as a sparse variable : 

![console](https://github.com/cvxpy/cvxpy/assets/73585075/8711f36a-c291-4a78-84e6-a7edf2944f83)

Thie variable which seems to be stored in a sparse fashion is a subpart of the matrix $T$, I think.

**To reproduce**
As it is part of a research paper implementation a minimal code takes a little time to write but if it helps I'll send one.

**Version**
 - CVXPY Version: 1.2.1

Thank you for your help !

**Comment by SteveDiamond** [comment]
it looks like you are combining numpy or some such library with cvxpy. This is not supported and leads to errors such as you are seeing. Specifically you cannot ever apply numpy function to cvxpy objects.
