### ISSUE TITLE
How do I suppress the ECOS solver warning

### ISSUE THREAD

**Issue by wayner9** [cvxpy/cvxpy#2281]
I am using PyPortfolioOpt which uses cvxpy.  Whenever I run my code I get the following warning:
`Python311\site-packages\cvxpy\reductions\solvers\solving_chain.py:336: FutureWarning:
    Your problem is being solved with the ECOS solver by default. Starting in
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS``
    argument to the ``problem.solve`` method.`

How do I suppress the warning from ever showing again?

**Comment by SteveDiamond** [comment]
Specify the ECOS solver explicitly using the ``solver=cp.ECOS`` argument to the ``problem.solve`` method.

**Comment by wayner9** [comment]
Thanks Steve - where/how do I do that?  Do I just edit a text file somewhere?

**Comment by SteveDiamond** [comment]
I missed that you were using PyPortfolioOpt. You should raise an issue there if you haven't already.

**Comment by SteveDiamond** [comment]
You can link to this issue.

**Comment by wayner9** [comment]
Thanks - PyPortfolioOpt is very useful, but the issues raised  on its Github area don't seem to get many responses.

**Comment by rileyjmurray** [comment]
You could try to contribute to PyPortfolioOpt to fix this yourself! :)

**Comment by phschiele** [comment]
Responded to the comment at PyPortfolioOpt, closing this issue.
