### ISSUE TITLE
Mutating NumPy array inplace with cp.Expression should have a clear error message 

### ISSUE THREAD

**Issue by PTNobel** [cvxpy/cvxpy#2282]
Currently, when calling a NumPy function on a CVXPY variable such as `np.log(cp.Variable())`, we raise an error telling people to use a CVXPY atom inside. This error incorrectly triggers on the following code:

```
import numpy as np
import cvxpy as cp

x = np.array([0])
x += cp.Variable()
```

This errors because of [this line](https://github.com/cvxpy/cvxpy/blob/4e76e6075c40367076429973e2116cf2c0daa875/cvxpy/expressions/expression.py#L745), since NumPy sets `kwargs = {'out': x}`. 

**Expected behavior**

It isn't clear to me what we want to do here. On the one hand people might expect this to mutate `x` the way it would for a non-NumPy array. It may not possible to both keep the error and make this have the same behaviour as `x = x + cp.Variable()`.

We could add a new error message that says to do `x = x + expression` in this case, I think this is probably better than trying to get this to work because of my concerns about people expecting mutation. It is possible to write a function that works when given a NumPy array but which depends on mutation that doesn't have the same behaviour when given a CVXPY expression and I think we want to make this an error. 

**Version**
 - OS: Linux
 - CVXPY Version: 1.4.1

**Comment by rileyjmurray** [comment]
I think the most we'd want to do is raise an error saying ``x = x + expression``. The idea of an in-place assignment on a numerical array with changing data types doesn't even make sense. Consider the following code as a non-cvxpy example:
```
>>> import numpy as np
>>> a = np.array([0],'d')
>>> a
array([0.])
>>> a += 1j
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
