### ISSUE TITLE
    raise DCPError( cvxpy.error.DCPError: Problem does not follow DCP rules. Specifically: The objective is not DCP. Its following subexpressions are not:

### ISSUE THREAD

**Issue by Longyouyuan** [cvxpy/cvxpy#2284]
Hi, everyone, this problem bothers me for a long time
u = cp.Variable((2, 3))
obj = cp.sum(u@u.T)
however, the expression of obj is Expression(UNKNOWN, UNKNOWN, ()).
But the expression of the obj should be convex, so how should I deal with this? I think there should be a way to reform the expression of the obj to let CVXPY recognize this is a convex objective function.
Thanks!

**Comment by chofchof** [comment]
In your example, the value of `cp.sum(u @ u.T)` is equal to `cp.norm2(cp.sum(u, axis=0))**2`, but the latter expression is `Expression(CONVEX, NONNEGATIVE, ())`.
