### ISSUE TITLE
Square-root cost - Multi-Period Trading via Convex Optimization

### ISSUE THREAD

**Issue by Pr0dt** [cvxpy/cvxpy#2295]
In the paper Multi-Period Trading via Convex Optimization, the normalised transaction cost is calculated based on an impact function of the power 3/2. However, in empirical finance literature unequivocal evidence shows a relationship of the power 1/2. I try to correct that but the problem is that the square root is a concave function. I read that there are ways around that with the modification of the objective function and additional constraints but I haven't been able to solve it. I am not a mathematician so I am not perfectly sure of how to do this. I would greatly appreciate some support with this Dr Diamond.

**Comment by phschiele** [comment]
Hi @Pr0dt!
You may find this link helpful: [market impact costs](https://docs.mosek.com/portfolio-cookbook/transaction.html#market-impact-costs)
In this simple model, the relative price change scales with an exponent of $\beta-1\approx 1/2$, so $\beta\approx3/2$. 

P.S.: You may want to use the [Discussions](https://github.com/cvxpy/cvxpy/discussions) section or the [Discord](https://discord.gg/4urRQeGBCr) server for general usage questions like this, which are neither a bug report nor a feature request :)

**Comment by Pr0dt** [comment]
Hi @phschiele,
The price impact _∆p/p_ is proportional to _d^0.5_ as per equation 6.4. That's the square root relationship we are trying to model. From what I understand the 3/2 relationship calculates the impact in dollar units  _(∆p/p)*d_ in equation 6.5. Am I correct? 

Sorry for not posting in the right place. My first time posting. I am closing it.

**Comment by Pr0dt** [comment]
Hi @phschiele,
The price impact _∆p/p_ is proportional to _d^0.5_ as per equation 6.4. That's the square root relationship we are trying to model. From what I understand the 3/2 relationship calculates the impact in dollar units  _(∆p/p)*d_ in equation 6.5. Am I correct? 

Sorry for not posting in the right place. My first time posting. I am closing it.
