### ISSUE TITLE
SCS solver import error

### ISSUE THREAD

**Issue by zhongruiw** [cvxpy/cvxpy#2305]
**Describe the bug**
 I install cvxpy with conda including the scs package. While the SCS solver can not be properly imported.

**To Reproduce**
``print(cp.installed_solvers()``

**Expected behavior**
output all the supported solver with SCS included

**Output**
(CVXPY) Dec 13 11:26:03 PM: Encountered unexpected exception importing solver SCS:
ImportError("dlopen(/Users/ree/miniconda3/envs/py/lib/python3.11/site-packages/_scs_direct.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib\n  Referenced from: <A08A2CF9-B9A1-393C-A32E-68987F02C61E> /Users/ree/miniconda3/envs/py/lib/python3.11/site-packages/_scs_direct.cpython-311-darwin.so\n  Reason: tried: '/Users/ree/miniconda3/envs/py/lib/python3.11/site-packages/../../liblapack.3.dylib' (no such file), '/Users/ree/miniconda3/envs/py/lib/python3.11/site-packages/../../liblapack.3.dylib' (no such file), '/Users/ree/miniconda3/envs/py/bin/../lib/liblapack.3.dylib' (no such file), '/Users/ree/miniconda3/envs/py/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)")
['CLARABEL', 'ECOS', 'ECOS_BB', 'OSQP', 'SCIPY']

**Version**
 - OS: Mac OS Ventura 13.5 (M2 chip)
 - CVXPY Version: 1.4.1

** Additional info **
All the dependencies meet the version requirements.

**Comment by nikkujensen** [comment]
I get this same error when trying to run my code

Check the installation
```
(NCH) njjensen@Nicks-MacBook-Air 2023-11 Three_N-Cornered Hat % conda update -c conda-forge cvxpy     
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
```

Run my script
```
(NCH) njjensen@Nicks-MacBook-Air 2023-11 Three_N-Cornered Hat % python threeCH_feasibility_20240122.py
(CVXPY) Jan 22 09:01:32 AM: Encountered unexpected exception importing solver SCS:
ImportError("dlopen(/Users/njjensen/miniconda3/envs/NCH/lib/python3.11/site-packages/_scs_direct.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib\n  Referenced from: <A08A2CF9-B9A1-393C-A32E-68987F02C61E> /Users/njjensen/miniconda3/envs/NCH/lib/python3.11/site-packages/_scs_direct.cpython-311-darwin.so\n  Reason: tried: '/Users/njjensen/miniconda3/envs/NCH/lib/python3.11/site-packages/../../liblapack.3.dylib' (no such file), '/Users/njjensen/miniconda3/envs/NCH/lib/python3.11/site-packages/../../liblapack.3.dylib' (no such file), '/Users/njjensen/miniconda3/envs/NCH/bin/../lib/liblapack.3.dylib' (no such file), '/Users/njjensen/miniconda3/envs/NCH/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)")
```

**Comment by nikkujensen** [comment]
@zhongruiw I installed separately and then my code worked. Please try this

`conda install conda-forge::liblapack`

**Comment by phschiele** [comment]
Thanks for the suggestion @nikkujensen, marking this issue as resolved.
