### ISSUE TITLE
ECOS solver failed

### ISSUE THREAD

**Issue by NamrataRade** [cvxpy/cvxpy#2306]
**Describe the bug**
Got error ECOS solver failed. I have provided the list of solvers(ECOS,SCS,OSQP) to the optimization problem. Goal of the problem is to adjust projected sales into area ,product and period wise. For few countries ECOS is working with zero delta. 

Total known sale 2,831,989,482.8; Total projected 74,629,475,848.6. Delta : 71,797,486,365.8. (96.2%)
Total actual sale: 2,831,989,482.8; Delta (projected-actual) : 71,797,486,365.8. (96.2%)
ECOS Failed for period 2000269. Moving to the next solver
Solver 'ECOS' failed. Try another solver, or solve with verbose=True for more information.
OSQP Failed for period 2000269. Moving to the next solver
Problem could not be reduced to a QP, and no conic solvers exist among candidate solvers ({'qp_solvers': ['OSQP'], 'conic_solvers': []}).
SCS Failed for period 2000269. Moving to the next solver

These are the constraints and objective function:

    A = vstack((Product_pa_importance*A_products, A_areas))
    b = np.concatenate([Product_pa_importance*b_products, b_areas])
    
    nx = C.shape[1]
    nA = A.shape[0]
    if verbose:
        print('removing zeros')
        print(nx, nA)
    nx = C.toarray().shape[1]
    gc.collect()

    x = cp.Variable(nx)
    objective = cp.Minimize(cp.norm(A @ x - b.flatten()))
    tol = 0
    constr1 = A_products @ x - b_products.flatten() <= tol
    constr2 = b_products.flatten() - A_products @ x <= tol
    constr3 = xmin <= x
    constraints = [constr1, constr2, constr3]
    
    prob = cp.Problem(objective, constraints)
    return prob, x, inds
___________________________________________________________
    for solver, solver_name in zip(lst_solvers, lst_solvers_name):
            # TODO better deal with qwargs?
            if lst_solvers_name in ['ECOS', 'OSQP']:
                eps_abs, eps_rel = 1e-5, 1e-5
            else:
                eps_abs, eps_rel = 1e-6, 1e-6 

**Expected behavior**
need delta value zero. ECOS should work

**Output**
This output is for different data for which ECOS is working
total sales projected:          208,577,503.2
total area_sales_acv_predicted: 208,577,503.2
Total known sale 164,847,493.2; Total projected 208,577,503.2. Delta : 43,730,010.0. (21.0%)
Total actual sale: 164,847,493.2; Delta (projected-actual) : 43,730,010.0. (21.0%)
ECOS for period 2000261 status: optimal
ECOS , Succeed for period 2000261 (channel=DataFrame[store_id: bigint, period_id: bigint, channel: string])
Total adjusted sale for 2000261: 208,577,503.2; Total projected 208,577,503.2. Delta: -0.0. (-0.0%)

**Version**
 - OS: 
 - CVXPY Version: 1.3.0
Please suggest solution

**Comment by SteveDiamond** [comment]
This sounds like an ECOS issue, not a cvxpy issue. Can you try clarabel, which should also be installed?

**Comment by NamrataRade** [comment]
Ok. I will try clarabel solver. Thank you

**Comment by phschiele** [comment]
Closing here, feel free to reopen if needed.
