### ISSUE TITLE
add DAQP as a solver

### ISSUE THREAD

**Issue by ghorn** [cvxpy/cvxpy#2310]
This is a feature request to add DAQP (https://github.com/darnstrom/daqp) as a solver. It is available on pypi.

It's a modern dual active set method that is useful for control problems, including embedded optimization problems.

**Comment by phschiele** [comment]
It would be nice to have an active set solver supported.
Note: this solver is also available via [qpsolvers](https://pypi.org/project/qpsolvers/)

**Comment by enzbus** [comment]
According to the paper it's super fast on small to medium programs (it uses dense LA). Would love to have it interfaced through Cvxpy. One of the co-authors is also co-author of OSQP so it's likely to have a very similar interface.

**Comment by phschiele** [comment]
Thanks again @enzbus, closing this issue.
