### ISSUE TITLE
Indexing reverses the orders of nested lists

### ISSUE THREAD

**Issue by BoltonBailey** [cvxpy/cvxpy#2317]
**Describe the bug**

When I create a constant from a nested array, the shape is not what I expect - If I pass in a array of three sub-arrays, each sub-array having 2 elements, I expect the result to be an array of shape (3,2). Instead, it seems to have shape (2,3).

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

Here is an MCE
```
import numpy as np
import cvxpy as cp

foo = [[6292.9718735712195, 12394.971615149743], [188.53574799502698, 1031.7579795558324], [251.0724582117561, 116.460331391552]]

foo_array = np.array(foo)
foo_constant = cp.Constant(foo)
foo_constant2 = cp.Constant(foo_array)

print(foo_constant)
# [[6292.97 188.54 251.07]
#  [12394.97 1031.76 116.46]]
print(foo_constant2)
# [[6292.97 12394.97]
#  [188.54 1031.76]
#  [251.07 116.46]]
```

**Expected behavior**

The `foo_constant` created directly from the nested array should be the same as the numpy array.

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

```
[[6292.97 188.54 251.07]
 [12394.97 1031.76 116.46]]
[[6292.97 12394.97]
 [188.54 1031.76]
 [251.07 116.46]]
```

**Version**
 - OS: MacOS 13.3.1 (a) (22E772610a)
 - CVXPY Version: 1.4.1

**Additional context**

**Comment by BoltonBailey** [comment]
#2240 appears potentially relevant.

**Comment by phschiele** [comment]
Hi @BoltonBailey! Thanks for reporting, I agree that this is a deviation from the numpy behavior. Changing this behavior will be a breaking change, and thus can only be done in the 2.0 release. 
For now, I suggest initializing the constants with numpy arrays.

**Comment by SteveDiamond** [comment]
I would add that using lists values of variables or constants is not officially supported or documented. It does sort of work as you can see, but it's not the intended way to initialize.

**Comment by rileyjmurray** [comment]
We might consider raising a warning if a user tries to provide a list of
lists. We could say the behavior is deprecated in the likely event that we
want to change it in 2.0.
