### ISSUE TITLE
work->info->status_polish segmentation fault

### ISSUE THREAD

**Issue by yslenjoy** [cvxpy/cvxpy#2318]
**Describe the bug**
I'm using osqp solver like [this](https://github.com/ApolloAuto/apollo/blob/3ecbf3006d9a1c3d832c3d925dc838d2d762c571/modules/planning/math/smoothing_spline/osqp_spline_2d_solver.cc#L163), with additional polish and status check. However, the program exits when accessing the polish value, with "segmentation falut" info.

This bug happened occasionally, when it happened, I did check the input value of related variable, but cannot find anything wrong.

**To Reproduce**
```
// Cleanup
  osqp_cleanup(work);
  c_free(data->A);
  c_free(data->P);
  c_free(data);
  c_free(settings);

  if (!spline_.set_splines(solved_params, spline_.spline_order())) {
    MULTILOG_ERROR("Set Spline Failed");
    return false;
  }

  // Check solving status
  int status_polish = work->info->status_polish;   // segmentation falut here!
  int status_solution = work->info->status_val;
  if (status_solution < 0 || (status_solution != 1 && status_solution != 2)) {
    MULTILOG_ERROR("failed optimization status: %d, %d", status_solution,
                   status_polish);
    return false;
  }
```

**Expected behavior**
Given me suggestion how to avoid this segmentation falut so that the program won't exit

**Output**
Segmentation falut

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version: 0.6.3

**Additional context**
In normal case, `osqp_cleanup(work)` won't clean polish and status value. In the segmentation falut case, I use debugger to look into the value of `work->info`, all value get empty.
![image](https://github.com/cvxpy/cvxpy/assets/30484964/0ee4bd99-d5d8-4469-b6d6-006a9d47e5ef)

**Comment by phschiele** [comment]
Hi @yslenjoy, kindly address this issue at the https://github.com/osqp/osqp repo.
P.S. your CVXPY version is very old, consider updating to a more recent version.

Feel free to reopen if the issue does turn out to be related to CVXPY!
