### ISSUE TITLE
Unnecessary pybind11 dependency?

### ISSUE THREAD

**Issue by wshanks** [cvxpy/cvxpy#2330]
https://github.com/cvxpy/cvxpy/pull/2125 (released in 1.4.0) added `pybind11` as a dependency, but it seems like it is just a build dependency, not a run time dependency?

One piece of evidence is that the cvxpy conda-forge feedstock did not add pybind11 as a dependency [here](https://github.com/conda-forge/cvxpy-feedstock/pull/83) and has gotten no complaints. I noticed this because I maintain a downstream feedstock that runs `pip check` as a test and that fails for cvxpy 1.4 because pybind11 is not installed.

**Comment by SteveDiamond** [comment]
Hmm it may be only a build dependency. @akshayka @rileyjmurray is pybind11 needed as a runtime dependency? I'm not that familiar with it.

**Comment by rileyjmurray** [comment]
Definitely only for build-time.
