### ISSUE TITLE
Introduce "vdot" as an alias (or replacement) for scalar_product

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#2336]
I wrote the ``scalar_product`` atom a while back to make computing things like ``trace(A @ B)`` more efficient. That atom also handles complex conjugation of the first argument when necessary. It turns out that numpy already has its own function for this, called [``vdot``](https://numpy.org/doc/stable/reference/generated/numpy.vdot.html).

For consistency with NumPy I suggest we introduce a ``vdot`` atom that has the same semantics as``scalar_product``. Supposing we do this, there's a question of whether we should keep ``scalar_product`` as a (much more sensibly named ...) alias for ``vdot``, or if we should deprecate ``scalar_product`` for removal in cvxpy 2.0.

Thoughts, @PTNobel, @phschiele, @SteveDiamond?

**Comment by PTNobel** [comment]
1. I don't think scalar_product is a better name. I think the vdot name makes more sense.
2. My soft preference is to mirror the NumPy API.
3. I would also love to just have a performance optimization that makes the trace form behave similarly... Writing a design doc for this has been on my to-do list for a little bit

**Comment by SteveDiamond** [comment]
I agree on introducing vdot. I don't think it's necessary to deprecate scalar_product, but don't feel strongly about this. I like @PTNobel 's suggestion about catching ``trace(A @ B)`` internally and replacing it with vdot.

**Comment by rileyjmurray** [comment]
Re, Parth's point 1: I actually just figured out what's meant by the ``v`` in ``vdot``. That indeed makes sense! I also agree with Parth's other two points.

So it sounds like we're in agreement about adding ``vdot`` and using it to more efficiently handle ``trace(A @ B)`` (like we do with ``quad_form`` to handle ``x.T @ P @ x``). The question remains as to whether we should deprecate ``scalar_product``. I think I have a soft preference for leaving it in place, but removing it from the web documentation.

**Comment by rileyjmurray** [comment]
Resolved by #2371.
