### ISSUE TITLE
remove ecos dependancy per default in cvxpy-1.5.0

### ISSUE THREAD

**Issue by stonebig** [cvxpy/cvxpy#2342]
ecos wheel doesn't exist for Python-3.12/Windows

**Comment by SteveDiamond** [comment]
We discussed this issue internally and the intention is still to keep ECOS until 1.6. However, that requires us to make a wheel for 3.12/Windows. If we can't do that for some reason we will drop ECOS in 1.5.

**Comment by rileyjmurray** [comment]
I’m opposed to dropping ECOS in 1.5. If we’re worried about this being a
problem then we can move up the release dates for 1.5 and 1.6. (The plan —
once upon a time — was to release once every 4 to 6 months.)

Happy to discuss more if needed.

**Comment by phschiele** [comment]
Wheels are now available: https://pypi.org/project/ecos/2.0.13/#files

**Comment by stonebig** [comment]
super, cvxpy wheels for python-3.12 would the nice final touch now.
