### ISSUE TITLE
Unexpected exception importing solver GLOP and PDLP - new version of ortools

### ISSUE THREAD

**Issue by ANovillo** [cvxpy/cvxpy#2345]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Hello,
I am doing a python exercise on Jupyter notebook (Anaconda). I need to use the module ContinuousOptimalBinning from optbinning.
After I installed the module of optbinning ('pip install optbinning') using the prompt from Anaconda, I run the python code and I get the following message:

(CVXPY) : Encountered unexpected exception importing solver GLOP:
RuntimeError ('Unrecognized new version of ortools (9.8.29). Expected < 9.8.0 Please open a feature request on cvxpy to enable support for this version.')

 (CVXPY) : Encountered unexpected exception importing solver PDLP:
RuntimeError ('Unrecognized new version of ortools (9.8.29). Expected < 9.8.0 Please open a feature request on cvxpy to enable support for this version.')

Could you please support me on this issue?

Many thanks
Ana

**Comment by SteveDiamond** [comment]
cvxpy does not support ortools >= 9.8.
