### ISSUE TITLE
Convexity Constraint Violation in Multivariate Normal Distribution

### ISSUE THREAD

**Issue by morenoca** [cvxpy/cvxpy#2346]
Hello,

I am currently working on a model that involves the following constraint:

$$
-\sum_i \log \Phi \left(\frac{b_i - \mu_i^Tx}{\Vert \Sigma^{1/2}x\Vert_2}\right) \leq - \log(1-\delta)
$$

In this expression, $b$ is a scalar, $\mu$ is a vector containing the mean values of a multivariate normal distribution, $\Sigma$ is the covariance matrix, and $\delta \leq 0.5$. $\Phi$ is the normal cumulative distribution function. 

The expression is convex, providing $\delta \leq 0.5$. According to the composition rules $f(x) = h(g(x))$, $f$ is convex if $h$ is convex and non decreasing, and $g$ is concave, the constraint should satisfy convexity conditions. Concave considering the minus before the $log$.

Despite these expectations, I am encountering an exception: "Problem does not follow DCP rules." I have carefully reviewed the formulation and believe that the constraint should adhere to DCP (Disciplined Convex Programming) rules, especially given the convexity properties mentioned above.

I am reaching out to seek guidance or assistance in resolving this matter. If there are any insights or suggestions you can provide, I would greatly appreciate it.

**Comment by SteveDiamond** [comment]
Can you post code that replicates the DCP error?

**Comment by morenoca** [comment]
Thank you for your prompt response. Here is a MWE that replicates the issue:

```
import cvxpy as cp
import numpy as np

c = np.array([12,8])
A = np.array([[1,0],[0,1]])
mu = np.array([[1,1],[4,2]])
d = np.array([1000,1500])
b = np.array([1800,4500])
delta = 0.05
variance = 0.05
covariance = np.array([variance * np.eye(len(c)) for i in range(len(b))])

x = cp.Variable(len(c))

FO = cp.Maximize(c.T @ x)
constraints = []
constraints.append(A @ x <= d)
for i in range(len(b)):
    constraints.append(cp.log_normcdf((b[i]- mu[i].T @ x)/ cp.norm(covariance[i] @ x)) >= cp.log(1-delta))

problem = cp.Problem(FO, constraints)
problem.solve(solver=cp.ECOS_BB, verbose=True)

print("Optimal value x:", x.value)
print("Optimal objective value (FO):", problem.value)
```

Running this code throws an exception with the message "Problem does not follow DCP rules". The second set of constraints seems to be causing the problem. Any help would be greatly appreciated.

**Comment by rileyjmurray** [comment]
Sadly your problem is nonconvex in a fundamental way. You have  constraint
that puts a lower bound on a norm. Norm lower bounds (except for trivial
lower bounds like 0 or negative numbers) will always be nonconvex. You can
check this by plotting a toy 2 dimensional case.

**Comment by morenoca** [comment]
@rileyjmurray Thank you for your clarification. I appreciate your insight into the non-convex nature of the norm lower bound constraint. I understand that putting a lower bound on a norm introduces non-convexity into the problem, and I will explore alternative approaches or techniques suitable for handling it. If you have any recommendations or references for doing so, I would be grateful for your guidance.

Nevertheless, I wouldn't close the issue. You can check than even when defining an the constraint as an upper bound it throws an exception with the message "Problem does not follow DCP rules". 

```py
x = cp.Variable(len(c))
y = cp.Variable(len(b))

FO = cp.Maximize(c.T @ x)
constraints = []
constraints.append(A @ x <= d)
for i in range(len(b)):
    constraints.append(cp.log_normcdf((b[i]- mu[i].T @ x)/ cp.norm(covariance[i] @ x)) <= y[i])

problem = cp.Problem(FO, constraints)
problem.solve(solver=cp.ECOS_BB, verbose=True)
```
Particularly,

```py
a = b[0] - mu[0].T @ x
a.curvature
'AFFINE'

b = cp.norm(covariance[0] @ x)
b.curvature
'CONVEX'

c = (b[0]- mu[0].T @ x)/cp.norm(covariance[0] @ x)
c.curvature
'UNKNOWN'
```

**Comment by SteveDiamond** [comment]
Maybe this constraint ``cp.log_normcdf((b[i]- mu[i].T @ x)/ cp.norm(covariance[i] @ x)) <= y[i]`` could be rewritten in the form ``b[i]- mu[i].T @ x >= z[i] * cp.norm(covariance[i] @ x)`` for some positive z? I checked that the constraint is convex but it's not clear to me how to make it DCP. Since it is a scalar constraint you can apply the inverse of the log_normcdf function to both sides.

**Comment by rileyjmurray** [comment]
@morenoca I wouldn't call an expression ``1 / cp.norm(expr1) <= expr2`` an upper bound on the norm. It's an upper bound on the _reciprocal_ of the norm, which of course translates to a lower bound on the norm itself (still nonconvex in general). Based on Steven's comment there might be hope in your particular situation, but

**Comment by morenoca** [comment]
Thank you both for your insightful comments and suggestions. @SteveDiamond I appreciate your idea to rewrite the constraint. However, it might be an option to test a different approach to solving the problem. Since the inverse of the log_normcdf function is applied to both sides, I acknowledge that it may not be numerically equivalent. @rileyjmurray Thanks again for your observation and explanation. Now I have the same feeling, not very optimistic either. Thanks again you both!

**Comment by phschiele** [comment]
@morenoca I'm closing this issue since there don't seem to be any open questions. Feel free to reopen if needed.
