### ISSUE TITLE
CVXPY help

### ISSUE THREAD

**Issue by JreigeF** [cvxpy/cvxpy#2349]
**Error**
ValueError: Cannot broadcast dimensions  (16, 12) (12,)
If someone can help to solve this error what to modify in my code? 

**Code**
import cvxpy as cp
import numpy as np

# Given input values
A = np.array([1, 3, 4, 6, 7, 9, 11, 12, 13, 13, 10, 12])
D = np.array([6, 13, 10, 10, 10, 13, 14, 16, 16, 17, 17, 17])
theta = np.array([[1, 0.375, 0.5, 1.5, 3, 0.75, 1, 0.25, 1, 1.75, 0.125, 1.25]])
W = np.array([5, 3.75, 3, 6, 9, 3, 3, 1, 3, 7, 0.875, 6.25])
s_min = 1
s_max = 6
T = 16
n = 12

# Define variables
theta_var = cp.Variable((T, n))  # Theta matrix
s_var = cp.Variable(T)           # Processor speed

# Define objective function
objective = cp.Minimize(cp.sum(cp.multiply(s_var, np.ones(T))))

# Define constraints
constraints = [
    s_min <= s_var,                     # Minimum processor speed constraint
    s_var <= s_max,                     # Maximum processor speed constraint
    cp.sum(theta_var, axis=1) == 1,     # Sum of theta per time period equals 1
    s_var == cp.sum(cp.multiply(theta_var, W), axis=1),  # Processor speed constraint
    theta_var >= 0,                     # Theta must be non-negative
    theta_var <= W                      # Theta must be less than or equal to the work required
]

# Define and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

# Output results
print("Minimum energy consumption:", problem.value)
print("Optimal theta:", theta_var.value)
print("Optimal processor speeds:", s_var.value)

**Comment by SteveDiamond** [comment]
maybe this line?
```
s_var == cp.sum(cp.multiply(theta_var, W[None, :]), axis=1), # Processor speed constraint
```

**Comment by JreigeF** [comment]
> maybe this line?
> 
> ```
> s_var == cp.sum(cp.multiply(theta_var, W[None, :]), axis=1), # Processor speed constraint
> ```

Thank you for replying, but still got the same error

**Comment by SteveDiamond** [comment]
Had to fix one other line
```
import cvxpy as cp
import numpy as np

#Given input values
A = np.array([1, 3, 4, 6, 7, 9, 11, 12, 13, 13, 10, 12])
D = np.array([6, 13, 10, 10, 10, 13, 14, 16, 16, 17, 17, 17])
theta = np.array([[1, 0.375, 0.5, 1.5, 3, 0.75, 1, 0.25, 1, 1.75, 0.125, 1.25]])
W = np.array([5, 3.75, 3, 6, 9, 3, 3, 1, 3, 7, 0.875, 6.25])
s_min = 1
s_max = 6
T = 16
n = 12

#Define variables
theta_var = cp.Variable((T, n)) # Theta matrix
s_var = cp.Variable(T) # Processor speed

#Define objective function
objective = cp.Minimize(cp.sum(cp.multiply(s_var, np.ones(T))))

#Define constraints
constraints = [
s_min <= s_var, # Minimum processor speed constraint
s_var <= s_max, # Maximum processor speed constraint
cp.sum(theta_var, axis=1) == 1, # Sum of theta per time period equals 1
s_var == cp.sum(cp.multiply(theta_var, W[None, :]), axis=1), # Processor speed constraint
theta_var >= 0, # Theta must be non-negative
theta_var <= W[None, :] # Theta must be less than or equal to the work required
]

#Define and solve the problem
problem = cp.Problem(objective, constraints)
problem.solve()

#Output results
print("Minimum energy consumption:", problem.value)
print("Optimal theta:", theta_var.value)
print("Optimal processor speeds:", s_var.value)
```

**Comment by JreigeF** [comment]
> Had to fix one other line
> 
> ```
> import cvxpy as cp
> import numpy as np
> 
> #Given input values
> A = np.array([1, 3, 4, 6, 7, 9, 11, 12, 13, 13, 10, 12])
> D = np.array([6, 13, 10, 10, 10, 13, 14, 16, 16, 17, 17, 17])
> theta = np.array([[1, 0.375, 0.5, 1.5, 3, 0.75, 1, 0.25, 1, 1.75, 0.125, 1.25]])
> W = np.array([5, 3.75, 3, 6, 9, 3, 3, 1, 3, 7, 0.875, 6.25])
> s_min = 1
> s_max = 6
> T = 16
> n = 12
> 
> #Define variables
> theta_var = cp.Variable((T, n)) # Theta matrix
> s_var = cp.Variable(T) # Processor speed
> 
> #Define objective function
> objective = cp.Minimize(cp.sum(cp.multiply(s_var, np.ones(T))))
> 
> #Define constraints
> constraints = [
> s_min <= s_var, # Minimum processor speed constraint
> s_var <= s_max, # Maximum processor speed constraint
> cp.sum(theta_var, axis=1) == 1, # Sum of theta per time period equals 1
> s_var == cp.sum(cp.multiply(theta_var, W[None, :]), axis=1), # Processor speed constraint
> theta_var >= 0, # Theta must be non-negative
> theta_var <= W[None, :] # Theta must be less than or equal to the work required
> ]
> 
> #Define and solve the problem
> problem = cp.Problem(objective, constraints)
> problem.solve()
> 
> #Output results
> print("Minimum energy consumption:", problem.value)
> print("Optimal theta:", theta_var.value)
> print("Optimal processor speeds:", s_var.value)
> ```

Thanks!
