### ISSUE TITLE
Mac M3: unexpected exception importing solver CBC

### ISSUE THREAD

**Issue by solbes** [cvxpy/cvxpy#2372]
Hi,

I have a new Mac M3. `cvxpy` installation goes through fine, but when importing I get an error:

```
(CVXPY) Mar 06 11:22:00 AM: Encountered unexpected exception importing solver CBC:
ImportError("dlopen(/opt/miniconda3/envs/prodplan/lib/python3.11/site-packages/cylp/cy/CyCoinIndexedVector.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9CoinError12printErrors_E'")
```

Any idea what's going on?

**Version**
 - OS: Sonoma 14.1
 - CVXPY Version: 1.4.2

**Comment by phschiele** [comment]
Hi @solbes!
I suppose CBC by itself also doesn't work?
In this case, you should address it directly with the CBC devs.

**Comment by solbes** [comment]
Thank you @phschiele for a quick response!

It seems that CBC does work (I tested via the `pulp` interface that writes some LP-files and calls CBC from the command line). But with `cvxpy` I get that error when importing.

**Comment by solbes** [comment]
Seems to be an issue with the `cylp` package, I get the same error when trying to run that

**Comment by phschiele** [comment]
Thanks for the update @solbes. Would you mind reopening this issue with `CyLP`?

**Comment by solbes** [comment]
Opened the issue here: https://github.com/coin-or/CyLP/issues/193

**Comment by phschiele** [comment]
Looks like this has been resolved upstream.
