### ISSUE TITLE
Is there a way to add new atomic functions

### ISSUE THREAD

**Issue by langit** [cvxpy/cvxpy#2381]
**Is your feature request related to a problem? Please describe.**
When using cvxpy, I encountered the DCP error, though I know for sure my problem is a convex optimization problem. Therefore, I wonder if there is a way to add new atomic functions to cvxpy.

**Describe the solution you'd like**
It would be ideal to write some python code and declare a new atomic function with certain curvature.

**Describe alternatives you've considered**
Or maybe provide some documentation on how to do this at a lower level than python.

**Additional context**
This feature can dramatically widen the range of use for cvxpy.

**Comment by phschiele** [comment]
Hi @langit, can you describe the function you want to model? Sometimes it is possible to rewrite it using existing atoms.

**Comment by langit** [comment]
Sure, thanks for asking! It is basically the following:
```
# x is a vector of 5 variables
# A is a matrix, C is a vector of constants
maximize sum (x[i] * cvxpy.log(1/x[i]) for i in range(5))
s.t.   A x <= C
```

**Comment by jonathanberthias** [comment]
What about [`cvxpy.entr`](https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#entr)?

**Comment by langit** [comment]
That solves my problem! Many thanks! @jonathanberthias 

By the way, if a class is coded in the same way as cvxpy.entr, does that define a new atomic function?

**Comment by rileyjmurray** [comment]
Alas, implementing the functions you see in cvxpy.atoms.entr is not enough
to define a new atom.

New atoms also need “canonicalizers” in cvxpy.reductions.dcp2cone. Writing
canonicalizers requires some expertise in convex cone programming. Once you
have a canonicalizer there are small boilerplate changes needed elsewhere
so the rest of cvxpy “sees” these changes.

**Comment by langit** [comment]
Wow, it is cool to create an atom. Would it be nice to have everything in one single python file, like the atom class, the “canonicalizers”, and the boilerplate code that can be dynamically propagated to the rest of cvxpy. Just a random thought.

**Comment by rileyjmurray** [comment]
I agree that it would be nice to have an everything in one place. That’s
hard though because the reduction system isn’t part of our public API. A
good middle ground would be to have our web documentation include a guide
to writing new atoms. We already have a guide for writing new solver
interfaces, so a guide for atoms is a reasonable next step.

**Comment by phschiele** [comment]
Closing this issue since the question about the concrete problem about `cp.entr` has been answered. Opening a new issue about a doc update on how to add an atom.
