### ISSUE TITLE
Huge memory consumption in `cp.sum(list)`

### ISSUE THREAD

**Issue by xuzhiying9510** [cvxpy/cvxpy#2385]
**Describe the bug**
Huge memory consumption in `cp.sum(list)`.  I know `cp.sum(cp.hstack(list))` solves the problem, but can `cp.sum(list)` be improved?

**To Reproduce**
``` 
x = [cp.Variable() for i in range(100000)]
expr = cp.sum(x)
```

**Output**
`expr = cp.sum(x)` uses > 30G memory and is super slow.

**Version**
 - OS: Ubuntu 18.04.3 LTS
 - CVXPY Version: 1.1.24

**Comment by rileyjmurray** [comment]
Thanks for reporting this, @xuzhiying9510! 

You appear to be using an outdated version of cvxpy, but I can confirm that the issue occurs with version 1.4 as well. I also tried 
```
expr = cp.sum([cp.Variable(), cp.Variable()] + [0.00001 * i for i in range(2,100000)])
```
and found that it consumed as similar amount of memory.

We'd need more detailed performance profiling to see what can be done in this situation. I'm not terribly optimistic that this could be accelerated without moving some of cvxpy's logic into C/C++. 

@phschiele, @Transurgeon, could you take a look?
