### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [cvxpy/cvxpy#2390]
I suggest adding the topics `convex-optimization` and `numerical-optimization` in the About section. Currently there is `optimization`, but many if not most of the projects with that tag are about compiler optimization.

**Comment by Transurgeon** [comment]
Hello @Beliavsky I am not sure which ``About`` section you are referring to? Could you give us more details on where and what exactly you would like to see being changed?

**Comment by Transurgeon** [comment]
Ohhh I think I see what you mean now!
Yes, I think it's a good suggestion to add the convex/numerical optimization tags for GitHub below:
<img width="319" alt="image" src="https://github.com/cvxpy/cvxpy/assets/89562186/d213e2cd-b1de-471a-8499-f63db8860a1c">

**Comment by rileyjmurray** [comment]
I've changed to the following:
<img width="345" alt="image" src="https://github.com/cvxpy/cvxpy/assets/10662932/690f4fb5-2e99-4435-bbc4-dc8ced676919">

Thoughts? Maybe we remove "cvxpy" and/or "optimization" as standalone tags?

**Comment by Beliavsky** [comment]
Since there are 251 hits for `numerical-optimization` and it's relevant to the project, I suggest adding it. There are 61 hits for `cvxpy` so I suggest keeping it.

**Comment by rileyjmurray** [comment]
Added ``numerical-optimization``. Thanks for your suggestions, @Beliavsky!

We can leave this issue open a little longer in case someone wants to chime in about removing some tags.

**Comment by phschiele** [comment]
Looks like the updated set of tags works for everyone, closing the issue for now.
