### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by yurivict** [cvxpy/cvxpy#2416]
**Describe the bug**
See the [log](https://freebsd.org/~yuri/py-cvxpy-1.4.3-tests.log).

**Version**
 - OS: FreeBSD 14.0
 - CVXPY Version:1.4.3

**Additional context**
cvxpy was built w/in the FreeBSD ports framework.

**Comment by rileyjmurray** [comment]
Most of the failures seem to be due to some type-checking enforcer. I think we'll need to know more about your development environment in order to help.

**Comment by phschiele** [comment]
@yurivict Can you confirm @rileyjmurray's comment? If so, I'd say this is not a bug on the CVXPY side, even though we do work on improving our type hints over time.

**Comment by phschiele** [comment]
Closing as stale. @yurivict Please let us know if you are still facing issues.
