### ISSUE TITLE
Changing parameter doesn't get propogated to solver for cp.quad_over_lin with Clarabel

### ISSUE THREAD

**Issue by AHsu98** [cvxpy/cvxpy#2433]
**Describe the bug**
Using Clarabel with a quad_over_lin objective, where the parameter is in the denominator, when I solve the parametrized problem, then change the parameter, the solution doesn't change.
**To Reproduce**
This bug doesn't appear with ECOS, or in other simpler cases of the parameter appearing. Here is code to reproduce the error:
```
x = cp.Variable()
p = cp.Parameter()

loss = cp.quad_over_lin(x,p) + x
prob = cp.Problem(
    cp.Minimize(loss),
)

p.value = 1
prob.solve(solver=cp.CLARABEL)
sol1 = x.value.copy()
p.value = 1000
prob.solve(solver=cp.CLARABEL)
sol2 = x.value.copy()
print(sol1)
print(sol2)
```

This gives the output 
```
-0.4999999999999999
-0.4999999999999999
```

as the solution doesn't change with the two parameters. When I switch the solver to ECOS,
```
x = cp.Variable()
p = cp.Parameter()

loss = cp.quad_over_lin(x,p) + x
prob = cp.Problem(
    cp.Minimize(loss),
)

p.value = 1
prob.solve(solver=cp.ECOS)
sol1 = x.value.copy()
p.value = 1000
prob.solve(solver=cp.ECOS)
sol2 = x.value.copy()
```
the solution does change, and we get 
```
-0.5000006523005858
-500.023639561259
```

Additionally, changing parameter and resolving does work if the parameter appears just in a sum_squares, for example if we set the objective to `cp.sum_squares(x-p)`, re-solving with different p will yield the correct solution.

**Version**
 - OS: macOS 14.4.1 (23E224)
 - CVXPY Version: cvxpy-1.4.3
I'm on clarabel-0.7.1

**Comment by SteveDiamond** [comment]
I confirmed this bug still exists in CVXPY 1.5.
