### ISSUE TITLE
Solving a simple problem is broken on most solvers after 1.4.2

### ISSUE THREAD

**Issue by davidia** [cvxpy/cvxpy#2437]
**Describe the bug**
The solution to a simple problem is incorrect in 1.4.3 onwards when solving with PIQP, CLARABEL and OSQP - ECOS still apparently works

**To Reproduce**
```
import cvxpy as cp
import numpy as np

print(f'{cp.__version__}')

np.random.seed(42)
N = 100

ivol = 0.6 * np.ones(N)

alpha = np.random.normal(size=N)
t_cost = np.random.rand(N)
A = np.random.normal(size=(N,N))
sigma = A @ A.T

w = cp.Variable(N,name='w')

risk = 0.02 * (cp.multiply(w, ivol) ** 2).sum()
U = w @ alpha - risk - cp.abs(w) @ t_cost
problem = cp.Problem(cp.Maximize(U), [])

for solver in [cp.ECOS, cp.PIQP, cp.CLARABEL, cp.OSQP]:
    v = problem.solve(verbose=False, solver=solver)
    print(f'{solver}: {v:0.1f}')
```

**Expected behavior**
With 1.4.2 the program outputs
```
1.4.2
ECOS: 1384.0
PIQP: 1384.0
CLARABEL: 1384.0
OSQP: 1384.0
```
But with =>1.4.3
```
1.4.3
ECOS: 1384.0
PIQP: 817.1
CLARABEL: 817.1
OSQP: 817.1
```

**Version**
 - OS: Seen on multiple Linux
 - CVXPY Version: 1.4.3

**Additional context**
There is no problem with
```
risk = 0.02 * cp.quad_form(w,sigma)
```

**Comment by phschiele** [comment]
@davidia Thanks for reporting and the reproducible example! We believe we have fix, and will push a bug fix release shortly.
