### ISSUE TITLE
Incompatibility with numpy 2.0 not written in `pyproject.toml`

### ISSUE THREAD

**Issue by ValerianRey** [cvxpy/cvxpy#2474]
**Describe the bug**
As discussed in https://github.com/cvxpy/cvxpy/issues/2389, cvxpy is not yet compatible with numpy 2.0. However, in `pyproject.toml`, this is not clearly stated as there is no upper cap on numpy's version.
```
dependencies = [
    ...
    "numpy >= 1.15",
    ...
]
```

Now that numpy 2.0 is released, this breaks some installations. In my case, [pdm](https://pdm-project.org/en/latest/) tries to install cvxpy 1.5.1 alongside numpy 2.0, which then leads to the error described in https://github.com/cvxpy/cvxpy/issues/2389.

**Expected behavior**
If it requires significant work to make cvxpy compatible with numpy 2.0, I suggest to release a patch of cvxpy (1.5.2) in which the `pyproject.toml` is updated to reflect the incompatibility:

```
dependencies = [
    ...
    "numpy >= 1.15, <2.0.0",
    ...
]
```
The compatibility could then be provided in a future release, and the upper cap on numpy's version could then be removed.

**Comment by Transurgeon** [comment]
Hello @ValerianRey thanks for bringing this issue up. We did in fact plan for the NumPy release by updating the swig interface which caused these build errors. 
I just made a PR updating the pyproject.toml to reflect those changes. The issue should be resolved quite soon with a new minor release.
In the meantime, you can try to build cvxpy from source into your env, then once you try to install pdm it should be smooth sailing from there :)

**Comment by phschiele** [comment]
We just released CVXPY 1.5.2, which is compatible with NumPy >= 2.0 (and also backward compatible!).
You might still see installation issues, as we are waiting for SCS and OSQP to do the same.

In the meantime, instead of `cvxpy`, you can add `cvxpy-base` + your solver of choice (assuming it is compatible with the new NumPy release).

I'll leave this issue open as a status tracker:
- [x] CVXPY (https://github.com/cvxpy/cvxpy/pull/2475)
- [ ] OSQP (https://github.com/osqp/osqp-python/pull/146)
- [ ] SCS (https://github.com/bodono/scs-python/pull/99)
- [x] ECOS (https://github.com/embotech/ecos-python/pull/54)

**Comment by imciner2** [comment]
> You might still see installation issues, as we are waiting for SCS and OSQP to do the same.

Note that OSQP is now compatible with NumPy 2.0 as of 0.6.7.post0. The PR linked above is actually not for the stable release of OSQP, it was made to the 1.0 beta tree. PR https://github.com/osqp/osqp-python/pull/147 implemented the NumPy 2.0 compatibility for the stable version.

**Comment by yasirroni** [comment]
I'm using latest cvxpy 1.6.0 and numpy 2.2.0, and it still cause this error in my M1,

```
AttributeError                            Traceback (most recent call last)
AttributeError: _ARRAY_API not found
```

```
(CVXPY) Dec 21 05:11:24 PM: Encountered unexpected exception importing solver ECOS:
ImportError('numpy.core.multiarray failed to import')

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

Using numpy==1.26.4, every just works.

Can you help with this?

**Comment by carlosgmartin** [comment]
@yasirroni I have a similar issue: https://github.com/cvxpy/cvxpy/issues/2840
