### ISSUE TITLE
Release v1.5.3 is missing source distribution

### ISSUE THREAD

**Issue by jonathanberthias** [cvxpy/cvxpy#2539]
In the latest release, the source distribution was not uploaded along with the wheels: https://pypi.org/project/cvxpy/1.5.3/#files.

This does not impact me, I just thought I'd report it as I guess some distributors will not be able to package this release without source files.

**Comment by Transurgeon** [comment]
Should be closed in #2585 , thanks for raising this @jonathanberthias . I initially didn't know why this was happening, but now we realized that we deleted action config behavior while removing support for Python 3.8.
