### ISSUE TITLE
Supported solvers missing from "install" part of web docs

### ISSUE THREAD

**Issue by rileyjmurray** [cvxpy/cvxpy#2559]
Web docs for CVXPY 1.4 (and most lower versions) list the solvers we support and how to get them:

https://www.cvxpy.org/version/1.4/install/index.html

The web docs for CVXPY 1.5 do not:

https://www.cvxpy.org/version/1.5/install/index.html

It would be great if we could fix this ASAP.

**Comment by rileyjmurray** [comment]
I love the new theme!

How about we merge the sign and monotonicity columns under a new "DCP Properties" column?

We could also make the "meaning" column more narrow for a few atoms. Here are screenshots with how I'd format things in a LaTeX (MathJax) align environment. 

<img width="470" alt="image" src="https://github.com/user-attachments/assets/d427aab6-3592-4516-93a0-1695243ee796">

could become
```
& \text{dot product of} \\
& \operatorname{sort}\operatorname{vec}(X) \text{ and } \\
& \operatorname{sort}\operatorname{vec}(X)  \\
```

<img width="452" alt="image" src="https://github.com/user-attachments/assets/648ffb5b-549a-4f77-9806-52f7c479ede6">

could be like the following (although it seems that this is already intended and just implemented incorrectly):
```
&\text{sum of } k \text{ largest} \\
&\text{eigenvalues of } X
```

<img width="446" alt="image" src="https://github.com/user-attachments/assets/7b9cc107-409d-4ccc-9be3-6fcd9e88ce4d">

could be the following (where numpy.std is a clickable link [to this page](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy-std))
```
cvxpy analog
to numpy.std
```

<img width="419" alt="image" src="https://github.com/user-attachments/assets/428fd20d-5384-4c1f-add4-eb02890a0a9b">

could be analogous to with the std atom:
```
cvxpy analog
to numpy.var
```

**Comment by rileyjmurray** [comment]
@Transurgeon this table also should have the columns narrowed. Right now it looks like the whole table fits but that's because the MIP column is getting hidden:

<img width="802" alt="image" src="https://github.com/user-attachments/assets/5e99f798-0f3c-4b4a-9c75-8300ca112d21">

**Comment by SteveDiamond** [comment]
Probably we should roll forward with the new theme and make the tables work as best we can. With @rileyjmurray's improvements hopefully the tables will fit.

**Comment by Transurgeon** [comment]
this issue is resolved from the two PRs above.
