### ISSUE TITLE
cvxpy pypi distribution requires >= 3.8, but actually need >= 3.9

### ISSUE THREAD

**Issue by laazy** [cvxpy/cvxpy#2576]
**Describe the bug**
as https://pypi.org/project/cvxpy/1.5.3/#description shown, it requires python >= 3.8, but actually need python >= 3.9.
![image](https://github.com/user-attachments/assets/3e915810-10c5-4c09-b2b1-a0970ade95be)

**To Reproduce**
just open https://pypi.org/project/cvxpy/1.5.3/#description

**Expected behavior**
require python >= 3.9

**Comment by Transurgeon** [comment]
fixed after new release!
