### ISSUE TITLE
inverse product of one variable

### ISSUE THREAD

**Issue by aszekMosek** [cvxpy/cvxpy#2583]
``inv_prod`` does something incorrect when the argument has length 1 so one has to use ``inv_pos`` for this special case. Compare these two models of ``1/x[0] + 1/(x[0]*x[1])``:

```
import cvxpy as cp

x = cp.Variable(2)
prob = cp.Problem(cp.Minimize(cp.inv_prod(x[:1])+cp.inv_prod(x[:2])), [cp.sum(x)==2])
prob.solve(verbose=True)
print(x.value)
print(prob.value) # Wrong

x = cp.Variable(2)
prob = cp.Problem(cp.Minimize(cp.inv_pos(x[0])+cp.inv_prod(x[:2])), [cp.sum(x)==2])
prob.solve(verbose=True)
print(x.value)
print(prob.value) # Correct
```

**Comment by Transurgeon** [comment]
I digged a bit into this and it seems like both ``geo_mean`` and ``inv_pos`` are not able to deal with scalar inputs. 
A fix in the source code of ``atoms/inv_prod.py`` could be something like the following:
Before:
```py
    return power(inv_pos(geo_mean(value)), int(sum(value.shape)))
```
After:
```py
    p = int(sum(value.shape))
    if p in [0, 1]:
        return inv_pos(value)
    return power(inv_pos(geo_mean(value)), p)
```
I think this could fix the issue with a minimal amount of changes, but it might also be worth trying to generalize ``geo_mean``. Any thoughts?

**Comment by SteveDiamond** [comment]
> I digged a bit into this and it seems like both `geo_mean` and `inv_pos` are not able to deal with scalar inputs. A fix in the source code of `atoms/inv_prod.py` could be something like the following: Before:
> 
> ```python
>     return power(inv_pos(geo_mean(value)), int(sum(value.shape)))
> ```
> 
> After:
> 
> ```python
>     p = int(sum(value.shape))
>     if p in [0, 1]:
>         return inv_pos(value)
>     return power(inv_pos(geo_mean(value)), p)
> ```
> 
> I think this could fix the issue with a minimal amount of changes, but it might also be worth trying to generalize `geo_mean`. Any thoughts?

It would be better to fix geo_mean so it works with scalar inputs.

**Comment by UweGensheimer** [comment]
It seems that when we pass an argument of shape (1, ) to `cp.inv_prod` then `gm_constrs` returns an empty constraint.
Would it make sense to add an if block in `gm_constrs` like below?

`# Handle single-variable case
    if len(x_list) == 1:
        # Assuming p[0] = 1 for geometric mean
        constraints += [t <= x_list[0]]`

**Comment by SteveDiamond** [comment]
> It seems when an argument of shape (1, ) is passed to `cp.inv_prod` then `gm_constrs` in `power_tools.py` returns an empty SOC constraint list. Would it make sense to add an if block in `gm_constrs` like below?
> 
> ```python
> # Handle single-variable case
>     if len(x_list) == 1:
>         # Assuming p[0] = 1 for geometric mean
>         x = x_list[0]
>         constraints += [gm(t, x, x)]
> ```
> 
> We can then support inputs of length 1 for geo_mean this way.

The docs for geo_mean suggest that when you have a scalar input geo_mean should be the identity. See below
```
    """ The (weighted) geometric mean of vector ``x``, with optional powers given by ``p``:

    .. math::

        \\left(x_1^{p_1} \\cdots x_n^{p_n} \\right)^{\\frac{1}{\\mathbf{1}^Tp}}

    The powers ``p`` can be a ``list``, ``tuple``, or ``numpy.array`` of nonnegative
    ``int``, ``float``, or ``Fraction`` objects with nonzero sum.

    If not specified, ``p`` defaults to a vector of all ones, giving the
    **unweighted** geometric mean

    .. math::

        x_1^{1/n} \\cdots x_n^{1/n}.

    The geometric mean includes an implicit constraint that :math:`x_i \\geq 0`
    whenever :math:`p_i > 0`. If :math:`p_i = 0`, :math:`x_i` will be unconstrained.

    The only exception to this rule occurs when
    ``p`` has exactly one nonzero element, say, ``p_i``, in which case
    ``geo_mean(x, p)`` is equivalent to ``x_i`` (without the nonnegativity constraint).
    A specific case of this is when :math:`x \\in \\mathbf{R}^1`.
```

**Comment by UweGensheimer** [comment]
Thanks! Totally missed it.

**Comment by Transurgeon** [comment]
Is the exception implemented though?
I tried the following test but it doesn't seem to pass :(
```py
    def test_geo_mean_exception(self) -> None:
        x = cp.Variable(1, pos=True)
        p = [1]
        expr = cp.geo_mean(x, p)
        prob = cp.Problem(cp.Maximize(expr), [x == 2])
        prob.solve()
        assert prob.value == 2
```

**Comment by UweGensheimer** [comment]
I think it's about what I mentioned above. When the shape is (1,)  `gm_constrs` in `power_tools.py` returns an empty SOC constraint list and does not enforce the relation of geo_mean's epigraph with the x per the documentation (which had the shape (1,) ).

**Comment by UweGensheimer** [comment]
With help of @Transurgeon, I prepared a [PR](https://github.com/cvxpy/cvxpy/pull/2609) to address this issue.
