### ISSUE TITLE
Source Distribution (sdist) publishing broken

### ISSUE THREAD

**Issue by bkurtz** [cvxpy/cvxpy#2584]
**Describe the bug**
As of the 1.5.3 release, source distributions are no longer being published to pypi.

It appears this was broken in 69e3e6c95b3908a6d3e897d7ba665379c20191af, which removed the `single_action_config` matrix entries that were being used to build/publish sdists.

Sdist builds are keyed on the `SINGLE_ACTION_CONFIG` env var
https://github.com/cvxpy/cvxpy/blob/fc92b6937e0fb95ce96f10cd56f4c67cc5045e18/.github/workflows/build.yml#L114-L118

Which is set from the similarly-named matrix variable:
https://github.com/cvxpy/cvxpy/blob/fc92b6937e0fb95ce96f10cd56f4c67cc5045e18/.github/workflows/build.yml#L82

**To Reproduce**
Visit [pypi](https://pypi.org/project/cvxpy/#files) and observe no files available under the "Source Distributions header.

**Expected behavior**
Source distribution expected to be available, e.g. [this example from the 1.5.2 release](https://pypi.org/project/cvxpy-base/1.5.2/#files)

**Version**
 - OS: Any
 - CVXPY Version: 1.5.3

**Additional context**

**Comment by bkurtz** [comment]
Looks from the code like this will also have broken coverage file uploads for test runs:
https://github.com/cvxpy/cvxpy/blob/fc92b6937e0fb95ce96f10cd56f4c67cc5045e18/.github/workflows/build.yml#L62-L67

**Comment by bkurtz** [comment]
Wrote up a draft of some possible fixes here:
https://github.com/cvxpy/cvxpy/compare/master...bkurtz:cvxpy:fix-ci

**Comment by Transurgeon** [comment]
thanks for raising this and giving possible fixes @bkurtz . Can you make a PR with your suggestions?
I have some questions and it might be easier to do a review on a PR.

**Comment by Transurgeon** [comment]
also sidenote, in #2577 I have been trying to test building wheels for cvxpy in python 3.13, I was wondering if you knew what would be the best way to go about it? (I am running into some weird errors which seem to be related to installing py13 through conda).

**Comment by bkurtz** [comment]
Went ahead and opened a PR and added some preliminary comments.

I'm afraid I'm likely not much help with python 3.13 or conda - I haven't tried upgrading any of my projects to 3.13, and don't use conda.
