### ISSUE TITLE
Variable bounds are ignored if parameter is omitted in constructor

### ISSUE THREAD

**Issue by warwickmm** [cvxpy/cvxpy#2599]
**Describe the bug**

Variable bounds defined by the property setter are not imposed if the `bounds` parameter is not provided to the `Variable` constructor.

**To Reproduce**
```
import cvxpy

x = cvxpy.Variable(1)
x.bounds = [0, 0]

problem = cvxpy.Problem(cvxpy.Minimize(0), [x == 1])
problem.solve(solver=cvxpy.CLARABEL)

# This returns 'optimal'
problem.status
```

**Expected behavior**
The above problem should be infeasible.  If instead, we do the following:
```
import cvxpy
import numpy as np

x = cvxpy.Variable(1, bounds=[-np.inf, np.inf])
x.bounds = [0, 0]

problem = cvxpy.Problem(cvxpy.Minimize(0), [x == 1])
problem.solve(solver=cvxpy.CLARABEL)

# This returns 'infeasible'
problem.status
```
then the variable bounds are obeyed.

**Version**
 - CVXPY Version: 1.5.3

**Comment by Transurgeon** [comment]
I think this is unfortunately the expected behavior because we are not allowed to set anything outside of the constructor. Is there a reason why you want to specify the bounds outside of the constructor?

**Comment by warwickmm** [comment]
We have code where we first instantiate the variables, and then constraints are added as required.  We then derive any bounds implied by the constraints and want to set these on the variables (to help with big-M formulations).

If we're not allowed to set the bounds outside the constructor, what's the intention of the [property setter](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/expressions/leaf.py#L562C5-L562C29)?

**Comment by SteveDiamond** [comment]
> We have code where we first instantiate the variables, and then constraints are added as required. We then derive any bounds implied by the constraints and want to set these on the variables (to help with big-M formulations).
> 
> If we're not allowed to set the bounds outside the constructor, what's the intention of the [property setter](https://github.com/cvxpy/cvxpy/blob/fc66f1449835580cc6f0d47dea2051b6428520f0/cvxpy/expressions/leaf.py#L562C5-L562C29)?

That property setter should be changed/removed. The MR to add bounds had a lot going on and we apparently overlooked that having a setter implies the property is changeable.

**Comment by warwickmm** [comment]
Thanks.  So it seems there won't be a way to set bounds that we derive from the constraints?  If not, that's not a huge problem since we can just impose these are regular constraints.

**Comment by SteveDiamond** [comment]
Yeah fundamentally the reason is that CVXPY problems are immutable. This is an assumption used many places internally. So while it's easy enough to have things like variable bounds be changeable it breaks the immutability assumption.

**Comment by warwickmm** [comment]
Understood.  Thanks for the explanation!

Feel free to close this, or leave it open as a reminder to remove the property setter.
