### ISSUE TITLE
Booleans through tuple in version 1.6

### ISSUE THREAD

**Issue by JTPfi** [cvxpy/cvxpy#2629]
Dear all,

many thanks for CVXPY. Great package!

**Bug (or wrong usage):** Version 1.6 throws an error where ver 1.5.3 works:
 
**To reproduce** (slightly sdjusted example from the CVXPY page (list of tuples to define integer variables):
    import cvxpy as cp
    import numpy as np
    
    # Generate a random problem
    np.random.seed(0)
    m, n= 40, 25
    
    A = np.random.rand(m, n)
    b = np.random.randn(m)
    
    # Construct a CVXPY problem
    x = cp.Variable(n, integer=[(1,),(2,)])
    objective = cp.Minimize(cp.sum_squares(A @ x - b))
    prob = cp.Problem(objective)
    prob.solve()
    
    print("Status: ", prob.status)
    print("The optimal value is", prob.value)
    print("A solution x is")
    print(x.value)

**Expected behavior:** As in version 1.5.3 solve problem, variable 1 & 2 are integers, the others continuous

**Output version 1.6:**  ValueError: parameter multi_index must be a sequence of length 1
  File "...\test_cvxpy.py", line 15, in <module>     prob.solve()  ValueError: parameter multi_index must be a sequence of length 1

**Output version 1.5.3:**
    Status:  optimal
    The optimal value is 10.409201403151743
    A solution x is
    [-0.78665511  1.          1.         -0.79562891  0.00378049 -0.01001837
     -1.2359994  -1.82992003  0.06284507  0.41667334  0.03186715  0.42820555
      0.86493171  0.59093233  0.90781325  0.34822982 -0.95236169 -1.40855028
     -1.03179636 -0.20089764  1.51551031 -0.65533306  2.06834266 -0.05933137
     -1.07998069]

**OS:** Windows; miniforge

**Comment by SteveDiamond** [comment]
This doesn't seem like something that should work. Could you say more about why a list of tuples would be preferred over a list? The official docs only say that the integer argument can take in an iterable.

**Comment by JTPfi** [comment]
Thanks for your reply! Tried with a list ( x = cp.Variable(n, integer=[1,2])  ), which does not work either in 1.6 nor 1.5.3. 

Happy to try it another way. I would be happy to learn how to formulate!

For 1.5.3 tuples worked, as indicated in the API  (https://www.cvxpy.org/tutorial/constraints/index.html#Leaf.complex): 
[...] boolean : bool or list of tuple[¶](https://www.cvxpy.org/tutorial/constraints/index.html#Leaf.boolean)
Is the variable boolean (i.e., 0 or 1)? True, which constrains the entire variable to be boolean, False, or a list of indices which should be constrained as boolean, where each index is a tuple of length exactly equal to the length of shape.

**Comment by Transurgeon** [comment]
Hello @JTPfi thanks for raising this!
can you try the following?:
``x = cp.Variable(n, integer=[(1,2)])``
the idea being you have one tuple with all the entries you want to be boolean since your variable has 1 dimension.
We can definitely improve the instructions in the docs though.

**Comment by Transurgeon** [comment]
hmm, I just tried running this and am getting another error.
```
  File "/workspaces/cvxpy/cvxpy/reductions/solvers/solving_chain.py", line 377, in construct_solving_chain
    raise SolverError("Either candidate conic solvers (%s) do not support the "
cvxpy.error.SolverError: Either candidate conic solvers (['HIGHS']) do not support the cones output by the problem (SOC), or there are not enough constraints in the problem.
```
will investigate. also for reference, #2546 is most likely what caused this change in behavior.. so this means we have some more tests to add :).

**Comment by SteveDiamond** [comment]
> Thanks for your reply! That way may be a legacy from the 1.5.3 version, where this was the only way I figured out how to formulate it. You are right - seems a bit complicated.
> 
> Tried with a list ( x = cp.Variable(n, integer=[1,2]) ), which does not work either in 1.6 nor 1.5.3.
> 
> Happy to try it another way. It would be great if you could help me how to formulate!
> 
> My "index tuple version" came from the API description (https://www.cvxpy.org/tutorial/constraints/index.html#Leaf.complex): [...] boolean : bool or list of tuple[¶](https://www.cvxpy.org/tutorial/constraints/index.html#Leaf.boolean) Is the variable boolean (i.e., 0 or 1)? True, which constrains the entire variable to be boolean, False, or a list of indices which should be constrained as boolean, where each index is a tuple of length exactly equal to the length of shape.

Sorry for the confusion. To maybe add a bit to the discussion, previously we used a sort of COO format for specifying which indices were integer or boolean. We switched to a new, more efficient format. Specifying specific indices as integer or boolean is a feature used internally in cvxpy but not discussed in the docs outside the leaf API that you referenced, so this wasn't intended as a change to the user-facing API.

**Comment by Transurgeon** [comment]
@JTPfi does it work now for you? I just realized that I was using HiGHS to solve an integer QP, so it was naturally raising an error. I think the indices input for boolean/integer should be the same as the new sparsity attribute that we have recently added, see here for the related docs: https://www.cvxpy.org/tutorial/constraints/index.html#sparsity-attribute. Let me know if it makes sense!

**Comment by JTPfi** [comment]
Deal William,


works with 1.6 - thanks! Does not work with 1.5.3, though, but I guess the
new indexing isn‘t backwaren compatible.


Thanks for the help,
Tobias


William Zijie Zhang ***@***.***> schrieb am Fr. 15. Nov. 2024
um 19:59:

**Comment by JTPfi** [comment]
Many thanks for the help!
