### ISSUE TITLE
pip upgrade to 1.6.0 fails

### ISSUE THREAD

**Issue by keithbriggs** [cvxpy/cvxpy#2649]
When I do this, it thinks I am up to date, even though I only have 1.5.2.  Is there something wrong on pypi?

```
kbriggs> python3 -m pip install  cvxpy --user --upgrade
Requirement already satisfied: cvxpy in /home/kbriggs/.local/lib/python3.8/site-packages (1.5.2)
```

Also, the "latest" menu at https://www.cvxpy.org/install/index.html only goes up to 1.4.

**Comment by keithbriggs** [comment]
Thanks, but python3 does run python3.8 on my Ubuntu system, so I can't see how that would cause the behaviour.

**Comment by Transurgeon** [comment]
I meant that cvxpy 1.5.2 is the last version that supports python3.8.
If you were using python3.9 or higher, the latest version would be 1.6.0.
