### ISSUE TITLE
Generic perspective function support

### ISSUE THREAD

**Issue by b4be1** [cvxpy/cvxpy#420]
I would like to implement an [f-divergence](https://en.wikipedia.org/wiki/F-divergence) in cvxpy. How can I do that? Let's say for a fixed function such as f(x) = x**2 - 1.

**Comment by rileyjmurray** [comment]
An f-divergence is just a sum of perspective functions. I don't know if cvxpy has native support for general perspective functions (its documentation does not say so), but it *does* have the perspective function for quadratics "quad_over_lin". So if you really only need f-divergences built off of quadratics, then you can get by with quad_over_lin.

**Comment by b4be1** [comment]
Hi @rileyjmurray, thanks a lot for the info. I want an implementation for any convex f, because I am in particular interested in using the [alpha-divergence](www.mdpi.com/1099-4300/12/6/1532/pdf), and the quadratic was just an example.

**Comment by SteveDiamond** [comment]
Perspective functions are actually possible generically, but never implemented.

**Comment by rileyjmurray** [comment]
@SteveDiamond , can explain what you mean by your last comment? It sounds like you're saying that in principle, it would be possible to have a meta-atom that transforms existing cvxpy atoms into their perspective function variants. If that's the case such a feature would be very useful. For one: it would apply not only allow things like f-divergences, but it could also unify seemingly distinct functions like kl_div, quad_over_lin, etc.... The benefit of putting these functions through a common parser is that for general nonlinear solvers (e.g. cvxopt), work spent improving performance on one type of perspective function might carry over to another.

**Comment by moehle** [comment]
Not sure if this is helpful, but see Section 2 of [this paper](http://web.stanford.edu/~boyd/papers/pdf/sw_aff_ctrl.pdf) for an idea of how this *could* be done.  I wouldn't worry too much about the technical conditions, like closedness, which only really apply if you're doing integer stuff.  It basically says that if f(x) has a conic representation with cone K, then so does its perspective.  Basically you just take any affine terms in the epigraph representations and scale them by a new scalar variable.

**Comment by rileyjmurray** [comment]
@moehle , that looks awesome!  @SteveDiamond , if someone was willing to implement the procedure in Nicholas's paper, would you be open to including it in cvxpy 1.0?

(Under normal circumstances I would volunteer for such an implementation, but at this point it would be pretty far back in my queue of work.)

**Comment by ericlux** [comment]
> @moehle , that looks awesome! @SteveDiamond , if someone was willing to implement the procedure in Nicholas's paper, would you be open to including it in cvxpy 1.0?

Whoops, we were in the shower. We *were* willing to implement the procedure in #1867. CVPXY 1.3 will support the perspective transform of an expression w.r.t. its variables.

I think this can be closed now.
