### ISSUE TITLE
Kronecker product with variable matrix as first input

### ISSUE THREAD

**Issue by mattgiamou** [cvxpy/cvxpy#457]
The current implementation only supports Kronecker products with a constant first argument. I would like to construct the following semidefinite constraint which is simple to write when the first argument is a `cvxpy` variable:

`import numpy as np`
`import cvxpy as cvx`
`mu = cvx.Variable(3,3)`
`obj = cvx.Minimize(cvx.trace(mu))`
`constraints = [A + cvx.kron(mu, np.eye(3)) >> 0]`

where `A` is a constant `numpy` matrix. Is there any `cvxpy` function or procedure that makes this possible? Is there any reason `kron` is designed to require a constant first input?

**Comment by SteveDiamond** [comment]
The only reason for the requirement is that it's more work for me to implement both versions :( Obviously allowing both would be better but adding it will be kind of complicated. If you help by at least writing a PR with some tests I might take a look.

**Comment by rileyjmurray** [comment]
Can you try using numpy's Kron function instead? Due to operator overloading, CVXPY variables are compatible with a wide range of affine numpy transformations.
