### ISSUE TITLE
Better error reporting for non-DCP problems

### ISSUE THREAD

**Issue by akshayka** [cvxpy/cvxpy#713]
Attempting to solve a non-DCP problem raises the following uninformative message:

```python
DCPError: Problem does not follow DCP rules.
```

It would be great if the error message actually informed the user the way in which the problem fails to be DCP. This would make it substantially easier for new users to learn how to use CVXPY.

**Example**
Right now, running the following script

```python
import cvxpy as cp
x = cp.Variable(name='x')
expr = x * x + 5
prob = cp.Problem(cp.Minimize(expr))
prob.solve()
```

raises the error

```
DCPError: Problem does not follow DCP rules.
```

It would be very helpful if instead the error message looked something like

```python
DCPError: Problem does not follow DCP rules because the objective is not DCP. Specifically, the subexpression

    x * x

is not DCP.
```

This wouldn't be too much work to implement. An even fancier extension might print why the subexpression is not DCP.

**Requirements**
The DCP error message when trying to solve a non-DCP problem would include the following information:
* whether the objective is not DCP, or whether one of the constraints is not DCP
* why the objective or the constraint is not DCP; specifically, it should report the inner-most subexpression that is not DCP

**Help wanted!**
We welcome contributions for this issue. Interested contributors should comment on this issue or, if you have a prototype, open a pull request. A member of the development team or community will provide guidance as needed.

A good way to start would be to look at [problems.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/problem.py) and understand how the `is_dcp()` method works.

**Comment by SteveDiamond** [comment]
As part of this, we would want to finally fix expression printing. Right now it's often broken, particularly parentheses aren't kept. Also not so clear what to print for matrix constants.
