### ISSUE TITLE
cvxpy throws error when Gurobi solver encounters time limit

### ISSUE THREAD

**Issue by TShimko126** [cvxpy/cvxpy#735]
Thank you all for your work developing cvxpy! I am currently using the package with the Gurobi solver to solve an ILP problem that can have extremely long runtimes. In some of these cases, I would like to halt the solver after a predetermined period of time (maybe limited by runtime limits on a cluster, for example) but still be able to parse the best identified solution. Right now, I'm encountering an error from cvxpy that is preventing me from working with time limits on the Gurobi solver. Thank you in advance for any and all help you can offer!

**Describe the bug**
When using the Gurobi solver with a time limit and the time limit is encountered by the solver, cvxpy will throw an error instead of producing the partial (sub-optimal) solution. In cases where run times are long, it may be desirable to yield the partial solution.

**To Reproduce**
The problem is observed when running this modified version of the `tsp_mip.py` example. (Modifications necessary to ensure long runtime.) 

```
import numpy as np
from cvxpy import *

# Based on formulation described
#    @ https://en.wikipedia.org/wiki/Travelling_salesman_problem (February 2016)

np.random.seed(1)

N = 30
distances = np.random.rand(N, N)
distances = (distances + distances.T)/2  # make symmetric = symmetric-TSP

# VARS
x = Variable((N, N), boolean=True)
u = Variable(N, integer=True)

# CONSTRAINTS
constraints = []
for j in range(N):
    indices = np.hstack((np.arange(0, j), np.arange(j + 1, N)))
    constraints.append(sum(x[indices, j]) == 1)
for i in range(N):
    indices = np.hstack((np.arange(0, i), np.arange(i + 1, N)))
    constraints.append(sum(x[i, indices]) == 1)

for i in range(1, N):
    for j in range(1, N):
        if i != j:
            constraints.append(u[i] - u[j] + N*x[i, j] <= N-1)

# OBJ
obj = Minimize(sum(multiply(distances, x)))

# SOLVE
prob = Problem(obj, constraints)

# Limit the solver to one thread and 5s runtime
prob.solve(solver=GUROBI, verbose=True, Threads=1, TimeLimit=3)
print(prob.value)
```

**Expected behavior**
When the above example is run, the output below is produced. Instead of throwing the SolverError, it would be nice if CVXPY parsed the solution with the objective value of  5.6481025 (the best found, but sub-optimal solution).

**Output**
```
Academic license - for non-commercial use only
Parameter OutputFlag unchanged
   Value: 1  Min: 0  Max: 1  Default: 1
Changed value of parameter QCPDual to 1
   Prev: 0  Min: 0  Max: 1  Default: 0
Changed value of parameter Threads to 1
   Prev: 0  Min: 0  Max: 1024  Default: 0
Changed value of parameter TimeLimit to 3.0
   Prev: 1e+100  Min: 0.0  Max: 1e+100  Default: 1e+100
Optimize a model with 872 rows, 930 columns and 4176 nonzeros
Variable types: 0 continuous, 930 integer (900 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+01]
  Objective range  [9e-03, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+01]
Presolve removed 0 rows and 31 columns
Presolve time: 0.01s
Presolved: 872 rows, 899 columns, 4176 nonzeros
Variable types: 0 continuous, 899 integer (870 binary)

Root relaxation: objective 4.797968e+00, 191 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0    4.79797    0   32          -    4.79797      -     -    0s
H    0     0                       5.8931209    4.79797  18.6%     -    0s
     0     0    5.24074    0   83    5.89312    5.24074  11.1%     -    0s
     0     0    5.24446    0   84    5.89312    5.24446  11.0%     -    0s
     0     0    5.24490    0   91    5.89312    5.24490  11.0%     -    0s
     0     0    5.24490    0   91    5.89312    5.24490  11.0%     -    0s
     0     0    5.24490    0   79    5.89312    5.24490  11.0%     -    0s
     0     2    5.24812    0   79    5.89312    5.24812  10.9%     -    0s
*  436   363              34       5.8768522    5.26558  10.4%   9.8    1s
H  510   375                       5.7355863    5.26641  8.18%   9.6    1s
H  550   381                       5.6481025    5.28144  6.49%   8.9    1s

Cutting planes:
  Learned: 8
  Gomory: 3
  MIR: 4
  Flow cover: 14
  Zero half: 3

Explored 593 nodes (7784 simplex iterations) in 3.00 seconds
Thread count was 1 (of 40 available processors)

Solution count 4: 5.6481 5.73559 5.87685 5.89312

Time limit reached
Best objective 5.648102505876e+00, best bound 5.305506851111e+00, gap 6.0657%
Traceback (most recent call last):
  File "time_test.py", line 36, in <module>
    prob.solve(solver=GUROBI, verbose=True, Threads=1, TimeLimit=3)
  File "/home/tshimko/.virtualenvs/wildcodon/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/tshimko/.virtualenvs/wildcodon/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 574, in _solve
    self.unpack_results(solution, full_chain, inverse_data)
  File "/home/tshimko/.virtualenvs/wildcodon/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 717, in unpack_results
    "Try another solver, or solve with verbose=True for more "
cvxpy.error.SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.
```

**Version**
 - OS: Ubuntu 18.04 LTS
 - CVXPY Version: 1.0.23

**Comment by rostyboost** [comment]
@TShimko126 one hacky stop-gap way to solve this is to change [this line](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/gurobi_qpif.py#L39) to `9: s.OPTIMAL_INACCURATE`.

I think more generally there should be a new constant in [cvxpy/settings.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/settings.py) to describe feasible solutions that are time bound. Most solvers offer a way to specify a time budget. I have at least used such options in Gurobi, GLPK and MOSEK.

@akshayka @SteveDiamond any opinion? I'm happy to take this one. The status of a feasible solution could be refined with non-exclusive attributes such `OPTIMAL`, `SUBOPTIMAL`, `TIME BOUND`. 

In a production setup where there's always some sort of compute time budget, this is critical.

**Comment by SteveDiamond** [comment]
@rostyboost a time bound status sounds reasonable. Are you proposing to replace the current status string with something more complex?

**Comment by rostyboost** [comment]
> Are you proposing to replace the current status string with something more complex?

Yes. Status would have to be some object with potentially multiple attributes describing the solution (feasible/infeasible/optimal/inaccurate/time-bound..). To avoid exploding the combinatorics of all possible descriptions (like the `_INACCURATE` constants at the moment).

**Comment by pjssilva** [comment]
I will keep the discussion here and close the issue I opened today. Sorry for not finding this thread before.

It looks to me that in both cases (quadratic and cone programming) the return code 9 is associated with the `TimeLimit` hence I believe, considering what is available now in cvxpy code, that it should be associated with the `USER_LIMIT` constant, since the solver was stopped because a user imposed limit was achieved. 

Of course, in the future, the suggestion of @rostyboost  should be implemented so that we could get the information that the time limit was achieved but at least a feasible solution was found.

As for a workaround, @TShimko126, if you are sure the `TimeLimit` is long enough to get a feasible solution you can try to use the following ugly code when importing cvxpy
```python
import cvxpy as cvx                                                                                                       
cvx.settings.ERROR = [cvx.settings.USER_LIMIT]                                                                            
cvx.settings.SOLUTION_PRESENT = [cvx.settings.OPTIMAL, cvx.settings.OPTIMAL_INACCURATE, cvx.settings.SOLVER_ERROR]      
```
It tricks the solver to accept the `SOLVER_ERROR` as a situation that generates at least a feasible solution (since reaching the time limit is flagged using `SOLVER_ERROR`).  It seems to work here.

**Comment by rodfloripa** [comment]
I'm using Gurobi solver, and I received a similar enigmatic error.
My optimization worked fine using small data, but when I increase the data I receive this error.
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Traceback (most recent call last):
  File "solver.py", line 280, in <module>
    print(solve_it(input_data))
  File "solver.py", line 225, in solve_it
    route_lst[i],obj1 = order_pts2(state_matrix_l,cust_pts)
  File "solver.py", line 120, in order_pts2
    state_matrix,obj = order_pts(state_matrix,cust_pts)
  File "solver.py", line 108, in order_pts
    result = prob.solve(cp.GUROBI,verbose = True) #,scip_params ={"limits/time":2400})
  File "/usr/local/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 472, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 978, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/usr/local/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 1302, in unpack_results
    "Try another solver, or solve with verbose=True for more "
cvxpy.error.SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.

**Comment by phschiele** [comment]
@rodfloripa I'm not too familiar with Gurobi myself, but seeing "Restricted license" in the verbose output most likely means that your license was not found. 

Did you follow the instructions as outlined [here](https://www.gurobi.com/academia/academic-program-and-licenses/)?

**Comment by rodfloripa** [comment]
@phschiele  Thanks for answering. I remember using Gurobi with big problems and receiving a message that my problem had passed the maximum number of variables for my license.So I got this restricted license and I don't receive the old message anymore, just an enigmatic error.Maybe there's a status problem not totally solved:
https://github.com/cvxpy/cvxpy/pull/616
