### ISSUE TITLE
Numpy lower bound in setup.py

### ISSUE THREAD

**Issue by aadamson** [cvxpy/cvxpy#780]
Hello,

Is there a reason for the lower bound on numpy in setup.py being set to 1.15 as opposed to something like 1.9? It seems to have initially been increased to 1.13 in [this commit](https://github.com/cvxgrp/cvxpy/commit/7bc878735111e9ee2a57b55f12efb7e85ae4ee0d), but that commit does not appear to use any numpy APIs that weren't also present in 1.9, and then increased again recently to 1.15.

Thanks,
Alex

**Comment by SteveDiamond** [comment]
We were prompted to increase the version number because of issues with installation of cvxpy. Increasing the version number of NumPy to 1.15 seemed to make installation more reliable.
