### ISSUE TITLE
Problem loading  library libc++.1.dylib on MAC OS Mojave

### ISSUE THREAD

**Issue by cbonet** [cvxpy/cvxpy#807]
Hi, 

I had a problem running CVXPY on a macOS Mojave 10.14.6 with Python 2.7. I installed CVXPY using pip, then I tried to run one of the examples and I got the the following error: 

Traceback (most recent call last):
    ...
    import _cvxcore
ImportError: dlopen(/Library/Python/2.7/site-packages/_cvxcore.so, 2): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /Library/Python/2.7/site-packages/_cvxcore.so
  Reason: image not found

Then I checked the _cvxcore.so with "otool -L /Library/Python/2.7/site-packages/_cvxcore.so" getting:

/Library/Python/2.7/site-packages/_cvxcore.so:
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

I replaced rpath by /usr/lib using: "install_name_tool -change  @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib /Library/Python/2.7/site-packages/_cvxcore.so"

After that I was able to run the code without problems.

**Comment by madeleine-b** [comment]
I had the same issue. Thanks so much for documenting your solution!

**Comment by aerijman** [comment]
I have the same problem

**Comment by n0rdp0l** [comment]
Thanks, that solved it for me!! Could you explain, or point me to resources that explain, what was going on here ?!
