### ISSUE TITLE
Offset for the diag function 

### ISSUE THREAD

**Issue by cvanwynsberghe** [cvxpy/cvxpy#808]
In matlab, cvx enables one to set a matrix with an offset of k from the diagonal, ie by `diag(v, k)`.

If I write, for example, the following code :

```
import cvxpy as cvx

v = cvx.Variable(10)
cvx.diag(v, 2)
```
then it returns 
> TypeError: diag() takes 1 positional argument but 2 were given

Same remark about extracting the k-th diagonal from a matrix X by `diag(X, k)`.

Is it possible to add this feature ?

**Comment by Transurgeon** [comment]
done with PR above :)
