### ISSUE TITLE
PyPy crashes since python wrappers were built with SWIG 3.0.8

### ISSUE THREAD

**Issue by mattip** [cvxpy/cvxpy#837]
Tracking down [this StackOverflow question](https://stackoverflow.com/questions/58328323/using-cvxpy-under-pypy3), it turns out the python wrappers were built with [SWIG 3.0.8](https://github.com/cvxgrp/cvxpy/blob/v1.0.25/cvxpy/cvxcore/python/cvxcore_wrap.cpp#L3) and this [bug was fixed in SWIG 4.0.0](https://github.com/swig/swig/issues/1645#issuecomment-541393019).

While supporting [PyPy](http://pypy.org/) may not be a top priority for CVXPY, probably the time has come to update the wrappers anyway for more modern CPython versions. I think 3.0.8 was released in 2015.

**Comment by akshayka** [comment]
We've updated the SWIG-generated wrappers in CVXPY 1.1, which is still under development. Want to send a pull request that updates the wrappers at master?

**Comment by mattip** [comment]
Sure. Are there particular flags used when generating the wrappers?

**Comment by SteveDiamond** [comment]
We used default arguments. It's possible we missed flags we should be using actually!
