### ISSUE TITLE
Add condition number as quasiconvex atom

### ISSUE THREAD

**Issue by sbarratt** [cvxpy/cvxpy#858]
**Is your feature request related to a problem? Please describe.**
Currently, lambda_max / lambda_min is not quasiconvex in CVXPY:
```python
import cxvpy as cp

A = cp.Variable((2, 2))
objective = cp.lambda_max(A) / cp.lambda_min(A)
objective.is_quasiconvex() # False
```

**Describe the solution you'd like**
I'd like to add a (quasiconvex) atom, `cp.condition_number(A)`.

**Describe alternatives you've considered**
Make `cp.lambda_max / cp.lambda_min` work.

**Comment by rileyjmurray** [comment]
Technically, condition number is only quasi-convex on the set of positive definite matrices. Refer to MOSEK's modeling cookbook for an example showing how to do this. (Printed page 57, PDF page 60, https://docs.mosek.com/MOSEKModelingCookbook-letter.pdf)

**Comment by akshayka** [comment]
Thanks for sharing, @rileyjmurray. I hadn't previously read that cookbook; it's excellent!

I loved this bit:

> In other words, we present simple convex building blocks, which can then be
combined into more elaborate convex models. We call this approach *extremely disciplined
modeling*. With the advent of more expressive and sophisticated tools like conic optimization,
we feel that this approach is better suited.

**Comment by rileyjmurray** [comment]
Oh yeah, I love their modeling cookbook. I think it should be required reading for anyone who uses  convex optimization in their research. It's super short, shows you a huge number of tricks, and covers a large range of applications. I also got a laugh out of the "extremely disciplined modeling" bit!

**Comment by parthb83** [comment]
Hey @rileyjmurray! I would like to work on this issue as was suggested by you. Kindly guide me through the process of working on this issue.

**Comment by rileyjmurray** [comment]
Hi Parth. Sorry, my bandwidth is actually pretty limited right now. Maybe @phschiele could help?

**Comment by phschiele** [comment]
@rileyjmurray Sure, we'll figure out some details on Discord. 
Perhaps besides the atom itself, we could leverage this to add (at least high-level) instructions for adding an atom.

**Comment by SteveDiamond** [comment]
completed
